Repository bcgov/healthgateway, pull requests merged in 2020-12, with the labels that each got.

#1382 Fix space in terms of service banner
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1383 Update dependent icon
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: ready

#1390 Features/9621
  Testing/functional/e2e/cypress/integration/timeline/modals.js
Labels: ready

#1394 Snowplow CSP Issue AB#9665
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#1392 Functional tests for Reports
  Apps/WebClient/src/ClientApp/src/components/modal/genericMessage.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/misc.js
Labels: ready

#1391 Fixes lab result order on dependent page
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
Labels: ready

#1395 Change test date to covid-19 test date
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/models/addDependentRequest.ts
Labels: ready

#1393 Add func. tests for Med service
  Testing/functional/e2e/cypress/fixtures/MedicationService/medicationStatement.json
  Testing/functional/e2e/cypress/integration/services/medication.js
Labels: ready

#1402 Update Export Recods Page
  Apps/WebClient/src/ClientApp/src/components/modal/genericMessage.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/misc.js
Labels: ready

#1401 Fixes dependent covid result tests AB#9652
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
Labels: ready

#1361 Dependent maximum age change
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/test/landing.test.ts
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/Server/Services/DependentService.cs
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Services.Test/DependentService_Test.cs
Labels: ready

#1380 Add action Covid modal
  Apps/Database/src/Delegates/DBUserPreferenceDelegate.cs
  Apps/Database/src/Delegates/IUserPreferenceDelegate.cs
  Apps/WebClient/src/ClientApp/src/components/communication.vue
  Apps/WebClient/src/ClientApp/src/components/modal/covid.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/models/userPreference.ts
  Apps/WebClient/src/ClientApp/src/models/userProfile.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restUserProfileService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/src/Server/Models/UserPreferenceModel.cs
  Apps/WebClient/src/Server/Models/UserProfileModel.cs
  Apps/WebClient/src/Server/Services/IUserProfileService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/test/unit/Controllers.Test/UserProfileController_Test.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileService_Test.cs
Labels: ready

#1403 Fixes dependent name and functional test
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
Labels: ready

#1405 Covid modal story
  Apps/Database/src/Delegates/DBUserPreferenceDelegate.cs
  Apps/Database/src/Delegates/IUserPreferenceDelegate.cs
  Apps/WebClient/src/ClientApp/src/components/communication.vue
  Apps/WebClient/src/ClientApp/src/components/modal/covid.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/models/userPreference.ts
  Apps/WebClient/src/ClientApp/src/models/userProfile.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restUserProfileService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/src/Server/Models/UserPreferenceModel.cs
  Apps/WebClient/src/Server/Models/UserProfileModel.cs
  Apps/WebClient/src/Server/Services/IUserProfileService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/test/unit/Controllers.Test/UserProfileController_Test.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileService_Test.cs
  Testing/functional/e2e/cypress/integration/services/webClient/userProfile.js
  Testing/functional/e2e/cypress/integration/timeline/modals.js
Labels: ready

#1404 Update menu items order AB#9673
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: ready

#1396 Add sensitive doc upload
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/WebClient.csproj
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
Labels: ready

#1407 dependent page message AB#9674
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
Labels: ready

#1409 Add logs to lab report and error out when no content
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/test/functional/README.md
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
Labels: ready

#1410 Add Msp Visits report to export records page
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/plugins/pdfDefinition.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1411 Add functional tests to msp visits report
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: ready

#1414 Dependent Agreement Update
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
Labels: ready

#1417 Fix Cypress tests for AB#9686
  Testing/functional/e2e/cypress/fixtures/WebClientService/userProfile.json
  Testing/functional/e2e/cypress/integration/services/medication.js
  Testing/functional/e2e/cypress/integration/services/webClient/userProfile.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready

#1416 Fix covid modal's func. tests
  Testing/functional/e2e/cypress/integration/timeline/modals/covidModal.js
  Testing/functional/e2e/cypress/integration/timeline/modals/protectiveWordModal.js
Labels: ready

#1415 Fixes disabled modules showing up on reports page AB#9685
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: ready

#1412 Adds MSP Visits Report
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/plugins/pdfDefinition.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: ready

#1425 Update PDF Reports
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: ready

#1431 Updated Export Records label on side menu
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: ready

#1437 Fix func. tests for Dependents
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
Labels: ready

#1441 Fixes dependent covid results AB#9697
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Delegates/ILaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Services/ILaboratoryService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: ready

#1429 Add COVID-19 report
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1438 Remove comments from immunization
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/note.vue
Labels: ready

#1439 Fixes record type label AB#9696
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: ready

#1445 Implement SonarCloud
  Tools/SonarCloud/azure/build.yaml
  Tools/SonarQube/.gitignore
  Tools/SonarQube/CODE_OF_CONDUCT.md
  Tools/SonarQube/CONTRIBUTING.md
  Tools/SonarQube/Dockerfile
  Tools/SonarQube/LICENSE
  Tools/SonarQube/README.md
  Tools/SonarQube/azure/build.yaml
  Tools/SonarQube/docs/scanning-with-gradle.md
  Tools/SonarQube/docs/troubleshooting-jenkins-slave-startup-issues.md
  Tools/SonarQube/docs/upgrading-with-bundled-plugins.md
  Tools/SonarQube/jenkins/SonarQube-Integrated-ZapScan-Jenkinsfile
  Tools/SonarQube/jenkins/SonarQube-StaticScan-Jenkinsfile
  Tools/SonarQube/jenkins/ZapScan-Integration-Example-Jenkinsfile
  Tools/SonarQube/provisioning/updatesqadminpw.sh
  Tools/SonarQube/root/usr/bin/fix-permissions
  Tools/SonarQube/run.sh
  Tools/SonarQube/sonar-runner/build.gradle
  Tools/SonarQube/sonar-runner/gradle/wrapper/gradle-wrapper.jar
  Tools/SonarQube/sonar-runner/gradle/wrapper/gradle-wrapper.properties
  Tools/SonarQube/sonar-runner/gradlew
  Tools/SonarQube/sonar-runner/gradlew.bat
  Tools/SonarQube/sonarqube-postgresql-template.yaml
Labels: ready

#1443 Add func. tests for Covid-19 report
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: ready

#1444 fix func tests AB#9692
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
Labels: ready

#1440 Destroy Beta Request AB#9661
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/components/core/MainNavbar.vue
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/models/email.ts
  Apps/AdminWebClient/src/ClientApp/src/models/userBetaRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restBetaRequestService.ts
  Apps/AdminWebClient/src/ClientApp/src/views/BetaQueue.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Controllers/BetaRequestController.cs
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Models/AdminEmail.cs
  Apps/AdminWebClient/src/Server/Models/UserBetaRequest.cs
  Apps/AdminWebClient/src/Server/Services/BetaRequestService.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Services/IBetaRequestService.cs
  Apps/AdminWebClient/src/Server/Services/IDashboardService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/Database/src/Delegates/DBBetaRequestDelegate.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/IBetaRequestDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/WebClient/src/ClientApp/src/constants/registrationStatus.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/betaRequest.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restBetaRequestService.ts
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/registrationInfo.vue
  Apps/WebClient/src/Server/Constants/RegistrationStatus.cs
  Apps/WebClient/src/Server/Controllers/BetaRequestController.cs
  Apps/WebClient/src/Server/Models/CreateUserRequest.cs
  Apps/WebClient/src/Server/Services/BetaRequestService.cs
  Apps/WebClient/src/Server/Services/IBetaRequestService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/test/unit/Controllers.Test/BetaRequestControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/DumpHeadersControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/BetaRequestServiceTests.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileService_Test.cs
  Testing/k6/src/inc/common.js
  Testing/k6/src/services/k6_beta.js
Labels: ready

#1446 Add covid-19 export records
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: ready

#1451 Updated covid-19 report selector
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1453 Fix for name qualifier and sections
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegate_Test.cs
Labels: bug, ready

#1454 Fixes functional tests AB#9718
  Testing/functional/e2e/cypress/fixtures/PatientService/patient.json
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
  Testing/functional/e2e/cypress/integration/services/patient.js
Labels: ready

#1457 update release notes AB#9719
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1456 Enable delete old emails job AB#9658
  Apps/Database/src/Delegates/DBEmailDelegate.cs
  Apps/JobScheduler/src/Startup.cs
Labels: ready

#1455 Updated Audit filter to check for the Authentication attribute
  Apps/Common/src/Filters/AuditFilter.cs
Labels: ready

#1469 Dependants menu button does not show on closed accounts
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: ready

#1462 Update dependent error handling AB#9707
  Apps/Common/src/Constants/ErrorMessages.cs
  Apps/Common/src/Constants/ResultType.cs
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/src/ErrorHandling/ActionType.cs
  Apps/Common/src/ErrorHandling/ErrorTranslator.cs
  Apps/Common/src/Models/RequestResultError.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegate_Test.cs
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/test/unit/Delegates/MedicationDelegate_Test.cs
  Apps/Medication/test/unit/Services/MedicationStatementService_Test.cs
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/constants/actionType.ts
  Apps/WebClient/src/ClientApp/src/constants/resulttype.ts
  Apps/WebClient/src/ClientApp/src/models/requestResult.ts
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/Server/Constants/RegistrationStatus.cs
  Apps/WebClient/src/Server/Models/AddDependentRequest.cs
  Apps/WebClient/src/Server/Services/DependentService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/test/unit/Services.Test/DependentService_Test.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileService_Test.cs
Labels: ready

#1478 Fix - Loading comments is slow
  Apps/Database/src/Delegates/DBCommentDelegate.cs
  Apps/Database/src/Delegates/ICommentDelegate.cs
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/components/timeline/addComment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/commentSection.vue
  Apps/WebClient/src/ClientApp/src/models/baseTypes.ts
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/models/userComment.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restUserCommentService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/comment.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/store.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
  Apps/WebClient/src/Server/Controllers/CommentController.cs
  Apps/WebClient/src/Server/Services/CommentService.cs
  Apps/WebClient/src/Server/Services/ICommentService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/test/unit/Controllers.Test/CommentControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/CommentService_Test.cs
Labels: bug, ready

#1492 Tasks/9727
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/Database/src/Delegates/DBCommentDelegate.cs
  Apps/Database/src/Delegates/ICommentDelegate.cs
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/addComment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/commentSection.vue
  Apps/WebClient/src/ClientApp/src/models/baseTypes.ts
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationResult.ts
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/models/userComment.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restImmunizationService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserCommentService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/comment.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/immunization.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/store.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
  Apps/WebClient/src/Server/Controllers/CommentController.cs
  Apps/WebClient/src/Server/Services/CommentService.cs
  Apps/WebClient/src/Server/Services/ICommentService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/test/unit/Controllers.Test/CommentControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/CommentService_Test.cs
Labels: ready

#1485 Add Immunization vue page
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientService.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1491 Update Immz timeline card
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
Labels: ready

#1486 Dependent Error Handling
  Apps/Common/src/Constants/ErrorMessages.cs
  Apps/Common/src/Constants/ResultType.cs
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/src/ErrorHandling/ActionType.cs
  Apps/Common/src/ErrorHandling/ErrorTranslator.cs
  Apps/Common/src/Models/RequestResultError.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegate_Test.cs
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/test/unit/Delegates/MedicationDelegate_Test.cs
  Apps/Medication/test/unit/Services/MedicationStatementService_Test.cs
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/constants/actionType.ts
  Apps/WebClient/src/ClientApp/src/constants/resulttype.ts
  Apps/WebClient/src/ClientApp/src/models/requestResult.ts
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/Server/Constants/RegistrationStatus.cs
  Apps/WebClient/src/Server/Models/AddDependentRequest.cs
  Apps/WebClient/src/Server/Services/DependentService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/test/unit/Services.Test/DependentService_Test.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileService_Test.cs
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
Labels: ready

#1494 Update Functional Tests for Immunization Card
  Apps/Immunization/src/appsettings.Development.json
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/e2e/cypress/integration/services/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready

#1497 adds project lifecycle badge
  README.md
Labels: ready

#1499 Add functional tests for AB#9732
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunizationrefresh.json
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: functional tests, ready

#1498 Fixed comment + some other functional tests
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/e2e/cypress/fixtures/WebClientService/comments.json
  Testing/functional/e2e/cypress/integration/services/webClient/comment.js
  Testing/functional/e2e/cypress/integration/timeline/misc.js
Labels: bug, functional tests, ready

#1502 update landing page AB#9748
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#1503 Add real data to immz. report
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
Labels: ready

#1501 update release notes #AB9747
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1506 fix func. tests
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
Labels: ready

#1508 Immz duplication fix
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/mutations.ts
Labels: bug, ready

#1510 Add func. tests
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
Labels: ready

#1527 Add Dependent Count
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Services/IDashboardService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/test/unit/AdminWebClientTests.csproj
  Apps/AdminWebClient/test/unit/Controllers.Test/DashboardControllerTest.cs
  Apps/AdminWebClient/test/unit/Services.Test/DashboardService_Test.cs
  Apps/Database/src/Delegates/DBResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IUserDelegateDelegate.cs
Labels: ready

#1528 Update Immz TimeLine card & delegate
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Models/ImmunizationModel.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationController_Test.cs
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
Labels: ready

#1515 Fixes PDF quality
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1529 Update immz. report and pdf
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
Labels: ready

#1530 Add Admin Dashboard Stats - Dependents
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Services/IDashboardService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/test/unit/AdminWebClientTests.csproj
  Apps/AdminWebClient/test/unit/Controllers.Test/DashboardControllerTest.cs
  Apps/AdminWebClient/test/unit/Services.Test/DashboardService_Test.cs
  Apps/Database/src/Delegates/DBResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IUserDelegateDelegate.cs
Labels: ready

#1534 Fix syntax error
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
Labels: ready
