Repository bcgov/healthgateway, pull requests merged in 2020-10, with the labels that each got.

#901 Completes AB#9119 - Update unit test code coverage for meds
  Apps/Medication/src/Controllers/MedicationController.cs
  Apps/Medication/src/Models/MedicationStatement.cs
  Apps/Medication/src/Program.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/test/unit/Controllers/MedicationController_Test.cs
  Apps/Medication/test/unit/Controllers/MedicationStatementController_Test.cs
  Apps/Medication/test/unit/Delegates/MedicationDelegate_Test.cs
  Apps/Medication/test/unit/Delegates/PatientDelegate_Test.cs
  Apps/Medication/test/unit/Services/MedicationService_Test.cs
  Apps/Medication/test/unit/Services/MedicationStatementService_Test.cs
Labels: unit tests

#900 Rewrite Functional Tests
  Apps/WebClient/src/ClientApp/src/components/monthYearPicker.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/addComment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/encounter.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/medication.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/note.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/calendar.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/comments.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/filter.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/immunization.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/medication.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/menu.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/mspvisits.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/notes.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/pagination.js
Labels: enhancement, functional tests

#912 Fixes event name for AB#9258
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: bug

#917 Fixed details not expanding
  Apps/WebClient/src/ClientApp/src/components/timeline/encounter.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/laboratory.vue
Labels: bug

#918 Delete folder that shouldn't exist for AB#9282
  Apps/ExternalClient/src/ClientApp/package-lock.json
Labels: bug

#930 Idir without hdid & bookmarking fixes
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/loginCallback.vue
Labels: bug

#929 Resolves AB#9188 - Functional Tests for blocked IDIR
  Apps/WebClient/test/functional/e2e/cypress.json
  Apps/WebClient/test/functional/e2e/cypress/integration/authentication/auth.js
Labels: functional tests

#932 Implement CSP for AdminWebClient AB#9196
  Apps/AdminWebClient/README.md
  Apps/AdminWebClient/src/Server/Services/CommunicationService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/src/appsettings.json
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/WebClient/README.md
Labels: enhancement

#914 Added functional tests
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/test/functional/e2e/cypress.json
  Apps/WebClient/test/functional/e2e/cypress/integration/healthinsights/insights.js
  Apps/WebClient/test/functional/e2e/cypress/integration/user/profile.js
  Apps/WebClient/test/functional/e2e/cypress/integration/user/profileaccountclosure.js
  Apps/WebClient/test/functional/e2e/cypress/support/commands.js
Labels: functional tests

#948 Fixes Auth, Filter and Pagination functional tests
  Apps/WebClient/test/functional/e2e/cypress/integration/authentication/auth.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/filter.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/pagination.js
Labels: bug, functional tests, ready

#950 Fixed func.tests
  Apps/WebClient/test/functional/e2e/cypress/integration/healthinsights/insights.js
  Apps/WebClient/test/functional/e2e/cypress/integration/pages/Login.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/starRating.js
  Apps/WebClient/test/functional/e2e/cypress/integration/user/feedback.js
  Apps/WebClient/test/functional/e2e/cypress/integration/user/profile.js
Labels: bug, functional tests

#953 Added func. tests for countdown timer
  Apps/WebClient/src/ClientApp/src/components/modal/verifySMS.vue
  Apps/WebClient/test/functional/e2e/cypress/integration/user/profile.js
Labels: functional tests

#956 Completes AB#9202 - Cypress validate filter counts
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/filter.js
Labels: functional tests, ready

#966 Update Release Notes R1.2.8 #AB9316
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#964 Slider tests and removed warnings
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/modal/verifySMS.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/vue.config.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/filter.js
Labels: functional tests

#965 Fix filter counts appearing on disabled filters
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/filter.js
Labels: needs attention

#976 Remove PR trigger on main build for AB#9303
  Apps/Immunization/azure/build.yaml
Labels: ready

#1003 AB#9327 - Run Cypress Locally
  Apps/WebClient/test/functional/e2e/cypress/integration/authentication/auth.js
  Apps/WebClient/test/functional/e2e/cypress/integration/healthinsights/insights.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/menu.js
  Apps/WebClient/test/functional/e2e/cypress/support/commands.js
  Apps/WebClient/test/functional/e2e/cypress/support/constants.js
Labels: ready

#974 Add dependents page
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
Labels: ready

#978 Expand sidebar on login
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/store/modules/sidebar/actions.ts
  Apps/WebClient/test/functional/e2e/cypress/integration/navmenu/sideBar.js
Labels: ready

#1004 Creates User Delegate Delegate
  Apps/Database/src/Delegates/DBUserDelegateDelegate.cs
Labels: ready

#1016 fixed admin packages
  Apps/AdminWebClient/src/ClientApp/package.json
Labels: ready

#1018 Patient controller, model and service updates Features/9348
  Apps/Common/src/Delegates/IPatientDelegate.cs
  Apps/Common/src/Delegates/RestPatientDelegate.cs
  Apps/Common/src/Models/PatientModel.cs
  Apps/Common/src/Models/ResourceIdentifier.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/test/unit/Services/EncounterService_Test.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/test/unit/Services/MedicationStatementService_Test.cs
  Apps/Patient/src/Constants/OIDType.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/src/Delegates/IPatientDelegate.cs
  Apps/Patient/src/Patient.csproj
  Apps/Patient/src/Services/IPatientService.cs
  Apps/Patient/src/Services/PatientService.cs
  Apps/Patient/src/Services/SoapPatientService.cs
  Apps/Patient/src/Startup.cs
  Apps/Patient/test/unit/Delegates/ClientRegistriesDelegate_Test.cs
  Apps/Patient/test/unit/Services/PatientService_Test.cs
  Apps/WebClient/src/ClientApp/package-lock.json
Labels: ready

#1017 Added dependent controller
  Apps/WebClient/src/Server/Controllers/DependentController.cs
  Apps/WebClient/src/Server/Models/AddDependentRequest.cs
  Apps/WebClient/src/Server/Models/DependentModel.cs
  Apps/WebClient/src/Server/Models/UserNote.cs
  Apps/WebClient/src/Server/Models/UserProfileModel.cs
  Apps/WebClient/src/Server/Services/IDependentService.cs
Labels: ready

#1067 Added UserDelegate Get method
  Apps/Database/src/Delegates/DBUserDelegateDelegate.cs
  Apps/Database/src/Delegates/IUserDelegateDelegate.cs
Labels: ready

#1076 Resolve AB#9362 - Update server side packages
  .github/dependabot.yml
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/AdminWebClient/test/unit/AdminWebClientTests.csproj
  Apps/Common/src/Common.csproj
  Apps/Common/test/unit/CommonTests.csproj
  Apps/DBMaintainer/DBMaintainer.csproj
  Apps/Database/src/Database.csproj
  Apps/Database/test/unit/DatabaseTests.csproj
  Apps/Encounter/src/Encounter.csproj
  Apps/Encounter/test/unit/EncounterTests.csproj
  Apps/Immunization/src/Immunization.csproj
  Apps/Immunization/test/unit/ImmunizationTests.csproj
  Apps/JobScheduler/src/JobScheduler.csproj
  Apps/Laboratory/src/Laboratory.csproj
  Apps/Laboratory/test/unit/LaboratoryTests.csproj
  Apps/Medication/src/Medication.csproj
  Apps/Medication/test/unit/MedicationTests.csproj
  Apps/Patient/src/Patient.csproj
  Apps/Patient/test/unit/PatientTests.csproj
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/WebClientTests.csproj
Labels: ready

#1071 Fixes Functional Tests AB#9349, AB#9350, AB#9351 and lots more
  Apps/WebClient/src/ClientApp/src/components/timeline/encounter.vue
  Apps/WebClient/test/functional/e2e/README.md
  Apps/WebClient/test/functional/e2e/cypress/fixtures/AllDisabledConfig.json
  Apps/WebClient/test/functional/e2e/cypress/integration/authentication/auth.js
  Apps/WebClient/test/functional/e2e/cypress/integration/healthinsights/insights.js
  Apps/WebClient/test/functional/e2e/cypress/integration/navmenu/sideBar.js
  Apps/WebClient/test/functional/e2e/cypress/integration/pages/Login.js
  Apps/WebClient/test/functional/e2e/cypress/integration/pages/Registration.js
  Apps/WebClient/test/functional/e2e/cypress/integration/pages/Routes.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/calendar.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/comments.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/encounter.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/filter.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/immunization.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/medication.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/menu.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/misc.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/modals.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/notes.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/pagination.js
  Apps/WebClient/test/functional/e2e/cypress/integration/timeline/starRating.js
  Apps/WebClient/test/functional/e2e/cypress/integration/user/feedback.js
  Apps/WebClient/test/functional/e2e/cypress/integration/user/profile.js
  Apps/WebClient/test/functional/e2e/cypress/support/commands.js
  Apps/WebClient/test/functional/e2e/cypress/support/constants.js
  Apps/WebClient/test/functional/e2e/package-lock.json
  Apps/WebClient/test/functional/e2e/package.json
Labels: functional tests, ready

#1020 Update Patroni documentation
  Tools/Postgres/README.md
Labels: ready

#1082 Add DB Health checks to resolve AB#9367
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.csproj
  Apps/global.json
Labels: ready

#1019 Added GetAll to DependentController
  Apps/WebClient/src/Server/Controllers/DependentController.cs
  Apps/WebClient/src/Server/Models/DependentModel.cs
  Apps/WebClient/src/Server/Services/IDependentService.cs
  Apps/WebClient/test/unit/Controllers.Test/DependentController_Test.cs
  Apps/WebClient/test/unit/WebClientTests.csproj
Labels: ready

#1080 Add AddDependent to the DependentService
  Apps/WebClient/src/Server/Controllers/DependentController.cs
  Apps/WebClient/src/Server/Models/AddDependentRequest.cs
  Apps/WebClient/src/Server/Models/DependentModel.cs
  Apps/WebClient/src/Server/Services/DependentService.cs
  Apps/WebClient/src/Server/Services/IDependentService.cs
  Apps/WebClient/test/unit/Services.Test/DependentService_Test.cs
Labels: ready

#1100 Refactor patient to allow API access for AB#9242
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Constants/OIDType.cs
  Apps/Common/src/Constants/PatientIdentifierType.cs
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/src/Delegates/IClientRegistriesDelegate.cs
  Apps/Common/src/Delegates/RestPatientDelegate.cs
  Apps/Common/src/Models/ResourceIdentifier.cs
  Apps/Common/src/ServiceReference/Reference.cs
  Apps/Common/src/ServiceReference/dotnet-svcutil.params.json
  Apps/Common/src/Services/EndpointConfig.cs
  Apps/Common/src/Services/IPatientService.cs
  Apps/Common/src/Services/LoggingEndpointBehaviour.cs
  Apps/Common/src/Services/LoggingMessageInspector.cs
  Apps/Common/src/Services/PatientService.cs
  Apps/Common/src/resources/(Asynchronous)PRPA_AR101002.wsdl
  Apps/Common/src/resources/(Asynchronous)PRPA_AR101202.wsdl
  Apps/Common/src/resources/(Synchronous)PRPA_AR101002.wsdl
  Apps/Common/src/resources/(Synchronous)PRPA_AR101202.wsdl
  Apps/Common/src/resources/PRPA_AR101006.wsdl
  Apps/Common/src/resources/PRPA_AR101201.wsdl
  Apps/Common/src/resources/QUPA_AR101102.wsdl
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegate_Test.cs
  Apps/Common/test/unit/Delegates/RestPatientDelegate_Test.cs
  Apps/Common/test/unit/Services/LoggingMessageInspector_Test.cs
  Apps/Common/test/unit/Services/PatientService_Test.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/src/Startup.cs
  Apps/Encounter/src/appsettings.Development.json
  Apps/Encounter/src/appsettings.json
  Apps/Encounter/test/unit/Services/EncounterService_Test.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/src/appsettings.Development.json
  Apps/Medication/src/appsettings.json
  Apps/Medication/test/unit/Services/MedicationStatementService_Test.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Delegates/IPatientDelegate.cs
  Apps/Patient/src/Patient.csproj
  Apps/Patient/src/Startup.cs
  Apps/Patient/src/appsettings.Development.json
  Apps/Patient/src/appsettings.json
  Apps/Patient/test/unit/PatientTests.csproj
  Apps/Patient/test/unit/UnitTest.json
  Apps/WebClient/src/Server/Services/DependentService.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Services.Test/DependentService_Test.cs
Labels: ready

#1101 Resolves AB#9378 - Patient Not required in Lab.
  Apps/Laboratory/src/Startup.cs
Labels: ready

#1121 Fixed labels not showing. Header menu icon
  Apps/WebClient/src/ClientApp/src/components/feedback.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: bug, ready

#1120 Fixes View Dependent
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
Labels: ready

#1122 Update patroni resource limits
  Tools/Postgres/patroni.yaml
Labels: documentation, ready

#1126 Fixes Check Dependent Module
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
Labels: ready

#1136 Fixes get all dependents route
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restDependentService.ts
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/Server/Controllers/DependentController.cs
  Apps/WebClient/test/unit/Controllers.Test/DependentController_Test.cs
Labels: ready

#1125 Add dependent auth to lab
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceAuthorizationHandler.cs
  Apps/Common/test/unit/AccessManagement/Authorization/FhirResourceAuthorizationHandler_Test.cs
  Apps/Database/src/Delegates/DBUserDelegateDelegate.cs
  Apps/Database/src/Delegates/IUserDelegateDelegate.cs
  Apps/WebClient/test/unit/Services.Test/DependentService_Test.cs
Labels: ready

#1133 Add delete dependent controller
  Apps/WebClient/src/Server/Controllers/DependentController.cs
  Apps/WebClient/test/unit/Controllers.Test/DependentController_Test.cs
Labels: ready

#1163 added fun. tests
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/test/functional/e2e/cypress/integration/dependent/dependentsList.js
Labels: ready

#1165 Added data testid to error Card
  Apps/WebClient/src/ClientApp/src/components/errorCard.vue
Labels: ready

#1164 Fixes AB#9404 - Removes GenericCache object from Context if save fails
  Apps/Database/src/Delegates/DBGenericCacheDelegate.cs
Labels: ready

#1162 Updated registration view with unerage message
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restBetaRequestService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserProfileService.ts
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/test/landing.test.ts
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
  Apps/WebClient/src/Server/Services/UserProfileService.cs
Labels: ready

#1171 Resolves AB#9364 - Mask PHN for Lab Result
  Apps/Laboratory/src/Models/LaboratoryModel.cs
Labels: ready

#1170 Moving note's date to a new line
  Apps/WebClient/src/ClientApp/src/components/timeline/note.vue
Labels: ready

#1147 Add validate minimum age
  Apps/WebClient/src/Server/Controllers/DependentController.cs
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/Server/Services/IUserProfileService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Controllers.Test/UserProfileController_Test.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileService_Test.cs
Labels: ready

#1138 Fix for time conversion Labs
  Apps/WebClient/src/ClientApp/src/models/dateWrapper.ts
Labels: ready

#1186 Update Release Notes 1.2.9 AB#9469
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1185 Implemented dependents not found when disabled AB#9429
  Apps/WebClient/src/ClientApp/src/router.ts
Labels: ready

#1191 Added data-testid for fun. tests
  Apps/WebClient/src/ClientApp/src/views/registration.vue
Labels: ready

#1196 Add Lab ID required for PDF report for AB#9476
  Apps/Laboratory/src/Models/LaboratoryModel.cs
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
Labels: ready

#1189 Updated dependencies
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
Labels: dependencies, javascript, ready

#1184 Features/9423 - New Auth Policy for UserProfile and cleanup on Auth Handler
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Policy/UserProfilePolicy.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Constants/FhirResource.cs
  Apps/Common/test/unit/AccessManagement/Authorization/FhirResourceAuthorizationHandler_Test.cs
Labels: ready

#1193 OpenShift 4 Azure Agents for AB#9434
  Tools/AzureAgent/README.md
  Tools/AzureAgent/docker/Dockerfile
  Tools/AzureAgent/openshift/AzureAgentOCP4.yaml
  Tools/AzureAgent/openshift/rb-dev.yaml
  Tools/AzureAgent/openshift/rb-tools.yaml
Labels: ready
