Repository bcgov/healthgateway, pull requests merged in 2021-07, with the labels that each got.

#2522 Update Registration Page AB#10735
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready, user story

#2523 Implement Immunization report template AB#10741
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/Server/Assets/Templates/ImmunizationReport.docx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/WebClient.xml
Labels: ready, user story

#2530 Create Health Visits Report AB#10744
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/models/reportHeader.ts
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/Server/Assets/Templates/EncounterReport.docx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/WebClient.xml
Labels: ready, user story

#2531 Rename Health Care Timeline to Timeline AB#10831
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/tests/cypress/support/commands.js
Labels: enhancement, ready, user story

#2532 Add template for Covid Test results for AB#10829
  Apps/WebClient/src/Server/Assets/Templates/CovidReport.docx
  Apps/WebClient/src/Server/Assets/Templates/ImmunizationReport.docx
  Apps/WebClient/src/Server/Assets/Templates/MedicationReport.docx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
Labels: ready

#2535 Add xlsx templates for covid, imms, and sa
  Apps/WebClient/src/Server/Assets/Templates/CovidReport.xlsx
  Apps/WebClient/src/Server/Assets/Templates/ImmunizationReport.xlsx
  Apps/WebClient/src/Server/Assets/Templates/MedicationRequestReport.xlsx
Labels: ready

#2534 Add xlsx template for Medication
  Apps/WebClient/src/Server/Assets/Templates/MedicationReport.xlsx
Labels: ready

#2538 Add new PDF template for special authority request export AB#10742
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/Server/Assets/Templates/MedicationRequestReport.docx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/WebClient.xml
Labels: enhancement, ready, user story

#2536 Show N/A for the average when there are no ratings AB#10849
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
Labels: bug, ready

#2537 Add refresh button and clean up admin dashboard AB#10732
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
Labels: enhancement, ready, user story

#2545 Download CSV, XLS, PDF Reports AB#10747 AB#10786 AB#10749 AB#10746 AB#10748
  Apps/Common/test/unit/CommonTests.xml
  Apps/JobScheduler/src/JobScheduler.xml
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/models/report.ts
  Apps/WebClient/src/ClientApp/src/models/reportFilter.ts
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/Server/Assets/Templates/EncounterReport.xlsx
  Apps/WebClient/src/Server/Models/ReportModel.cs
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/Server/Services/ReportService.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/test/unit/Controllers.Test/ReportControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
  Testing/functional/tests/cypress/integration/e2e/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/e2e/report/report.js
Labels: ready, user story

#2549 Add HDID lookup for AB#10852
  Apps/AdminWebClient/src/Server/Constants/UserQueryType.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
Labels: ready

#2551 Fix govt logo for all docx templates for AB#10854
  Apps/WebClient/src/Server/Assets/Templates/CovidReport.docx
  Apps/WebClient/src/Server/Assets/Templates/EncounterReport.docx
  Apps/WebClient/src/Server/Assets/Templates/ImmunizationReport.docx
  Apps/WebClient/src/Server/Assets/Templates/MedicationReport.docx
  Apps/WebClient/src/Server/Assets/Templates/MedicationRequestReport.docx
Labels: ready

#2550 Fix reports functional tests AB#10747
  Testing/functional/tests/cypress/integration/e2e/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/e2e/report/reportFiltering.js
Labels: ready

#2552 Added Imms recommendations to xlsx and csv with new headers for AB#10856
  Apps/WebClient/src/Server/Assets/Templates/ImmunizationReport.xlsx
Labels: ready

#2554 Design system Fonts AB#10357
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/fonts/BCSans-Bold.woff
  Apps/WebClient/src/ClientApp/src/assets/fonts/BCSans-Bold.woff2
  Apps/WebClient/src/ClientApp/src/assets/fonts/BCSans-BoldItalic.woff
  Apps/WebClient/src/ClientApp/src/assets/fonts/BCSans-BoldItalic.woff2
  Apps/WebClient/src/ClientApp/src/assets/fonts/BCSans-Italic.woff
  Apps/WebClient/src/ClientApp/src/assets/fonts/BCSans-Italic.woff2
  Apps/WebClient/src/ClientApp/src/assets/fonts/BCSans-Regular.woff
  Apps/WebClient/src/ClientApp/src/assets/fonts/BCSans-Regular.woff2
  Apps/WebClient/src/ClientApp/src/assets/fonts/MyriadWebPro.eot
  Apps/WebClient/src/ClientApp/src/assets/fonts/MyriadWebPro.svg
  Apps/WebClient/src/ClientApp/src/assets/fonts/MyriadWebPro.ttf
  Apps/WebClient/src/ClientApp/src/assets/fonts/MyriadWebPro.woff
  Apps/WebClient/src/ClientApp/src/assets/fonts/MyriadWebPro.woff2
  Apps/WebClient/src/ClientApp/src/assets/scss/_typography.scss
  Apps/WebClient/src/ClientApp/src/assets/scss/bcgov/_fonts.scss
  Apps/WebClient/src/ClientApp/src/assets/scss/bcgov/_variables.scss
  Apps/WebClient/src/ClientApp/src/assets/scss/hg-styles.scss
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/ClientApp/test/vueSetup.ts
Labels: enhancement, ready

#2555 Add HDID lookup to support page AB#10756
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/models/userFeedback.ts
  Apps/AdminWebClient/src/ClientApp/src/models/userQuery.ts
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Feedback.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
  Apps/AdminWebClient/src/Server/Constants/UserQueryType.cs
  Apps/AdminWebClient/src/Server/Models/UserFeedbackView.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
Labels: enhancement, ready, user story

#2558 Correct Verification Alert Grammar AB#10841
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#2559 Add clear button to filter input AB#10180
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/shared/hgButton.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/addComment.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
Labels: ready

#2563 Fix word wrapping AB#10870
  Apps/WebClient/src/ClientApp/src/components/monthYearPicker.vue
  Apps/WebClient/src/ClientApp/src/components/resourceCentre.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
Labels: ready

#2564 Fix test failure for AB#10873
  Testing/functional/tests/cypress/integration/e2e/user/profile.js
Labels: ready

#2565 Fixes Axios delete method AB#10506
  Apps/WebClient/src/ClientApp/src/services/httpDelegate.ts
Labels: ready

#2566 Add PHN to Profile for AB#10874
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: ready, user story

#2568 Imms card logo update - Features/10860
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-192x192.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-512x512.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-apple-touch-icon.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-favicon-16x16.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-favicon-32x32.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-mstile-144x144.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-mstile-150x150.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-mstile-310x150.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-mstile-310x310.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-mstile-70x70.png
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid02-favicon-32x32.png
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
Labels: UI, enhancement, ready

#2567 Fix wrapping on immunizationCard AB#10870
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
Labels: UI, ready

#2572 Add test for PHN on Profile for AB#10875
  Testing/functional/tests/cypress/integration/e2e/user/profile.js
Labels: functional tests, ready

#2569 Added mod check for PHN to dependent for AB#10720
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/utility/phnValidator.ts
Labels: ready, user story

#2573 Update landing page for AB#10703
  Apps/WebClient/src/ClientApp/src/assets/images/landing/006-BCServicesCardLogo.png
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready, user story

#2574 Fixes warnings detected by edge
  Apps/WebClient/src/ClientApp/public/index.html
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: bug, ready

#2581 Fix extra spacing in PDF report AB#10855
  Apps/WebClient/src/Server/Assets/Templates/ImmunizationReport.docx
Labels: ready

#2576 Fix functional tests for login and nav for AB#10887
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/integration/ui/pages/Login.js
Labels: bug, ready

#2582 Fixes broken layout on responsive screen AB#10871
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#2575 Add home screen icons for iOS and Android
  Apps/WebClient/src/ClientApp/public/apple-touch-icon.png
  Apps/WebClient/src/ClientApp/public/img/android-icon-128x128.png
  Apps/WebClient/src/ClientApp/public/img/android-icon-192x192.png
  Apps/WebClient/src/ClientApp/public/img/android-icon-48x48.png
  Apps/WebClient/src/ClientApp/public/img/android-icon-512x512.png
  Apps/WebClient/src/ClientApp/public/img/android-icon-72x72.png
  Apps/WebClient/src/ClientApp/public/img/android-icon-96x96.png
  Apps/WebClient/src/ClientApp/public/img/apple-icon-114x114.png
  Apps/WebClient/src/ClientApp/public/img/apple-icon-120x120.png
  Apps/WebClient/src/ClientApp/public/img/apple-icon-144x144.png
  Apps/WebClient/src/ClientApp/public/img/apple-icon-152x152.png
  Apps/WebClient/src/ClientApp/public/img/apple-icon-180x180.png
  Apps/WebClient/src/ClientApp/public/img/apple-icon-57x57.png
  Apps/WebClient/src/ClientApp/public/img/apple-icon-60x60.png
  Apps/WebClient/src/ClientApp/public/index.html
  Apps/WebClient/src/ClientApp/public/manifest.json
Labels: ready

#2584 Resolve patient promise when not querying AB#10891
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
Labels: ready

#2583 update positive covid test text AB#10869
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
Labels: ready

#2586 Fixed profile text size AB#10879
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: UI, bug, ready

#2588 Centered button icon AB#10893
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: UI, bug, ready

#2596 Added pr objectives. AB#10901
  .github/pull_request_template.md
Labels: documentation, ready

#2595 Updated label text. AB#10500
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: UI, ready

#2597 Config and Documentation to create Mock
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/Encounter/src/appsettings.hgmock.json
  Apps/Immunization/src/appsettings.hgmock.json
  Apps/JobScheduler/src/appsettings.hgmock.json
  Apps/Laboratory/src/appsettings.hgmock.json
  Apps/Medication/src/appsettings.hgmock.json
  Apps/Patient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgmock.json
  Tools/AzureAgent/README.md
  Tools/AzureAgent/openshift/AzureAgent.yaml
  Tools/AzureAgent/openshift/AzureAgentBuild.yaml
  Tools/AzureAgent/openshift/rb-dev.yaml
  Tools/AzureAgent/openshift/rb-tools.yaml
  Tools/BaseBuild/README.md
  Tools/BaseBuild/deploy_services.sh
  Tools/BaseBuild/nsp.yaml
  Tools/Postgres/README.md
Labels: ready, user story

#2598 Added tracker code to check for loading of data. AB#10916
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
Labels: ready

#2605 Fixed unittests and removed errors. AB#10931
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/ClientApp/test/vueSetup.ts
Labels: bug, ready

#2606 Added logic to prevent button from being active if no records present
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: UI, ready

#2608 Add Mock project AB#10903
  Apps/HealthGateway.code-workspace
  Apps/Mock/Dockerfile
  Apps/Mock/Mock.sln
  Apps/Mock/README.md
  Apps/Mock/azure/build.yaml
  Apps/Mock/azure/prbuild.yaml
  Apps/Mock/src/AssemblyInfo.cs
  Apps/Mock/src/Controllers/OdrController.cs
  Apps/Mock/src/Mock.csproj
  Apps/Mock/src/Mock.xml
  Apps/Mock/src/Program.cs
  Apps/Mock/src/Properties/launchSettings.json
  Apps/Mock/src/Startup.cs
  Apps/Mock/src/appsettings.json
  Apps/Mock/src/omnisharp.json
Labels: ready

#2609 Updated documentation and added mock test folder for AB#10904
  Testing/functional/tests/README.md
  Testing/functional/tests/cypress/integration/mock/authentication/auth.js
Labels: ready

#2610 Selector on Report Analytics - Features/10896
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#2611 Add ODR mock controller AB#10908
  Apps/Encounter/src/Delegates/RestMSPVisitDelegate.cs
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Mock/src/Assets/Encounter.json
  Apps/Mock/src/Assets/Medication.json
  Apps/Mock/src/Assets/ProtectiveWord.json
  Apps/Mock/src/Controllers/OdrController.cs
  Apps/Mock/src/Mock.csproj
  Apps/Mock/src/Mock.xml
  Apps/Mock/src/Models/OdrRequest.cs
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
Labels: ready

#2612 Add favicon for desktop browsers AB#10917
  Apps/WebClient/src/ClientApp/public/favicon.ico
  Apps/WebClient/src/ClientApp/public/img/favicon-16x16.png
  Apps/WebClient/src/ClientApp/public/img/favicon-32x32.png
  Apps/WebClient/src/ClientApp/public/index.html
Labels: enhancement, ready, user story

#2607 Move add note button to timeline page AB#10913
  Apps/WebClient/src/ClientApp/src/components/calendar/calendar.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/addNoteButton.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/calendarTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: UI, ready

#2613 Fixed issue with reports not showing. AB#10935
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: bug, ready

#2614 Create Salesforce controller for mock project AB#10907
  Apps/Mock/src/Assets/MedicationRequest.json
  Apps/Mock/src/Controllers/SalesforceController.cs
  Apps/Mock/src/Mock.csproj
  Apps/Mock/src/Mock.xml
Labels: ready

#2616 Fixed Report name & Improved logging. AB#10935
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/ClientApp/test/vueSetup.ts
Labels: bug, ready

#2618 Move add note button to timeline page AB#10913 (#2607)
  Apps/WebClient/src/ClientApp/src/components/calendar/calendar.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/addNoteButton.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/calendarTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/menu.js
Labels: enhancement, ready, user story

#2619 Trace notification setting responses from PHSA AB#10909
  Apps/Common/src/Delegates/RestNotificationSettingsDelegate.cs
Labels: ready

#2620 Fix padding on log in button AB#10940
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: UI, bug, ready

#2621 Update user profile to allow jwt email address AB#10924
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/src/Server/Services/IUserEmailService.cs
  Apps/WebClient/src/Server/Services/IUserProfileService.cs
  Apps/WebClient/src/Server/Services/UserEmailService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: ready

#2623 Load immunization records AB#10948
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: enhancement, ready, user story

#2627 Fixed functional tests for ODR integration. AB#10949
  Testing/functional/tests/cypress/support/commands.js
Labels: functional tests, ready

#2630 Create PHSA controller for mock project AB#10909
  Apps/Mock/src/Assets/Immunization.json
  Apps/Mock/src/Assets/Immunizations.json
  Apps/Mock/src/Assets/LabReport.json
  Apps/Mock/src/Assets/LaboratoryOrders.json
  Apps/Mock/src/Assets/NotificationSettings-Get.json
  Apps/Mock/src/Assets/NotificationSettings-Put.json
  Apps/Mock/src/Controllers/PhsaController.cs
  Apps/Mock/src/Mock.csproj
  Apps/Mock/src/Mock.xml
  Apps/Mock/src/Models/NotificationSettingRequest.cs
Labels: enhancement, ready

#2625 Prepopulate email on registration from external provider AB#10923
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/views/registration.vue
Labels: enhancement, ready

#2631 Added Patient service mock Tasks/10906
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Services/EndpointConfig.cs
  Apps/Mock/src/AssemblyInfo.cs
  Apps/Mock/src/Assets/Patient.xml
  Apps/Mock/src/Controllers/OdrController.cs
  Apps/Mock/src/Mock.csproj
  Apps/Mock/src/Mock.xml
  Apps/Mock/src/Models/OdrRequest.cs
  Apps/Mock/src/Program.cs
  Apps/Mock/src/Soap/Resources/(Asynchronous)PRPA_AR101002.wsdl
  Apps/Mock/src/Soap/Resources/(Asynchronous)PRPA_AR101202.wsdl
  Apps/Mock/src/Soap/Resources/(Synchronous)PRPA_AR101002.wsdl
  Apps/Mock/src/Soap/Resources/(Synchronous)PRPA_AR101202.wsdl
  Apps/Mock/src/Soap/Resources/PRPA_AR101006.wsdl
  Apps/Mock/src/Soap/Resources/PRPA_AR101201.wsdl
  Apps/Mock/src/Soap/Resources/QUPA_AR101102.wsdl
  Apps/Mock/src/Soap/Services/ClientRegistries.cs
  Apps/Mock/src/Soap/Services/Reference.cs
  Apps/Mock/src/Startup.cs
  Apps/Mock/src/appsettings.json
  Apps/Patient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#2633 Fixed protected word not popping up. AB#10933
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
Labels: bug, ready

#2629 BCSC Verified Email AB#10789
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/src/Server/Services/IUserEmailService.cs
  Apps/WebClient/src/Server/Services/IUserProfileService.cs
  Apps/WebClient/src/Server/Services/UserEmailService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: enhancement, needs attention, ready

#2632 Add covid card button to timeline AB#10961
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/immunization.js
Labels: UI, ready

#2634 Update endpoints for hgmock environment AB#10976
  Apps/Encounter/src/appsettings.hgmock.json
  Apps/Immunization/src/appsettings.hgmock.json
  Apps/JobScheduler/src/appsettings.hgmock.json
  Apps/Laboratory/src/appsettings.hgmock.json
  Apps/Medication/src/appsettings.hgmock.json
  Apps/Mock/src/Controllers/OdrController.cs
  Apps/WebClient/src/appsettings.Development.json
Labels: ready

#2635 Fix endpoints for hgmock environment AB#10976
  Apps/Encounter/src/appsettings.hgmock.json
  Apps/Immunization/src/appsettings.hgmock.json
  Apps/JobScheduler/src/appsettings.hgmock.json
  Apps/Laboratory/src/appsettings.hgmock.json
  Apps/Medication/src/appsettings.hgmock.json
  Apps/Patient/src/appsettings.hgmock.json
Labels: bug, ready

#2636 Separated database services configuration AB#10977
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.xml
  Apps/Encounter/src/Startup.cs
  Apps/Immunization/src/Startup.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Medication/src/Startup.cs
  Apps/Mock/src/Mock.xml
  Apps/Mock/src/Startup.cs
  Apps/Patient/src/Startup.cs
  Apps/WebClient/src/Server/Startup.cs
Labels: ready

#2637 Fixed immunization report date
  Apps/WebClient/src/Server/Assets/Templates/ImmunizationReport.docx
Labels: ready

#2641 Add mock routes and fixes Patient binding - Tasks/10979
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.xml
  Apps/Common/src/Services/EndpointConfig.cs
  Apps/Encounter/src/appsettings.hgmock.json
  Apps/Laboratory/src/appsettings.hgmock.json
  Apps/Medication/src/appsettings.hgmock.json
  Apps/Mock/src/Startup.cs
  Apps/Mock/src/appsettings.json
  Apps/Patient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgmock.json
Labels: ready

#2643 Validate PHN on server side for AB#11002
  Apps/Common/src/.gitignore
  Apps/Common/src/Common.xml
  Apps/Common/src/Services/PatientService.cs
  Apps/Common/src/Utils/PHNValidator.cs
  Apps/Common/test/unit/.gitignore
  Apps/Common/test/unit/CommonTests.xml
  Apps/Common/test/unit/Services/PatientServiceTests.cs
  Apps/Common/test/unit/Utils/PHNValidatorTests.cs
Labels: ready
