Repository bcgov/healthgateway, pull requests merged in 2021-11, with the labels that each got.

#2972 Clean up logic in VaccineStatusService AB#11607
  Apps/Immunization/src/Services/VaccineStatusService.cs
Labels: ready

#2975 Default sort to date descending on admin covid-19 immunizations for AB#11486
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: bug, ready

#2976 Display small landing banner when sidebar is shown AB#11613
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: bug, ready

#2974 Fix warnings and errors for AB#11619
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Delegates/PHSA/RestNotificationSettingsDelegate.cs
  Apps/Common/src/Delegates/PHSA/RestVaccineStatusDelegate.cs
  Apps/Common/src/Delegates/RestImmunizationDelegate.cs
  Apps/Common/src/Delegates/VaccineProofDelegate.cs
  Apps/Common/src/Services/NotificationSettingsService.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/Common/test/unit/Delegates/NotificationSettingsDelegateTests.cs
  Apps/Common/test/unit/Delegates/VaccineStatusDelegateTests.cs
  Apps/Common/test/unit/Delegates/WalletIssuerDelegateTests.cs
  Apps/Common/test/unit/Services/NotificationSettingsServiceTests.cs
  Apps/Common/test/unit/Swagger/SwaggerTests.cs
  Apps/Encounter/src/Delegates/RestMSPVisitDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Models/TargetDisease.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Medication/src/Delegates/SalesforeceDelegate.cs
  Apps/Medication/test/unit/Controllers/MedicationStatementControllerTests.cs
  Apps/Medication/test/unit/Delegates/SalesforceDelegateTests.cs
  Apps/WebClient/src/Properties/launchSettings.json
  Apps/WebClient/src/Server/Controllers/WalletController.cs
  Apps/WebClient/src/Server/Controllers/WalletStatusController.cs
  Apps/WebClient/src/Server/Listeners/BannerListener.cs
  Apps/WebClient/src/Server/Services/UserEmailService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/Views/Shared/Error.cshtml
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/test/unit/Controllers.Test/CommentControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/NoteControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/WalletControllerTests.cs
Labels: ready

#2978 Add navbar getters to determine if sidebar and footer are shown AB#11666
  Apps/WebClient/src/ClientApp/src/components/navmenu/navFooter.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/types.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/navbarStub.ts
Labels: ready

#2979 Add missing padding to Profile page AB#11670
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: bug, ready

#2977 Fix Unit Tests for VaccineStatusService AB#11648
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
Labels: unit tests, ready

#2983 Update error handling for empty vaccine proofs AB#11684
  Apps/Immunization/src/Services/VaccineStatusService.cs
Labels: bug, ready

#2984 Fix fragile functional tests for error pages AB#11688
  Testing/functional/tests/cypress/integration/ui/pages/errors.js
Labels: bug, ready

#2982 Apply Retry in Public Site and Functional test AB#11608
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/vaccinationStatusStub.ts
  Testing/functional/tests/cypress/fixtures/ImmunizationService/covidVaccineRecordLoaded.json
  Testing/functional/tests/cypress/fixtures/ImmunizationService/vaccineProofLoaded.json
  Testing/functional/tests/cypress/fixtures/ImmunizationService/vaccineProofNotLoaded.json
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/authenticatedWithRetry.js
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/publicSave.js
Labels: functional tests, ready

#2989 Add callout for "save as" PDF AB#11686
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready, UI

#2986 update release notes 1.4.14
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#2994 Upgrade Cypress to 8.7.0 for AB#11654
  Testing/functional/tests/README.md
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/fixtures/ImmunizationService/proofOfVaccination.json
  Testing/functional/tests/cypress/fixtures/ImmunizationService/vaccineProof.json
  Testing/functional/tests/cypress/integration/e2e/dashboard/proofOfVaccination.js
  Testing/functional/tests/cypress/integration/e2e/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/e2e/timeline/immunization.js
  Testing/functional/tests/cypress/integration/e2e/timeline/immunizationNoRecords.js
  Testing/functional/tests/cypress/integration/e2e/timeline/menu.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/authenticated.js
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/publicSave.js
  Testing/functional/tests/cypress/support/constants.js
  Testing/functional/tests/package-lock.json
  Testing/functional/tests/package.json
Labels: enhancement, functional tests

#2993 Standardize page margins AB#11679
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/errorCard.vue
  Apps/WebClient/src/ClientApp/src/components/shared/pageTitle.vue
  Apps/WebClient/src/ClientApp/src/views/contactUs.vue
  Apps/WebClient/src/ClientApp/src/views/dashboard.vue
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/faq.vue
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/termsOfService.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: bug, ready, UI

#2995 Refactor release notes page AB#11704
  Apps/WebClient/src/ClientApp/src/components/releaseNote.vue
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: enhancement, ready

#2996 Fix uncaught Promise exception for AB#11654
  Testing/functional/tests/cypress/support/index.js
Labels: bug, functional tests

#2997 Fix functional tests to run on Cypress 8.7.0 for AB#11654
  Testing/functional/tests/cypress/integration/e2e/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/e2e/timeline/immunization.js
  Testing/functional/tests/cypress/integration/e2e/timeline/immunizationNoRecords.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/immunization.js
Labels: bug, functional tests

#3007 Fix functional tests to run in Cypress 8.7.0 for AB#11654
  Testing/functional/tests/cypress/integration/e2e/report/immunizationInvalidDoses.js
  Testing/functional/tests/cypress/integration/e2e/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/e2e/timeline/immunization.js
  Testing/functional/tests/cypress/integration/e2e/timeline/immunizationInvalidDoses.js
  Testing/functional/tests/cypress/integration/e2e/timeline/immunizationNoRecords.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/immunization.js
Labels: bug, functional tests

#3012 Update to .Net 6
  Apps/AdminWebClient/Dockerfile
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/AdminWebClient/src/Properties/launchSettings.json
  Apps/AdminWebClient/test/unit/AdminWebClientTests.csproj
  Apps/Common/src/Common.csproj
  Apps/Common/test/unit/CommonTests.csproj
  Apps/DBMaintainer/DBMaintainer.csproj
  Apps/Database/src/Delegates/DBDrugLookupDelegate.cs
  Apps/Database/src/Delegates/DBEmailDelegate.cs
  Apps/Database/src/Delegates/DBFeedbackDelegate.cs
  Apps/Database/src/Delegates/DBNoteDelegate.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/test/unit/DatabaseTests.csproj
  Apps/Directory.Build.props
  Apps/Encounter/Dockerfile
  Apps/Encounter/src/Encounter.csproj
  Apps/Encounter/src/Models/EncounterModel.cs
  Apps/Encounter/test/unit/EncounterTests.csproj
  Apps/Immunization/Dockerfile
  Apps/Immunization/src/Immunization.csproj
  Apps/Immunization/test/unit/ImmunizationTests.csproj
  Apps/JobScheduler/Dockerfile
  Apps/Laboratory/Dockerfile
  Apps/Laboratory/src/Laboratory.csproj
  Apps/Laboratory/test/unit/LaboratoryTests.csproj
  Apps/Medication/Dockerfile
  Apps/Medication/src/Medication.csproj
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/test/unit/MedicationTests.csproj
  Apps/Mock/Dockerfile
  Apps/Mock/src/Mock.csproj
  Apps/Patient/Dockerfile
  Apps/Patient/src/Patient.csproj
  Apps/Patient/test/unit/PatientTests.csproj
  Apps/WebClient/Dockerfile
  Apps/WebClient/src/Server/Listeners/BannerListener.cs
  Apps/WebClient/src/Server/Services/DependentService.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/WebClientTests.csproj
  Apps/global.json
  Tools/BaseImage/build.yaml
  Tools/BaseImage/docker/Dockerfile
Labels: ready

#3013 Fix 'Admin not showing logged in users on dashboard' for AB#11351
  Apps/AdminWebClient/src/appsettings.json
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
Labels: bug

#3006 Fix bug when no pdf found in Public site AB#11711
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/vaccinationStatusStub.ts
  Testing/functional/tests/cypress/fixtures/ImmunizationService/vaccineProofLoadedNoPdf.json
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/publicSave.js
Labels: bug, functional tests, ready

#3008 Ambiguous error message for overlapping banner posts in admin site AB#10890
  Apps/AdminWebClient/src/ClientApp/src/components/core/CommunicationTable.vue
  Apps/AdminWebClient/test/unit/Controllers.Test/CommunicationControllerTests.cs
  Apps/Database/src/Delegates/DBCommunicationDelegate.cs
  Apps/Database/src/Migrations/20211109195934_AdminAllowOverlapMultipleStatus.Designer.cs
  Apps/Database/src/Migrations/20211109195934_AdminAllowOverlapMultipleStatus.cs
Labels: bug, unit tests, ready, UI

#3016 Fix uncaught promise exception for AB#11710
  Apps/WebClient/src/ClientApp/src/views/loginCallback.vue
  Testing/functional/tests/cypress/support/index.js
Labels: functional tests

#3020 Update functional test AB#11727
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/publicSave.js
Labels: bug, functional tests, ready

#3021 Upgrade Cypress Functional Testing framework to 9.0.0 for AB#11721
  Testing/functional/tests/package-lock.json
  Testing/functional/tests/package.json
Labels: enhancement, functional tests

#3017 Refactor User Profile unit tests AB#10077
  Apps/WebClient/test/unit/Services.Test/Constants/TestConstants.cs
  Apps/WebClient/test/unit/Services.Test/Mock/ConfigServiceMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/CryptoDelegateMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/EmailQueueServiceMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/HttpContextAccessorMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/LegalAgreementDelegateMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/MessagingVerificationDelegateMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/NotificationSettingsServiceMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/PatientServiceMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/UserPreferenceDelegateMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/UserProfileDelegateMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: unit tests, ready

#3022 Standardize button names and capitalization AB#10800
  Apps/WebClient/src/ClientApp/src/components/modal/deleteConfirmation.vue
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/verifySMS.vue
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/login.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/registrationInfo.vue
Labels: bug, ready, UI

#3018 Don't show the comment section when config is disabled AB#8668
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/comments.js
Labels: bug, functional tests, ready, UI

#3025 Update deprecated cypress code for AB#11736
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
Labels: enhancement, functional tests

#3024 Fix UI Navigation guard AB#11079
  Apps/WebClient/src/ClientApp/src/router.ts
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/integration/ui/pages/dashboard.js
Labels: bug, functional tests, ready

#3026 Disable Edit button when reach expired date time AB#10488
  Apps/AdminWebClient/src/ClientApp/src/components/core/CommunicationTable.vue
Labels: bug, ready

#3028 Fix functional test not using fixture for AB#11744
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/immunization.js
Labels: functional tests

#3034 Fix uncaught promise in public and authenticated AB#11746
  Apps/WebClient/src/ClientApp/src/views/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: bug, ready

#3036 Reorder Dashboard cards AB#11762
  Apps/WebClient/src/ClientApp/src/views/dashboard.vue
Labels: UI

#3035 Update text for public vaccine card for AB#11761
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready, UI

#3037 Resolve dashboard query issues with updated EF for AB#11796
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/DBRatingDelegate.cs
  Apps/Database/src/Delegates/IRatingDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
Labels: bug, ready

#3042 Add FK in UserPreference Table AB#9687
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Migrations/20211118173135_AddFkInUserPreferenceTable.Designer.cs
  Apps/Database/src/Migrations/20211118173135_AddFkInUserPreferenceTable.cs
Labels: bug, ready

#3043 Sort export records in reverse chronological order AB#11675
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
Labels: bug, enhancement, ready

#3044 Update delegate, service and model to add list of last login date time AB#11775
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/WebClient/src/Server/Models/UserProfileModel.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/appsettings.json
Labels: enhancement, ready

#3049 Resolves Hangfire jobid issue and new warnings for AB#11812
  Apps/Common/src/Models/ODR/ODRHistoryResponse.cs
  Apps/Common/src/Models/ODR/ODRHistoryWrapper.cs
  Apps/Directory.Build.props
  Apps/JobScheduler/src/Startup.cs
  Apps/Medication/src/Models/ODR/ProtectiveWord.cs
Labels: bug, ready

#3047 Add controller and model for public COVID-19 test results AB#11798
  Apps/Immunization/src/Controllers/PublicVaccineStatusController.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
  Apps/Laboratory/src/Models/PublicCovidTestResponse.cs
Labels: enhancement, ready

#3048 Update UI to display up to 5 logins AB#11774
  Apps/WebClient/src/ClientApp/src/models/userProfile.ts
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: ready, UI

#3052 Update unit tests for displaying last login date time AB#11805
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/WebClient/test/unit/Services.Test/Mock/UserProfileDelegateMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileServiceTests.cs
  Apps/WebClient/test/unit/UnitTest.json
Labels: unit tests, ready

#3051 Fix migration issue AB#9687
  Apps/Database/src/Migrations/20211118173135_AddFkInUserPreferenceTable.cs
Labels: bug, ready

#3054 Profile History Functional Test AB#11776
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfile.json
  Testing/functional/tests/cypress/integration/e2e/user/profile.js
Labels: functional tests, ready

#3053 Refactor Common Startup code for AB#11814
  Apps/Common/src/AspNetConfiguration/Modules/Audit.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Common/src/AspNetConfiguration/Modules/Db.cs
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Apps/Common/src/AspNetConfiguration/Modules/JobScheduler.cs
  Apps/Common/src/AspNetConfiguration/Modules/Patient.cs
  Apps/Common/src/AspNetConfiguration/Modules/SwaggerDoc.cs
  Apps/Common/src/AspNetConfiguration/Modules/Utility.cs
  Apps/Common/src/AspNetConfiguration/ProgramConfiguration.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.csproj
  Apps/Patient/src/Program.cs
  Apps/Patient/src/Startup.cs
  Apps/WebClient/test/unit/Services.Test/UserSMSServiceTests.cs
Labels: enhancement, ready

#3055 Feature add login History to Profile AB#11667
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/WebClient/src/ClientApp/src/models/userProfile.ts
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/Server/Models/UserProfileModel.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Services.Test/Mock/UserProfileDelegateMock.cs
  Apps/WebClient/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileServiceTests.cs
  Apps/WebClient/test/unit/UnitTest.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfile.json
  Testing/functional/tests/cypress/integration/e2e/user/profile.js
Labels: enhancement, functional tests, unit tests, ready, user story, UI

#3056 Integrate Admin to Common
  Apps/Admin/Admin.sln
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
Labels: enhancement, ready

#3058 Update bugfix label on pull request template AB#11730
  .github/pull_request_template.md
Labels: bugfix, ready

#3057 Landing Page Public COVID Test AB#11787
  Apps/WebClient/src/ClientApp/src/assets/images/landing/007_background-covid-test.png
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/appsettings.json
Labels: ready, UI

#3064 Admin Security
  Apps/Admin/Client/Pages/Index.razor
  Apps/Admin/Client/Pages/Index.razor.cs
  Apps/Admin/Server/Admin.Server.csproj
  Apps/Admin/Server/Assets/Templates/CovidCard.docx
  Apps/Admin/Server/Constants/UserInviteStatus.cs
  Apps/Admin/Server/Constants/UserQueryType.cs
  Apps/Admin/Server/Controllers/CommunicationController.cs
  Apps/Admin/Server/Controllers/ConfigurationController.cs
  Apps/Admin/Server/Controllers/CovidSupportController.cs
  Apps/Admin/Server/Controllers/CsvExportController.cs
  Apps/Admin/Server/Controllers/DashboardController.cs
  Apps/Admin/Server/Controllers/EmailAdminController.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Server/Controllers/TagController.cs
  Apps/Admin/Server/Controllers/UserFeedbackController.cs
  Apps/Admin/Server/Delegates/IImmunizationAdminDelegate.cs
  Apps/Admin/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/Admin/Server/Mappers/CommentCsvMap.cs
  Apps/Admin/Server/Mappers/NoteCsvMap.cs
  Apps/Admin/Server/Mappers/UserProfileCsvMap.cs
  Apps/Admin/Server/Models/AdminConfiguration.cs
  Apps/Admin/Server/Models/AdminEmail.cs
  Apps/Admin/Server/Models/AdminTagView.cs
  Apps/Admin/Server/Models/Communication.cs
  Apps/Admin/Server/Models/ContentSecurityPolicyConfig.cs
  Apps/Admin/Server/Models/CovidSupport/CovidInformation.cs
  Apps/Admin/Server/Models/CovidSupport/MailDocumentRequest.cs
  Apps/Admin/Server/Models/CovidSupport/VaccineDetails.cs
  Apps/Admin/Server/Models/CovidSupport/VaccineDose.cs
  Apps/Admin/Server/Models/DocumentStorageConfiguration.cs
  Apps/Admin/Server/Models/ExternalConfiguration.cs
  Apps/Admin/Server/Models/ForwardProxiesConfiguration.cs
  Apps/Admin/Server/Models/Immunization/CovidImmunizationsRequest.cs
  Apps/Admin/Server/Models/Immunization/EmpiDataResponse.cs
  Apps/Admin/Server/Models/Immunization/LoadStateModel.cs
  Apps/Admin/Server/Models/Immunization/VaccineDetailsResponse.cs
  Apps/Admin/Server/Models/Immunization/VaccineDoseResponse.cs
  Apps/Admin/Server/Models/OpenIdConnectConfiguration.cs
  Apps/Admin/Server/Models/TimeoutsConfiguration.cs
  Apps/Admin/Server/Models/UserFeedbackTagView.cs
  Apps/Admin/Server/Models/UserFeedbackView.cs
  Apps/Admin/Server/Models/UserProfile.cs
  Apps/Admin/Server/Parsers/Immunization/VaccineDoseParser.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/CommunicationService.cs
  Apps/Admin/Server/Services/ConfigurationService.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/DashboardService.cs
  Apps/Admin/Server/Services/EmailAdminService.cs
  Apps/Admin/Server/Services/ICommunicationService.cs
  Apps/Admin/Server/Services/IConfigurationService.cs
  Apps/Admin/Server/Services/ICovidSupportService.cs
  Apps/Admin/Server/Services/ICsvExportService.cs
  Apps/Admin/Server/Services/IDashboardService.cs
  Apps/Admin/Server/Services/IEmailAdminService.cs
  Apps/Admin/Server/Services/IUserFeedbackService.cs
  Apps/Admin/Server/Services/UserFeedbackService.cs
  Apps/Common/src/Auditing/AuditLogger.cs
Labels: enhancement, ready

#3067 Squash HG and Minor cleanup
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Properties/launchSettings.json
  Apps/Admin/Client/Store/Configuration/LoadEffect.cs
  Apps/Admin/Client/Store/Configuration/Reducers.cs
  Apps/Admin/Client/wwwroot/manifest.json
  Apps/Admin/Server/Admin.Server.csproj
  Apps/Admin/Server/Properties/launchSettings.json
Labels: bugfix, ready

#3066 Added functional tests for Immunization recommendation AB#11829
  Testing/functional/tests/cypress/fixtures/Report/immunizationUnSorted.json
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: bugfix, functional tests, ready

#3069 Update controller to include multiple test responses AB#11817
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
  Apps/Laboratory/src/Models/PublicCovidTestResponseResult.cs
Labels: enhancement, ready

#3070 Fix IsLoading property of MudProgressLinear in Claim page AB#11848
  Apps/Admin/Client/Pages/Claims.razor
Labels: bugfix, ready

#3065 Fix Verify SMS Number AB#11821
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileSMSVerified.json
  Testing/functional/tests/cypress/integration/e2e/user/profile.js
Labels: bugfix, functional tests, ready

#3068 Rearrange functional tests AB#10996 #10995 #10994
  Apps/Mock/src/Assets/Medication.json
  Apps/Mock/src/Assets/Patient.xml
  Testing/functional/tests/cypress/integration/e2e/timeline/immunizationNoRecords.js
  Testing/functional/tests/cypress/integration/mock/healthinsights/insights.js
  Testing/functional/tests/cypress/integration/mock/pages/Registration.js
  Testing/functional/tests/cypress/integration/mock/pages/communication.js
  Testing/functional/tests/cypress/integration/mock/report/report.js
  Testing/functional/tests/cypress/integration/mock/resourceCentre/resourceCentre.js
  Testing/functional/tests/cypress/integration/mock/services/encounter.js
  Testing/functional/tests/cypress/integration/mock/services/immunization.js
  Testing/functional/tests/cypress/integration/mock/services/laboratory.js
  Testing/functional/tests/cypress/integration/mock/services/medication.js
  Testing/functional/tests/cypress/integration/mock/services/patient.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/comment.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/communication.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/dependent.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/note.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/userFeedback.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/userProfile.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/webClient.js
  Testing/functional/tests/cypress/integration/mock/timeline/calendar.js
  Testing/functional/tests/cypress/integration/mock/timeline/comments.js
  Testing/functional/tests/cypress/integration/mock/timeline/encounter.js
  Testing/functional/tests/cypress/integration/mock/timeline/filter.js
  Testing/functional/tests/cypress/integration/mock/timeline/medication.js
  Testing/functional/tests/cypress/integration/mock/timeline/mobile/encounter.js
  Testing/functional/tests/cypress/integration/mock/timeline/mobile/medication.js
  Testing/functional/tests/cypress/integration/mock/timeline/modals/protectiveWordModal.js
  Testing/functional/tests/cypress/integration/mock/timeline/notes.js
  Testing/functional/tests/cypress/integration/mock/timeline/pagination.js
  Testing/functional/tests/cypress/integration/mock/user/dependents.js
  Testing/functional/tests/cypress/integration/mock/user/feedback.js
  Testing/functional/tests/cypress/integration/mock/user/profile.js
  Testing/functional/tests/cypress/integration/mock/user/starRating.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/report/reportFiltering.js
  Testing/functional/tests/cypress/integration/ui/resourceCentre/covidcard.js
  Testing/functional/tests/cypress/integration/ui/timeline/errors.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/medicationrequest.js
  Testing/functional/tests/cypress/integration/ui/timeline/menu.js
  Testing/functional/tests/cypress/integration/ui/timeline/misc.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratory.js
  Testing/functional/tests/cypress/integration/ui/timeline/modals/covidModal.js
  Testing/functional/tests/cypress/integration/ui/user/emailValidation.js
  Testing/functional/tests/cypress/integration/ui/user/tutorial.js
Labels: functional tests, ready

#3075 Rearrange functional tests AB#10996 #10995 #10994 (#3068)
  Apps/Mock/src/Assets/Medication.json
  Apps/Mock/src/Assets/Patient.xml
  Testing/functional/tests/cypress/integration/e2e/timeline/immunizationNoRecords.js
  Testing/functional/tests/cypress/integration/mock/healthinsights/insights.js
  Testing/functional/tests/cypress/integration/mock/pages/Registration.js
  Testing/functional/tests/cypress/integration/mock/pages/communication.js
  Testing/functional/tests/cypress/integration/mock/report/report.js
  Testing/functional/tests/cypress/integration/mock/resourceCentre/resourceCentre.js
  Testing/functional/tests/cypress/integration/mock/services/encounter.js
  Testing/functional/tests/cypress/integration/mock/services/immunization.js
  Testing/functional/tests/cypress/integration/mock/services/laboratory.js
  Testing/functional/tests/cypress/integration/mock/services/medication.js
  Testing/functional/tests/cypress/integration/mock/services/patient.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/comment.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/communication.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/dependent.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/note.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/userFeedback.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/userProfile.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/webClient.js
  Testing/functional/tests/cypress/integration/mock/timeline/calendar.js
  Testing/functional/tests/cypress/integration/mock/timeline/comments.js
  Testing/functional/tests/cypress/integration/mock/timeline/encounter.js
  Testing/functional/tests/cypress/integration/mock/timeline/filter.js
  Testing/functional/tests/cypress/integration/mock/timeline/medication.js
  Testing/functional/tests/cypress/integration/mock/timeline/mobile/encounter.js
  Testing/functional/tests/cypress/integration/mock/timeline/mobile/medication.js
  Testing/functional/tests/cypress/integration/mock/timeline/modals/protectiveWordModal.js
  Testing/functional/tests/cypress/integration/mock/timeline/notes.js
  Testing/functional/tests/cypress/integration/mock/timeline/pagination.js
  Testing/functional/tests/cypress/integration/mock/user/dependents.js
  Testing/functional/tests/cypress/integration/mock/user/feedback.js
  Testing/functional/tests/cypress/integration/mock/user/profile.js
  Testing/functional/tests/cypress/integration/mock/user/starRating.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/report/reportFiltering.js
  Testing/functional/tests/cypress/integration/ui/resourceCentre/covidcard.js
  Testing/functional/tests/cypress/integration/ui/timeline/errors.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/medicationrequest.js
  Testing/functional/tests/cypress/integration/ui/timeline/menu.js
  Testing/functional/tests/cypress/integration/ui/timeline/misc.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratory.js
  Testing/functional/tests/cypress/integration/ui/timeline/modals/covidModal.js
  Testing/functional/tests/cypress/integration/ui/user/emailValidation.js
  Testing/functional/tests/cypress/integration/ui/user/tutorial.js
Labels: functional tests, ready

#3072 Build Blazor
  Apps/Admin/Client/Properties/launchSettings.json
  Apps/Admin/Dockerfile
  Apps/Admin/Server/Properties/launchSettings.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Tests/Admin.Tests.csproj
  Apps/Admin/azure/build.yaml
  Apps/Admin/azure/prbuild.yaml
  Build/hg-steps-template.yaml
  Build/hg.yaml
Labels: enhancement, ready

#3074 Create public covid test pages for AB#11788.
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/laboratory.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
Labels: enhancement, ready, UI
