Repository bcgov/healthgateway, pull requests merged in 2021-09, with the labels that each got.

#2754 Update public vaccine card form and landing page AB#11089
  Apps/Immunization/src/Controllers/VaccineStatusController.cs
  Apps/Immunization/src/Delegates/CaptchaDelegate.cs
  Apps/Immunization/src/Delegates/ICaptchaDelegate.cs
  Apps/Immunization/src/Delegates/RestVaccineStatusDelegate.cs
  Apps/Immunization/src/Models/CaptchaConfig.cs
  Apps/Immunization/src/Models/CaptchaVerificationResponse.cs
  Apps/Immunization/src/Models/VaccineStatus.cs
  Apps/Immunization/src/Models/VaccineStatusQuery.cs
  Apps/Immunization/src/Models/VaccineStatusResult.cs
  Apps/Immunization/src/Services/IVaccineStatusService.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/src/appsettings.json
  Apps/Immunization/test/unit/Controllers.Test/VaccineStatusControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/CaptchaDelegateTests.cs
  Apps/Immunization/test/unit/ImmunizationTests.xml
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/assets/images/landing/vaccination-status-banner-image.png
  Apps/WebClient/src/ClientApp/src/assets/images/vaccine-card/vaccine-card-banner-image.svg
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgIcon.vue
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/models/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restVaccinationStatusService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#2757 Allow empty passphrase and update config for new provider for AB#11148
  Apps/AdminWebClient/src/Server/Delegates/SFTPMailDelegate.cs
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/AdminWebClient/src/appsettings.hgdev.json
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/AdminWebClient/src/appsettings.hgpoc.json
  Apps/AdminWebClient/src/appsettings.hgtest.json
  Apps/AdminWebClient/src/appsettings.json
Labels: ready

#2762 Fixes hdid on admin web client vax status request AB#11233
  Apps/Common/src/Delegates/PHSA/RestVaccineStatusDelegate.cs
Labels: ready

#2763 Update vaccine card for authenticated users AB#11149 AB#111230
  Apps/Common/src/Models/PHSA/VaccineStatus.cs
  Apps/Immunization/src/Controllers/AuthenticatedVaccineStatusController.cs
  Apps/Immunization/src/Controllers/VaccineStatusController.cs
  Apps/Immunization/src/Services/IImmunizationService.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/images/vaccination-status/dose-1.svg
  Apps/WebClient/src/ClientApp/src/assets/images/vaccination-status/dose-2.svg
  Apps/WebClient/src/ClientApp/src/assets/images/vaccination-status/fully-vaccinated.svg
  Apps/WebClient/src/ClientApp/src/assets/images/vaccination-status/no-doses.svg
  Apps/WebClient/src/ClientApp/src/components/modal/covidTestModal.vue
  Apps/WebClient/src/ClientApp/src/components/modal/vaccineCardModal.vue
  Apps/WebClient/src/ClientApp/src/components/resourceCentre.vue
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/components/vaccineCard.vue
  Apps/WebClient/src/ClientApp/src/models/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restImmunizationService.ts
  Apps/WebClient/src/ClientApp/src/services/restVaccinationStatusService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/views/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#2764 Fix spacing error
  .editorconfig
  Apps/Immunization/src/Services/ImmunizationService.cs
Labels: ready

#2765 Add snowplow events to public vax card AB#11214
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready

#2769 Vaccine card UI updates AB#11249 AB#11219
  Apps/WebClient/src/ClientApp/src/assets/images/landing/vaccine-card-banner-bg-lg.svg
  Apps/WebClient/src/ClientApp/src/assets/images/landing/vaccine-card-banner-bg-sm.svg
  Apps/WebClient/src/ClientApp/src/assets/images/landing/vaccine-card-banner-icon-lg.svg
  Apps/WebClient/src/ClientApp/src/assets/images/landing/vaccine-card-banner-icon-sm.svg
  Apps/WebClient/src/ClientApp/src/assets/images/vaccine-card/vaccine-card-banner-image.svg
  Apps/WebClient/src/ClientApp/src/components/vaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready

#2771 Update vaccine card form to match mockup AB#11251
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready

#2775 Update UI on vaccine card form AB#11262 AB#11265
  Apps/WebClient/src/ClientApp/src/components/shared/hgDateDropdown.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready

#2785 Fix vaccine card timezone bugs AB#11267 AB#11266
  Apps/Common/src/Delegates/ReportDelegate.cs
  Apps/WebClient/src/ClientApp/src/components/vaccineCard.vue
Labels: bug, ready

#2788 Update messaging and buttons on vaccine card AB#11282
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/vaccineCardModal.vue
  Apps/WebClient/src/ClientApp/src/components/vaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready

#2789 Retry PHSA requests in admin COVID support service AB#11285
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/Common/src/Delegates/PHSA/IVaccineStatusDelegate.cs
  Apps/Common/src/Delegates/PHSA/RestVaccineStatusDelegate.cs
Labels: bug, ready

#2791 Resolve PHN input issues for AB#11316
  Apps/AdminWebClient/src/ClientApp/src/utility/phnValidator.ts
  Apps/Common/src/Utils/PHNValidator.cs
  Apps/Common/test/unit/Utils/PHNValidatorTests.cs
  Apps/WebClient/src/ClientApp/src/utility/masks.ts
  Apps/WebClient/src/ClientApp/src/utility/phnValidator.ts
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/WebClient.csproj
Labels: ready

#2793 Add functionality to save vaccine card image AB#11281
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/modal/vaccineCardModal.vue
  Apps/WebClient/src/ClientApp/src/components/vaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready

#2794 Update privacy statement on vaccine card form AB#11287
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready

#2804 Fix spacing around callout on vaccine card AB#11248
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: bug, ready

#2805 Stop retrieving vaccination history for mailed documents AB#11317
  Apps/AdminWebClient/src/Server/Controllers/CovidSupportController.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/Server/Services/ICovidSupportService.cs
  Apps/Common/src/Delegates/IReportDelegate.cs
  Apps/Common/src/Delegates/ReportDelegate.cs
Labels: ready

#2812 Update mock routes AB#10979
  Apps/Immunization/src/appsettings.hgmock.json
  Apps/Mock/src/appsettings.Development.json
  Apps/Mock/src/appsettings.json
Labels: ready

#2815 Implements VaccineStatus on mock env
  Apps/Mock/src/Assets/VaccineStatus.json
  Apps/Mock/src/Controllers/OdrController.cs
  Apps/Mock/src/Controllers/PhsaController.cs
  Apps/Mock/src/Controllers/SalesforceController.cs
  Apps/Mock/src/Mock.csproj
  Apps/Mock/src/Mock.xml
Labels: ready

#2816 Display data mismatch error instead of not found AB#11301
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
Labels: ready

#2817 Remove data that is no longer used in PDF template AB#11229
  Apps/Common/src/Delegates/ReportDelegate.cs
Labels: bug

#2821 Vaccine Card Functional Tests AB#11339 and Date Dropdown Bug Fix AB#11370
  Apps/WebClient/src/ClientApp/src/components/modal/vaccineCardModal.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgDateDropdown.vue
  Apps/WebClient/src/ClientApp/src/components/vaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Testing/functional/tests/cypress.json
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/authenticated.js
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/public.js
  Testing/functional/tests/cypress/integration/ui/pages/vaccineCard.js
Labels: ready

#2832 Remove invalid doses from admin AB#11359
  Apps/AdminWebClient/src/ClientApp/src/models/covidCardPatientResult.ts
  Apps/AdminWebClient/src/ClientApp/src/models/immunizationModel.ts
  Apps/AdminWebClient/src/ClientApp/src/models/vaccineDetails.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/Server/Controllers/CovidSupportController.cs
  Apps/AdminWebClient/src/Server/Delegates/IImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidInformation.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/MailDocumentRequest.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/VaccineDetails.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/VaccineDose.cs
  Apps/AdminWebClient/src/Server/Models/Immunization/CovidImmunizationsRequest.cs
  Apps/AdminWebClient/src/Server/Models/Immunization/EmpiDataResponse.cs
  Apps/AdminWebClient/src/Server/Models/Immunization/VaccineDetailsResponse.cs
  Apps/AdminWebClient/src/Server/Models/Immunization/VaccineDoseResponse.cs
  Apps/AdminWebClient/src/Server/Models/Support/CovidInformation.cs
  Apps/AdminWebClient/src/Server/Models/Support/CovidReport.cs
  Apps/AdminWebClient/src/Server/Models/Support/ReportAddress.cs
  Apps/AdminWebClient/src/Server/Parsers/Immunization/AgentParser.cs
  Apps/AdminWebClient/src/Server/Parsers/Immunization/EventParser.cs
  Apps/AdminWebClient/src/Server/Parsers/Immunization/ForecastParser.cs
  Apps/AdminWebClient/src/Server/Parsers/Immunization/VaccineDoseParser.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/Server/Services/ICovidSupportService.cs
Labels: ready, user story

#2829 Remove Dose 2 Update info from timeline AB#11383
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/immunization.js
Labels: ready

#2828 Remove invalid doses from COVID-19 page and vaccine card AB#11366
  Apps/Common/src/Models/Immunization/ImmunizationEvent.cs
  Apps/Common/src/Models/PHSA/ImmunizationViewResponse.cs
  Apps/Immunization/src/Parsers/EventParser.cs
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/test/credential.test.ts
  Testing/functional/tests/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/tests/cypress/fixtures/ImmunizationService/immunizationEmptyName.json
  Testing/functional/tests/cypress/integration/e2e/timeline/immunization.js
Labels: ready, user story

#2836 Remove auto-generating .xml docs from source control AB#11400
  Apps/AdminWebClient/test/unit/.gitignore
  Apps/AdminWebClient/test/unit/AdminWebClientTests.xml
  Apps/DBMaintainer/.gitignore
  Apps/DBMaintainer/DBMaintainer.xml
  Apps/Database/src/.gitignore
  Apps/Database/src/Database.xml
  Apps/Database/test/unit/.gitignore
  Apps/Database/test/unit/DatabaseTests.xml
  Apps/Encounter/src/.gitignore
  Apps/Encounter/src/Encounter.xml
  Apps/Encounter/test/unit/.gitignore
  Apps/Encounter/test/unit/EncounterTests.xml
  Apps/Immunization/test/unit/.gitignore
  Apps/Immunization/test/unit/ImmunizationTests.xml
  Apps/JobScheduler/src/.gitignore
  Apps/JobScheduler/src/JobScheduler.xml
  Apps/Laboratory/src/.gitignore
  Apps/Laboratory/src/Laboratory.xml
  Apps/Laboratory/test/unit/.gitignore
  Apps/Laboratory/test/unit/LaboratoryTests.xml
  Apps/Medication/src/.gitignore
  Apps/Medication/src/Medication.xml
  Apps/Medication/test/unit/.gitignore
  Apps/Medication/test/unit/MedicationTests.xml
  Apps/Mock/src/.gitignore
  Apps/Mock/src/Mock.xml
  Apps/Patient/test/unit/.gitignore
  Apps/Patient/test/unit/PatientTests.xml
  Apps/WebClient/test/unit/.gitignore
  Apps/WebClient/test/unit/WebClientTests.xml
Labels: ready

#2835 Add Refresh Button to Covid 19 Immunizations on Admin BC Vaccine Card for AB#11377 and AB#11378
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restCovidSupportService.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/Server/Controllers/CovidSupportController.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
Labels: ready

#2837 Resolve Low priority job issues for AB#11399
  Apps/Database/src/Delegates/DBEmailDelegate.cs
  Apps/JobScheduler/src/appsettings.json
Labels: ready

#2839 Display error message on COVID support page for blocked PHNs AB#11402
  Apps/AdminWebClient/src/ClientApp/src/models/covidCardPatientResult.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidInformation.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/VaccineDetails.cs
  Apps/AdminWebClient/src/Server/Models/Immunization/VaccineDetailsResponse.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
Labels: ready
