Repository bcgov/healthgateway, pull requests merged in 2021-12, with the labels that each got.

#3080 Add unit test for AB#11876
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
  Apps/WebClient/src/ClientApp/test/router.test.ts
Labels: unit tests, ready

#3090 Revert EF Core 6 Upgrade
  Apps/Common/src/Common.csproj
  Apps/DBMaintainer/DBMaintainer.csproj
  Apps/DBMaintainer/Parsers/FederalDrugProductParser.cs
  Apps/DBMaintainer/Parsers/PharmaCareDrugParser.cs
  Apps/Database/src/Database.csproj
  Apps/Database/src/Delegates/DBNoteDelegate.cs
  Apps/Database/src/Migrations/20211110202507_ef6upgrade.Designer.cs
  Apps/Database/src/Migrations/20211110202507_ef6upgrade.cs
  Apps/Database/src/Migrations/20211115195258_NoteJournalDateOnly.Designer.cs
  Apps/Database/src/Migrations/20211115195258_NoteJournalDateOnly.cs
  Apps/Database/src/Migrations/20211115195505_RenameNoteJournalDate.Designer.cs
  Apps/Database/src/Migrations/20211118173135_AddFkInUserPreferenceTable.cs
  Apps/Database/src/Migrations/20211202201731_AddFkInUserPreferenceTable.Designer.cs
  Apps/Database/src/Migrations/20211202201731_AddFkInUserPreferenceTable.cs
  Apps/Database/src/Migrations/GatewayDbContextModelSnapshot.cs
  Apps/Database/src/Models/Note.cs
  Apps/JobScheduler/src/JobScheduler.csproj
  Apps/JobScheduler/src/Startup.cs
  Apps/WebClient/src/Server/Models/UserNote.cs
Labels: bugfix, ready

#3088 Fix route issue for nav bar for covidtest and vaccinecard for AB#11898
  Apps/WebClient/src/ClientApp/src/app.vue
Labels: ready, UI

#3082 Fixed failing mock tests AB#11886
  Apps/Mock/src/Assets/CovidImmunizations.json
  Apps/Mock/src/Assets/Immunization.json
  Apps/Mock/src/Assets/Immunizations.json
  Apps/Mock/src/Assets/Patient.xml
  Apps/Mock/src/Assets/VaccineStatus.json
Labels: ready, do not merge

#3079 Configure new projects for AB#11882
  Apps/Common/src/Common.csproj
  Apps/Common/src/Services/PatientService.cs
  Apps/CommonData/CommonData.sln
  Apps/CommonData/README.md
  Apps/CommonData/azure/build.yaml
  Apps/CommonData/azure/prbuild.yaml
  Apps/CommonData/src/.gitignore
  Apps/CommonData/src/AssemblyInfo.cs
  Apps/CommonData/src/Common.Data.csproj
  Apps/CommonData/src/Utils/PhnValidator.cs
  Apps/CommonData/src/omnisharp.json
  Apps/CommonData/test/unit/.gitignore
  Apps/CommonData/test/unit/AssemblyInfo.cs
  Apps/CommonData/test/unit/CommonDataTests.csproj
  Apps/CommonData/test/unit/Utils/PhnValidatorTests.cs
  Apps/CommonUi/CommonUi.sln
  Apps/CommonUi/README.md
  Apps/CommonUi/azure/build.yaml
  Apps/CommonUi/azure/prbuild.yaml
  Apps/CommonUi/src/.gitignore
  Apps/CommonUi/src/AssemblyInfo.cs
  Apps/CommonUi/src/Common.Ui.csproj
  Apps/CommonUi/src/omnisharp.json
  Apps/CommonUi/test/unit/.gitignore
  Apps/CommonUi/test/unit/AssemblyInfo.cs
  Apps/CommonUi/test/unit/CommonUiTests.csproj
  Apps/Encounter/test/unit/Delegates/EncounterDelegateTests.cs
  Apps/HealthGateway.sln
  Apps/Immunization/src/Immunization.csproj
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Laboratory/src/Laboratory.csproj
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/WebClient/test/unit/Services.Test/CommentServiceTests.cs
  Apps/WebClient/test/unit/Services.Test/CommunicationServiceTests.cs
  Apps/WebClient/test/unit/Services.Test/DependentServiceTests.cs
  Apps/WebClient/test/unit/Services.Test/NoteServiceTests.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileServiceTests.cs
  Build/hg.yaml
Labels: enhancement, ready, do not merge

#3093 Add index to Hdid on UserProfileHistory table for AB#11908.
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Migrations/20211206215849_AddIndexToUserProfileHistory.Designer.cs
  Apps/Database/src/Migrations/20211206215849_AddIndexToUserProfileHistory.cs
  Apps/Database/src/Migrations/GatewayDbContextModelSnapshot.cs
Labels: bugfix, ready

#3087 Add functional Test for Public Covid Record AB#11877 AB#11899 AB#11901
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
  Testing/functional/tests/cypress/fixtures/LaboratoryService/covidTest.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/dataMismatchCovidTest.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/emptyCovidTest.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/invalidCovidTest.json
  Testing/functional/tests/cypress/integration/e2e/dashboard/proofOfVaccination.js
  Testing/functional/tests/cypress/integration/e2e/vaccineCard/public.js
  Testing/functional/tests/cypress/integration/ui/pages/publicRoute.js
  Testing/functional/tests/cypress/integration/ui/vaccineCard/publicCovidTest.js
  Testing/functional/tests/cypress/support/constants.js
Labels: functional tests, ready

#3097 Fix label text for Check Another Test button for AB#11900
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: bugfix, ready, UI

#3099 Fix UI problem convert to PST AB#11917
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: bugfix, ready

#3098 Fix delete download folder call for functional tests for AB#11920.
  Testing/functional/tests/cypress/integration/e2e/dashboard/proofOfVaccination.js
  Testing/functional/tests/cypress/plugins/index.js
Labels: bugfix, functional tests, ready

#3104 Fix datetime to PST AB#11917
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: bugfix, ready

#3103 Update COVID Test Banner Colour AB#11924
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#3100 Removed registration and dependent test in mock folder AB#11886
  Testing/functional/tests/cypress/integration/mock/pages/Registration.js
  Testing/functional/tests/cypress/integration/mock/user/dependents.js
Labels: bugfix, ready

#3105 Delete auth test in mock folder AB#11886
  Testing/functional/tests/cypress/integration/mock/authentication/auth.js
Labels: bugfix, ready, do not merge

#3108 Fix public covid test to match PHSA response for AB#11923.
  Apps/Common/src/Models/PHSA/CovidTestResult.cs
  Apps/Laboratory/src/Models/PublicCovidTestRecord.cs
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: .NET, unit tests, ready, UI

#3111 Add back-end unit tests for public COVID-19 test results AB#11878
  Apps/Common/src/Models/PHSA/CovidTestResult.cs
  Apps/Laboratory/src/Models/PublicCovidTestRecord.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: enhancement, ready

#3122 Add HDID to COVID-19 page in admin AB#11818
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: enhancement, ready, user story, UI

#3123 Update release notes R1.4.16 and R1.4.17
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#3124 Update FAQ AB#11981
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#3125 Fix missing data and convert to UTC to PST AB#11985
  Apps/Laboratory/src/Models/PublicCovidTestRecord.cs
Labels: ready

#3126 Add breadcrumbs for AB#11952
  Apps/WebClient/src/ClientApp/src/components/navmenu/breadcrumb.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/breadcrumbItem.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/contactUs.vue
  Apps/WebClient/src/ClientApp/src/views/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/faq.vue
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/home.vue
  Apps/WebClient/src/ClientApp/src/views/login.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/termsOfService.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/src/views/validateEmail.vue
  Apps/WebClient/src/ClientApp/test/home.test.ts
  Testing/functional/tests/cypress/integration/e2e/home/proofOfVaccination.js
  Testing/functional/tests/cypress/integration/ui/pages/Routes.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/timeline/menu.js
  Testing/functional/tests/cypress/integration/ui/user/emailValidation.js
Labels: enhancement, functional tests, unit tests, ready, UI

#3127 Update COVID Test Page Verbiage
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready

#3129 Add breadcrumb navigation AB#11894
  Apps/WebClient/src/ClientApp/src/components/navmenu/breadcrumb.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/breadcrumbItem.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/contactUs.vue
  Apps/WebClient/src/ClientApp/src/views/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/faq.vue
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/home.vue
  Apps/WebClient/src/ClientApp/src/views/login.vue
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/termsOfService.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/src/views/validateEmail.vue
  Apps/WebClient/src/ClientApp/test/home.test.ts
  Testing/functional/tests/cypress/integration/e2e/home/proofOfVaccination.js
  Testing/functional/tests/cypress/integration/e2e/pages/breadcrumbs.js
  Testing/functional/tests/cypress/integration/ui/pages/Routes.js
  Testing/functional/tests/cypress/integration/ui/pages/breadcrumbs.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/timeline/menu.js
  Testing/functional/tests/cypress/integration/ui/user/emailValidation.js
Labels: ready, user story

#3130 Remove top padding from breadcrumb navigation AB#11998
  Apps/WebClient/src/ClientApp/src/components/navmenu/breadcrumb.vue
Labels: bugfix, ready

#3143 Add missing intercept for functional test AB#11871
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
Labels: bugfix, ready

#3149 Fix link name for AB#12015.
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready, UI

#3150 Remove extra periods for AB#12063.
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready, UI

#3148 Wire up support page in Admin project AB#11959
  Apps/Admin/Client/Pages/ClaimsPage.razor
  Apps/Admin/Client/Pages/ClaimsPage.razor.cs
  Apps/Admin/Client/Pages/Support.razor
  Apps/Admin/Client/Pages/Support.razor.cs
  Apps/Admin/Client/Services/IConfigurationApi.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationActions.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationEffects.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationReducers.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationState.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationActions.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationEffects.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationReducers.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationState.cs
  Apps/CommonData/src/Utils/DateFormatter.cs
  Apps/CommonData/src/ViewModels/MessagingVerificationModel.cs
Labels: enhancement, ready
