Repository bcgov/healthgateway, pull requests merged in 2021-08, with the labels that each got.

#2664 Moved cdogs delegate and models to common
  Apps/Common/src/Delegates/CDogsDelegate.cs
  Apps/Common/src/Delegates/ICDogsDelegate.cs
  Apps/Common/src/Models/CDogs/CDogsConfig.cs
  Apps/Common/src/Models/CDogs/CDogsOptionsModel.cs
  Apps/Common/src/Models/CDogs/CDogsRequestModel.cs
  Apps/Common/src/Models/CDogs/CDogsTemplateModel.cs
  Apps/Common/src/Models/CDogs/ReportModel.cs
  Apps/WebClient/src/Server/Controllers/ReportController.cs
  Apps/WebClient/src/Server/Services/IReportService.cs
  Apps/WebClient/src/Server/Services/ReportService.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/test/unit/Controllers.Test/ReportControllerTests.cs
  Apps/WebClient/test/unit/Delegates.Test/CDogsDelegateTest.cs
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
Labels: ready

#2668 Add SFTP delegate AB#11009
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/AdminWebClient/src/Server/Delegates/IMailDelegate.cs
  Apps/AdminWebClient/src/Server/Delegates/SFTPMailDelegate.cs
  Apps/AdminWebClient/src/Server/Models/DocumentStorageConfiguration.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/AdminWebClient/src/appsettings.hgdev.json
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/AdminWebClient/src/appsettings.hgpoc.json
  Apps/AdminWebClient/src/appsettings.hgtest.json
  Apps/AdminWebClient/src/appsettings.json
  Apps/Common/src/ErrorHandling/ServiceType.cs
Labels: enhancement, ready

#2667 Covid-19 Support Controller and service
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/Properties/launchSettings.json
  Apps/AdminWebClient/src/Server/Assets/Templates/CovidCard.docx
  Apps/AdminWebClient/src/Server/Controllers/CovidSupportController.cs
  Apps/AdminWebClient/src/Server/Delegates/IMailDelegate.cs
  Apps/AdminWebClient/src/Server/Models/Support/CovidInformation.cs
  Apps/AdminWebClient/src/Server/Models/Support/CovidReport.cs
  Apps/AdminWebClient/src/Server/Models/Support/MailDocumentRequest.cs
  Apps/AdminWebClient/src/Server/Models/Support/ReportAddress.cs
  Apps/AdminWebClient/src/Server/Models/Support/ReportDose.cs
  Apps/AdminWebClient/src/Server/Models/Support/ReportPatient.cs
  Apps/AdminWebClient/src/Server/Models/Support/RetrieveImmunizationResult.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/Server/Services/ICovidSupportService.cs
  Apps/AdminWebClient/src/Server/Services/IEmailAdminService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/AdminWebClient/src/appsettings.hgdev.json
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/AdminWebClient/src/appsettings.hgpoc.json
  Apps/AdminWebClient/src/appsettings.json
  Apps/Common/src/Delegates/RestImmunizationDelegate.cs
  Apps/Common/src/Utils/AssetReader.cs
  Apps/Mock/src/Assets/CovidImmunizations.json
  Apps/Mock/src/Assets/Patient.xml
  Apps/Mock/src/Controllers/PhsaController.cs
  Apps/Mock/src/Mock.xml
  Apps/WebClient/src/WebClient.csproj
Labels: ready

#2666 Initial Covid Support UI changes AB#10989
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/components/core/BannerFeedback.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/MainNavbar.vue
  Apps/AdminWebClient/src/ClientApp/src/constants/countryList.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/provinceList.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/snackbarPosition.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/stateList.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/userRoles.ts
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/models/address.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidCardDocumentResult.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidCardMailRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidCardPatientResult.ts
  Apps/AdminWebClient/src/ClientApp/src/models/immunizationModel.ts
  Apps/AdminWebClient/src/ClientApp/src/models/patientData.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restCovidSupportService.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/auth/getters.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/Server/Models/Support/CovidReport.cs
  Apps/AdminWebClient/src/appsettings.json
  Apps/Common/src/Models/PatientModel.cs
Labels: ready, UI

#2670 Add retry logic to Admin Imms delegate for AB#11031
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Models/Immunization/ImmunizationConfig.cs
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/AdminWebClient/src/appsettings.hgdev.json
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/AdminWebClient/src/appsettings.hgpoc.json
  Apps/AdminWebClient/src/appsettings.hgtest.json
  Apps/AdminWebClient/src/appsettings.json
Labels: ready

#2674 Swap methodless classes with interfaces in Admin front-end AB#11034
  Apps/AdminWebClient/src/ClientApp/src/models/address.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidCardDocumentResult.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidCardMailRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidCardPatientResult.ts
  Apps/AdminWebClient/src/ClientApp/src/models/patientData.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: ready

#2675 Fix method signature to match interface change AB#11034
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: bug, ready

#2676 Show success indication after mailing COVID Card AB#11035
  Apps/AdminWebClient/src/Server/Delegates/SFTPMailDelegate.cs
Labels: bug, ready

#2677 Update delegate to POST and Update filename
  Apps/AdminWebClient/src/Server/Delegates/IImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Models/Support/PHSA/CovidImmunizationsRequest.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
Labels: ready

#2678 Fixes Admin Covid Card auditing for AB#11043
  Apps/Common/src/Auditing/AuditLogger.cs
Labels: ready

#2680 Updated routing for support users AB#11039
  Apps/AdminWebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Login.vue
Labels: bug, ready

#2679 Add input masks to COVID Support page AB#11038
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/@types/v-mask.d.ts
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/utility/masks.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: ready

#2688 Fix date parsing on COVID support page AB#11056
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: bug, ready

#2693 Address fixes for COVID Support page
  Apps/AdminWebClient/src/ClientApp/src/constants/countries.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/countryList.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/provinces.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/states.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
Labels: bug, ready

#2699 Fix address initialization to prevent undefined array AB#11066
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: bug, ready

#2700 Create initial vaccination status page AB#11053
  Apps/WebClient/src/ClientApp/src/components/datePicker.vue
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/constants/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/models/vaccinationIndication.ts
  Apps/WebClient/src/ClientApp/src/models/vaccinationIndicationResult.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
Labels: ready

#2713 UI Updates for the Vaccination Status Page AB#11067
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/images/landing/vaccination-status-banner-image.png
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/shared/hgButton.vue
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
Labels: ready

#2714 Display stage in vaccination process on status result page AB#11073
  Apps/WebClient/src/ClientApp/src/assets/images/vaccination-status/dose-1.svg
  Apps/WebClient/src/ClientApp/src/assets/images/vaccination-status/dose-2.svg
  Apps/WebClient/src/ClientApp/src/assets/images/vaccination-status/fully-vaccinated.svg
  Apps/WebClient/src/ClientApp/src/assets/images/vaccination-status/no-doses.svg
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/models/vaccinationIndication.ts
Labels: ready

#2716 Update vaccination status banner AB#11074
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#2717 Template Kong Config for Test and Prod
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
  Tools/Kong/.gitignore
  Tools/Kong/README.md
  Tools/Kong/hg-dev.yaml
  Tools/Kong/immunization.tmpl
  Tools/Kong/networkpolicy.yaml
Labels: ready

#2718 Add loading spinner and error handling to vaccination status form AB#11068
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
Labels: ready

#2719 Add CDogs report to vaccine status AB#11069
  Apps/Immunization/src/Assets/Templates/VaccineStatusCard_FullyVaccinated.docx
  Apps/Immunization/src/Assets/Templates/VaccineStatusCard_Partial1Dose.docx
  Apps/Immunization/src/Assets/Templates/VaccineStatusCard_Partial2Doses.docx
  Apps/Immunization/src/Controllers/VaccineStatusController.cs
  Apps/Immunization/src/Immunization.csproj
  Apps/Immunization/src/Immunization.xml
  Apps/Immunization/src/Models/VaccineStatusReportRequest.cs
  Apps/Immunization/src/Services/IVaccineStatusService.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/src/appsettings.Development.json
  Apps/Immunization/src/appsettings.hgdev.json
  Apps/Immunization/src/appsettings.hgmock.json
  Apps/Immunization/src/appsettings.hgpoc.json
  Apps/Immunization/src/appsettings.json
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restVaccinationStatusService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
Labels: ready

#2724 Display message when loading vaccination result is delayed AB#11082
  Apps/WebClient/src/ClientApp/src/components/loading.vue
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
Labels: ready

#2726 Implements Captcha on Vaccination Status
  Apps/Immunization/src/Controllers/VaccineStatusController.cs
  Apps/Immunization/src/Delegates/CaptchaDelegate.cs
  Apps/Immunization/src/Delegates/ICaptchaDelegate.cs
  Apps/Immunization/src/Immunization.xml
  Apps/Immunization/src/Models/CaptchaConfig.cs
  Apps/Immunization/src/Models/CaptchaVerificationResponse.cs
  Apps/Immunization/src/Services/IVaccineStatusService.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/src/appsettings.json
  Apps/Immunization/test/unit/Controllers.Test/VaccineStatusControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/CaptchaDelegateTests.cs
  Apps/Immunization/test/unit/Delegates.Test/VaccineStatusDelegateTests.cs
  Apps/Immunization/test/unit/ImmunizationTests.xml
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
  Apps/Mock/src/Mock.xml
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restVaccinationStatusService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#2725 Update UI for vaccination check AB#11083
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
Labels: ready

#2727 Disable Vaccine status indicator by default
  Apps/Immunization/src/appsettings.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#2730 Fix GetCovidImmunizations mock endpoint AB#11080
  Apps/Mock/src/Controllers/PhsaController.cs
Labels: ready

#2729 Updates on Vaccine Status (reCaptcha, Sensitive Doc Modal, Fix Build)
  Apps/Immunization/src/appsettings.Development.json
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restVaccinationStatusService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
  Apps/WebClient/src/appsettings.Development.json
Labels: ready

#2746 Grab vaccine history PDF from PHSA AB#10999
  Apps/Immunization/src/Controllers/CovidVaccineRecordController.cs
  Apps/Immunization/src/Delegates/IImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Models/CovidVaccineRecord.cs
  Apps/Immunization/src/Services/IImmunizationService.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/WebClient/src/.gitignore
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/models/covidVaccineRecord.ts
  Apps/WebClient/src/ClientApp/src/models/encodedMedia.ts
  Apps/WebClient/src/ClientApp/src/models/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/plugins/pdfDefinition.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restImmunizationService.ts
  Apps/WebClient/src/ClientApp/src/shims-vue.d.ts
  Apps/WebClient/src/ClientApp/src/utility/pdfUtil.ts
  Apps/WebClient/src/WebClient.xml
Labels: ready

#2750 Updates the UI and path for the vaccine card result page
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/vaccinationStatusResult.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/vaccinationStatus.vue
Labels: ready, UI
