Repository bcgov/healthgateway, pull requests merged in 2021-01, with the labels that each got.

#1540 Update Immunization Card and Report
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Models/ImmunizationModel.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationController_Test.cs
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Testing/functional/e2e/cypress.json
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
Labels: ready

#1547 Update JobScheduler app settings
  Apps/JobScheduler/src/appsettings.hgtest.json
Labels: ready

#1559 Update Cypress and resolve issues with tests failing for AB#9784
  Testing/functional/e2e/cypress.json
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/e2e/cypress/integration/authentication/auth.js
  Testing/functional/e2e/cypress/integration/services/medication.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/package-lock.json
  Testing/functional/e2e/package.json
Labels: functional tests, ready

#1549 Add func. tests
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
Labels: ready

#1561 update release notes AB#9785
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1562 Hide immz. for empty product
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
Labels: ready

#1569 Fix terms of service date
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Migrations/20210106170417_UpdateToSDate2.Designer.cs
  Apps/Database/src/Migrations/20210106170417_UpdateToSDate2.cs
  Apps/Database/src/Migrations/GatewayDbContextModelSnapshot.cs
Labels: ready

#1568 Added logic to prevent AllowAnonymous methods to be logged
  Apps/Common/src/Filters/AuditFilter.cs
Labels: bug, ready

#1564 Removed close arrow on mobile.
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/components/feedback.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: bug, ready

#1581 Fixes app settings and medication test AB#9573
  Apps/WebClient/src/appsettings.json
  Testing/functional/e2e/cypress/integration/services/medication.js
Labels: ready

#1583 Update hangfireSecrets.yaml
  Tools/BaseBuild/hangfireSecrets.yaml
Labels: ready

#1548 Add the HSTS
  Apps/WebClient/src/Server/Startup.cs
Labels: ready

#1587 Update report view AB#9792
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1585 Update landing AB#9801
  Apps/Encounter/src/appsettings.Development.json
  Apps/Medication/src/appsettings.Development.json
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#1588 Updated registration flow
  Apps/WebClient/src/ClientApp/src/views/registration.vue
Labels: ready

#1593 Update ResendSMS timeout
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#1591 Add phone mask & popup to profile vue
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: ready

#1594 Update meta description AB#9789
  Apps/WebClient/src/ClientApp/public/index.html
Labels: ready

#1604 Fix Smells and Migration to OCP4 Dev Workstation config
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceAuthorizationHandler.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Constants/ErrorMessages.cs
  Apps/Common/src/ErrorHandling/ActionType.cs
  Apps/Common/src/ErrorHandling/ErrorTranslator.cs
  Apps/Common/src/Filters/AuditFilter.cs
  Apps/Common/src/Services/HttpClientService.cs
  Apps/Common/src/Services/IHttpClientService.cs
  Apps/Encounter/src/appsettings.Development.json
  Apps/Medication/src/appsettings.Development.json
Labels: ready

#1603 revert Hsts
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/WebClient/src/Server/Startup.cs
  Tools/BaseBuild/route.sh
Labels: ready

#1605 Registration functional tests
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Testing/functional/e2e/cypress.json
  Testing/functional/e2e/cypress/integration/authentication/auth.js
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
  Testing/functional/e2e/cypress/integration/healthinsights/insights.js
  Testing/functional/e2e/cypress/integration/pages/Registration.js
  Testing/functional/e2e/cypress/integration/pages/Routes.js
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/calendar.js
  Testing/functional/e2e/cypress/integration/timeline/comments.js
  Testing/functional/e2e/cypress/integration/timeline/encounter.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/menu.js
  Testing/functional/e2e/cypress/integration/timeline/modals/protectiveWordModal.js
  Testing/functional/e2e/cypress/integration/timeline/notes.js
  Testing/functional/e2e/cypress/integration/timeline/pagination.js
  Testing/functional/e2e/cypress/integration/timeline/starRating.js
  Testing/functional/e2e/cypress/integration/user/feedback.js
  Testing/functional/e2e/cypress/integration/user/profile.js
  Testing/functional/e2e/cypress/integration/user/registration.js
  Testing/functional/e2e/cypress/support/commands.js
Labels: ready

#1606 Added table section to the admin dashboard AB#9771
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
Labels: ready

#1607 Features/9749 Landing Page and Metadata update
  Apps/WebClient/src/ClientApp/public/index.html
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#1611 Fix Functional Tests
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready

#1612 Update README.md
  Tools/Postgres/README.md
Labels: ready

#1615 Updated backend and front end to display daily information AB#9847
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Services/IDashboardService.cs
  Apps/AdminWebClient/test/unit/Controllers.Test/DashboardControllerTest.cs
  Apps/AdminWebClient/test/unit/Services.Test/DashboardService_Test.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/DBResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IUserDelegateDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
Labels: ready

#1620 Release Notes for R1.3.2 AB#9848
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1623 Fixes admin site not retrieving feedback
  Apps/Database/src/Delegates/DBFeedbackDelegate.cs
  Apps/Database/src/Models/Comment.cs
Labels: bug, ready

#1626 Merge to Master
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/test/unit/AdminWebClientTests.csproj
  Apps/Common/src/Common.csproj
  Apps/Common/test/unit/CommonTests.csproj
  Apps/Database/src/Database.csproj
  Apps/Database/src/Delegates/DBFeedbackDelegate.cs
  Apps/Database/src/Models/Comment.cs
  Apps/Database/test/unit/DatabaseTests.csproj
  Apps/Encounter/test/unit/EncounterTests.csproj
  Apps/Immunization/test/unit/ImmunizationTests.csproj
  Apps/Laboratory/test/unit/LaboratoryTests.csproj
  Apps/Medication/test/unit/MedicationTests.csproj
  Apps/Patient/test/unit/PatientTests.csproj
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/test/unit/WebClientTests.csproj
Labels: ready

#1625 Fix cypress failure when downloading file for dependents for AB#9883
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/support/commands.js
Labels: ready

#1635 Dashboard and Admin fixes- Features/9766 b
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/.eslintrc.js
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/public/manifest.json
  Apps/AdminWebClient/src/ClientApp/src/App.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/BannerFeedback.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/CommunicationTable.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/Footer.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/Loading.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/MainNavbar.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/Toolbar.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/modals/BannerModal.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/modals/EmailModal.vue
  Apps/AdminWebClient/src/ClientApp/src/filters/date.filter.ts
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/models/storeState.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/vuetify.ts
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/httpDelegate.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restAuthenticationService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restCommunicationService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restConfigService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restEmailAdminService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restUserFeedbackService.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/auth/auth.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/auth/getters.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/auth/mutations.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/config/actions.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/config/config.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/config/getters.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/config/mutations.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/drawer/actions.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/drawer/drawer.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/drawer/getters.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/drawer/mutations.ts
  Apps/AdminWebClient/src/ClientApp/src/store/store.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Communication.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Feedback.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Login.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Logout.vue
  Apps/AdminWebClient/src/ClientApp/src/views/ResendEmail.vue
  Apps/AdminWebClient/src/ClientApp/vue.config.js
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Models/AdminConfiguration.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Services/IDashboardService.cs
  Apps/AdminWebClient/test/unit/Controllers.Test/DashboardControllerTest.cs
  Apps/AdminWebClient/test/unit/Services.Test/DashboardService_Test.cs
  Apps/Database/src/Delegates/DBNoteDelegate.cs
  Apps/Database/src/Delegates/INoteDelegate.cs
Labels: ready

#1636 Updated RocketChat channel for AB#9875
  Tools/BaseBuild/service.yaml
Labels: ready

#1638 Add server configuration and client model
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/Server/Controllers/ConfigurationController.cs
  Apps/WebClient/src/Server/Models/OfflineModeConfiguration.cs
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#1644 Remove print from timeline
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1632 Update reports AB#9855
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1645 fix notes popover for mobile
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: bug, ready

#1634 Add tuto. popover for Export Records
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
Labels: ready

#1647 Router and VUEx changes for Offline mode - Tasks/9870
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/config/getters.ts
  Apps/WebClient/src/Server/Controllers/CommentController.cs
  Apps/WebClient/src/Server/Controllers/CommunicationController.cs
  Apps/WebClient/src/Server/Controllers/NoteController.cs
  Apps/WebClient/src/Server/Controllers/UserFeedbackController.cs
  Apps/WebClient/src/Server/Models/OfflineModeConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
Labels: ready

#1658 Export Records Update
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/README.md
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: enhancement, ready, user story

#1622 Popover Tutorial: Export Records
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/db/seed.sql
  Testing/functional/e2e/cypress/integration/user/tutorial.js
Labels: ready, user story

#1657 Hide menu when offline. Hide Login button. AB#9871
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: ready

#1660 Updated landing for offline mode. AB#9832
  Apps/WebClient/src/ClientApp/src/components/navmenu/navFooter.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#1659 Filter count and color updates - AB#9863
  Apps/WebClient/src/ClientApp/src/components/timeline/calendarTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1672 Fixed popover and preference issues - AB#9887
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/modal/covid.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/models/userProfile.ts
  Apps/WebClient/src/ClientApp/src/services/httpDelegate.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restMedicationService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserNoteService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserProfileService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/db/seed.sql
  Testing/functional/e2e/cypress/integration/user/tutorial.js
Labels: ready

#1671 update release notes R1.3.3 AB#9885
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1646 Implement Filter Active
  Apps/WebClient/src/ClientApp/src/components/timeline/calendarTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/timeline/menu.js
Labels: enhancement, ready, user story

#1637 Offline mode
  Apps/Directory.Build.props
  Apps/WebClient/src/ClientApp/src/components/navmenu/navFooter.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/config/getters.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/Server/Controllers/CommentController.cs
  Apps/WebClient/src/Server/Controllers/CommunicationController.cs
  Apps/WebClient/src/Server/Controllers/ConfigurationController.cs
  Apps/WebClient/src/Server/Controllers/NoteController.cs
  Apps/WebClient/src/Server/Controllers/UserFeedbackController.cs
  Apps/WebClient/src/Server/Models/OfflineModeConfiguration.cs
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/e2e/cypress/integration/pages/LandingPage.js
Labels: enhancement, ready, user story

#1670 Add new Date Picker
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/assets/scss/bcgov/_overrides.scss
  Apps/WebClient/src/ClientApp/src/components/datePicker.vue
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/note.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/timeline/notes.js
Labels: enhancement, ready, user story

#1673 Fix func. test
  Testing/functional/e2e/cypress/integration/pages/LandingPage.js
Labels: ready

#1675 Fix broken func. tests
  Testing/functional/e2e/cypress/integration/dependent/dependents.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/package.json
Labels: bug, ready

#1674 Fix dropdown overlay AB#9809
  Apps/WebClient/src/ClientApp/src/components/datePicker.vue
Labels: ready

#1691 Tasks/9891 Update Launch Date for Encounter
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#1690 Combined Encounter Models
  Apps/Encounter/src/Models/EncounterModel.cs
  Apps/Encounter/test/unit/Services/EncounterService_Test.cs
Labels: ready

#1692 Fixes expired delegate lookup AB#9666
  Apps/Common/src/AccessManagement/Authorization/Handlers/BaseFhirAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceDelegateAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Requirements/FhirRequirement.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Models/RequestResult.cs
  Apps/Common/test/unit/AccessManagement/Authorization/FhirResourceAuthorizationHandler_Test.cs
  Apps/Common/test/unit/AccessManagement/Authorization/FhirResourceDelegateAuthorizationHandler_Test.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/src/appsettings.Development.json
  Apps/Laboratory/src/appsettings.hgdev.json
  Apps/Laboratory/src/appsettings.hgpoc.json
  Apps/Laboratory/src/appsettings.hgtest.json
  Apps/Laboratory/src/appsettings.json
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/components/loading.vue
  Apps/WebClient/src/Server/Services/DependentService.cs
  Testing/functional/e2e/cypress/db/seed.sql
  Testing/functional/e2e/cypress/fixtures/WebClientService/dependents.json
  Testing/functional/e2e/cypress/integration/services/laboratory.js
  Testing/functional/e2e/cypress/integration/services/webClient/dependent.js
  Testing/functional/e2e/cypress/integration/user/dependents.js
Labels: ready

#1686 Combine Claims for MSP Visit
  Apps/Encounter/src/Models/EncounterModel.cs
  Apps/Encounter/test/unit/Services/EncounterService_Test.cs
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Testing/functional/e2e/cypress/fixtures/EncounterService/encounter.json
  Testing/functional/e2e/cypress/integration/services/encounter.js
  Testing/functional/e2e/cypress/integration/timeline/comments.js
Labels: enhancement, ready, user story

#1714 Update immunization vue
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Apps/WebClient/src/ClientApp/src/constants/dateTimeFormat.ts
  Apps/WebClient/src/ClientApp/src/models/dateWrapper.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
Labels: ready

#1715 fixed functional tests
  Testing/functional/e2e/cypress/db/seed.sql
  Testing/functional/e2e/cypress/integration/services/webClient/comment.js
  Testing/functional/e2e/cypress/integration/services/webClient/dependent.js
  Testing/functional/e2e/cypress/integration/timeline/comments.js
Labels: ready

#1716 Enable reviewers in Admin Web Client
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/src/components/core/MainNavbar.vue
  Apps/AdminWebClient/src/ClientApp/src/constants/userRoles.ts
  Apps/AdminWebClient/src/ClientApp/src/models/authenticationData.ts
  Apps/AdminWebClient/src/ClientApp/src/models/menuItem.ts
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/auth/getters.ts
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Controllers/UserFeedbackController.cs
  Apps/AdminWebClient/src/Server/Models/AuthenticationData.cs
  Apps/AdminWebClient/src/Server/Services/AuthenticationService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/src/appsettings.json
Labels: enhancement, ready, user story

#1722 update release notes 1.3.3 AB#9961
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1723 Fix build (duplicated role prop)
  Apps/AdminWebClient/src/ClientApp/src/models/authenticationData.ts
Labels: ready

#1730 Corrected forecast text
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready

#1729 Fixed 5 broken functional tests
  Testing/functional/e2e/cypress/integration/services/webClient/dependent.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready

#1718 Add Recommendation to Immz Report
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/models/immunizationResult.ts
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/services/restImmunizationService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/immunization.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/login.ignore.ts
  Apps/WebClient/src/ClientApp/test/router.ignore.ts
  Apps/WebClient/src/ClientApp/test/store/auth.ignore.ts
  Apps/WebClient/src/ClientApp/test/timeline.ignore.ts
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
Labels: enhancement, ready, user story

#1732 Fix functional tests
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunizationrefresh.json
Labels: ready

#1736 Added route checking for access
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/actions.ts
Labels: bug, ready

#1738 Fix bug with html2canvas AB#9882
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1739 Fix immz report functional test AB#9986
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
Labels: ready

#1737 Handled failure in retrieving Patient Data
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1740 Fixed pagination func. tests
  Testing/functional/e2e/cypress/integration/timeline/pagination.js
Labels: bug, ready

#1741 removed msp launch date AB#9990
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready
