Repository bcgov/healthgateway, pull requests merged in 2021-03, with the labels that each got.

#1928 Fixed build issues and removed some warnings
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/Server/Controllers/EmailAdminController.cs
  Apps/AdminWebClient/src/Server/Mappers/CommentCsvMap.cs
  Apps/AdminWebClient/src/Server/Mappers/NoteCsvMap.cs
  Apps/AdminWebClient/src/Server/Mappers/UserProfileCsvMap.cs
  Apps/AdminWebClient/src/Server/Models/UserFeedbackView.cs
  Apps/AdminWebClient/src/Server/Services/CsvExportService.cs
  Apps/AdminWebClient/src/Server/Services/EmailAdminService.cs
  Apps/AdminWebClient/src/Server/Services/IUserFeedbackService.cs
  Apps/AdminWebClient/src/Server/Services/UserFeedbackService.cs
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AspNetConfiguration/ProgramConfiguration.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Utils/AssetReader.cs
  Apps/DBMaintainer/Apps/FedDrugDBApp.cs
  Apps/DBMaintainer/Parsers/FederalDrugProductParser.cs
  Apps/DBMaintainer/Parsers/IDrugProductParser.cs
  Apps/DBMaintainer/Parsers/IPharmaCareDrugParser.cs
  Apps/DBMaintainer/Parsers/PharmaCareDrugParser.cs
  Apps/Database/src/Delegates/DBCommunicationDelegate.cs
  Apps/Database/src/Delegates/DBDrugLookupDelegate.cs
  Apps/Database/src/Delegates/DBEmailDelegate.cs
  Apps/Database/src/Delegates/DBFeedbackDelegate.cs
  Apps/Database/src/Delegates/DBGenericCacheDelegate.cs
  Apps/Database/src/Delegates/IDrugLookupDelegate.cs
  Apps/Database/src/Delegates/IEmailDelegate.cs
  Apps/Database/src/Delegates/IFeedbackDelegate.cs
  Apps/Directory.Build.props
Labels: ready

#1927 Upgrade CsvHelper for DBMaintainer
  Apps/DBMaintainer/DBMaintainer.csproj
  Apps/DBMaintainer/Mappers/ActiveIngredientMapper.cs
  Apps/DBMaintainer/Mappers/CompanyMapper.cs
  Apps/DBMaintainer/Mappers/DrugProductMapper.cs
  Apps/DBMaintainer/Mappers/FormMapper.cs
  Apps/DBMaintainer/Mappers/PackagingMapper.cs
  Apps/DBMaintainer/Mappers/PharmaCareDrugMapper.cs
  Apps/DBMaintainer/Mappers/PharmaceuticalStdMapper.cs
  Apps/DBMaintainer/Mappers/RouteMapper.cs
  Apps/DBMaintainer/Mappers/ScheduleMapper.cs
  Apps/DBMaintainer/Mappers/StatusMapper.cs
  Apps/DBMaintainer/Mappers/TherapeuticMapper.cs
  Apps/DBMaintainer/Mappers/VeterinarySpeciesMapper.cs
  Apps/DBMaintainer/Parsers/FederalDrugProductParser.cs
  Apps/DBMaintainer/Parsers/PharmaCareDrugParser.cs
Labels: ready

#1938 Email verification banner functional tests AB#10187
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Testing/functional/e2e/cypress.json
  Testing/functional/e2e/cypress/integration/pages/Registration.js
Labels: ready

#1936 Add FAQ page AB#9988
  Apps/WebClient/src/ClientApp/src/components/navmenu/navFooter.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/faq.vue
  Testing/functional/e2e/cypress/integration/pages/faq.js
Labels: enhancement, ready, user story

#1925 Add functional tests
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready

#1940 Fix the covid modal
  Apps/WebClient/src/ClientApp/src/components/modal/covid.vue
  Testing/functional/e2e/cypress/integration/timeline/modals/covidModal.js
Labels: bug, ready

#1937 Upgrade CsvHelper
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/.eslintrc.js
  Apps/AdminWebClient/src/Server/Controllers/EmailAdminController.cs
  Apps/AdminWebClient/src/Server/Mappers/CommentCsvMap.cs
  Apps/AdminWebClient/src/Server/Mappers/NoteCsvMap.cs
  Apps/AdminWebClient/src/Server/Mappers/UserProfileCsvMap.cs
  Apps/AdminWebClient/src/Server/Models/UserFeedbackView.cs
  Apps/AdminWebClient/src/Server/Services/CsvExportService.cs
  Apps/AdminWebClient/src/Server/Services/EmailAdminService.cs
  Apps/AdminWebClient/src/Server/Services/IUserFeedbackService.cs
  Apps/AdminWebClient/src/Server/Services/UserFeedbackService.cs
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AspNetConfiguration/ProgramConfiguration.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Utils/AssetReader.cs
  Apps/DBMaintainer/Apps/FedDrugDBApp.cs
  Apps/DBMaintainer/DBMaintainer.csproj
  Apps/DBMaintainer/Mappers/ActiveIngredientMapper.cs
  Apps/DBMaintainer/Mappers/CompanyMapper.cs
  Apps/DBMaintainer/Mappers/DrugProductMapper.cs
  Apps/DBMaintainer/Mappers/FormMapper.cs
  Apps/DBMaintainer/Mappers/PackagingMapper.cs
  Apps/DBMaintainer/Mappers/PharmaCareDrugMapper.cs
  Apps/DBMaintainer/Mappers/PharmaceuticalStdMapper.cs
  Apps/DBMaintainer/Mappers/RouteMapper.cs
  Apps/DBMaintainer/Mappers/ScheduleMapper.cs
  Apps/DBMaintainer/Mappers/StatusMapper.cs
  Apps/DBMaintainer/Mappers/TherapeuticMapper.cs
  Apps/DBMaintainer/Mappers/VeterinarySpeciesMapper.cs
  Apps/DBMaintainer/Parsers/FederalDrugProductParser.cs
  Apps/DBMaintainer/Parsers/IDrugProductParser.cs
  Apps/DBMaintainer/Parsers/IPharmaCareDrugParser.cs
  Apps/DBMaintainer/Parsers/PharmaCareDrugParser.cs
  Apps/Database/src/Delegates/DBCommunicationDelegate.cs
  Apps/Database/src/Delegates/DBDrugLookupDelegate.cs
  Apps/Database/src/Delegates/DBEmailDelegate.cs
  Apps/Database/src/Delegates/DBFeedbackDelegate.cs
  Apps/Database/src/Delegates/DBGenericCacheDelegate.cs
  Apps/Database/src/Delegates/IDrugLookupDelegate.cs
  Apps/Database/src/Delegates/IEmailDelegate.cs
  Apps/Database/src/Delegates/IFeedbackDelegate.cs
  Apps/Directory.Build.props
Labels: enhancement, ready, user story

#1942 Add comments to keyword filter
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/noteTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/getters.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1945 Fixed compilation issues
  Apps/JobScheduler/src/Jobs/EmailJob.cs
  Apps/Medication/src/Services/RestMedicationService.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: bug, ready

#1944 Updated details pane AB#10166
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/note.ts
  Apps/WebClient/src/ClientApp/src/store/store.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: bug, ready

#1943 Email Verification Notice AB#10140
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Testing/functional/e2e/cypress.json
  Testing/functional/e2e/cypress/integration/pages/Registration.js
Labels: enhancement, ready, user story

#1941 Update button look for AB#10102
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/addComment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: enhancement, pending story verification, ready, user story

#1949 FAQ Update AB#10200
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#1951 Features/10141
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/utility/pdfUtil.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: enhancement, ready, user story

#1953 Hide immz loading if no records
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: bug, ready

#1952 Update email input validation state AB#10219
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: ready

#1950 update release notes 1.3.9 AB#10169
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1954 Comments filter - Features/10075
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/noteTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/getters.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/integration/timeline/comments.js
Labels: enhancement, ready, user story

#1956 Fixed Webclient build
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
Labels: ready

#1958 Fix functional tests
  Testing/functional/e2e/cypress/integration/timeline/calendar.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/medication.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/encounter.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/medication.js
Labels: bug, ready

#1959 Update immunization card justify AB#10227
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
Labels: ready

#1957 Update landing page AB#10225
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#1961 Fixed notes and comments issues
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/noteTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: bug, ready

#1960 Features/10192 docs
  Apps/HealthGateway.code-workspace
  Tools/Design/README.md
  Tools/Design/images/accent.png
  Tools/Design/images/background.png
  Tools/Design/images/buttons.png
  Tools/Design/images/colours.png
  Tools/Design/images/comment-icons.png
  Tools/Design/images/error.png
  Tools/Design/images/header-desktop.png
  Tools/Design/images/header-mobile.png
  Tools/Design/images/header-tablet.png
  Tools/Design/images/heading-text.png
  Tools/Design/images/icon-typeface.png
  Tools/Design/images/input-text.png
  Tools/Design/images/links.png
  Tools/Design/images/mobile-sample.png
  Tools/Design/images/navigation-bar.png
  Tools/Design/images/primary.png
  Tools/Design/images/secondary.png
  Tools/Design/images/success.png
  Tools/Design/sampler/README.md
  Tools/Design/sampler/package-lock.json
Labels: documentation, ready

#1966 Edit button and timelines fixes - AB#10228
  Apps/WebClient/src/ClientApp/src/components/calendar/calendar.vue
  Apps/WebClient/src/ClientApp/src/components/communication.vue
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/feedback.vue
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/protectiveWord.vue
  Apps/WebClient/src/ClientApp/src/components/modal/rating.vue
  Apps/WebClient/src/ClientApp/src/components/modal/verifySMS.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/addComment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: bug, ready

#1968 Display lab result outcome AB#10239
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
Labels: ready

#1975 Features/10222
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
  Testing/functional/e2e/cypress.json
  Testing/functional/e2e/cypress/fixtures/LaboratoryService/laboratory.json
  Testing/functional/e2e/cypress/integration/timeline/mobile/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/laboratory.js
  Testing/functional/e2e/cypress/support/commands.js
  Testing/functional/e2e/cypress/support/index.d.ts
  Testing/functional/e2e/cypress/tsconfig.json
  Testing/functional/e2e/package.json
Labels: ready, user story

#1977 Hide pdf button if report not ready
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
Labels: bug, ready

#1986 Provincial Drug Loader issue
  Apps/DBMaintainer/Parsers/PharmaCareDrugParser.cs
Labels: bug, ready

#1972 Fix functional tests AB#10237
  Testing/functional/e2e/cypress/integration/timeline/encounter.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/support/commands.js
Labels: ready

#1973 update covid card and vuex
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/user.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1985 Add Sysdig OpenShift configuration for the team for AB#10002
  Tools/Sysdig/README.md
  Tools/Sysdig/team.yaml
Labels: ready, user story

#1987 Update date format AB#10251
  Apps/WebClient/src/ClientApp/src/components/datePicker.vue
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/models/dateWrapper.ts
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready

#1990 Add DOB to Immz Card Features/10174
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/user.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready

#1992 Update functional tests
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/user/dependents.js
Labels: ready

#1989 Auth & timing out after inactivity
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/services/restAuthService.ts
Labels: bug, ready

#1996 Resolve build issues for AB#10286
  Apps/.editorconfig
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceDelegateAuthorizationHandler.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Models/PHSA/PHSAResult.cs
  Apps/Common/src/Utils/AssetReader.cs
  Apps/Common/test/unit/Services/SwaggerTest.cs
  Apps/Common/test/unit/Utils/MockMethodInfo.cs
  Apps/Directory.Build.props
  Apps/HealthGateway.sln
  Apps/Immunization/src/Models/ImmunizationAgent.cs
  Apps/Immunization/src/Models/ImmunizationDefinition.cs
  Apps/Immunization/src/Models/ImmunizationForecast.cs
  Apps/Immunization/src/Models/PHSA/ImmunizationForecastResponse.cs
  Apps/Immunization/src/Models/PHSA/ImmunizationViewResponse.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/test/unit/Controllers.Test/CommentControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/NoteControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/UserFeedbackControllerTests.cs
Labels: bug, ready

#1994 Update Date Format
  Apps/WebClient/src/ClientApp/src/components/datePicker.vue
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/models/dateWrapper.ts
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/user/dependents.js
Labels: enhancement, ready

#1991 Fix functional tests AB#10238
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Testing/functional/e2e/cypress/integration/timeline/mobile/encounter.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/medication.js
Labels: ready

#1988 Add Medication Requests vue
  Apps/WebClient/src/ClientApp/src/components/modal/protectiveWord.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/models/MedicationRequest.ts
  Apps/WebClient/src/ClientApp/src/models/medicationRequestTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restMedicationService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/medication.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1997 Update FAQ Features/10283
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#1999 Updated state store to use session storage AB#10288
  Apps/WebClient/src/ClientApp/src/services/restAuthService.ts
Labels: bug, ready

#2007 Add config setting for enabling SpecialAuthorityRequests module AB#10261
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#2008 Update most failing functional tests for AB#10301
  Testing/functional/e2e/README.md
  Testing/functional/e2e/cypress/integration/authentication/auth.js
  Testing/functional/e2e/cypress/integration/timeline/calendar.js
  Testing/functional/e2e/cypress/integration/timeline/notes.js
  Testing/functional/e2e/cypress/support/commands.js
  Testing/functional/e2e/package-lock.json
  Testing/functional/e2e/package.json
Labels: bug, ready

#2015 Renable blocked IDIR test for AB#10314
  Testing/functional/e2e/cypress/integration/authentication/auth.js
Labels: bug, ready

#2013 Fix download pdf on safari AB#10278
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
Labels: ready

#2023 Update SA Request filter AB#10295
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/models/medicationRequestTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/getters.ts
Labels: ready

#2033 Update medication request functional tests AB#10319
  Testing/functional/e2e/cypress/integration/services/medication.js
Labels: ready

#2037 Update SA filter AB#10297
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready

#2036 Update alerts for deferred immunizations AB#10298
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#2035 Add file-saver to download pdf AB#10278
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
Labels: ready

#2038 Update functional tests for immunization loading AB#10300
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunizationNoRecords.json
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/immunizationNoRecords.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/immunization.js
Labels: ready

#2040 Immunization Load Message Features/10208
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunizationNoRecords.json
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/immunizationNoRecords.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/immunization.js
Labels: enhancement, ready

#2039 Features/10064
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/models/medicationRequestTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/services/restMedicationService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/getters.ts
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/timeline/medicationrequest.js
Labels: ready

#2041 Fixed Swagger CSP. Added missing vuex modules. AB#10329
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/appsettings.json
Labels: ready

#2052 Fixes functional tests AB#10334
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready

#2053 Fixed config name for phsa notifications. AB#10347
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
Labels: bug, ready

#2055 Sync Dev-Master
  Apps/AdminWebClient/src/ClientApp/package-lock.json
Labels: ready

#2042 Backend refactor - Tasks/10302
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Constants/EmailTemplateVariable.cs
  Apps/Common/src/Services/EmailQueueService.cs
  Apps/Common/src/Services/IEmailQueueService.cs
  Apps/Common/src/Services/INotificationSettingsService.cs
  Apps/Common/src/Services/NotificationSettingsService.cs
  Apps/Common/test/unit/Services/EmailQueueService_Test.cs
  Apps/Database/src/Delegates/DBDrugLookupDelegate.cs
  Apps/Database/src/Delegates/DBMessagingVerificationDelegate.cs
  Apps/Database/src/Delegates/IMessagingVerificationDelegate.cs
  Apps/WebClient/src/Server/Controllers/NoteController.cs
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/src/Server/Models/TermsOfServiceModel.cs
  Apps/WebClient/src/Server/Models/UserEmailInvite.cs
  Apps/WebClient/src/Server/Models/UserProfileModel.cs
  Apps/WebClient/src/Server/Models/UserSMSInvite.cs
  Apps/WebClient/src/Server/Services/CommentService.cs
  Apps/WebClient/src/Server/Services/IUserEmailService.cs
  Apps/WebClient/src/Server/Services/IUserProfileService.cs
  Apps/WebClient/src/Server/Services/IUserSMSService.cs
  Apps/WebClient/src/Server/Services/UserEmailService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/Server/Services/UserSMSService.cs
  Apps/WebClient/test/unit/Controllers.Test/NoteControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/UserProfileController_Test.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileService_Test.cs
  Apps/WebClient/test/unit/Services.Test/UserSMSServiceTests.cs
Labels: ready

#2060 Fix SA Functional tests AB#10334
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready

#2058 Attempt to fix safari download with blob AB#10278
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
Labels: ready

#2056 Added medication request report AB#10293
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#2065 Updated text filter terms for Immz.
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
Labels: ready

#2063 Updated log level to info AB#10369
  Apps/HealthGateway.code-workspace
  Apps/WebClient/src/appsettings.json
Labels: ready

#2079 Export Records: Special Authority Requests AB#10293
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: enhancement, ready, user story

#2076 Update functional tests AB#10344
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready

#2082 Update Profile Page AB#10306
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: ready

#2081 Fixes dependent not found / invalid phn AB#9750
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/WebClient/src/Server/Services/DependentService.cs
Labels: ready

#2080 Updated the logout flow to make sure it completes AB#10335
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restAuthService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/WebClient/src/ClientApp/src/views/logout.vue
  Apps/WebClient/src/ClientApp/src/views/logoutComplete.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#2089 Features/10181
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready

#2090 Update Release Notes AB#10380
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#2092 Health Visits Update
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/encounter.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready, user story

#2091 Fix for two producs with cards. AB#10330
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
Labels: ready

#2093 Update profile page functional tests AB#10307
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Testing/functional/e2e/cypress/db/seed.sql
  Testing/functional/e2e/cypress/integration/user/profile.js
Labels: ready

#2096 Update Profile Page
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Testing/functional/e2e/cypress/db/seed.sql
  Testing/functional/e2e/cypress/integration/user/profile.js
Labels: ready, user story

#2095 Added address formating to records exporting. AB#10383
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
Labels: bug, ready

#2094 Removed banner when email is empty. AB#10370
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: bug, ready

#2097 Update Landing Page AB#10386
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#2099 Fix Health Visits Address AB#10387
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
Labels: ready

#2098 Fix functional tests AB#10385
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Testing/functional/e2e/cypress/integration/timeline/mobile/laboratory.js
  Testing/functional/e2e/cypress/integration/user/profile.js
Labels: ready

#2100 Fix verify button spacing on profile page AB#10384
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: bug, ready

#2104 Add multiselect component AB#10372
  Apps/WebClient/src/ClientApp/src/components/multiSelect.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#2107 Show forecast - removed button. AB#10395
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
Labels: ready

#2106 Updated comments sticky on mobile AB#10397
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
Labels: ready, user story

#2123 fixed typos in FAQ AB#10408
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#2114 Update sort dashboard stats AB#10277
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
Labels: ready, user story

#2116 Added attachment icon AB#10393
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
Labels: ready

#2112 Added filtering to medication reports. AB#10371
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/components/multiSelect.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/models/reportFilter.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#2125 date for last updated AB#10413
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#2126 Fix ODR error forcing protected word for AB#10405
  Apps/Common/src/omnisharp.json
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Medication/src/Delegates/SalesforeceDelegate.cs
  Apps/Medication/test/unit/Delegates/MedicationDelegate_Test.cs
  Apps/Medication/test/unit/Delegates/SalesforceDelegate_Test.cs
Labels: bug, ready

#2115 Remove show forecast Features/10282
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready, user story

#2128 Added email verification messaging. AB#10391
  Apps/WebClient/src/ClientApp/src/views/validateEmail.vue
  Apps/WebClient/src/Server/Services/UserEmailService.cs
Labels: ready

#2129 Update functional tests AB#10392
  Testing/functional/e2e/cypress/fixtures/WebClientService/EmailValidation/invalid.json
  Testing/functional/e2e/cypress/fixtures/WebClientService/EmailValidation/valid.json
  Testing/functional/e2e/cypress/integration/user/emailValidation.js
Labels: ready

#2133 Add functional tests for attachment icons AB#10394
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Testing/functional/e2e/cypress/fixtures/LaboratoryService/laboratory.json
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/laboratory.js
Labels: ready

#2135 Features/10281
  Apps/WebClient/src/ClientApp/src/views/validateEmail.vue
  Apps/WebClient/src/Server/Services/UserEmailService.cs
  Testing/functional/e2e/cypress/fixtures/WebClientService/EmailValidation/invalid.json
  Testing/functional/e2e/cypress/fixtures/WebClientService/EmailValidation/valid.json
  Testing/functional/e2e/cypress/integration/user/emailValidation.js
Labels: ready, user story

#2138 Button resizing Bugs/10419
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
Labels: bug, ready

#2136 Fixes medications not loading
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/medication.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/request.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/statement.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/timeline.test.ignore.ts
Labels: bug, ready

#2137 Fix issue with before block impacting other tests for AB#10420
  Testing/functional/e2e/cypress/integration/timeline/mobile/laboratory.js
  Testing/functional/e2e/package-lock.json
  Testing/functional/e2e/package.json
Labels: bug, functional tests, ready

#2139 Add functional tests for medication exclusions on reports AB#10373
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/fixtures/MedicationService/medicationStatement.json
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/report/reportFiltering.js
Labels: functional tests, ready

#2108 Exclude Med Records - Features/10292
  Apps/WebClient/src/ClientApp/src/components/multiSelect.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/reportFilter.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/fixtures/MedicationService/medicationStatement.json
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/report/reportFiltering.js
Labels: ready, user story

#2141 Fix display of last login date AB#10404
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: bug, ready

#2140 Fix reports with null demographics AB#10418
  Apps/WebClient/src/ClientApp/src/components/modal/covid.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/views/loginCallback.vue
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/src/views/validateEmail.vue
Labels: bug, ready
