Repository bcgov/healthgateway, pull requests merged in 2021-05, with the labels that each got.

#2254 Rename stub files AB#10444
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/views/login.vue
  Apps/WebClient/src/ClientApp/test/app.test.ts
  Apps/WebClient/src/ClientApp/test/components/monthYearPicker.test.ts
  Apps/WebClient/src/ClientApp/test/components/navbar.header.test.ts
  Apps/WebClient/src/ClientApp/test/healthInsights.test.ts
  Apps/WebClient/src/ClientApp/test/landing.test.ts
  Apps/WebClient/src/ClientApp/test/login.test.ts
  Apps/WebClient/src/ClientApp/test/router.test.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/authStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/commentStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/configStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/encounterStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/errorBannerStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/idleStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/immunizationStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/medicationStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/navbarStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/noteStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/storeOptionsStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/timelineStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/userStub.ts
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
Labels: ready

#2262 Fixes SonarCloud Pipeline Features/10444
  Apps/sonar-config.xml
  Tools/SonarCloud/azure/build.yaml
Labels: ready

#2263 Shrink background of loading animation to match icon size AB#10502
  Apps/WebClient/src/ClientApp/src/components/loading.vue
Labels: bug, ready

#2264 Improve Jest Integration with VSCode AB#10520
  Apps/HealthGateway.code-workspace
Labels: ready

#2267 Added Secondary selected styles
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/shared/hgButton.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/test/components/monthYearPicker.test.ts
  Apps/WebClient/src/ClientApp/test/components/navbar.header.test.ts
  Apps/WebClient/src/ClientApp/test/healthInsights.test.ts
  Apps/WebClient/src/ClientApp/test/landing.test.ts
  Apps/WebClient/src/ClientApp/test/login.test.ts
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
Labels: ready

#2266 Report view & Router tests + cleanup
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/plugins/inversify.container.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/.eslintrc.js
  Apps/WebClient/src/ClientApp/test/app.test.ts
  Apps/WebClient/src/ClientApp/test/components/error.test.ts
  Apps/WebClient/src/ClientApp/test/components/monthYearPicker.test.ts
  Apps/WebClient/src/ClientApp/test/components/navbar.header.test.ts
  Apps/WebClient/src/ClientApp/test/login.test.ts
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/ClientApp/test/router.test.ts
  Apps/WebClient/src/ClientApp/test/store/auth.test.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/authStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/commentStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/configStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/encounterStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/immunizationStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/medicationStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/noteStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/storeOptionsStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/userStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/util.ts
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
Labels: ready

#2248 Cleanup webclient package.json Features/10499
  Apps/WebClient/src/ClientApp/.eslintrc.js
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
Labels: ready

#2280 Fixes for Cypress tests for AB#10552
  Testing/functional/e2e/.eslintrc.json
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/calendar.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/support/commands.js
  Testing/functional/e2e/package-lock.json
  Testing/functional/e2e/package.json
Labels: bug, ready

#2299 Admin tag user interface and FE services - Tasks/10541
  .editorconfig
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/models/userFeedback.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restUserFeedbackService.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Feedback.vue
  Apps/AdminWebClient/src/Server/Controllers/TagController.cs
  Apps/AdminWebClient/src/Server/Models/AdminTagView.cs
  Apps/AdminWebClient/src/Server/Models/UserFeedbackView.cs
Labels: ready

#2300 Updated Release Notes 1.4.1 AB#10559
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#2307 Admin Tag - Backend changes Tasks/10544
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restUserFeedbackService.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Feedback.vue
  Apps/AdminWebClient/src/Server/Controllers/TagController.cs
  Apps/AdminWebClient/src/Server/Models/AdminTagView.cs
  Apps/AdminWebClient/src/Server/Models/UserFeedbackView.cs
  Apps/AdminWebClient/src/Server/Services/IUserFeedbackService.cs
  Apps/AdminWebClient/src/Server/Services/UserFeedbackService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/Database/src/Database.xml
  Apps/Database/src/Delegates/DBFeedbackDelegate.cs
  Apps/Database/src/Models/UserFeedback.cs
  Apps/Database/src/Models/UserFeedbackAdmin.cs
  Apps/Database/src/Models/UserFeedbackTag.cs
Labels: ready

#2309 Resource Centre Functional Tests
  Apps/WebClient/src/ClientApp/src/components/resourceCentre.vue
  Testing/functional/e2e/cypress/integration/resourceCentre/resourceCentre.js
Labels: ready

#2308 Add resource centre to nav pages AB#10403
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/resourceCentre.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgButton.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgIcon.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/immunizationStub.ts
  Testing/functional/e2e/cypress/integration/resourceCentre/resourceCentre.js
Labels: user story

#2310 Features/10539
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/views/Feedback.vue
  Apps/AdminWebClient/src/Server/Controllers/TagController.cs
  Apps/AdminWebClient/src/Server/Services/IUserFeedbackService.cs
  Apps/AdminWebClient/src/Server/Services/UserFeedbackService.cs
  Apps/Database/src/Database.xml
  Apps/Database/src/Delegates/DBFeedbackTagDelegate.cs
  Apps/Database/src/Delegates/IFeedbackTagDelegate.cs
Labels: ready, user story

#2323 Add title to resource centre menu AB#10568
  Apps/WebClient/src/ClientApp/src/components/resourceCentre.vue
  Apps/WebClient/src/ClientApp/src/main.ts
Labels: bug, ready

#2337 refresh user profile after email verified AB#10533
  Apps/WebClient/src/ClientApp/src/views/validateEmail.vue
  Testing/functional/e2e/cypress/integration/user/emailValidation.js
Labels: ready

#2334 Update report tables - Features/10475
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/loading.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationRequest.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/models/reportField.ts
  Apps/WebClient/src/ClientApp/src/utility/pdfUtil.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
Labels: ready

#2336 Filter user feedback by tags AB#10538
  Apps/AdminWebClient/src/ClientApp/src/views/Feedback.vue
Labels: ready, user story

#2338 Recurring Users count AB#10438
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Services/IDashboardService.cs
  Apps/Database/src/Database.xml
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
Labels: ready

#2339 Fixes immunization loaded banner AB#10514
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/immunizationNoRecords.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/immunization.js
Labels: ready

#2344 Report table functional tests update - AB#10599
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/models/reportField.ts
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/report/reportFiltering.js
  Testing/functional/e2e/cypress/integration/resourceCentre/resourceCentre.js
  Testing/functional/e2e/cypress/integration/user/emailValidation.js
  Testing/functional/e2e/cypress/support/commands.js
Labels: ready

#2345 Update Release Notes 1.4.2 AB#10604
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#2366 Merge to Master
  .github/CODEOWNERS
  .github/dependabot.yml
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
Labels: ready

#2363 Added services and store to create and retrieve credentials. AB#10619
  Apps/WebClient/src/ClientApp/src/models/credentialConnection.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restCredentialService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/credential.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/types.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/store/types.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/credentialStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/storeOptionsStub.ts
Labels: ready

#2367 Create Aca-Py Delegate and DB Delegate and associated models
  Apps/Common/src/Common.xml
  Apps/Common/src/ErrorHandling/ServiceType.cs
  Apps/Database/src/Constants/WalletConnectionStatus.cs
  Apps/Database/src/Constants/WalletCredentialStatus.cs
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Database.xml
  Apps/Database/src/Delegates/DBWalletDelegate.cs
  Apps/Database/src/Delegates/IWalletDelegate.cs
  Apps/Database/src/Models/WalletConnection.cs
  Apps/Database/src/Models/WalletConnectionStatusCode.cs
  Apps/Database/src/Models/WalletCredential.cs
  Apps/Database/src/Models/WalletCredentialStatusCode.cs
  Apps/Database/src/Utils/EnumUtility.cs
  Apps/Medication/src/Properties/launchSettings.json
  Apps/WebClient/src/Server/Delegates/IWalletIssuerDelegate.cs
  Apps/WebClient/src/Server/Delegates/WalletIssuerDelegate.cs
  Apps/WebClient/src/Server/Models/AcaPy/Connection.cs
  Apps/WebClient/src/Server/Models/AcaPy/CreateConnectionResponse.cs
  Apps/WebClient/src/Server/Models/AcaPy/ImmunizationCredential.cs
  Apps/WebClient/src/Server/Models/AcaPy/WalletIssuerConfiguration.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Delegates.Test/WalletIssuerDelegateTests.cs
  Apps/WebClient/test/unit/WebClientTests.csproj
  Apps/WebClient/test/unit/WebClientTests.xml
  Tools/AzureAgent/openshift/AzureAgent.yaml
Labels: enhancement

#2372 WalletStatus Controller & Delegate
  Apps/Common/src/AccessManagement/Authorization/Handlers/ApiKeyAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Policy/ApiKeyPolicy.cs
  Apps/Common/src/AccessManagement/Authorization/Requirements/ApiKeyRequirement.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.xml
  Apps/Common/test/unit/AccessManagement/Authorization/ApiKeyAuthorizationHandlerTests.cs
  Apps/Common/test/unit/CommonTests.xml
  Apps/Database/src/Database.xml
  Apps/Database/src/Delegates/DBWalletDelegate.cs
  Apps/Database/src/Delegates/IWalletDelegate.cs
  Apps/Database/src/Models/WalletCredential.cs
  Apps/WebClient/src/Server/Controllers/WalletStatusController.cs
  Apps/WebClient/src/Server/Delegates/IWalletIssuerDelegate.cs
  Apps/WebClient/src/Server/Delegates/WalletIssuerDelegate.cs
  Apps/WebClient/src/Server/Models/AcaPy/ConnectionResponse.cs
  Apps/WebClient/src/Server/Models/AcaPy/ConnectionState.cs
  Apps/WebClient/src/Server/Models/AcaPy/CredentialExchangeState.cs
  Apps/WebClient/src/Server/Models/AcaPy/CredentialPayload.cs
  Apps/WebClient/src/Server/Models/AcaPy/CredentialResponse.cs
  Apps/WebClient/src/Server/Models/AcaPy/ImmunizationCredentialPayload.cs
  Apps/WebClient/src/Server/Models/AcaPy/WebhookData.cs
  Apps/WebClient/src/Server/Models/AcaPy/WebhookTopic.cs
  Apps/WebClient/src/Server/Services/IWalletStatusService.cs
  Apps/WebClient/src/Server/Services/WalletStatusService.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Delegates.Test/WalletIssuerDelegateTests.cs
  Apps/WebClient/test/unit/WebClientTests.xml
Labels: enhancement, ready

#2373 Add retrieval of single immunization | Tasks/10581
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Delegates/IImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Immunization.xml
  Apps/Immunization/src/Models/ImmunizationEvent.cs
  Apps/Immunization/src/Models/PHSA/ImmunizationResponse.cs
  Apps/Immunization/src/Services/IImmunizationService.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmsDelegateTests.cs
  Apps/Immunization/test/unit/ImmunizationTests.xml
  Apps/Immunization/test/unit/Services.Test/ImmsServiceTests.cs
  Apps/WebClient/src/ClientApp/src/services/restImmunizationService.ts
Labels: ready

#2376 Fixed parsing of recommendation due date. AB#10648
  Apps/Immunization/src/Immunization.xml
  Apps/Immunization/src/Models/ImmunizationRecommendation.cs
  Apps/Immunization/src/Models/PHSA/Recommendation/RecommendationResponse.cs
  Apps/Immunization/src/Models/PHSA/Recommendation/VaccineCode.cs
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
Labels: bug, ready
