Repository bcgov/healthgateway, pull requests merged in 2021-04, with the labels that each got.

#2161 Fix fetch laboratory AB#10441
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
Labels: ready

#2183 FAQ Typo Fix AB#10446
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#2185 Fix Fetch Laboratory Error Handler AB#10441
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
Labels: ready

#2191 Update Immunization tests AB#10453
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready

#2196 Removed address from msp visits AB#10473
  Apps/Encounter/src/Encounter.xml
  Apps/Encounter/src/Models/Clinic.cs
  Apps/Encounter/src/Models/EncounterModel.cs
  Apps/Encounter/test/unit/Controllers/EncounterController_Test.cs
  Apps/Encounter/test/unit/Services/EncounterService_Test.cs
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/encounter.vue
  Apps/WebClient/src/ClientApp/src/models/clinic.ts
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Testing/functional/e2e/cypress/integration/timeline/encounter.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/encounter.js
Labels: ready

#2204 Fixes the SMS being different between registration and DB
  Apps/Common/src/Common.xml
  Apps/Common/src/Services/INotificationSettingsService.cs
  Apps/Common/src/Services/NotificationSettingsService.cs
  Apps/WebClient/src/Server/Services/IUserSMSService.cs
  Apps/WebClient/src/Server/Services/UserProfileService.cs
  Apps/WebClient/src/Server/Services/UserSMSService.cs
Labels: ready

#2213 Fixed common unit tests
  Apps/Common/test/unit/Services/NotificationSettingsService_Test.cs
Labels: bug, ready

#2193 Fix last month sometimes missing from health insight graph AB#10061
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
Labels: bug, ready

#2230 Fixed banners not working
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
  Tools/Dev/Design/sampler/.gitignore
Labels: bug, ready

#2238 Fix sonarcloud pipeline
  Tools/SonarCloud/azure/build.yaml
Labels: ready

#2239 Update SonarCloud build.yaml for Azure Pipelines
  Tools/SonarCloud/azure/build.yaml
Labels: ready

#2241 Fix logout and navigation issues when resizing timeline AB#10412
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
Labels: bug, ready

#2244 Update sonarcloud pipeline
  Apps/.gitignore
  Apps/AdminWebClient/.gitignore
  Apps/AdminWebClient/sonar-config.yml
  Apps/AdminWebClient/xUnitResults/TestResults.xml
  Apps/Common/sonar-config.yml
  Apps/Database/src/Context/BaseDbContext.cs
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Encounter/.gitignore
  Apps/Encounter/sonar-config.yml
  Apps/HealthGateway.sln
  Apps/Immunization/.gitignore
  Apps/Immunization/sonar-config.yml
  Apps/Immunization/test/unit/coverage.opencover.xml
  Apps/Immunization/test/unit/xUnitResults/TestResults.xml
  Apps/Laboratory/.gitignore
  Apps/Laboratory/sonar-config.yml
  Apps/Medication/sonar-config.yml
  Apps/Patient/sonar-config.yml
  Apps/WebClient/.gitignore
  Apps/WebClient/sonar-config.yml
  Apps/WebClient/src/WebClient.xml
  Apps/sonar-config.xml
  Tools/SonarCloud/azure/build.yaml
Labels: ready

#2242 Create healthinsights unit tests AB#10430
  Apps/WebClient/src/ClientApp/test/healthInsights.test.ts
Labels: ready

#2251 Code Smells - Remove unused variables
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/App.vue
  Apps/AdminWebClient/src/ClientApp/src/services/httpDelegate.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Controllers/UserFeedbackController.cs
  Apps/AdminWebClient/src/Server/Services/AuthenticationService.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Services/EmailAdminService.cs
  Apps/AdminWebClient/test/unit/Services.Test/DashboardServiceTests.cs
  Apps/Common/test/unit/FileDownload/FileDownloadServiceTests.cs
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/Encounter/src/Encounter.xml
  Apps/Encounter/src/Startup.cs
  Apps/Encounter/test/unit/Controllers/EncounterControllerTests.cs
  Apps/Encounter/test/unit/EncounterTests.xml
  Apps/Encounter/test/unit/Services/EncounterServiceTests.cs
  Apps/Immunization/src/Immunization.xml
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/test/unit/ImmunizationTests.xml
  Apps/Immunization/test/unit/Services.Test/ImmsServiceTests.cs
  Apps/JobScheduler/src/JobScheduler.xml
  Apps/JobScheduler/src/Jobs/CleanCacheJob.cs
  Apps/JobScheduler/src/Jobs/DBMigrationsJob.cs
  Apps/JobScheduler/src/Jobs/DeleteEmailJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/Tasks/SendValidatedUsersToPHSA.cs
  Apps/Laboratory/src/Laboratory.xml
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/Medication/src/Medication.xml
  Apps/Medication/src/Services/MedicationRequestService.cs
  Apps/Medication/test/unit/MedicationTests.xml
  Apps/Medication/test/unit/Services/MedicationRequestServiceTests.cs
  Apps/Medication/test/unit/Services/MedicationServiceTests.cs
  Apps/Medication/test/unit/Services/MedicationStatementServiceTests.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Patient.xml
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
  Apps/WebClient/src/ClientApp/src/services/httpDelegate.ts
  Apps/WebClient/src/Server/Controllers/CommentController.cs
  Apps/WebClient/src/Server/Controllers/NoteController.cs
  Apps/WebClient/src/Server/Controllers/UserFeedbackController.cs
  Apps/WebClient/src/Server/Listeners/BannerListener.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/test/unit/Controllers.Test/CommentControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/NoteControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/UserFeedbackControllerTests.cs
Labels: needs attention
