Repository bcgov/healthgateway, pull requests merged in 2021-02, with the labels that each got.

#1742 Update Immunization Report
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
Labels: enhancement, ready, user story

#1744 Update reports header AB#9951
  Apps/WebClient/src/ClientApp/src/assets/images/gov/bcid-logo-rev-en.png
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
Labels: ready

#1754 Moved date/list toggle to filter
  Apps/WebClient/src/ClientApp/src/components/calendar/calendar.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/header.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/calendarTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1743 Forecast status parsing AB#9993
  Apps/Immunization/src/Constants/ForecastStatus.cs
  Apps/Immunization/src/Models/ImmunizationForecast.cs
  Apps/Immunization/src/Models/ImmunizationRecommendation.cs
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
Labels: bug, hotfix, ready

#1763 Updated cards for new design
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/errorCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/noteEdit.vue
  Apps/WebClient/src/ClientApp/src/components/plot/lineChart.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/encounter.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/addComment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/comment.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/encounter.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/medication.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/medication.vue
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/termsOfService.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/integration/timeline/calendar.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/timeline/pagination.js
Labels: ready

#1764 Fix unit tests AB#9965
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/constants/resulttype.ts
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/test/login.test.ts
  Apps/WebClient/src/ClientApp/test/router.test.ts
  Apps/WebClient/src/ClientApp/test/store/auth.test.ts
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
Labels: ready

#1765 Updated Note functionality for mobile - Tasks/9998
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/calendar.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/header.vue
  Apps/WebClient/src/ClientApp/src/components/modal/noteEdit.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/models/noteTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1766 Fix report header AB#10000
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
Labels: ready

#1768 Update immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
Labels: ready

#1770 Merge from master b
  Apps/Immunization/src/Constants/ForecastStatus.cs
  Apps/Immunization/src/Models/ImmunizationForecast.cs
  Apps/Immunization/src/Models/ImmunizationRecommendation.cs
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
Labels: ready

#1774 Update reports layout AB#10007
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1778 Remove profile from sidebar AB#100019
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
Labels: ready

#1776 Fix login redirect AB#10028
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restAuthenticationService.ts
Labels: ready

#1777 Mobile sticky header on scroll - AB#9934
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/calendar/calendar.vue
  Apps/WebClient/src/ClientApp/src/components/feedback.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/constants/screenWidth.ts
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/navbar.ts
  Apps/WebClient/src/ClientApp/src/store/modules/sidebar/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/sidebar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/sidebar/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/store.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/navbar.header.test.ts
  Apps/WebClient/src/ClientApp/test/timeline.test.ignore.ts
Labels: enhancement, pending story verification, ready

#1775 add cookies to cypress tests
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/support/commands.js
  Testing/functional/e2e/cypress/support/globalStorage.js
Labels: bug, ready

#1786 Update export records filter
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready

#1789 Updated the header profile AB#10018
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Testing/functional/e2e/cypress/integration/authentication/auth.js
  Testing/functional/e2e/cypress/integration/timeline/menu.js
  Testing/functional/e2e/cypress/integration/user/profile.js
  Testing/functional/e2e/cypress/support/commands.js
Labels: ready

#1787 Update Immz Model AB#10013
  Apps/Immunization/src/Models/ImmunizationEvent.cs
  Apps/Immunization/src/Models/PHSA/ImmunizationViewResponse.cs
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
Labels: ready

#1788 Update functional tests
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: ready

#1779 Advanced Filter on Export Records Features/9895
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/e2e/cypress/integration/report/report.js
Labels: enhancement, ready

#1793 Move Profile from side bar to top right
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/test/navbar.header.test.ts
  Testing/functional/e2e/cypress/integration/authentication/auth.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/timeline/menu.js
  Testing/functional/e2e/cypress/integration/user/profile.js
  Testing/functional/e2e/cypress/integration/user/starRating.js
  Testing/functional/e2e/cypress/support/commands.js
Labels: ready, user story

#1794 fix covidModal func. test
  Testing/functional/e2e/cypress/integration/timeline/modals/covidModal.js
Labels: bug, ready

#1795 Added the immunization card AB#10012
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/noteEdit.vue
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/encounter.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/models/dateWrapper.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1804 Add traceId to request result error AB#10021
  Apps/Common/src/Models/RequestResultError.cs
Labels: ready

#1805 Rename Laboratory Filter AB#10016
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: enhancement, ready

#1808 Display TraceId
  Apps/WebClient/src/ClientApp/src/components/errorCard.vue
  Apps/WebClient/src/ClientApp/src/models/bannerError.ts
  Apps/WebClient/src/ClientApp/src/models/requestResult.ts
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
Labels: ready

#1809 Immz Proof Card functional tests
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/navbar.header.test.ts
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/e2e/cypress/integration/authentication/auth.js
  Testing/functional/e2e/cypress/integration/report/report.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/menu.js
  Testing/functional/e2e/cypress/integration/timeline/modals/covidModal.js
  Testing/functional/e2e/cypress/integration/user/profile.js
  Testing/functional/e2e/cypress/integration/user/starRating.js
  Testing/functional/e2e/cypress/support/commands.js
Labels: ready

#1826 Fix build error with date formatting for AB#10051
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: bug, ready

#1830 Update Email Verification Page AB#10047
  Apps/Common/src/ErrorHandling/ActionType.cs
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restUserProfileService.ts
  Apps/WebClient/src/ClientApp/src/views/validateEmail.vue
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/src/Server/Services/IUserEmailService.cs
  Apps/WebClient/src/Server/Services/UserEmailService.cs
  Testing/functional/e2e/cypress/fixtures/WebClientService/EmailValidation/expired.json
  Testing/functional/e2e/cypress/fixtures/WebClientService/EmailValidation/invalid.json
  Testing/functional/e2e/cypress/fixtures/WebClientService/EmailValidation/valid.json
  Testing/functional/e2e/cypress/integration/user/emailValidation.js
Labels: ready

#1825 Added extra logic to check if the number should be removed
  Apps/WebClient/src/ClientApp/src/components/modal/verifySMS.vue
  Build/hg.yaml
  Testing/functional/azure/build.yaml
  Tools/SonarCloud/azure/build.yaml
Labels: bug, hotfix, ready

#1833 Updated timeline card with date AB#10025
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
Labels: ready

#1835 Updated immz message
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1827 Add expiry hours logic
  Apps/Common/src/Services/EmailQueueService.cs
  Apps/Common/src/Services/IEmailQueueService.cs
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/Server/Services/UserEmailService.cs
  Apps/WebClient/src/appsettings.json
Labels: ready

#1810 Add func. test for Banner Error
  Testing/functional/e2e/cypress/fixtures/WebClientService/dbError.json
  Testing/functional/e2e/cypress/integration/timeline/errors.js
Labels: ready

#1840 Update functional tests
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready

#1841 Fixed expiry hours display format
  Apps/Common/src/Services/EmailQueueService.cs
  Apps/WebClient/src/Server/Services/UserEmailService.cs
Labels: ready

#1842 Fix calendar view navigation AB#10054
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
Labels: ready

#1807 Error Messaging AB#9999
  Apps/Common/src/Models/RequestResultError.cs
  Apps/WebClient/src/ClientApp/src/components/errorCard.vue
  Apps/WebClient/src/ClientApp/src/models/bannerError.ts
  Apps/WebClient/src/ClientApp/src/models/requestResult.ts
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
  Testing/functional/e2e/cypress/fixtures/WebClientService/dbError.json
  Testing/functional/e2e/cypress/integration/timeline/errors.js
Labels: enhancement, ready, user story

#1859 Update Immunization Message AB#10004
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: enhancement, ready, user story

#1860 update release notes AB#10044
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1855 Timeline card updates - Features/9996
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/monthYearPicker.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Testing/functional/e2e/cypress/integration/timeline/calendar.js
  Testing/functional/e2e/cypress/integration/timeline/notes.js
  Testing/functional/e2e/cypress/integration/timeline/pagination.js
Labels: enhancement, ready, user story

#1861 Bugs/10076
  Apps/Common/test/unit/Services/EmailQueueService_Test.cs
  Apps/WebClient/test/unit/Services.Test/UserProfileService_Test.cs
Labels: bug, ready

#1867 Add documentation for missing robots.txt for AB#10088
  Apps/WebClient/src/WebClient.csproj
  Tools/BaseBuild/README.md
  Tools/BaseBuild/robots.txt
Labels: bug, ready

#1868 Display Type if Title is empty
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
Labels: ready

#1866 Remove 405 test
  Testing/functional/e2e/cypress/integration/services/webClient/userProfile.js
Labels: bug, ready

#1870 Add note icon to timeline entry
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
Labels: ready

#1877 Add functional tests
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Testing/functional/e2e/cypress/integration/timeline/comments.js
Labels: ready

#1885 Add empty title functional test AB#10098
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunizationEmptyName.json
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: ready

#1888 Add access control to webclient AB#10116
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Encounter/src/Startup.cs
  Apps/Immunization/src/Startup.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/Laboratory/src/Startup.cs
  Apps/WebClient/src/Server/Startup.cs
Labels: ready

#1887 Default card title if name missing
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Testing/functional/e2e/cypress/fixtures/ImmunizationService/immunizationEmptyName.json
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
Labels: enhancement, ready, user story

#1886 Enable comments icon AB#10039
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Testing/functional/e2e/cypress/integration/timeline/comments.js
Labels: enhancement, ready, user story

#1894 Landing Page Update - Clarity on Immunizations AB#10160
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: ready

#1895 Filter updates
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/calendar.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/header.vue
  Apps/WebClient/src/ClientApp/src/components/modal/covid.vue
  Apps/WebClient/src/ClientApp/src/components/modal/noteEdit.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/calendarTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/noteTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/timeline.ts
  Apps/WebClient/src/ClientApp/src/store/store.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1897 Filter and Vuex updates - Features/10020
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/calendar.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/header.vue
  Apps/WebClient/src/ClientApp/src/components/modal/covid.vue
  Apps/WebClient/src/ClientApp/src/components/modal/noteEdit.vue
  Apps/WebClient/src/ClientApp/src/components/monthYearPicker.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/calendarTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/noteTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/storeState.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/timeline.ts
  Apps/WebClient/src/ClientApp/src/store/store.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/integration/timeline/calendar.js
  Testing/functional/e2e/cypress/integration/timeline/filter.js
Labels: ready, user story

#1896 Update Release Notes 1.3.8
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#1900 Fixed typo for Cancel button
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
Labels: bug, ready

#1899 Add robots asset AB#10128
  Apps/Common/src/Utils/AssetReader.cs
  Apps/WebClient/src/Server/Assets/Robots.Production.txt
  Apps/WebClient/src/Server/Assets/Robots.txt
  Apps/WebClient/src/Server/Controllers/RobotsController.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/Controllers.Test/RobotsController_Test.cs
Labels: ready

#1898 Add entry details for mobile
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/encounter.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/medication.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: ready

#1901 Features/9935
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/encounter.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/medication.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/e2e/cypress/integration/timeline/mobile/encounter.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/medication.js
Labels: enhancement, user story

#1912 Added menu buttons and routing AB#10172
  Apps/WebClient/src/ClientApp/src/components/navmenu/navFooter.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#1916 Removed packages breaking Azure agent build for AB#10196
  Tools/AzureAgent/docker/Dockerfile
Labels: bug, ready

#1911 Add faq.vue
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#1917 Switchover to Kubernetes Network policies for AB#10178
  Tools/BaseBuild/README.md
  Tools/BaseBuild/nsp.yaml
Labels: ready, user story

#1923 Add alert for email verifification
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
Labels: ready

#1924 Add FAQ functional tests AB#10173
  Apps/WebClient/src/ClientApp/src/views/faq.vue
  Testing/functional/e2e/cypress/integration/pages/faq.js
Labels: ready

#1922 Add download immz card AB#10175
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/report/immunizationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/components/report/mspVisits.vue
  Apps/WebClient/src/ClientApp/src/utility/pdfUtil.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
Labels: ready
