Repository bcgov/healthgateway, pull requests merged in 2021-06, with the labels that each got.

#2392 Add credentials page to front-end AB#10578
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/credential/credentialCollectionCard.vue
  Apps/WebClient/src/ClientApp/src/components/credential/credentialInstructions.vue
  Apps/WebClient/src/ClientApp/src/components/credential/credentialList.vue
  Apps/WebClient/src/ClientApp/src/components/credential/credentialManagement.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/wallet.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restCredentialService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/types.ts
  Apps/WebClient/src/ClientApp/src/views/credentials.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/credentialStub.ts
  Apps/WebClient/src/appsettings.json
Labels: ready

#2393 Bug Fixes for AB#10661
  Apps/Database/src/Migrations/20210531204515_SetupWallet.Designer.cs
  Apps/Database/src/Migrations/20210601231647_AlterCredentialAddSource.cs
  Apps/Database/src/Migrations/20210601235231_SetupWallet.Designer.cs
  Apps/Database/src/Migrations/20210601235231_SetupWallet.cs
  Apps/WebClient/src/ClientApp/src/services/restCredentialService.ts
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/appsettings.Development.json
Labels: bug, ready

#2396 Fixes nullable list of credentials AB#10662
  Apps/WebClient/src/Server/Models/WalletConnectionModel.cs
  Apps/WebClient/src/Server/Services/WalletService.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/test/unit/Services.Test/VerifiableCredentialServiceTests.cs
  Apps/WebClient/test/unit/WebClientTests.xml
Labels: ready

#2398 Fix connection QR code not displaying AB#10665
  Apps/WebClient/src/ClientApp/src/components/credential/credentialCollectionCard.vue
Labels: bug, ready

#2400 Updated store and front end services to add credentials. AB#10670
  Apps/WebClient/src/ClientApp/src/models/wallet.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restCredentialService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/credential.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/types.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/credentialStub.ts
  Apps/WebClient/src/WebClient.xml
Labels: ready

#2406 Added service and store for revoking credentials. AB#10672
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restCredentialService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/types.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/credentialStub.ts
Labels: ready

#2402 Update front-end for new connection/credential flow AB#10668
  Apps/Common/src/Models/AcaPy/CredentialResponse.cs
  Apps/WebClient/src/ClientApp/src/components/credential/credentialCollectionCard.vue
  Apps/WebClient/src/ClientApp/src/components/credential/credentialList.vue
  Apps/WebClient/src/ClientApp/src/components/credential/credentialManagement.vue
  Apps/WebClient/src/ClientApp/src/models/wallet.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restCredentialService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/credentials.vue
  Apps/WebClient/src/Server/Controllers/WalletController.cs
  Apps/WebClient/src/Server/Controllers/WalletStatusController.cs
  Apps/WebClient/src/Server/Models/AcaPy/WebhookData.cs
  Apps/WebClient/src/Server/Models/WalletConnectionModel.cs
  Apps/WebClient/src/Server/Models/WalletCredentialModel.cs
  Apps/WebClient/src/Server/Services/IWalletStatusService.cs
  Apps/WebClient/src/Server/Services/WalletService.cs
  Apps/WebClient/src/Server/Services/WalletStatusService.cs
  Apps/WebClient/src/WebClient.xml
  Tools/Dev/WalletAgent/manage
Labels: ready

#2413 Fix add after revoke and revoke without add for AB#10679
  Apps/WebClient/src/Server/Services/IWalletService.cs
  Apps/WebClient/src/Server/Services/IWalletStatusService.cs
  Apps/WebClient/src/Server/Services/WalletService.cs
  Apps/WebClient/src/Server/Services/WalletStatusService.cs
  Apps/WebClient/src/WebClient.xml
Labels: bug, ready

#2414 Added revoke credential UI elements AB#10628
  Apps/Database/src/Delegates/DBWalletDelegate.cs
  Apps/WebClient/src/ClientApp/src/components/credential/credentialList.vue
  Apps/WebClient/src/ClientApp/src/store/modules/credential/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/mutations.ts
Labels: ready

#2429 Create Wallet related Unit Tests AB#10669
  Apps/Common/test/unit/CommonTests.xml
  Apps/Common/test/unit/Delegates/WalletIssuerDelegateTests.cs
  Apps/WebClient/src/Server/Controllers/WalletController.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/test/unit/Controllers.Test/WalletControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/WalletServiceTests.cs
  Apps/WebClient/test/unit/WebClientTests.xml
Labels: ready

#2434 Add Swagger auth mechanism for Api Key on AB#10682
  Apps/Common/src/Swagger/AuthenticationRequirementsOperationFilter.cs
  Apps/Common/src/Swagger/ConfigureSwaggerGenOptions.cs
Labels: bug, ready

#2435 Implement Disconnect AB#10629
  Apps/WebClient/src/Server/Controllers/WalletController.cs
  Apps/WebClient/src/Server/Services/IWalletService.cs
  Apps/WebClient/src/Server/Services/WalletService.cs
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/test/unit/Controllers.Test/WalletControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/WalletServiceTests.cs
  Apps/WebClient/test/unit/WebClientTests.xml
Labels: ready

#2436 Fixes revoke issue for AB#10684
  Apps/WebClient/src/Server/Services/WalletStatusService.cs
Labels: bug, ready

#2441 Added reissue to the menu button. AB#10635
  Apps/WebClient/src/ClientApp/src/components/credential/credentialList.vue
Labels: ready

#2443 Added link for verification AB#10674
  Apps/WebClient/src/ClientApp/src/components/credential/credentialManagement.vue
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#2440 Add disconnect option to UI and Fixes Create Connection Error handler AB10683
  Apps/WebClient/src/ClientApp/src/components/credential/credentialCollectionCard.vue
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restCredentialService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/credential/actions.ts
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
  Apps/WebClient/src/Server/Services/WalletService.cs
Labels: ready

#2442 Features/10603
  Apps/WebClient/src/ClientApp/src/components/credential/credentialList.vue
  Apps/WebClient/src/ClientApp/src/components/credential/credentialManagement.vue
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.json
Labels: ready, user story

#2444 Fixes revoke issue on disconnect for AB#10689
  Apps/Database/src/Delegates/DBWalletDelegate.cs
Labels: bug, ready

#2448 Loading Spinner and Test Verifier Visibility
  Apps/WebClient/src/ClientApp/src/components/credential/credentialCollectionCard.vue
  Apps/WebClient/src/ClientApp/src/components/credential/credentialManagement.vue
Labels: ready

#2454 Added Connection and credential polling. AB#10686
  Apps/WebClient/src/ClientApp/src/views/credentials.vue
Labels: ready

#2457 Fix functional tests for AB#10701
  Testing/functional/e2e/cypress/integration/credential/credential.js
  Testing/functional/e2e/cypress/integration/report/immunizationReport.js
  Testing/functional/e2e/cypress/integration/resourceCentre/covidcard.js
  Testing/functional/e2e/cypress/integration/resourceCentre/resourceCentre.js
  Testing/functional/e2e/cypress/integration/services/immunization.js
  Testing/functional/e2e/cypress/integration/services/medication.js
  Testing/functional/e2e/cypress/integration/timeline/immunization.js
  Testing/functional/e2e/cypress/integration/timeline/immunizationNoRecords.js
  Testing/functional/e2e/cypress/integration/timeline/mobile/immunization.js
Labels: bug, functional tests, ready

#2459 Fixed wallet error reporting AB#10690
  Apps/Common/src/Common.xml
  Apps/Common/src/Models/RequestResultError.cs
  Apps/WebClient/src/Server/Services/WalletService.cs
Labels: bug, ready

#2462 update FAQ AB#10705
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: ready

#2466 Admin auth fix - AB#10733
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/JobScheduler/src/appsettings.hgtest.json
Labels: bug, ready

#2467 Update medication report max records AB#10553
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
Labels: bug, ready

#2483 Fix vertical padding on banner messages AB#10751
  Apps/WebClient/src/ClientApp/src/components/communication.vue
Labels: bug, ready

#2484 update release notes 1.4.4 AB#10739
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#2481 Add in-app communication management UI AB#10714
  Apps/AdminWebClient/src/ClientApp/src/components/core/CommunicationTable.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/modals/BannerModal.vue
Labels: ready

#2487 Display in-app messages when logged in and banners when not AB#10754
  Apps/WebClient/src/ClientApp/src/components/communication.vue
Labels: bug, ready

#2485 User lookup - Tasks/10717
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/App.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/BannerFeedback.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/MainNavbar.vue
  Apps/AdminWebClient/src/ClientApp/src/components/helper/Offset.vue2
  Apps/AdminWebClient/src/ClientApp/src/components/material/Card.vue2
  Apps/AdminWebClient/src/ClientApp/src/components/material/Notification.vue2
  Apps/AdminWebClient/src/ClientApp/src/components/material/StatsCard.vue2
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/models/messageVerification.ts
  Apps/AdminWebClient/src/ClientApp/src/models/requestResult.ts
  Apps/AdminWebClient/src/ClientApp/src/models/userQuery.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restSupportService.ts
  Apps/AdminWebClient/src/ClientApp/src/utility/phnValidator.ts
  Apps/AdminWebClient/src/ClientApp/src/utility/requestResultUtil.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Controllers/SupportController.cs
  Apps/Database/src/Database.xml
Labels: ready

#2486 Add comms functional tests AB#10717
  Apps/WebClient/src/ClientApp/src/components/communication.vue
  Testing/functional/e2e/cypress/db/seed.sql
  Testing/functional/e2e/cypress/integration/pages/communication.js
Labels: functional tests, ready

#2491 Add OC Deployment for HG CDogs and updated doc on AB#10775
  Tools/BaseBuild/README.md
  Tools/BaseBuild/hgcdogs.yaml
Labels: ready

#2490 Update snowplow analytics - AB#10139
  Apps/WebClient/src/ClientApp/src/components/modal/immunizationCard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/immunization.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/plugins/extensions.ts
  Apps/WebClient/src/ClientApp/src/utility/snowPlow.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/ClientApp/test/vueSetup.ts
Labels: ready

#2497 Snowplow - Updated endpoint AB#10790
  Apps/WebClient/src/ClientApp/public/snowplow.js
  Apps/WebClient/src/appsettings.hgdev.json
Labels: ready

#2496 Star Rating count - Features/10561
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Controllers/DashboardController.cs
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Services/IDashboardService.cs
  Apps/AdminWebClient/test/unit/Services.Test/DashboardServiceTests.cs
  Apps/Database/src/Database.xml
  Apps/Database/src/Delegates/DBRatingDelegate.cs
  Apps/Database/src/Delegates/IRatingDelegate.cs
Labels: ready

#2499 Added average count. AB#10561
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
Labels: ready

#2500 Add report controller, service and delegate AB#10776
  Apps/AdminWebClient/src/AdminWebClient.xml
  Apps/Common/src/Common.xml
  Apps/Common/src/ErrorHandling/ServiceType.cs
  Apps/WebClient/src/Server/Assets/Templates/MedicationReport.docx
  Apps/WebClient/src/Server/Controllers/ReportController.cs
  Apps/WebClient/src/Server/Delegates/CDogsDelegate.cs
  Apps/WebClient/src/Server/Delegates/ICDogsDelegate.cs
  Apps/WebClient/src/Server/Models/CDogsConfig.cs
  Apps/WebClient/src/Server/Models/CDogsOptionsModel.cs
  Apps/WebClient/src/Server/Models/CDogsRequestModel.cs
  Apps/WebClient/src/Server/Models/CDogsTemplateModel.cs
  Apps/WebClient/src/Server/Models/ReportModel.cs
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/Server/Services/IReportService.cs
  Apps/WebClient/src/Server/Services/ReportService.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/WebClient.xml
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Controllers.Test/ReportControllerTests.cs
  Apps/WebClient/test/unit/Delegates.Test/CDogsDelegateTest.cs
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
  Apps/WebClient/test/unit/WebClientTests.xml
Labels: ready

#2501 Added rating counts on bars. AB#10796
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
Labels: ready

#2502 Reports service Front end AB#10777
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/errorInterfaces.ts
  Apps/WebClient/src/ClientApp/src/models/report.ts
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restReportService.ts
  Apps/WebClient/src/Server/Assets/Templates/MedicationReport.docx
  Apps/WebClient/src/Server/Controllers/ReportController.cs
  Apps/WebClient/src/Server/Delegates/CDogsDelegate.cs
  Apps/WebClient/src/Server/Models/ReportModel.cs
  Apps/WebClient/src/Server/Services/ReportService.cs
  Apps/WebClient/src/WebClient.xml
Labels: ready

#2506 Recurring Users fix - AB#10723
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/Database/src/Database.xml
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/DBRatingDelegate.cs
  Apps/Database/src/Delegates/IRatingDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
Labels: bug, ready

#2507 Update Snowplow Endpoint AB#10795
  Apps/WebClient/src/ClientApp/public/snowplow.js
  Apps/WebClient/src/appsettings.hgdev.json
Labels: ready

#2508 Additional Common Tests
  Apps/Common/test/unit/Delegates/ImmunizationDelegateTest.cs
Labels: ready

#2509 Fix ordering of rating modal and loading overlay AB#9162
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/loading.vue
  Apps/WebClient/src/ClientApp/src/components/modal/rating.vue
Labels: bug, ready

#2510 Update Release Notes 1.4.5 AB#10797
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#2512 Changes report filter text AB#10802
  Apps/WebClient/src/ClientApp/src/components/report/header.vue
  Apps/WebClient/src/ClientApp/src/components/report/medicationHistory.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Testing/functional/tests/cypress/integration/e2e/report/reportFiltering.js
Labels: ready

#2513 Fix issues in medication report template AB#10801
  Apps/WebClient/src/Server/Assets/Templates/MedicationReport.docx
Labels: bug, ready

#2514 Fix front-end test folder not appearing in workspace AB#10804
  Apps/HealthGateway.code-workspace
Labels: bug, ready
