Repository bcgov/healthgateway, pull requests merged in 2022-12, with the labels that each got.

#4466 Prevent awkward word wrapping on hyphenated text
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/OptionDetails.vue
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/WebClient/src/ClientApp/public/index.html
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/HealthlinkSidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/CommentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/Covid19LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationRequestTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/views/ContactUsView.vue
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/FaqView.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicCovidTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
Labels: enhancement, ready

#4465 Fix logout issue by using cypress session to store login
  Testing/functional/tests/cypress.json
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
  Testing/functional/tests/cypress/integration/e2e/covid19/pcrTestKit.js
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/e2e/user/starRating.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTestWithTestKit.js
  Testing/functional/tests/cypress/integration/ui/pages/faq.js
  Testing/functional/tests/cypress/integration/ui/timeline/encounter.js
  Testing/functional/tests/cypress/support/commands.js
Labels: bugfix, functional tests, ready

#4445 Update dependent tab to include clinical documents for AB#14367
  Apps/ClinicalDocument/src/Startup.cs
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/clientModule.ts
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/tests/cypress/fixtures/ClinicalDocumentService/clinicalDocumentNoRecords.json
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: ready, UI

#4467 Implement Dependent Clinical Docs for AB#13647
  Apps/ClinicalDocument/src/Startup.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/clientModule.ts
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/tests/cypress/fixtures/ClinicalDocumentService/clinicalDocumentNoRecords.json
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: functional tests, ready, UI

#4468 Fix bug introduced by awkward word wrapping fix for AB#14355
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: bugfix, functional tests, ready

#4470 Refactor away from IApiResponse<T> on IImmunizationAdminApi for AB#14340
  Apps/AdminWebClient/src/Server/Api/IImmunizationAdminApi.cs
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/test/unit/Services.Test/CovidSupportServiceTests.cs
Labels: bugfix, .NET, ready

#4471 UI Enhancements Part 2 - filter button and menu width
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
Labels: enhancement, ready, UI

#4473 Enable Blazor Admin to use appropirate config for PHSA V2 for AB#14451.
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
  Apps/Common/src/AspNetConfiguration/Modules/PhsaV2.cs
  Apps/Common/src/Delegates/PHSA/RestTokenSwapDelegate.cs
  Apps/Common/src/Models/PHSA/PhsaConfigV2.cs
Labels: bugfix, .NET, ready

#4476 use obsolete mechanism for logout for AB#14344
  Apps/Admin/Client/Layouts/MainLayout.razor
  Apps/Admin/Client/Layouts/MainLayout.razor.cs
  Apps/Admin/Client/Pages/UnauthorizedPage.razor
  Apps/Admin/Client/Pages/UnauthorizedPage.razor.cs
Labels: bugfix, ready

#4477 Date Extending beyond Timeline Card
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
Labels: bugfix, ready, UI

#4478 Update desktop UI for notification centre AB#14361
  Apps/GatewayApi/src/Services/WebAlertService.cs
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/models/userProfile.ts
  Apps/WebClient/src/ClientApp/src/services/restNotificationService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/notification.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/store/types.ts
  Apps/WebClient/src/ClientApp/src/views/LoginCallbackView.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#4479 Implement session login for admin functional tests for AB#14449
  Apps/Admin/Tests/Functional/cypress.config.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
Labels: bugfix, functional tests, ready

#4491 Add unit tests for WebAlertService AB#14363
  Apps/GatewayApi/src/Services/WebAlertService.cs
  Apps/GatewayApi/test/unit/Services.Test/WebAlertServiceTests.cs
Labels: ready

#4494 In Cypress use client not server client id when accesing Keycloak for AB#14453
  Apps/Admin/Tests/Functional/cypress/support/commands.js
Labels: bugfix, functional tests, ready

#4495 Resolve login bug AB#14462
  Apps/WebClient/src/ClientApp/src/app.vue
Labels: bugfix, ready

#4496 Refactor Refit api to not use Dictionary for AB#14343
  Apps/Encounter/src/Api/IHospitalVisitApi.cs
  Apps/Encounter/src/Delegates/RestHospitalVisitDelegate.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
  Apps/Immunization/src/Api/IImmunizationApi.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Laboratory/src/Api/ILaboratoryApi.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
Labels: bugfix, .NET, ready

#4505 Remove references to getters within getters AB#14516
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/CommunicationComponent.vue
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/BreadcrumbComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/FooterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/LoginCallbackView.vue
Labels: bugfix, ready

#4508 Migrate to Cypress 12 for Health Gateway tests AB#14502
  Testing/functional/tests/README.md
  Testing/functional/tests/cypress.config.js
  Testing/functional/tests/cypress.json
  Testing/functional/tests/cypress/integration/e2e/services/encounter.js
  Testing/functional/tests/cypress/integration/e2e/services/immunization.js
  Testing/functional/tests/cypress/integration/e2e/services/medication.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/userProfile.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderReport.js
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/clinicalDocument.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrderReport.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
  Testing/functional/tests/cypress/plugins/index.js
  Testing/functional/tests/cypress/support/commands.js
  Testing/functional/tests/cypress/support/e2e.js
  Testing/functional/tests/package-lock.json
  Testing/functional/tests/package.json
Labels: functional tests, ready, do not merge

#4510 Update admin cypress to latest version for AB#14501
  Apps/Admin/Tests/Functional/README.md
  Apps/Admin/Tests/Functional/cypress.config.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
  Apps/Admin/Tests/Functional/package-lock.json
  Apps/Admin/Tests/Functional/package.json
  Testing/functional/tests/README.md
Labels: enhancement, functional tests, ready

#4518 Create ticket management model and interface for AB#14513
  Apps/WebClient/src/ClientApp/src/constants/ticketStatus.ts
  Apps/WebClient/src/ClientApp/src/models/checkInRequest.ts
  Apps/WebClient/src/ClientApp/src/models/ticket.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
Labels: enhancement, ready, UI

#4521 Switch to dotCover from OpenCover
  Apps/sonar-config.xml
  Tools/SonarCloud/azure/build.yaml
Labels: ready

#4527 Clean up issues on dependent page AB#14534 AB#14543 AB#14544
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
Labels: bugfix, ready, UI

#4528 Updated returned statuses for AB#14508.
  Apps/WebClient/src/ClientApp/src/constants/ticketStatus.ts
Labels: bugfix, javascript, ready

#4529 Client App Login Frequency
  Apps/Admin/Client/Api/IDashboardApi.cs
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
  Apps/Admin/Client/Store/Dashboard/DashboardActions.cs
  Apps/Admin/Client/Store/Dashboard/DashboardEffects.cs
  Apps/Admin/Client/Store/Dashboard/DashboardReducers.cs
  Apps/Admin/Client/Store/Dashboard/DashboardState.cs
  Apps/Admin/Client/Store/Dashboard/RecurringUser.cs
  Apps/Admin/Server/Controllers/DashboardController.cs
  Apps/Admin/Server/Services/DashboardService.cs
  Apps/Admin/Server/Services/IDashboardService.cs
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
  Apps/Database/src/Delegates/DbProfileDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
Labels: enhancement, functional tests, waiting, UI

#4535 Implement front-end store for waitlist AB#14506
  Apps/WebClient/src/ClientApp/src/models/checkInRequest.ts
  Apps/WebClient/src/ClientApp/src/models/ticket.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/waitlist.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/store/types.ts
Labels: ready

#4536 Create ticket service and http delegate helper method for AB#14514.
  Apps/WebClient/src/ClientApp/src/constants/serviceCodes.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/services/httpDelegate.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restTicketService.ts
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: enhancement, javascript, ready

#4506 Add Notification Centre functional tests
  Apps/WebClient/src/appsettings.hgdev.json
  Testing/functional/tests/cypress/fixtures/NotificationService/notifications.json
  Testing/functional/tests/cypress/integration/e2e/user/notificationCentre.js
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
Labels: functional tests, ready

#4540 UI Enhancement Part 3
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
Labels: ready, UI

#4541 UI Enhancement Part 3 - UI Task 3 - No Notifications
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/images/home/empty-state-notifications.svg
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
Labels: ready, UI

#4543 Implement ticket refresh management for AB#14507.
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restTicketService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/types.ts
  Apps/WebClient/src/appsettings.Development.json
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
  Testing/functional/tests/cypress/support/commands.js
Labels: enhancement, javascript, functional tests, ready

#4547 Client App Login Frequency - e2e functional test
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
  Testing/functional/tests/cypress/db/seed.sql
Labels: functional tests, ready

#4549 Map Problem Details error message to Http Error Message for AB#14557.
  Apps/WebClient/src/ClientApp/src/services/httpDelegate.ts
Labels: enhancement, javascript, ready

#4550 UI Enhancement Part 3 - UI Task 2 - Update Logo
  Apps/WebClient/src/ClientApp/src/assets/images/gov/hg-logo-rev.svg
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
Labels: enhancement, ready, UI

#4555 Update Dependent Lab No Records Message
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
Labels: ready

#4558 Fix browser reload issue for Queued and Busy pages for AB#14580.
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/actions.ts
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
Labels: bugfix, javascript, functional tests, ready

#4559 Simple Wait List Queue UI - AB#13743
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/images/queue/error.png
  Apps/WebClient/src/ClientApp/src/assets/images/queue/waiting.png
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/clientModule.ts
  Apps/WebClient/src/ClientApp/src/constants/serviceCodes.ts
  Apps/WebClient/src/ClientApp/src/constants/ticketStatus.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/checkInRequest.ts
  Apps/WebClient/src/ClientApp/src/models/ticket.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/httpDelegate.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restTicketService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/waitlist.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/store/types.ts
  Apps/WebClient/src/ClientApp/src/views/errors/AppErrorView.vue
  Apps/WebClient/src/ClientApp/src/views/waitlist/QueueFullView.vue
  Apps/WebClient/src/ClientApp/src/views/waitlist/QueueView.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
  Testing/functional/tests/cypress/support/commands.js
Labels: enhancement, functional tests, ready

#4560 Add waiting queue url to content security policy for AB#14592
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: bugfix, ready

#4562 Fix functional tests failing due to ticket module for AB#14593
  Testing/functional/tests/cypress/integration/e2e/pages/Registration.js
  Testing/functional/tests/cypress/integration/e2e/pages/breadcrumbs.js
  Testing/functional/tests/cypress/integration/e2e/resourceCentre/resourceCentre.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/e2e/user/acceptTermsOfService.js
  Testing/functional/tests/cypress/integration/e2e/user/starRating.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
  Testing/functional/tests/cypress/integration/ui/user/tutorial.js
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
Labels: bugfix, functional tests, ready
