Repository bcgov/healthgateway, pull requests merged in 2022-08, with the labels that each got.

#3960 Display error alerts for "too many requests" AB#13055
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/FeedbackComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/VerifySMSComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/AddCommentComponent.vue
  Apps/WebClient/src/ClientApp/src/services/restUserNoteService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/views/AcceptTermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/views/TermsOfServiceView.vue
Labels: ready, user story

#3968 Fix build warnings in Admin AB#13631
  Apps/Admin/Client/Pages/SupportPage.razor.cs
Labels: bugfix, ready

#3972 Features/13448
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Pages/LoginPage.razor
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/wwwroot/images/health-gateway-logo.svg
  Apps/Admin/Tests/Functional/cypress/integration/e2e/authentication.cy.js
Labels: functional tests, ready, UI

#3976 Update permissions for admin vaccine card page AB#13641
  Apps/AdminWebClient/src/ClientApp/src/components/core/MainNavbar.vue
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Login.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Logout.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Unauthorized.vue
  Apps/AdminWebClient/src/Server/Controllers/AuthenticationController.cs
  Apps/AdminWebClient/src/appsettings.Development.json
Labels: bugfix, ready

#3986 Update unauthorized page in AdminWebClient AB#13602
  Apps/AdminWebClient/src/ClientApp/public/assets/images/health-gateway-logo.svg
  Apps/AdminWebClient/src/ClientApp/src/components/core/Toolbar.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Unauthorized.vue
Labels: enhancement, ready

#3987 Update HGCDogs to use new image for AB#11001
  Apps/Common/src/Delegates/CDogsDelegate.cs
  Tools/BaseBuild/hgcdogs.yaml
Labels: ready

#3990 Update Landing page with app promo for AB#13669.
  Apps/WebClient/src/ClientApp/src/assets/images/landing/apple-badge.png
  Apps/WebClient/src/ClientApp/src/assets/images/landing/google-play-badge.png
  Apps/WebClient/src/ClientApp/src/assets/images/landing/mobile-app.png
  Apps/WebClient/src/ClientApp/src/components/laboratory/Covid19LaboratoryTestDescriptionComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/BreadcrumbComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/HealthlinkSidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/models/breadcrumbItem.ts
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicCovidTestView.vue
Labels: enhancement, ready, UI

#3989 Tasks/13620
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicCovidTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/medicationrequest.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: functional tests, ready

#3999 Add User Feedback to Blazor Admin System Analytics for AB#13682 and AB#13683
  Apps/Admin/Client/Pages/AnalyticsPage.razor
  Apps/Admin/Client/Pages/AnalyticsPage.razor.cs
  Apps/Admin/Client/Services/IAnalyticsApi.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsActions.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsEffects.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsReducers.cs
  Apps/Admin/Server/Controllers/CsvExportController.cs
  Apps/Admin/Server/Mappers/UserFeedbackCsvMap.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/ICsvExportService.cs
Labels: enhancement, ready, UI

#3993 Fix broken Admin functional tests AB#13635
  Apps/Admin/Tests/Functional/cypress/integration/e2e/analytics.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
  Apps/Admin/Tests/Functional/cypress/support/constants.js
  Apps/Admin/Tests/Functional/cypress/support/globalStorage.js
  Apps/Admin/Tests/Functional/cypress/support/index.d.ts
Labels: bugfix, ready

#4001 Add functional test for download user feedback in Blazor Admin for AB#13684.
  Apps/Admin/Server/Mappers/UserFeedbackCsvMap.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/analytics.cy.js
Labels: functional tests, ready

#4002 Initial restructure of Cache
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/CacheProviders/ICacheProvider.cs
  Apps/Common/src/CacheProviders/MemoryCacheProvider.cs
  Apps/Common/src/CacheProviders/RedisCacheProvider.cs
  Apps/Common/src/Common.csproj
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/Common/test/unit/CacheProviders/MemoryCacheProviderTests.cs
  Apps/Common/test/unit/CacheProviders/RedisCacheProviderTests.cs
  Apps/Common/test/unit/CommonTests.csproj
  Apps/GatewayApi/src/Startup.cs
  Apps/Immunization/src/Startup.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Medication/src/Startup.cs
Labels: ready

#4003 Added 429 too many requests error handling to Notes
  Apps/WebClient/src/ClientApp/src/components/TooManyRequestsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NoteEditComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/NoteTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/store/modules/note/actions.ts
  Testing/functional/tests/cypress/fixtures/NoteService/notes-test-note.json
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
Labels: bugfix, functional tests, ready

#4004 Remove IMemoryCache from CommunicationService and fixes for AB#13725
  Apps/Admin/Server/Program.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/Common/src/CacheProviders/ICacheProvider.cs
  Apps/Common/src/CacheProviders/MemoryCacheProvider.cs
  Apps/Common/src/CacheProviders/RedisCacheProvider.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/GatewayApi/src/Services/CommunicationService.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/src/appsettings.Development.json
  Apps/GatewayApi/test/unit/Services.Test/CommunicationServiceTests.cs
  Tools/Dev/Postgres/docker-compose.yml
Labels: ready

#4012 Add configuration to deploy Redis for AB#13727
  Apps/GatewayApi/src/Services/CommunicationService.cs
  Apps/GatewayApi/test/unit/Services.Test/CommunicationServiceTests.cs
  Tools/BaseBuild/README.md
  Tools/BaseBuild/redis/.helmignore
  Tools/BaseBuild/redis/Chart.yaml
  Tools/BaseBuild/redis/templates/NOTES.txt
  Tools/BaseBuild/redis/templates/_helpers.tpl
  Tools/BaseBuild/redis/templates/configmap.yml
  Tools/BaseBuild/redis/templates/secret.yaml
  Tools/BaseBuild/redis/templates/service.yaml
  Tools/BaseBuild/redis/templates/statefulset.yaml
  Tools/BaseBuild/redis/templates/tests/test-connection.yaml
  Tools/BaseBuild/redis/values.yaml
Labels: ready

#4013 Removes GenericCache and sets up Redis
  Apps/Admin/Server/Program.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Common/src/AspNetConfiguration/Modules/GatewayCache.cs
  Apps/Common/src/AspNetConfiguration/Modules/Patient.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Constants/HashFunction.cs
  Apps/Common/src/Delegates/HmacHashDelegate.cs
  Apps/Common/src/Delegates/IHashDelegate.cs
  Apps/Common/src/Models/Cacheable/HmacHash.cs
  Apps/Common/src/Models/Cacheable/IHash.cs
  Apps/Common/src/Services/PatientService.cs
  Apps/Common/test/unit/Delegates/HmacHashDelegateTests.cs
  Apps/Common/test/unit/Services/PatientServiceTests.cs
  Apps/Database/src/Database.csproj
  Apps/Database/src/Delegates/DBGenericCacheDelegate.cs
  Apps/Database/src/Delegates/IGenericCacheDelegate.cs
  Apps/Encounter/src/Startup.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/src/appsettings.Development.json
  Apps/Immunization/src/Startup.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/src/appsettings.Development.json
  Apps/Medication/test/unit/Delegates/MedicationDelegateTests.cs
  Apps/Medication/test/unit/Delegates/SalesforceDelegateTests.cs
  Apps/Patient/src/Program.cs
  Tools/BaseBuild/redis/templates/NOTES.txt
  Tools/BaseBuild/redis/templates/service.yaml
  Tools/BaseBuild/redis/templates/statefulset.yaml
  Tools/BaseBuild/redis/values.yaml
Labels: ready

#4005 Add more error handling and 429 handling (Part 1) AB#13633
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/VerifySMSComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/errors.ts
  Apps/WebClient/src/ClientApp/src/services/winstonLogger.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
  Apps/WebClient/src/ClientApp/src/utility/promiseUtility.ts
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/views/ValidateEmailView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/AppErrorView.vue
Labels: ready

#4016 Move BannerListener from GatewayApi to JobScheduler for AB#13736
  Apps/Common/src/Converters/DateTimeConverter.cs
  Apps/Common/src/Models/BannerChangeEvent.cs
  Apps/Common/src/Services/CommunicationService.cs
  Apps/Common/src/Services/ICommunicationService.cs
  Apps/Common/test/unit/Services/CommunicationServiceTests.cs
  Apps/Common/test/unit/Utils/Scenario.cs
  Apps/GatewayApi/src/Controllers/CommunicationController.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Controllers.Test/CommunicationControllerTests.cs
  Apps/JobScheduler/src/Listeners/BannerListener.cs
  Apps/JobScheduler/src/Startup.cs
Labels: ready

#4018 Serialize actual type for AB#13742
  Apps/Common/src/CacheProviders/RedisCacheProvider.cs
Labels: bugfix, ready

#4019 Add unit tests for token swap delegate and related service for AB#13680.
  Apps/Common/src/Services/AccessTokenService.cs
  Apps/Common/test/unit/Delegates/RestTokenSwapDelegateTests.cs
  Apps/Common/test/unit/Services/AccessTokenServiceTests.cs
Labels: .NET, unit tests, ready

#4027 Update Release Notes AB#13740
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#4028 Fixed profile.js functional test for AB#13747
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileSMSVerified.json
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: functional tests, ready

#4029 Add missing import for TooManyRequestsComponent AB#13751
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
Labels: bugfix, ready

#4030 Fix functional test for AB#13681.
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: bugfix, functional tests, ready

#4032 Turn down verbosity on some logging for AB#13752
  Apps/Common/src/AccessManagement/Authorization/Handlers/BaseFhirAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceDelegateAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/UserAuthorizationHandler.cs
  Apps/Encounter/src/Delegates/RestMspVisitDelegate.cs
Labels: ready

#4035 Merge to Master
  Apps/Common/src/AccessManagement/Authorization/Handlers/BaseFhirAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceDelegateAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/UserAuthorizationHandler.cs
  Apps/Encounter/src/Delegates/RestMspVisitDelegate.cs
Labels: ready

#4036 Create new Clinical Document projects
  Apps/ClinicalDocument/ClinicalDocument.sln
  Apps/ClinicalDocument/Dockerfile
  Apps/ClinicalDocument/azure/build.yaml
  Apps/ClinicalDocument/azure/prbuild.yaml
  Apps/ClinicalDocument/src/AssemblyInfo.cs
  Apps/ClinicalDocument/src/ClinicalDocument.csproj
  Apps/ClinicalDocument/src/Program.cs
  Apps/ClinicalDocument/src/Properties/launchSettings.json
  Apps/ClinicalDocument/src/Services/ClinicalDocumentService.cs
  Apps/ClinicalDocument/src/Services/IClinicalDocumentService.cs
  Apps/ClinicalDocument/src/Startup.cs
  Apps/ClinicalDocument/src/appsettings.Development.json
  Apps/ClinicalDocument/src/appsettings.hgdev.json
  Apps/ClinicalDocument/src/appsettings.hgmock.json
  Apps/ClinicalDocument/src/appsettings.hgpoc.json
  Apps/ClinicalDocument/src/appsettings.hgtest.json
  Apps/ClinicalDocument/src/appsettings.json
  Apps/ClinicalDocument/test/unit/AssemblyInfo.cs
  Apps/ClinicalDocument/test/unit/ClinicalDocumentTests.csproj
  Apps/ClinicalDocument/test/unit/Services/ClinicalDocumentServiceTests.cs
  Apps/HealthGateway.code-workspace
  Apps/HealthGateway.sln
Labels: ready

#4037 Updated no records found message for Dependent Immunizations
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Testing/functional/tests/cypress/db/seed.sql
Labels: bugfix, ready

#4047 Minor Update to FAQ
  Apps/WebClient/src/ClientApp/src/views/FaqView.vue
Labels: ready

#4040 Refactor Auditing to optionally support Redis for AB#13750
  Apps/Admin/Server/Program.cs
  Apps/ClinicalDocument/src/appsettings.json
  Apps/Common/src/AspNetConfiguration/Modules/Audit.cs
  Apps/Common/src/AspNetConfiguration/Modules/GatewayCache.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Auditing/AuditLogger.cs
  Apps/Common/src/Auditing/DbAuditLogger.cs
  Apps/Common/src/Auditing/RedisAuditLogger.cs
  Apps/Common/test/unit/Auditing/DbAuditLoggerTests.cs
  Apps/Encounter/src/appsettings.json
  Apps/GatewayApi/src/appsettings.json
  Apps/Immunization/src/appsettings.json
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/src/appsettings.json
  Apps/Medication/src/appsettings.json
  Apps/Patient/src/Program.cs
  Apps/Patient/src/appsettings.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#4050 Fix navbar list containing non-list items AB#8916
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
  Testing/functional/tests/cypress/integration/ui/pages/Login.js
Labels: bugfix, ready

#4051 Fix functional test intercepts AB#13817
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
Labels: bugfix, ready

#4052 Catch promise rejection and fix up validate email view AB#13819
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/views/ValidateEmailView.vue
Labels: bugfix, ready

#4054 Update BaseURL for mobile configuration
  Apps/WebClient/src/appsettings.hgtest.json
Labels: ready

#4055 Use OrderBy before Take/Skip for predictable results AB#13790
  Apps/Database/src/Delegates/DBEmailDelegate.cs
  Apps/Database/src/Delegates/DBResourceDelegateDelegate.cs
Labels: bugfix, ready

#4060 Add vaccine proof download to dependent card for AB#13781.
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
Labels: ready, UI

#4062 Disable new Audit Queue handling in Redis
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/ClinicalDocument/src/appsettings.hgdev.json
  Apps/Encounter/src/appsettings.hgdev.json
  Apps/GatewayApi/src/appsettings.hgdev.json
  Apps/Immunization/src/appsettings.hgdev.json
  Apps/JobScheduler/src/Listeners/AuditQueueListener.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/Laboratory/src/appsettings.hgdev.json
  Apps/Medication/src/appsettings.hgdev.json
  Apps/Patient/src/appsettings.hgdev.json
Labels: ready

#4063 Add clinical document controller, model, and service interface AB#13793
  Apps/ClinicalDocument/src/Controllers/ClinicalDocumentController.cs
  Apps/ClinicalDocument/src/Models/ClinicalDocumentRecord.cs
  Apps/ClinicalDocument/src/Services/ClinicalDocumentService.cs
  Apps/ClinicalDocument/src/Services/IClinicalDocumentService.cs
Labels: enhancement, ready

#4079 Update front-end for clinical documents AB#13799
  Apps/ClinicalDocument/src/Controllers/ClinicalDocumentController.cs
  Apps/HealthGateway.code-workspace
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntryDetailsComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/clientModule.ts
  Apps/WebClient/src/ClientApp/src/constants/commentEntryType.ts
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/constants/serviceCodes.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/clinicalDocument.ts
  Apps/WebClient/src/ClientApp/src/models/clinicalDocumentTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restClinicalDocumentService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/clinicalDocument.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/types.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/store/types.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: enhancement, ready, UI

#4080 Update front-end for mobile app communications AB#13806
  Apps/Admin/Client/Pages/CommunicationsPage.razor
  Apps/Admin/Client/Pages/CommunicationsPage.razor.cs
  Apps/CommonData/src/Constants/CommunicationType.cs
Labels: enhancement, ready
