Repository bcgov/healthgateway, pull requests merged in 2022-05, with the labels that each got.

#3619 Update Immunization History and Forecast plus Report for AB#12955.
  Apps/Immunization/src/Api/IImmunizationClient.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Delegates/IImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Services/IImmunizationService.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/services/restImmunizationService.ts
Labels: enhancement, unit tests, ready, UI

#3609 Fix code smells AB#12875
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/CalendarBodyComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/Covid19ReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgTimeDropdownComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/utility/fragmentStorage.ts
  Apps/WebClient/src/ClientApp/src/utility/phoneUtil.ts
  Apps/WebClient/src/ClientApp/src/views/HealthInsightsView.vue
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/ClientApp/test/mocks/mediaFileTransformer.js
Labels: bugfix, ready

#3621 Add immunization access for dependents AB#9419
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Immunization/src/Api/IImmunizationClient.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Delegates/IImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Immunization.csproj
  Apps/Immunization/src/Services/IImmunizationService.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/clientModule.ts
  Apps/WebClient/src/ClientApp/src/services/restImmunizationService.ts
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/tests/cypress/fixtures/ImmunizationService/dependentImmunization.json
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: ready, user story

#3628 Fix verification buttons always displaying on profile AB#13008
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
Labels: bugfix, ready

#3632 Add Configuration for new Endpoint
  Apps/WebClient/src/Server/Models/MobileConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#3633 Add download report button in dependent immunization tab for AB#12863
  Apps/GatewayApi/src/Assets/Templates/DependentImmunizationReport.docx
  Apps/GatewayApi/src/Assets/Templates/DependentImmunizationReport.xlsx
  Apps/GatewayApi/src/GatewayApi.csproj
  Apps/GatewayApi/src/Models/ReportRequestModel.cs
  Apps/GatewayApi/test/unit/Services.Test/ReportServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/Server/Assets/Templates/DependentImmunizationReport.docx
  Apps/WebClient/src/Server/Assets/Templates/DependentImmunizationReport.xlsx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
Labels: enhancement, .NET, unit tests, ready, UI

#3635 Remove leading slash on service base uri for AB#13021
  Apps/WebClient/src/ClientApp/src/services/restDependentService.ts
  Apps/WebClient/src/ClientApp/src/services/restReportService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserCommentService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserFeedback.ts
  Apps/WebClient/src/ClientApp/src/services/restUserNoteService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserProfileService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserRatingService.ts
Labels: ready

#3636 Fix column name bug for AB#13023.
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
Labels: bugfix, ready, UI

#3638 Add data-testid for functional tests for AB#12864.
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: functional tests, ready

#3641 Cleanup and use only displayable HDIDs for AB#13046
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
Labels: bugfix, ready

#3647 Resolve nullable id issue for EMPI lookup for AB#13046
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
Labels: bugfix, ready

#3648 Fix status for user readability on Timeline and Report for AB#13024.
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: bugfix, functional tests, ready

#3637 Add Kong configurations for services AB#12961
  Apps/HealthGateway.code-workspace
  Apps/WebClient/src/appsettings.hgdev.json
  Tools/Kong/.gitignore
  Tools/Kong/README.md
  Tools/Kong/config.tmpl
  Tools/Kong/generate.sh
  Tools/Kong/immunization.tmpl
  Tools/Kong/network-policies.yaml
  Tools/Kong/networkpolicy.yaml
  Tools/Kong/publish.sh
Labels: enhancement, ready

#3649 Display status on lab result timeline header AB#13044
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: ready, user story

#3650 Add hg-dev API to content security policy AB#13053
  Apps/WebClient/src/appsettings.hgdev.json
Labels: bugfix, ready

#3651 Update comms service to use Kong for AB#13057
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restCommunicationService.ts
Labels: ready

#3652 Re-check auth status when routing to new page AB#13013
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/types.ts
  Apps/WebClient/src/ClientApp/test/router.test.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/authStub.ts
Labels: bugfix, ready

#3657 Update Release Notes 1.5.8
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#3658 Update lab disclaimer for AB#12927.
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
Labels: ready, UI

#3660 Update Kong configurations for unauthenticated routes, PUTs, and DELETEs AB#13064
  Apps/WebClient/src/appsettings.hgdev.json
  Tools/Kong/.gitignore
  Tools/Kong/config-dev.yaml
  Tools/Kong/config.tmpl
  Tools/Kong/generate.sh
Labels: enhancement, ready

#3668 Remove service route prefix v1/api
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/GatewayApi/src/Controllers/CommentController.cs
  Apps/GatewayApi/src/Controllers/CommunicationController.cs
  Apps/GatewayApi/src/Controllers/ConfigurationController.cs
  Apps/GatewayApi/src/Controllers/DependentController.cs
  Apps/GatewayApi/src/Controllers/NoteController.cs
  Apps/GatewayApi/src/Controllers/ReportController.cs
  Apps/GatewayApi/src/Controllers/RobotsController.cs
  Apps/GatewayApi/src/Controllers/UserFeedbackController.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/GatewayApi/src/appsettings.Development.json
  Apps/GatewayApi/test/unit/Controllers.Test/DependentControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/RobotsControllerTests.cs
  Apps/Immunization/src/Controllers/AuthenticatedVaccineStatusController.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Controllers/PublicVaccineStatusController.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
  Apps/Medication/src/Controllers/MedicationController.cs
  Apps/Medication/src/Controllers/MedicationRequestController.cs
  Apps/Medication/src/Controllers/MedicationStatementController.cs
  Apps/Mock/src/Controllers/OdrController.cs
  Apps/Mock/src/Controllers/PhsaController.cs
  Apps/Mock/src/Controllers/SalesforceController.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/WebClient/src/ClientApp/src/services/restCommunicationService.ts
  Apps/WebClient/src/ClientApp/src/services/restConfigService.ts
  Apps/WebClient/src/ClientApp/src/services/restDependentService.ts
  Apps/WebClient/src/ClientApp/src/services/restEncounterService.ts
  Apps/WebClient/src/ClientApp/src/services/restImmunizationService.ts
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/services/restMedicationService.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientService.ts
  Apps/WebClient/src/ClientApp/src/services/restPcrTestService.ts
  Apps/WebClient/src/ClientApp/src/services/restReportService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserCommentService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserFeedback.ts
  Apps/WebClient/src/ClientApp/src/services/restUserNoteService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserProfileService.ts
  Apps/WebClient/src/ClientApp/src/services/restUserRatingService.ts
  Apps/WebClient/src/ClientApp/src/services/restVaccinationStatusService.ts
  Apps/WebClient/src/Server/Controllers/ConfigurationController.cs
Labels: bugfix, ready

#3669 FIx functional tests after service path update for AB#13123
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
  Testing/functional/tests/cypress/integration/e2e/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/covid19/federalProofOfVaccination.js
  Testing/functional/tests/cypress/integration/e2e/services/covid19Orders.js
  Testing/functional/tests/cypress/integration/e2e/services/encounter.js
  Testing/functional/tests/cypress/integration/e2e/services/immunization.js
  Testing/functional/tests/cypress/integration/e2e/services/laboratoryOrders.js
  Testing/functional/tests/cypress/integration/e2e/services/medication.js
  Testing/functional/tests/cypress/integration/e2e/services/patient.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/comment.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/communication.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/dependent.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/note.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/userFeedback.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/userProfile.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderReport.js
  Testing/functional/tests/cypress/integration/e2e/timeline/notes.js
  Testing/functional/tests/cypress/integration/mock/services/encounter.js
  Testing/functional/tests/cypress/integration/mock/services/immunization.js
  Testing/functional/tests/cypress/integration/mock/services/laboratory.js
  Testing/functional/tests/cypress/integration/mock/services/medication.js
  Testing/functional/tests/cypress/integration/mock/services/patient.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/comment.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/communication.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/dependent.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/note.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/userFeedback.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/userProfile.js
  Testing/functional/tests/cypress/integration/mock/user/profile.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTestWithTestKit.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/covid19/federalProofOfVaccination.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicCovidTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/report/reportFiltering.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
  Testing/functional/tests/cypress/integration/ui/resourceCentre/covidcard.js
  Testing/functional/tests/cypress/integration/ui/timeline/errors.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/medicationrequest.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrderReport.js
  Testing/functional/tests/cypress/integration/ui/timeline/modals/covidModal.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/user/emailValidation.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
  Testing/functional/tests/cypress/integration/ui/user/tutorial.js
  Testing/functional/tests/cypress/support/commands.js
  Tools/Kong/config-dev.yaml
  Tools/Kong/publish.sh
Labels: bugfix, ready

#3672 Fix broken links on FAQ for AB#13134.
  Apps/WebClient/src/ClientApp/src/views/FaqView.vue
Labels: bugfix, ready

#3676 Add EMPI address to user profile for AB#13093.
  Apps/Patient/src/Models/PatientModel.cs
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
Labels: enhancement, .NET, unit tests, ready, UI

#3678 Fix fragile timeline calendar test AB#13143
  Testing/functional/tests/cypress/integration/e2e/timeline/calendar.js
Labels: bugfix, ready

#3677 FAQ Edits May16.22
  Apps/WebClient/src/ClientApp/src/views/FaqView.vue
  package-lock.json
Labels: ready

#3687 Tasks/13085
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Components/BannerDialog.razor
  Apps/Admin/Client/Components/BannerDialog.razor.cs
  Apps/Admin/Client/Pages/CommunicationsPage.razor.cs
  Apps/Admin/Client/wwwroot/index.html
  Apps/Admin/Common/Admin.Common.csproj
  Apps/Admin/Common/Models/Communication.cs
  Apps/Admin/Server/Admin.Server.csproj
  Apps/Admin/Server/Converters/CommunicationConverter.cs
  Apps/Admin/Server/Services/CommunicationService.cs
  Apps/CommonData/src/Constants/CommunicationStatus.cs
  Apps/CommonData/src/Constants/CommunicationType.cs
  Apps/Database/src/Delegates/DBCommunicationDelegate.cs
  Apps/Database/src/Delegates/ICommunicationDelegate.cs
  Apps/Database/src/Models/CommunicationStatusCode.cs
  Apps/Database/src/Models/CommunicationTypeCode.cs
  Apps/Directory.Build.props
  Apps/GatewayApi/src/Controllers/CommunicationController.cs
  Apps/GatewayApi/src/Services/ICommunicationService.cs
  Apps/WebClient/src/Server/Controllers/CommunicationController.cs
  Apps/WebClient/src/Server/Services/ICommunicationService.cs
Labels: ready

#3679 Code review nit changes for AB#13142.
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
Labels: javascript, ready

#3691 Add functional tests for EMPI Address in user profile for AB#13095.
  Testing/functional/tests/cypress/fixtures/PatientService/patientCombinedAddress.json
  Testing/functional/tests/cypress/fixtures/PatientService/patientDifferentAddress.json
  Testing/functional/tests/cypress/fixtures/PatientService/patientNoAddress.json
  Testing/functional/tests/cypress/fixtures/PatientService/patientOnlyPhysicalAddress.json
  Testing/functional/tests/cypress/fixtures/PatientService/patientOnlyPostalAddress.json
  Testing/functional/tests/cypress/integration/e2e/user/profile.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: functional tests, ready

#3695 Update PDF button display for "Cancelled" test
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
Labels: ready

#3708 Fix missing download buttons for COVID-19 test PDFs AB#13186
  Apps/Laboratory/src/Models/Covid19Test.cs
Labels: bugfix, ready

#3701 Initial UI for adding and deleting tags AB#13171
  Apps/Admin/Client/Components/HgButton.razor
  Apps/Admin/Client/Components/HgButton.razor.cs
  Apps/Admin/Client/Pages/Feedback.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor.cs
  Apps/Admin/Client/Services/ITagApi.cs
  Apps/Admin/Client/Store/Tag/TagActions.cs
  Apps/Admin/Client/Store/Tag/TagReducers.cs
  Apps/Admin/Client/wwwroot/appsettings.json
  Apps/Admin/Server/Services/UserFeedbackService.cs
Labels: enhancement, ready

#3711 Update release notes for 1.5.10
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#3718 Remove ToS updated alert for AB#13182
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
Labels: ready

#3719 Resolve SonarCloud code smells AB#13214
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/services/restAuthService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
Labels: bugfix, ready

#3720 Remove mock functional tests AB#13177
  Testing/functional/tests/cypress/integration/mock/healthinsights/insights.js
  Testing/functional/tests/cypress/integration/mock/pages/communication.js
  Testing/functional/tests/cypress/integration/mock/report/report.js
  Testing/functional/tests/cypress/integration/mock/resourceCentre/resourceCentre.js
  Testing/functional/tests/cypress/integration/mock/services/encounter.js
  Testing/functional/tests/cypress/integration/mock/services/immunization.js
  Testing/functional/tests/cypress/integration/mock/services/laboratory.js
  Testing/functional/tests/cypress/integration/mock/services/medication.js
  Testing/functional/tests/cypress/integration/mock/services/patient.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/comment.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/communication.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/dependent.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/note.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/userFeedback.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/userProfile.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/webClient.js
  Testing/functional/tests/cypress/integration/mock/timeline/calendar.js
  Testing/functional/tests/cypress/integration/mock/timeline/comments.js
  Testing/functional/tests/cypress/integration/mock/timeline/encounter.js
  Testing/functional/tests/cypress/integration/mock/timeline/filter.js
  Testing/functional/tests/cypress/integration/mock/timeline/medication.js
  Testing/functional/tests/cypress/integration/mock/timeline/mobile/encounter.js
  Testing/functional/tests/cypress/integration/mock/timeline/mobile/medication.js
  Testing/functional/tests/cypress/integration/mock/timeline/modals/protectiveWordModal.js
  Testing/functional/tests/cypress/integration/mock/timeline/notes.js
  Testing/functional/tests/cypress/integration/mock/timeline/pagination.js
  Testing/functional/tests/cypress/integration/mock/user/feedback.js
  Testing/functional/tests/cypress/integration/mock/user/profile.js
  Testing/functional/tests/cypress/integration/mock/user/starRating.js
Labels: functional tests, ready

#3722 Remove unused communication email code AB#13183
  Apps/Admin/Common/Models/Communication.cs
  Apps/Admin/Server/Models/AdminEmail.cs
  Apps/Admin/Server/Services/CommunicationService.cs
  Apps/AdminWebClient/src/Server/Models/AdminEmail.cs
  Apps/AdminWebClient/src/Server/Services/CommunicationService.cs
  Apps/AdminWebClient/test/unit/Controllers.Test/CommunicationControllerTests.cs
  Apps/Common/src/Jobs/ICommunicationJob.cs
  Apps/Database/src/Delegates/DBCommunicationDelegate.cs
  Apps/Database/src/Delegates/DBCommunicationEmailDelegate.cs
  Apps/Database/src/Delegates/ICommunicationDelegate.cs
  Apps/Database/src/Delegates/ICommunicationEmailDelegate.cs
  Apps/JobScheduler/src/Jobs/CommunicationJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/appsettings.json
Labels: bugfix, ready

#3723 Fix date string comparisons in unit tests AB#13239
  Apps/Common/test/unit/Utils/ClaimsPrincipalReaderTests.cs
Labels: bugfix, unit tests, ready

#3726 Functional Test Seed Data - update terms of service id to latest for AB#13243.
  Testing/functional/tests/cypress/db/seed.sql
Labels: bugfix, functional tests, ready

#3714 Add User Feedback Fluxor and Refit for AB#12032.
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Services/IUserFeedbackApi.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackActions.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackEffects.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackReducers.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackState.cs
  Apps/Admin/Client/wwwroot/appsettings.json
  Apps/Admin/Common/Models/UserFeedbackTagView.cs
  Apps/Admin/Server/Converters/UserFeedbackConverter.cs
  Apps/Admin/Server/Converters/UserFeedbackTagConverter.cs
Labels: .NET, ready

#3729 Increase Common Data unit test coverage for AB#13217
  Apps/CommonData/src/ErrorHandling/ActionType.cs
  Apps/CommonData/src/Models/AuditableEntity.cs
  Apps/CommonData/src/Models/Email.cs
  Apps/CommonData/src/Models/IConcurrencyGuard.cs
  Apps/CommonData/src/Models/MessagingVerification.cs
  Apps/CommonData/src/Utils/DateFormatter.cs
  Apps/CommonData/src/Utils/StringManipulator.cs
  Apps/CommonData/src/ViewModels/MessagingVerificationModel.cs
  Apps/CommonData/src/ViewModels/RequestResult.cs
  Apps/CommonData/src/ViewModels/RequestResultError.cs
  Apps/CommonData/test/unit/Utils/StringManipulatorTests.cs
Labels: ready

#3730 Accept terms of service functional tests for AB#13098.
  Apps/WebClient/src/ClientApp/src/views/AcceptTermsOfService.vue
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileAcceptTos.json
  Testing/functional/tests/cypress/integration/e2e/user/acceptTermsOfService.js
  Testing/functional/tests/cypress/integration/ui/user/acceptTermsOfService.js
Labels: functional tests, ready

#3731 Funcitonal tests missing username in config for AB#13252.
  Testing/functional/tests/cypress.json
Labels: functional tests, ready

#3738 Increase Common unit test coverage for AB#13216
  Apps/Common/src/Auditing/AuditLogger.cs
  Apps/Common/src/Constants/OidType.cs
  Apps/Common/src/Swagger/AuthenticationRequirementsOperationFilter.cs
  Apps/Common/test/unit/Auditing/AuditLoggerTests.cs
  Apps/Common/test/unit/CommonTests.csproj
  Apps/Common/test/unit/Delegates/CDogsDelegateTests.cs
  Apps/Common/test/unit/Delegates/VaccineStatusDelegateTests.cs
  Apps/Common/test/unit/MockAsset.txt
  Apps/Common/test/unit/Utils/AssetReaderTests.cs
  Apps/Common/test/unit/Utils/DateOnlyJsonConverterTests.cs
  Apps/Common/test/unit/Utils/TimeOnlyJsonConverterTests.cs
Labels: ready

#3739 Increase Unit Test Coverage for GatewayApi
  Apps/CommonData/test/unit/Utils/StringManipulatorTests.cs
  Apps/GatewayApi/src/Controllers/CommentController.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/GatewayApi/src/Listeners/BannerListener.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSMSServiceTests.cs
Labels: ready

#3740 Fix flaky profile functional test for AB#13241.
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: functional tests, ready
