Repository bcgov/healthgateway, pull requests merged in 2022-04, with the labels that each got.

#3528 Change timeline card style when hovering AB#11681
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
Labels: ready, user story, UI

#3529 Laboratory Refresh and Report Download Functional Tests for AB#12764.
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratoryOrder.vue
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrdersRefresh.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryReportPdf.json
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/support/commands.js
Labels: functional tests, ready

#3530 Fix failing Laboratory Functional Tests for AB#12815.
  Apps/Laboratory/src/appsettings.Development.json
  Apps/Laboratory/src/appsettings.hgdev.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderQueued.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderReport.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrderReport.js
Labels: bugfix, functional tests, ready

#3536 Update COVID Treatment form Question
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
Labels: ready

#3537 Add new annotations for AB#12779
  Tools/BaseBuild/route.sh
Labels: ready

#3540 Update Release Notes 1.5.7
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#3542 Tidy up documentation for notification settings AB#12800
  Apps/Common/src/Services/NotificationSettingsService.cs
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
  Apps/JobScheduler/src/Tasks/SendValidatedUsersToPHSA.cs
  Apps/WebClient/src/Server/Services/DependentService.cs
Labels: ready

#3543 Fix Laboratory Test Status Results for AB#12821.
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrdersRefresh.json
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: bugfix, ready

#3545 Hide vaccination banner on landing page AB#12693
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
Labels: ready, user story

#3549 Removed vaccine card button checks for AB#12868..
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/pages/vaccineCard.js
Labels: bugfix, functional tests, ready

#3547 Moved info bubble on Laboratory result column for AB#12820.
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratoryOrder.vue
Labels: enhancement, ready, UI

#3546 Update BC Services Card login button AB#12822
  Apps/WebClient/src/ClientApp/src/assets/images/landing/006-BCServicesCardLogo.png
  Apps/WebClient/src/ClientApp/src/assets/images/registration/005_Mobile-Card.png
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/registrationInfo.vue
Labels: ready, user story

#3550 Fix flakey cypress functional tests for AB#12840.
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTestWithTestKit.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
Labels: bugfix, functional tests, ready

#3551 First Wave of Sonar Cloud Refactors for AB#12839
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/CommunicationComponent.vue
  Apps/WebClient/src/ClientApp/src/components/DatePickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/FeedbackComponent.vue
  Apps/WebClient/src/ClientApp/src/components/HtmlTextAreaComponent.vue
  Apps/WebClient/src/ClientApp/src/components/LoadingComponent.vue
  Apps/WebClient/src/ClientApp/src/components/MonthYearPickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/MultiSelectComponent.vue
  Apps/WebClient/src/ClientApp/src/components/PageErrorComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ReleaseNoteComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ResourceCentreComponent.vue
  Apps/WebClient/src/ClientApp/src/components/VaccineCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/CalendarBodyComponent.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/CalendarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/CalendarHeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/laboratory/Covid19LaboratoryTestDescriptionComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/noteEdit.vue
  Apps/WebClient/src/ClientApp/src/components/modal/verifySMS.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgCardButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgDateDropdownComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgDropdownComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgIconComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgTimeDropdownComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/pageTitleComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/statusLabelComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/calendarTimeline.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/covid19LaboratoryOrder.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/views/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/errors/idirLoggedIn.vue
  Apps/WebClient/src/ClientApp/src/views/errors/notFound.vue
  Apps/WebClient/src/ClientApp/src/views/errors/unauthorized.vue
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/home.vue
  Apps/WebClient/src/ClientApp/src/views/login.vue
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/termsOfService.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/components/error.test.ts
  Apps/WebClient/src/ClientApp/test/components/monthYearPicker.test.ts
Labels: ready

#3554 Update Dependent Page Message
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
Labels: ready

#3557 Update Landing Page for AB#12844.
  Apps/WebClient/src/ClientApp/src/assets/images/landing/landing-top.png
  Apps/WebClient/src/ClientApp/src/components/shared/HgIconComponent.vue
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderReport.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicCovidTest.js
Labels: enhancement, ready, UI

#3567 Update Verbiage for Quick Links/Home Page
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
Labels: ready

#3569 Update landing page AB#12847
  Apps/WebClient/src/ClientApp/src/assets/images/landing/000_Logo-Overlay.png
  Apps/WebClient/src/ClientApp/src/assets/images/landing/002_Devices.png
  Apps/WebClient/src/ClientApp/src/assets/images/landing/003_reduced-3.jpeg
  Apps/WebClient/src/ClientApp/src/assets/images/landing/004_reduced-living-room.jpeg
  Apps/WebClient/src/ClientApp/src/assets/images/landing/005_reduced-family.jpeg
  Apps/WebClient/src/ClientApp/src/assets/images/landing/007_background-covid-test.png
  Apps/WebClient/src/ClientApp/src/assets/images/landing/preview-laptop.png
  Apps/WebClient/src/ClientApp/src/assets/images/landing/preview-smartphone.png
  Apps/WebClient/src/ClientApp/src/assets/images/landing/preview-tablet.png
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationInfoView.vue
Labels: enhancement, ready, UI

#3570 Add functional test for device previews on landing page AB#12848
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
Labels: functional tests, ready

#3574 Update Message for Lab Result
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
Labels: ready

#3573 Update UI on landing page AB#12886
  Apps/WebClient/src/ClientApp/src/components/calendar/CalendarBodyComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/Covid19LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationRequestTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/NoteTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: enhancement, ready, UI

#3575 Hide landing page tooltips on mobile devices AB#12887
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
Labels: bugfix, ready

#3576 Clean up Admin Config and Nav
  Apps/Admin/Client/Layouts/MainLayout.razor
  Apps/Admin/Client/Layouts/MainLayout.razor.cs
  Apps/Admin/Client/Layouts/NavMenu.razor
  Apps/Admin/Client/Pages/ClaimsPage.razor
  Apps/Admin/Client/Pages/UserInfo.razor
  Apps/Admin/Client/Pages/UserInfo.razor.cs
  Apps/Admin/Client/wwwroot/appsettings.Development.json
  Apps/Admin/Client/wwwroot/appsettings.json
  Apps/Admin/Common/Models/ExternalConfiguration.cs
  Apps/Admin/Common/Models/IdentityProviderConfiguration.cs
  Apps/Admin/Common/Models/OfflineModeConfiguration.cs
  Apps/Admin/Common/Models/OpenIdConnectConfiguration.cs
  Apps/Admin/Common/Models/TimeoutsConfiguration.cs
  Apps/Admin/Common/Models/WebClientConfiguration.cs
  Apps/Admin/Server/Controllers/ConfigurationController.cs
  Apps/Admin/Server/Models/ExternalConfiguration.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/ConfigurationService.cs
  Apps/Admin/Server/Services/IConfigurationService.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.json
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Tools/BaseBuild/pruneImages.sh
Labels: ready

#3577 Fixes Lab PDF Status Mapping
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
Labels: bugfix, ready

#3579 Refactor Immunization Delegate to use ReFit for AB#12853 and AB#12857
  Apps/Immunization/src/Api/IImmunizationClient.cs
  Apps/Immunization/src/Delegates/IImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Immunization.csproj
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
Labels: enhancement, .NET, unit tests, ready

#3586 Fix trim issue on first and last name input text fields for AB#12910.
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
Labels: bugfix, ready

#3588 Switch from oidc-client to keycloak-js for authentication AB#12757
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/modal/IdleComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/authenticationData.ts
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restAuthService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/auth.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/views/LoginCallbackView.vue
  Apps/WebClient/src/ClientApp/src/views/LoginView.vue
  Apps/WebClient/src/ClientApp/src/views/LogoutCompleteView.vue
  Apps/WebClient/src/ClientApp/src/views/LogoutView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/test/store/auth.test.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/authStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/configStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/userStub.ts
  Apps/WebClient/src/Server/Models/OpenIdConnectConfiguration.cs
  Testing/functional/tests/cypress/support/commands.js
Labels: enhancement, ready

#3589 Fix laboratory order report functional test AB#12911
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderReport.js
Labels: bugfix, ready

#3593 Initialize DB with historical migrations for AB#12918
  Tools/Dev/Postgres/README.md
  Tools/Dev/Postgres/init/00_SetupDevDB.sql
  Tools/Dev/Postgres/init/01_init-to-AddAllLaboratoryOrdersCommentEntryType.sql
  Tools/Postgres/README.md
Labels: ready

#3595 Implement UI for Guardian Access Immunization for AB#12852, AB#12854, AB#12855 and AB#12856
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Startup.cs
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/clientModule.ts
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/tests/cypress/fixtures/ImmunizationService/dependentImmunization.json
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: functional tests, ready, UI

#3605 Fix functional test for "Log in" button AB#12929
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
Labels: functional tests, ready

#3607 Refactor auth store and calls to auth service AB#12925
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/authenticationData.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/auth.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/types.ts
  Apps/WebClient/src/ClientApp/src/views/LoginCallbackView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/test/router.test.ts
  Apps/WebClient/src/ClientApp/test/store/auth.test.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/authStub.ts
Labels: enhancement, ready
