Repository bcgov/healthgateway, pull requests merged in 2022-03, with the labels that each got.

#3392 Update comment for accuracy.
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentRequest.cs
Labels: ready

#3394 Merge 'dev' into 'features/12385'
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/models/covidTreatmentAssessmentRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentRequest.cs
  Apps/AdminWebClient/test/unit/AdminWebClientTests.csproj
  Apps/Common/src/Common.csproj
  Apps/Common/test/unit/CommonTests.csproj
  Apps/CommonData/test/unit/CommonDataTests.csproj
  Apps/CommonUi/src/Common.Ui.csproj
  Apps/CommonUi/test/unit/CommonUiTests.csproj
  Apps/Database/test/unit/DatabaseTests.csproj
  Apps/Directory.Build.props
  Apps/Encounter/test/unit/EncounterTests.csproj
  Apps/Immunization/test/unit/ImmunizationTests.csproj
  Apps/Laboratory/test/unit/LaboratoryTests.csproj
  Apps/Medication/test/unit/MedicationTests.csproj
  Apps/Offline/Dockerfile
  Apps/Offline/azure/build.yaml
  Apps/Offline/nginx.conf
  Apps/Offline/src/assets/BCSans-Bold.woff
  Apps/Offline/src/assets/BCSans-Bold.woff2
  Apps/Offline/src/assets/BCSans-Regular.woff
  Apps/Offline/src/assets/BCSans-Regular.woff2
  Apps/Offline/src/assets/bcid-logo-rev-en.png
  Apps/Offline/src/assets/logo.png
  Apps/Offline/src/favicon.ico
  Apps/Offline/src/index.html
  Apps/Patient/test/unit/PatientTests.csproj
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/test/unit/WebClientTests.csproj
  Testing/functional/tests/cypress/fixtures/LaboratoryService/authenticatedPcrTestError.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/publicPcrTestNoValidPhn.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/publicPcrTestValidPhn.json
  Testing/functional/tests/cypress/integration/e2e/covid19/pcrTestKit.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
  Testing/functional/tests/cypress/support/utils.js
  Tools/BaseBuild/offline.yaml
  Tools/Postgres/docker/Dockerfile
Labels: ready

#3393 Add must-revalidate to Cache-Control header for AB#12391
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
Labels: ready

#3396 Fix failing functional tests for public routes AB#12586
  Testing/functional/tests/cypress/integration/ui/pages/publicRoute.js
Labels: bugfix, functional tests, ready

#3397 Include patient info even when vaccine details are blocked AB#12587
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
Labels: bugfix, ready

#3398 Redirect unknown paths to /not-found AB#12584
  Apps/WebClient/src/ClientApp/src/router.ts
Labels: enhancement, ready

#3399 Remove Resend Emails for AB#12461
  Apps/AdminWebClient/src/ClientApp/src/components/core/MainNavbar.vue
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/models/email.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restEmailAdminService.ts
  Apps/AdminWebClient/src/ClientApp/src/views/ResendEmail.vue
  Apps/AdminWebClient/src/Server/Controllers/EmailAdminController.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/Server/Services/EmailAdminService.cs
  Apps/AdminWebClient/src/Server/Services/IEmailAdminService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
Labels: ready

#3400 Fix Proxy Disclosure for AB#12387
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/WebClient/src/Server/Startup.cs
Labels: ready

#3401 OWASP Zap Remediation for AB#12385
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Apps/WebClient/src/ClientApp/public/index.html
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/Server/Startup.cs
Labels: ready

#3403 Clean up functional test utilities AB#12562
  Testing/functional/tests/cypress/integration/e2e/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/covid19/federalProofOfVaccination.js
  Testing/functional/tests/cypress/integration/e2e/covid19/pcrTestKit.js
  Testing/functional/tests/cypress/integration/e2e/covid19/publicCovidTest.js
  Testing/functional/tests/cypress/integration/e2e/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/report/immunizationInvalidDoses.js
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/e2e/services/medication.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/e2e/timeline/notes.js
  Testing/functional/tests/cypress/integration/mock/report/report.js
  Testing/functional/tests/cypress/integration/mock/services/medication.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTestWithTestKit.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/covid19/federalProofOfVaccination.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicCovidTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/report/reportFiltering.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/support/commands.js
  Testing/functional/tests/cypress/support/functions/medication.js
  Testing/functional/tests/cypress/support/functions/pcrTestKit.js
  Testing/functional/tests/cypress/support/index.d.ts
  Testing/functional/tests/cypress/support/utils.js
Labels: bugfix, functional tests, ready

#3404 Add models, utilities, and store updates for quick links AB#12593 AB#12545
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/models/quickLink.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/utility/quickLinkUtil.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/userStub.ts
Labels: enhancement, ready

#3405 Disable Trace method calls entirely for AB#12602.
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/WebClient/src/Server/Startup.cs
Labels: bugfix, ready

#3421 Fixed missing description in swagger AB#12605
  Apps/Common/src/AspNetConfiguration/Modules/SwaggerDoc.cs
Labels: ready

#3422 Update home page with quick links and refactor EntryType AB#12546 AB#12621
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/models.ts
  Apps/WebClient/src/ClientApp/src/components/modal/addQuickLink.vue
  Apps/WebClient/src/ClientApp/src/components/modal/covidTestModal.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/constants/clientModule.ts
  Apps/WebClient/src/ClientApp/src/constants/commentEntryType.ts
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/models/covid19LaboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationRequestTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/noteTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/quickLink.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/models/userComment.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
  Apps/WebClient/src/ClientApp/src/utility/quickLinkUtil.ts
  Apps/WebClient/src/ClientApp/src/views/home.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/ClientApp/test/router.test.ts
Labels: enhancement, ready, UI

#3428 Remove Therapeutic file loading for AB#12618
  Apps/DBMaintainer/Apps/FedDrugDBApp.cs
Labels: bugfix, ready

#3427 Add functional test for adding and removing quick link AB#12552
  Apps/WebClient/src/ClientApp/src/components/shared/hgCardButton.vue
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
Labels: functional tests, ready

#3429 Add Data Set Quick Link to Home for AB#11734
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/models.ts
  Apps/WebClient/src/ClientApp/src/components/modal/addQuickLink.vue
  Apps/WebClient/src/ClientApp/src/components/modal/covidTestModal.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgCardButton.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/commentSection.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/constants/clientModule.ts
  Apps/WebClient/src/ClientApp/src/constants/commentEntryType.ts
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/models/covid19LaboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationRequestTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/noteTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/quickLink.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/models/userComment.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
  Apps/WebClient/src/ClientApp/src/utility/quickLinkUtil.ts
  Apps/WebClient/src/ClientApp/src/views/home.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/ClientApp/test/router.test.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/userStub.ts
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
Labels: ready, UI

#3436 Fix route path so its not under configuration for AB#12626
  Apps/WebClient/src/Server/Controllers/ConfigurationController.cs
Labels: bugfix, ready

#3435 Fix incorrect DateTime specification AB#11965
  Apps/Encounter/test/unit/Controllers/EncounterControllerTests.cs
Labels: bugfix, ready

#3438 Update Button Label for Dependent
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
Labels: ready

#3439 Fix SonarCloud code smells AB#12632
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Feedback.vue
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
  Apps/WebClient/src/ClientApp/src/components/monthYearPicker.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/models/covid19LaboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/immunizationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/mutations.ts
  Apps/WebClient/src/ClientApp/src/utility/fragmentStorage.ts
  Apps/WebClient/src/ClientApp/src/views/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/healthInsights.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: bugfix, ready

#3441 Fix sonarqube issue on v-bind:href AB#11747
  Apps/WebClient/src/ClientApp/src/components/laboratory/covid19LaboratoryTestDescription.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/breadcrumb.vue
  Apps/WebClient/src/ClientApp/src/views/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready

#3443 Fix odd wrapping for page title buttons AB#12685
  Apps/WebClient/src/ClientApp/src/components/shared/pageTitle.vue
Labels: bugfix, ready, UI

#3447 Update PHSA based APIs for AB#12688
  Apps/Common/src/Models/PHSA/PHSALoadState.cs
  Apps/Laboratory/src/Models/PHSA/PhsaLaboratoryOrder.cs
  Apps/Laboratory/src/Models/PHSA/PhsaLaboratorySummary.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: bugfix, ready

#3448 Upgrade Font Awesome Core and Icons to latest for AB#12664
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
Labels: ready, UI

#3451 Upgrade Admin VUE Cli Service to latest for AB#12692.
  Apps/AdminWebClient/src/ClientApp/.eslintrc.js
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/router.ts
  Apps/AdminWebClient/src/ClientApp/vue.config.js
Labels: ready, UI

#3450 Blazor System Analytics AB#12683 (#3449)
  Apps/Admin/Client/Pages/Analytics.razor
  Apps/Admin/Client/Pages/AnalyticsPage.razor
  Apps/Admin/Client/Pages/AnalyticsPage.razor.cs
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Services/IAnalyticsApi.cs
  Apps/Admin/Client/Services/ICsvExportApi.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsActions.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsBaseAction.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsEffects.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsReducers.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsState.cs
  Apps/Admin/Client/wwwroot/index.html
  Apps/Admin/Client/wwwroot/js/download.js
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
Labels: ready

#3453 Remove obsolete resend feature from Blazor admin for AB#12698
  Apps/Admin/Client/Layouts/NavMenu.razor
  Apps/Admin/Client/Pages/Emails.razor
Labels: bugfix, ready

#3454 Add Refit service for Dashboard AB#12668
  Apps/Admin/Client/Services/IAnalyticsApi.cs
  Apps/Admin/Client/Services/IConfigurationApi.cs
  Apps/Admin/Client/Services/IDashboardApi.cs
  Apps/Admin/Client/Services/ISupportApi.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationEffects.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationEffects.cs
Labels: ready

#3466 Resolve SonarCloud issues for AB#12704
  Apps/WebClient/src/ClientApp/src/components/vaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/Views/Shared/_Layout.cshtml
Labels: bugfix, ready

#3468 Fix cypress functional tests for AB#12653.
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/covid19LaboratoryOrder.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/pagination.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
Labels: functional tests, ready, UI

#3469 Cleanup Sonarcloud bugs and smells for AB#12711
  Apps/Admin/Client/Layouts/EmptyLayout.razor.css
  Apps/Admin/Client/Layouts/MainLayout.razor.css
  Apps/Admin/Client/Layouts/NavMenu.razor.css
  Apps/Admin/Client/Pages/Index.razor.cs
  Apps/Admin/Client/wwwroot/appsettings.Development.json
  Apps/Admin/Client/wwwroot/appsettings.json
  Apps/Admin/Client/wwwroot/index.html
  Apps/Admin/Client/wwwroot/js/utilities.js
  Apps/Admin/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/Admin/Server/Pages/Error.cshtml
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/ClientApp/src/views/Dashboard.vue
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/Common/src/Constants/OidType.cs
  Apps/Common/src/Delegates/AesCryptoDelegate.cs
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/src/Delegates/HmacHashDelegate.cs
  Apps/Common/src/Delegates/PHSA/RestVaccineStatusDelegate.cs
  Apps/Common/src/Delegates/VaccineProofDelegate.cs
  Apps/Common/src/Models/AesCryptoDelegateConfig.cs
  Apps/Common/src/Models/BcMailPlusConfig.cs
  Apps/Common/src/Models/BcMailPlusResponse.cs
  Apps/Common/src/Models/HmacHashDelegateConfig.cs
  Apps/Common/src/Models/PHSA/PHSAConfig.cs
  Apps/Common/test/unit/Delegates/AesCryptoDelegateTests.cs
  Apps/Common/test/unit/Delegates/HmacHashDelegateTests.cs
  Apps/CommonUi/test/unit/Dummy.Tests/DummyTest.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/WebClient/src/ClientApp/src/views/faq.vue
Labels: bugfix, ready

#3470 Add link to Job Scheduler navigation menu item for AB#12670
  Apps/Admin/Client/Layouts/MainLayout.razor.cs
  Apps/Admin/Client/Layouts/NavMenu.razor
  Apps/Admin/Client/Layouts/NavMenu.razor.cs
  Apps/Admin/Client/Pages/JobScheduler.razor
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
Labels: ready, UI

#3471 Fix prettier error for AB#12717.
  Apps/WebClient/src/ClientApp/src/utility/fragmentStorage.ts
Labels: bugfix, ready, UI

#3473 Add Consent Flag
  Apps/Admin/Server/Models/CovidSupport/CovidAssessmentRequest.cs
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/models/covidTreatmentAssessmentRequest.ts
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentRequest.cs
Labels: ready

#3474 Update Property Type on Consent Flag
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/models/covidTreatmentAssessmentRequest.ts
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentRequest.cs
Labels: ready

#3475 Update mock to use dev endpoints for AB#12642
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/Encounter/src/appsettings.hgmock.json
  Apps/Immunization/src/appsettings.hgmock.json
  Apps/Laboratory/src/appsettings.hgmock.json
  Apps/Medication/src/appsettings.hgmock.json
  Apps/Patient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgmock.json
Labels: ready

#3476 Fix Notes related functional tests for AB#12653.
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/note.js
  Testing/functional/tests/cypress/integration/e2e/timeline/notes.js
  Testing/functional/tests/cypress/integration/e2e/timeline/pagination.js
Labels: bugfix, functional tests, ready

#3478 Force keyword to upper and cleanup tuple for AB#12716
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Tools/Dev/Postgres/docker-compose.yml
Labels: ready

#3477 Blazor Dashboard UI AB#12669
  Apps/Admin/Client/Components/HgBannerFeedback.razor.cs
  Apps/Admin/Client/Components/RatingSummary.razor
  Apps/Admin/Client/Components/RatingSummary.razor.cs
  Apps/Admin/Client/Pages/Dashboard.razor
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Store/BaseRequestState.cs
  Apps/Admin/Client/Store/Dashboard/DashboardActions.cs
  Apps/Admin/Client/Store/Dashboard/DashboardEffects.cs
  Apps/Admin/Client/Store/Dashboard/DashboardRecurringUserState.cs
  Apps/Admin/Client/Store/Dashboard/DashboardReducers.cs
  Apps/Admin/Client/Store/Dashboard/DashboardState.cs
  Apps/Admin/Client/Store/Dashboard/DashboardUserState.cs
  Apps/Admin/Client/wwwroot/appsettings.Development.json
  Apps/Admin/Client/wwwroot/appsettings.json
Labels: ready, UI

#3479 Implement or update reject call in catch block for AB#12371.
  Apps/WebClient/src/ClientApp/src/services/restUserProfileService.ts
Labels: bugfix, ready

#3486 Fix flakey cypress functional tests for AB#12653.
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: functional tests, ready

#3496 Fix Laboratory Report ID property name
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Delegates/ILaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
  Apps/Laboratory/src/Models/PHSA/PhsaLaboratoryOrder.cs
  Apps/Laboratory/src/Services/ILaboratoryService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryDelegateMock.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/fixtures/Report/laboratoryUnSorted.json
Labels: ready

#3498 Add laboratory 'queued' message to timeline and reports for AB#12760.
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
Labels: enhancement, ready, UI

#3500 Add functional tests for queued laboratory orders for AB#12761.
  Testing/functional/tests/cypress.json
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrdersQueued.json
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: functional tests, ready

#3501 Queued Lab Result Merge Features branch to DEV AB#12677
  Apps/Laboratory/src/Models/LaboratoryOrderResult.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/laboratory.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
  Testing/functional/tests/cypress.json
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrdersQueued.json
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: ready

#3508 Update store to display partial results when refresh true for AB#12763.
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
Labels: ready

#3509 Add dialog for creating and editing banners AB#12665
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Components/BannerDialog.razor
  Apps/Admin/Client/Components/BannerDialog.razor.cs
  Apps/Admin/Client/Components/CommunicationsTable.razor
  Apps/Admin/Client/Components/CommunicationsTable.razor.cs
  Apps/Admin/Client/Components/HgButton.razor
  Apps/Admin/Client/Components/HgButton.razor.cs
  Apps/Admin/Client/Components/HgRichTextEditor.razor
  Apps/Admin/Client/Components/HgRichTextEditor.razor.cs
  Apps/Admin/Client/Components/HgRichTextEditor.razor.css
  Apps/Admin/Client/Components/HgTabs.razor
  Apps/Admin/Client/Components/HgTabs.razor.cs
  Apps/Admin/Client/Models/ExtendedCommunication.cs
  Apps/Admin/Client/Pages/CommunicationsPage.razor
  Apps/Admin/Client/Pages/CommunicationsPage.razor.cs
  Apps/Admin/Client/Store/Communications/CommunicationsEffects.cs
  Apps/Admin/Client/Store/Communications/CommunicationsReducers.cs
  Apps/Admin/Client/Store/Communications/CommunicationsState.cs
  Apps/Admin/Client/wwwroot/index.html
  Apps/Admin/Client/wwwroot/lib/quill/quill.bubble.css
  Apps/Admin/Client/wwwroot/lib/quill/quill.js
  Apps/Admin/Client/wwwroot/lib/quill/quill.min.js
  Apps/Admin/Client/wwwroot/lib/quill/quill.min.js.map
  Apps/Admin/Client/wwwroot/lib/quill/quill.snow.css
  Apps/CommonData/src/Utils/DateFormatter.cs
Labels: enhancement, ready

#3517 Implement communications page in Admin AB#11955
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Components/BannerDialog.razor
  Apps/Admin/Client/Components/BannerDialog.razor.cs
  Apps/Admin/Client/Components/CommunicationsTable.razor
  Apps/Admin/Client/Components/CommunicationsTable.razor.cs
  Apps/Admin/Client/Components/HgButton.razor
  Apps/Admin/Client/Components/HgButton.razor.cs
  Apps/Admin/Client/Components/HgRichTextEditor.razor
  Apps/Admin/Client/Components/HgRichTextEditor.razor.cs
  Apps/Admin/Client/Components/HgRichTextEditor.razor.css
  Apps/Admin/Client/Components/HgTabs.razor
  Apps/Admin/Client/Components/HgTabs.razor.cs
  Apps/Admin/Client/Models/ExtendedCommunication.cs
  Apps/Admin/Client/Pages/Communications.razor
  Apps/Admin/Client/Pages/CommunicationsPage.razor
  Apps/Admin/Client/Pages/CommunicationsPage.razor.cs
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Services/ICommunicationsApi.cs
  Apps/Admin/Client/Store/Communications/CommunicationsActions.cs
  Apps/Admin/Client/Store/Communications/CommunicationsEffects.cs
  Apps/Admin/Client/Store/Communications/CommunicationsReducers.cs
  Apps/Admin/Client/Store/Communications/CommunicationsState.cs
  Apps/Admin/Client/wwwroot/appsettings.json
  Apps/Admin/Client/wwwroot/index.html
  Apps/Admin/Client/wwwroot/lib/quill/quill.bubble.css
  Apps/Admin/Client/wwwroot/lib/quill/quill.js
  Apps/Admin/Client/wwwroot/lib/quill/quill.min.js
  Apps/Admin/Client/wwwroot/lib/quill/quill.min.js.map
  Apps/Admin/Client/wwwroot/lib/quill/quill.snow.css
  Apps/Admin/Common/Admin.Common.csproj
  Apps/Admin/Common/Models/Communication.cs
  Apps/Admin/Server/Controllers/CommunicationController.cs
  Apps/Admin/Server/Services/CommunicationService.cs
  Apps/Admin/Server/Services/ICommunicationService.cs
  Apps/CommonData/src/Utils/DateFormatter.cs
Labels: ready, user story

#3520 Use labPdfId as the unique identifier for lab orders AB#12785
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
Labels: bugfix, ready

#3525 Update download method for dependent reports AB#12803
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
Labels: bugfix, ready

#3523 Update 'CollectionDateTime' to nullable for AB#12802.
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
  Apps/Laboratory/src/Models/PHSA/PhsaLaboratoryOrder.cs
  Apps/WebClient/src/ClientApp/src/components/report/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratoryOrder.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
Labels: enhancement, ready

#3527 Display cached laboratory orders while loading timeline AB#12633
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
  Apps/Laboratory/src/Models/PHSA/PhsaLaboratoryOrder.cs
  Apps/Laboratory/src/appsettings.Development.json
  Apps/Laboratory/src/appsettings.hgdev.json
  Apps/WebClient/src/ClientApp/src/components/report/laboratory.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratoryOrder.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
Labels: ready, user story
