Repository bcgov/healthgateway, pull requests merged in 2022-09, with the labels that each got.

#4081 AB#13808 update communication service for mobile app communications
  Apps/Common/src/Services/CommunicationService.cs
  Apps/Common/src/Services/ICommunicationService.cs
  Apps/Common/test/unit/Services/CommunicationServiceTests.cs
  Apps/CommonData/src/Constants/CommunicationType.cs
  Apps/GatewayApi/src/Controllers/CommunicationController.cs
  Apps/GatewayApi/test/unit/Controllers.Test/CommunicationControllerTests.cs
Labels: enhancement, ready

#4082 Update UI and Store to support multiple Hdid vaccinations for AB#13822.
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/models/vaccinationRecord.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
Labels: javascript, ready, UI

#4086 Update unit tests for CommunicationService AB#13810
  Apps/Common/src/Services/CommunicationService.cs
  Apps/Common/test/unit/Services/CommunicationServiceTests.cs
Labels: unit tests, ready

#4087 Fix appearance of feedback instructions on small devices AB#13827
  Apps/WebClient/src/ClientApp/src/components/FeedbackComponent.vue
Labels: bugfix, ready

#4088 Updated admin webclient front end for client registry task handling
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/AdminWebClient/src/ClientApp/src/components/core/BannerFeedback.vue
  Apps/AdminWebClient/src/ClientApp/src/constants/feedbacktype.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/resulttype.ts
  Apps/AdminWebClient/src/ClientApp/src/models/bannerFeedback.ts
  Apps/AdminWebClient/src/ClientApp/src/models/patientData.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restSupportService.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
  Apps/AdminWebClient/src/Server/Services/SupportService.cs
Labels: enhancement, ready, UI

#4091 Add vaccine proof download functional tests for AB#13782
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Testing/functional/tests/cypress/fixtures/ImmunizationService/vaccineProofNotAvailable.json
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: functional tests, ready, UI

#4092 Client Registry Task Handling
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationEffects.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationReducers.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationState.cs
  Apps/Admin/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/ClientApp/src/components/core/BannerFeedback.vue
  Apps/AdminWebClient/src/ClientApp/src/constants/feedbacktype.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/resulttype.ts
  Apps/AdminWebClient/src/ClientApp/src/models/bannerFeedback.ts
  Apps/AdminWebClient/src/ClientApp/src/models/patientData.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restSupportService.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
  Apps/AdminWebClient/src/Server/Services/SupportService.cs
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/src/Models/PatientModel.cs
  Apps/CommonData/src/ErrorHandling/ActionType.cs
Labels: enhancement, ready

#4093 Update Dependent Page Message
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
Labels: ready

#4095 Resolves CROSSSLOT issue with AuditListener for AB#13858
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/ClinicalDocument/src/appsettings.hgdev.json
  Apps/Common/src/Auditing/RedisAuditLogger.cs
  Apps/Encounter/src/appsettings.hgdev.json
  Apps/GatewayApi/src/appsettings.hgdev.json
  Apps/Immunization/src/appsettings.hgdev.json
  Apps/JobScheduler/src/Listeners/AuditQueueListener.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/Laboratory/src/appsettings.hgdev.json
  Apps/Medication/src/appsettings.hgdev.json
  Apps/Patient/src/appsettings.hgdev.json
Labels: bugfix, ready

#4099 Change when to display table title as per close out review for AB#13862
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
Labels: bugfix, ready, UI

#4101 Removed no longer applicable test for AB#13857
  Testing/functional/tests/cypress/integration/e2e/pages/Registration.js
Labels: bugfix, functional tests, ready

#4102 update release notes for 2022.6.6
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#4089 Remove sidebar scrollbar and other sidebar/feedback fixes AB#13845
  Apps/WebClient/src/ClientApp/src/components/FeedbackComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/navbar.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/types.ts
Labels: bugfix, ready

#4104 Added functional tests to ui/support.cy.js for AB#13788
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-overlay.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-potential-duplicate.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-potential-linkage.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-review-identifier.json
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: functional tests, ready

#4112 Add unit tests for Personal Account Service for AB#13804
  Apps/Common/test/unit/Services/PersonalAccountServiceTests.cs
Labels: .NET, unit tests, ready

#4110 Update Kong tooling for clinical documents AB#13796
  Tools/Kong/generate.sh
  Tools/Kong/network-policies.yaml
Labels: ready

#4115 Create Auth Policy for Clinical Documents
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/ClinicalDocument/src/Controllers/ClinicalDocumentController.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/ApiKeyAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Policy/ClinicalDocumentPolicy.cs
  Apps/Common/src/AccessManagement/Authorization/Requirements/ApiKeyRequirement.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Common/src/Constants/FhirResource.cs
  Apps/Common/src/Swagger/AuthenticationRequirementsOperationFilter.cs
  Apps/Common/src/Swagger/ConfigureSwaggerGenOptions.cs
  Apps/Common/test/unit/AccessManagement/Authorization/ApiKeyAuthorizationHandlerTests.cs
Labels: ready

#4117 Add broadcast refit implemenation plus models for AB#13886
  Apps/Common/src/Api/ISystemBroadcastsApi.cs
  Apps/Common/src/Models/PHSA/BroadcastRequest.cs
  Apps/Common/src/Models/PHSA/BroadcastResponse.cs
  Apps/Common/src/Models/PHSA/PhsaConfigV2.cs
Labels: enhancement, .NET, ready

#4118 Add Helm chart for Clinical Documents for AB#13795
  Tools/BaseBuild/README.md
  Tools/BaseBuild/helm/clinicaldocument/.helmignore
  Tools/BaseBuild/helm/clinicaldocument/Chart.yaml
  Tools/BaseBuild/helm/clinicaldocument/dev-values.yaml
  Tools/BaseBuild/helm/clinicaldocument/mock-values.yaml
  Tools/BaseBuild/helm/clinicaldocument/prod-values.yaml
  Tools/BaseBuild/helm/clinicaldocument/templates/NOTES.txt
  Tools/BaseBuild/helm/clinicaldocument/templates/_helpers.tpl
  Tools/BaseBuild/helm/clinicaldocument/templates/deployment.yaml
  Tools/BaseBuild/helm/clinicaldocument/templates/hpa.yaml
  Tools/BaseBuild/helm/clinicaldocument/templates/pdb.yaml
  Tools/BaseBuild/helm/clinicaldocument/templates/service.yaml
  Tools/BaseBuild/helm/clinicaldocument/templates/tests/test-connection.yaml
  Tools/BaseBuild/helm/clinicaldocument/test-values.yaml
  Tools/BaseBuild/helm/clinicaldocument/values.yaml
  Tools/BaseBuild/helm/redis/.helmignore
  Tools/BaseBuild/helm/redis/Chart.yaml
  Tools/BaseBuild/helm/redis/templates/NOTES.txt
  Tools/BaseBuild/helm/redis/templates/_helpers.tpl
  Tools/BaseBuild/helm/redis/templates/configmap.yml
  Tools/BaseBuild/helm/redis/templates/secret.yaml
  Tools/BaseBuild/helm/redis/templates/service.yaml
  Tools/BaseBuild/helm/redis/templates/statefulset.yaml
  Tools/BaseBuild/helm/redis/templates/tests/test-connection.yaml
  Tools/BaseBuild/helm/redis/values.yaml
Labels: ready

#4124 Create clinical document service and refit API for AB#13792
  Apps/ClinicalDocument/src/Api/IClinicalDocumentsApi.cs
  Apps/ClinicalDocument/src/Models/ClinicalDocumentRecord.cs
  Apps/ClinicalDocument/src/Services/ClinicalDocumentService.cs
Labels: enhancement, ready

#4123 Update AccessTokenService to use sub as identifier for AB#13884
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Common/src/Services/AccessTokenService.cs
Labels: enhancement, .NET, ready

#4125 Fix dependent download report failure for AB#13908
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: bugfix, functional tests, ready

#4126 Fix unit test and refactored authenticated user method name for AB#13887
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Common/src/Services/AccessTokenService.cs
  Apps/Common/test/unit/Services/AccessTokenServiceTests.cs
Labels: .NET, unit tests, ready

#4128 Refactored CloseUserProfile to use Authtentication Delegate for AB#13909
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
Labels: .NET, unit tests, ready

#4133 Add error handling for downloading reports for AB#13757
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
Labels: functional tests, ready

#4116 Update and add tutorials AB#13063
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/AddNoteButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/AddCommentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/models/userPreference.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/user.ts
  Apps/WebClient/src/ClientApp/src/utility/preferenceUtil.ts
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/fixtures/MedicationService/medicationStatement.json
  Testing/functional/tests/cypress/integration/ui/user/tutorial.js
Labels: ready, user story, UI

#4137 Update popovers on lab result timeline cards AB#13528
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicCovidTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: ready, user story

#4139 Hide tutorials for default test user AB#13942
  Testing/functional/tests/cypress/db/seed.sql
Labels: bugfix, functional tests, ready

#4141 Update Sonar Analyzer and resolve issues + log cleanup for AB#13944
  Apps/Common/src/Models/BannerChangeEvent.cs
  Apps/Common/src/Services/CommunicationService.cs
  Apps/Directory.Build.props
  Apps/JobScheduler/src/Listeners/BannerListener.cs
Labels: bugfix, ready

#4142 Added clinical document unit tests and exception handling
  Apps/ClinicalDocument/src/Services/ClinicalDocumentService.cs
  Apps/ClinicalDocument/test/unit/Services/ClinicalDocumentServiceTests.cs
Labels: .NET, unit tests, ready

#4143 Fix Immunization Recommendations for AB#13912.
  Apps/Common/src/Models/PHSA/Recommendation/RecommendationResponse.cs
  Apps/Immunization/src/MapUtils/ImmunizationRecommendationMapUtils.cs
  Apps/Immunization/src/Models/ImmunizationRecommendation.cs
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/models/immunizationModel.ts
Labels: bugfix, .NET, javascript, unit tests, ready

#4144 Fix functional tests for Immunization Recommendations for AB#13945
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Testing/functional/tests/cypress/fixtures/ImmunizationService/dependentImmunization.json
  Testing/functional/tests/cypress/fixtures/ImmunizationService/immunization.json
  Testing/functional/tests/cypress/fixtures/Report/immunizationUnSorted.json
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: bugfix, functional tests, ready, UI

#4146 Fix immunization recommendation sorting for AB#13945
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Testing/functional/tests/cypress/fixtures/ImmunizationService/dependentImmunization.json
  Testing/functional/tests/cypress/fixtures/Report/immunizationUnSorted.json
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: bugfix, functional tests, ready, UI

#4154 Update Release Notes 2022.6.7
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#4155 Add additional error handling and functional tests for AB#13756
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/Covid19LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: enhancement, functional tests, ready

#4157 Resolve auth handler calling downstream when token swap fails
  Apps/Common/src/Utils/Phsa/AuthHeaderHandler.cs
Labels: bugfix, ready

#4160 Change invalid dose functional tests to use fixtures for AB#13956
  Testing/functional/tests/cypress.json
  Testing/functional/tests/cypress/fixtures/ImmunizationService/immunizationInvalidDoses.json
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/note.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationInvalidDoses.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunizationInvalidDoses.js
Labels: bugfix, functional tests, ready

#4161 Remove lab status colours for AB#13859, AB#13970
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
Labels: ready

#4156 Added functional tests for Clinical Document for AB#13797
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Testing/functional/tests/cypress/fixtures/ClinicalDocumentService/clinicalDocument.json
  Testing/functional/tests/cypress/fixtures/ClinicalDocumentService/clinicalDocumentPdf.json
  Testing/functional/tests/cypress/integration/e2e/services/clinicalDocument.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/comment.js
  Testing/functional/tests/cypress/integration/e2e/timeline/clinicalDocument.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/clinicalDocument.js
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/clinicalDocument.js
Labels: functional tests, ready

#4164 Update disclaimer on immunization export AB#13997
  Apps/GatewayApi/src/Assets/Templates/ImmunizationReport.docx
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
Labels: ready

#4165 Update disclaimer on dependent immunization forecasts AB#13905
  Apps/GatewayApi/src/Assets/Templates/DependentImmunizationReport.docx
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
Labels: ready, user story

#4166 Add functional test for deceased user for AB#13863
  Testing/functional/tests/cypress.json
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationInvalidDoses.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunizationInvalidDoses.js
Labels: bugfix, functional tests, ready

#4167 Fixed nav tootip for Dependents for AB#11763
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
Labels: bugfix

#4169 Update Imms Export Message
  Apps/GatewayApi/src/Assets/Templates/ImmunizationReport.docx
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
Labels: ready

#4168 Fix Database logging templates for AB#11718
  Apps/Database/src/Delegates/DBAdminTagDelegate.cs
  Apps/Database/src/Delegates/DBApplicationSettingsDelegate.cs
  Apps/Database/src/Delegates/DBCommentDelegate.cs
  Apps/Database/src/Delegates/DBCommunicationDelegate.cs
  Apps/Database/src/Delegates/DBDrugLookupDelegate.cs
  Apps/Database/src/Delegates/DBEmailDelegate.cs
  Apps/Database/src/Delegates/DBEventLogDelegate.cs
  Apps/Database/src/Delegates/DBFeedbackDelegate.cs
  Apps/Database/src/Delegates/DBFeedbackTagDelegate.cs
  Apps/Database/src/Delegates/DBLegalAgreementDelegate.cs
  Apps/Database/src/Delegates/DBMessagingVerificationDelegate.cs
  Apps/Database/src/Delegates/DBNoteDelegate.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/DBRatingDelegate.cs
  Apps/Database/src/Delegates/DBResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/DBSequenceDelegate.cs
  Apps/Database/src/Delegates/DBUserPreferenceDelegate.cs
  Apps/Database/src/Delegates/DBWriteAuditEventDelegate.cs
Labels: bugfix, ready

#4171 Fix visual bugs on dependent cards AB#14002
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
Labels: bugfix, ready

#4172 Add sorting and additional pagination per page value to dashboard for AB#13969
  Apps/Admin/Client/Pages/DashboardPage.razor
Labels: enhancement, .NET, ready, UI

#4173 Add Health Visits rolloff warning for AB#13988
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
Labels: ready

#4175 Add disclaimer to dependent immunization for AB#13974
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
Labels: enhancement, ready, UI

#4177 Add custom rows per page value for AB#14006
  Apps/Admin/Client/Pages/FeedbackPage.razor
Labels: bugfix, ready, UI

#4178 Add disclaimer to immunization time entry card for AB#13973
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
Labels: enhancement, ready, UI

#4170 Add error handling for update user preferences for AB#13726
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
Labels: enhancement, ready

#4181 Add disclaimer to timeline filter for AB #13975
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
Labels: enhancement, ready, UI

#4174 Add Health Visits rolloff warning for AB#13988 (#4173)
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/EncounterService/encountersrolloff.json
  Testing/functional/tests/cypress/integration/ui/timeline/encounter.js
Labels: ready

#4180 Update ClientApp to work with Volar and fix reported issues AB#13748
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/LoadingComponent.vue
  Apps/WebClient/src/ClientApp/src/components/MonthYearPickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/VaccineCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NoteEditComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/VerifySMSComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgIconComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/CommentSectionComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/Covid19LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntryDetailsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationRequestTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/NoteTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/views/AcceptTermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/ContactUsView.vue
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/ClientApp/src/views/FaqView.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/LoginView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicCovidTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
  Apps/WebClient/src/ClientApp/src/views/TermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/AppErrorView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/IdirLoggedInView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/NotFoundView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/UnauthorizedView.vue
  Apps/WebClient/src/ClientApp/tsconfig.json
Labels: bugfix, ready

#4190 Added functional tests for updating user preferences for AB#13892
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
Labels: functional tests, ready

#4193 Add home page card for immunization record website AB#13976
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
Labels: ready

#4196 Update Comms delete UI and add functional tests for AB#13991
  Apps/Admin/Client/Components/CommunicationsTable.razor
  Apps/Admin/Client/Components/CommunicationsTable.razor.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
Labels: ready

#4197 Add resources promoting the immunization record site AB#13616
  Apps/GatewayApi/src/Assets/Templates/ImmunizationReport.docx
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
  Testing/functional/tests/cypress/integration/e2e/user/immunizationRecordQuickLink.js
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
Labels: ready, user story

#4198 Expand pages to use all available width AB#13823
  Apps/WebClient/src/ClientApp/src/views/AcceptTermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/ContactUsView.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/ClientApp/src/views/FaqView.vue
  Apps/WebClient/src/ClientApp/src/views/LoginView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicCovidTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
  Apps/WebClient/src/ClientApp/src/views/TermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: ready

#4199 Update immunization card and title on quick link modal AB#14026
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
Labels: ready

#4200 Added functional tests for errors updating SMS and emails on user profile
  Apps/WebClient/src/ClientApp/src/components/modal/VerifySMSComponent.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
Labels: bugfix, functional tests, ready

#4201 Fix broken immunization functional tests AB#14032
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
Labels: bugfix, ready

#4202 Fix warning wrongly changed to error for AB#14035
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
Labels: ready

#4203 Fix logger warnings for Encounter and GatewayApi projects for AB#14030
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/Encounter/src/Delegates/RestMspVisitDelegate.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/GatewayApi/src/Services/CommentService.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/NoteService.cs
  Apps/GatewayApi/src/Services/ReportService.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/src/Services/UserSMSService.cs
Labels: bugfix, .NET, ready

#4205 Fixed logging warnings on various projects for AB#11718.
  Apps/Admin/Server/Services/CommunicationService.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/Common/src/AccessManagement/Administration/KeycloakUserAdminDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/BaseFhirAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceDelegateAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/UserAuthorizationHandler.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Common/src/AspNetConfiguration/Modules/Db.cs
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Apps/Common/src/AspNetConfiguration/Modules/Utility.cs
  Apps/Common/src/CacheProviders/RedisCacheProvider.cs
  Apps/Common/src/Delegates/CDogsDelegate.cs
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/src/Delegates/PHSA/RestNotificationSettingsDelegate.cs
  Apps/Common/src/Delegates/PHSA/RestVaccineStatusDelegate.cs
  Apps/Common/src/Delegates/VaccineProofDelegate.cs
  Apps/Common/src/FileDownload/FileDownloadService.cs
  Apps/Common/src/Services/EmailQueueService.cs
  Apps/Common/src/Services/LoggingMessageInspector.cs
  Apps/Common/src/Services/PatientService.cs
  Apps/DBMaintainer/Apps/BaseDrugApp.cs
  Apps/Immunization/src/Controllers/AuthenticatedVaccineStatusController.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Controllers/PublicVaccineStatusController.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/JobScheduler/src/Jobs/AdminFeedbackJob.cs
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/JobScheduler/src/Jobs/DBMigrationsJob.cs
  Apps/JobScheduler/src/Jobs/DeleteEmailJob.cs
  Apps/JobScheduler/src/Jobs/EmailJob.cs
  Apps/JobScheduler/src/Jobs/FedDrugJob.cs
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
  Apps/JobScheduler/src/Jobs/OneTimeJob.cs
  Apps/JobScheduler/src/Jobs/ProvincialDrugJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/Tasks/SendValidatedUsersToPHSA.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Medication/src/Delegates/SalesforceDelegate.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
Labels: bugfix, .NET, ready
