Repository bcgov/healthgateway, pull requests merged in 2022-01, with the labels that each got.

#3151 Removed space before period for AB#12063.
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready, UI

#3158 Change hyperlink text for AB#12071.
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready, UI

#3161 Update service endpoints to relative paths AB#12053
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/wwwroot/appsettings.json
Labels: bugfix, ready

#3162 Changed the error message for Data mismatch AB#12073
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready, UI

#3166 Fixed Failing Functional Tests AB#12097
  Testing/functional/tests/cypress/integration/e2e/covid19/publicCovidTest.js
Labels: functional tests, ready

#3165 Update Privacy Notice on Input Page AB#12096
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready, UI

#3153 Add Error Handling AB#12013
  Apps/Admin/Client/Components/HgBannerFeedback.razor
  Apps/Admin/Client/Components/HgBannerFeedback.razor.cs
  Apps/Admin/Client/Pages/ClaimsPage.razor
  Apps/Admin/Client/Pages/Support.razor
  Apps/Admin/Client/Pages/Support.razor.cs
  Apps/Admin/Client/Store/BaseLoadFailAction.cs
  Apps/Admin/Client/Store/BaseLoadSuccessAction.cs
  Apps/Admin/Client/Store/BaseState.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationActions.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationEffects.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationReducers.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationActions.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationEffects.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationReducers.cs
  Apps/Admin/Client/Store/RequestError.cs
  Apps/Admin/Client/Utils/StoreUtility.cs
Labels: ready, UI

#3164 Cache Auth token AB#12058
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/src/appsettings.json
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/Medication/src/Delegates/SalesforceDelegate.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/src/appsettings.json
  Apps/Medication/test/unit/Delegates/SalesforceDelegateTests.cs
Labels: enhancement, ready

#3167 Swagger Issue AB#12099
  Apps/Immunization/src/Controllers/AuthenticatedVaccineStatusController.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationControllerTests.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
Labels: unit tests, ready

#3172 Add server side code to create inactive users csv file for AB#12015.
  Apps/AdminWebClient/src/Server/Controllers/CsvExportController.cs
  Apps/AdminWebClient/src/Server/Mappers/AdminUserProfileViewCsvMap.cs
  Apps/AdminWebClient/src/Server/Models/AdminUserProfileView.cs
  Apps/AdminWebClient/src/Server/Services/CsvExportService.cs
  Apps/AdminWebClient/src/Server/Services/ICsvExportService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/AdminWebClient/src/appsettings.hgdev.json
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/AdminWebClient/src/appsettings.hgpoc.json
  Apps/AdminWebClient/src/appsettings.hgtest.json
  Apps/AdminWebClient/src/appsettings.json
  Apps/AdminWebClient/test/unit/Services.Test/AuthenticationServiceTests.cs
  Apps/Common/src/AccessManagement/Administration/IUserAdminDelegate.cs
  Apps/Common/src/AccessManagement/Administration/KeycloakUserAdminDelegate.cs
  Apps/Common/src/Constants/IdentityAccessRole.cs
  Apps/Common/src/ErrorHandling/ServiceType.cs
  Apps/Common/test/unit/AccessManagement/Administration/KeycloakUserAdminDelegateTests.cs
  Apps/Database/src/Delegates/DbAdminUserProfileDelegate.cs
  Apps/Database/src/Delegates/IAdminUserProfileDelegate.cs
Labels: enhancement, unit tests, ready

#3175 Remove MudHidden breakpoints from MudAppBar AB#11957
  Apps/Admin/Client/Layouts/MainLayout.razor
Labels: bugfix, ready

#3177 Add Get Inactive Users option to System Analytics in Admin for AB#12065.
  Apps/AdminWebClient/src/ClientApp/src/views/Stats.vue
Labels: enhancement, UI

#3183 Move login history under cancel/save for AB#12035
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: bugfix, ready

#3182 Remove Call Centre info from page AB12112
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
Labels: ready

#3198 Create notes templates and update backend AB#12144
  Apps/WebClient/src/Server/Assets/Templates/NotesReport.docx
  Apps/WebClient/src/Server/Assets/Templates/NotesReport.xlsx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
Labels: enhancement, unit tests, ready

#3200 Add Export Notes UI for AB#12143.
  Apps/WebClient/src/ClientApp/src/components/report/notes.vue
  Apps/WebClient/src/ClientApp/src/models/reportField.ts
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/Server/Assets/Templates/NotesReport.docx
  Apps/WebClient/src/Server/Assets/Templates/NotesReport.xlsx
Labels: unit tests, ready, UI

#3199 Fixed alignment issues on small mobile device AB#11811
  Apps/WebClient/src/ClientApp/src/views/profile.vue
Labels: ready, UI

#3201 Add UTC Local Time conversion support for AB#12159.
  Apps/AdminWebClient/src/ClientApp/src/views/Stats.vue
  Apps/AdminWebClient/src/Server/Controllers/CsvExportController.cs
  Apps/AdminWebClient/src/Server/Services/CsvExportService.cs
  Apps/AdminWebClient/src/Server/Services/ICsvExportService.cs
  Apps/AdminWebClient/src/Server/Services/IInactiveUserService.cs
  Apps/AdminWebClient/src/Server/Services/InactiveUserService.cs
  Apps/AdminWebClient/test/unit/Services.Test/InactiveUserServiceTests.cs
  Apps/Database/src/Delegates/DbAdminUserProfileDelegate.cs
  Apps/Database/src/Delegates/IAdminUserProfileDelegate.cs
Labels: bugfix, unit tests, ready

#3202 Update appearance of authenticated COVID-19 test results AB#12142
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Models/LaboratoryResult.cs
  Apps/Laboratory/src/Models/PublicCovidTestRecord.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/laboratory/laboratoryResultDescription.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratory.json
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
Labels: enhancement, ready, UI

#3203 Add Functional Tests for Notes Report AB#12145
  Apps/WebClient/src/Server/Assets/Templates/NotesReport.docx
  Testing/functional/tests/cypress/fixtures/Report/noteUnSorted.json
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: functional tests, ready

#3208 Features/12091
  Apps/WebClient/src/ClientApp/src/components/report/notes.vue
  Apps/WebClient/src/ClientApp/src/models/reportField.ts
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/Server/Assets/Templates/NotesReport.docx
  Apps/WebClient/src/Server/Assets/Templates/NotesReport.xlsx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
  Testing/functional/tests/cypress/fixtures/Report/noteUnSorted.json
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: enhancement, functional tests, unit tests, ready, UI

#3209 Update Release Notes AB#12186
  Apps/WebClient/src/ClientApp/src/views/releaseNotes.vue
Labels: ready

#3210 Update header text on notes report AB#12183
  Apps/WebClient/src/Server/Assets/Templates/NotesReport.docx
Labels: enhancement, ready

#3211 Add functional Test AB#12175
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratory.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/dependent.json
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratory.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: ready

#3212 Update appearance of authenticated COVID-19 test results AB#12142
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Models/LaboratoryResult.cs
  Apps/Laboratory/src/Models/PublicCovidTestRecord.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/laboratory/laboratoryResultDescription.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratory.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratory.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/dependent.json
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratory.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: ready, user story

#3213 Fix missing menu for note cards AB#12187
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entrycard.vue
Labels: bugfix, ready

#3214 Add notes to fixed functional tests AB#12188
  Testing/functional/tests/cypress/db/seed.sql
Labels: ready

#3217 Update laboratory data in mock project to match updated model AB#12190
  Apps/Mock/src/Assets/LaboratoryOrders.json
Labels: bugfix, ready

#3215 Fixed Failing Test due to adding new notes AB#12191
  Testing/functional/tests/cypress/integration/e2e/services/webClient/note.js
  Testing/functional/tests/cypress/integration/e2e/timeline/notes.js
  Testing/functional/tests/cypress/integration/e2e/timeline/pagination.js
Labels: functional tests, ready

#3225 Created model plus interface for delegate and service for AB#12213.
  Apps/Laboratory/src/Delegates/ILaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
  Apps/Laboratory/src/Models/LaboratoryTest.cs
  Apps/Laboratory/src/Models/PHSA/PhsaLaboratoryOrder.cs
  Apps/Laboratory/src/Models/PHSA/PhsaLaboratoryTest.cs
  Apps/Laboratory/src/Services/ILaboratoryService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: enhancement, .NET, unit tests, ready

#3227 Refactor existing laboratory references (Unit Tests) AB#12229
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Laboratory/test/unit/LaboratoryTests.csproj
  Apps/Laboratory/test/unit/Mock/HttpContextAccessorMock.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryDelegateFactoryMock.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryDelegateMock.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: unit tests, ready

#3230 Refactor existing laboratory references in front-end AB#12228
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/laboratory/covid19LaboratoryTestDescription.vue
  Apps/WebClient/src/ClientApp/src/components/modal/covidTestModal.vue
  Apps/WebClient/src/ClientApp/src/components/report/covid19.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/covid19LaboratoryOrder.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/models/covid19LaboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/userComment.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/laboratory.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
  Testing/functional/tests/cypress/integration/e2e/services/laboratory.js
Labels: enhancement, ready

#3228 Fixed Functional Test AB#12208
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/support/commands.js
Labels: functional tests, ready

#3229 Implemented controller, delegate and service for AB#12211.
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Delegates/ILaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Models/LaboratoryConfig.cs
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
  Apps/Laboratory/src/Models/LaboratorySummary.cs
  Apps/Laboratory/src/Models/PHSA/PhsaLaboratorySummary.cs
  Apps/Laboratory/src/Services/ILaboratoryService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/src/appsettings.json
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: enhancement, ready

#3231 Update models, store, and service for Laboratory front-end AB#12214
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/userComment.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/laboratory.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
Labels: ready

#3232 Fixed Failing functional Tests AB#12246
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/modals/protectiveWordModal.js
  Testing/functional/tests/cypress/integration/mock/timeline/modals/protectiveWordModal.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/support/commands.js
Labels: functional tests, ready

#3235 Fixed failing tests AB#12258
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratory.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: functional tests, ready

#3236 Add laboratory orders to timeline AB#12215
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/WebClient/src/ClientApp/src/components/calendar/body.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/entryDetails.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratoryOrder.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/filters.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/linearTimeline.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/userComment.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/appsettings.json
Labels: enhancement, ready, UI

#3238 Add new functional tests AB#12216
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/laboratoryOrder.vue
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Testing/functional/tests/cypress/fixtures/LaboratoryService/covid19Orders.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/integration/e2e/services/covid19Orders.js
  Testing/functional/tests/cypress/integration/e2e/services/laboratoryOrders.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: functional tests, ready

#3240 Add retry logic to lab order requests AB#12259
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Delegates/ILaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Models/Covid19Order.cs
  Apps/Laboratory/src/Models/Covid19OrderResult.cs
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
  Apps/Laboratory/src/Models/LaboratoryOrderResult.cs
  Apps/Laboratory/src/Services/ILaboratoryService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryDelegateMock.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
Labels: enhancement, ready

#3237 Controller, Service, and Delegate for Lab TestKit registration
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/CommonData/src/ErrorHandling/ActionType.cs
  Apps/Laboratory/src/Api/ILabTestKitClient.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
  Apps/Laboratory/src/Laboratory.csproj
  Apps/Laboratory/src/Models/PHSA/LabTestKit.cs
  Apps/Laboratory/src/Models/PHSA/PublicLabTestKit.cs
  Apps/Laboratory/src/Services/ILabTestKitService.cs
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: ready

#3242 Changed fixtures based on refresh logic AB#12276
  Testing/functional/tests/cypress/fixtures/LaboratoryService/covid19Orders.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
Labels: functional tests, ready

#3250 Fixed Failing mock tests AB#12230
  Testing/functional/tests/cypress/integration/mock/services/laboratory.js
  Testing/functional/tests/cypress/integration/mock/services/webClient/note.js
  Testing/functional/tests/cypress/integration/mock/timeline/notes.js
  Testing/functional/tests/cypress/integration/mock/timeline/pagination.js
Labels: ready

#3251 Fixed medication export issue AB#12255
  Apps/WebClient/src/Server/Assets/Templates/MedicationReport.xlsx
Labels: ready

#3247 Fixed the fixture filename AB#12277
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: ready

#3248 Update UI for TestKit Registration
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgTimeDropdown.vue
  Apps/WebClient/src/ClientApp/src/constants/pcrTestDataSource.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/pcrTestData.ts
  Apps/WebClient/src/ClientApp/src/models/registerTestKitPublicRequest.ts
  Apps/WebClient/src/ClientApp/src/models/registerTestKitRequest.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPCRTestService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/navbar.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/types.ts
  Apps/WebClient/src/ClientApp/src/utility/masks.ts
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/navbarStub.ts
Labels: ready

#3249 Add Laboratory Report AB#12266
  Apps/WebClient/src/Server/Assets/Templates/LaboratoryReport.docx
  Apps/WebClient/src/Server/Assets/Templates/LaboratoryReport.xlsx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
Labels: enhancement, unit tests, ready

#3253 Fixed failing mock functional test AB#12230
  Testing/functional/tests/cypress/integration/mock/services/webClient/note.js
Labels: ready

#3254 Add Laboratory Tests export for AB#12267.
  Apps/WebClient/src/ClientApp/src/components/report/laboratory.vue
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/Server/Assets/Templates/LaboratoryReport.docx
  Apps/WebClient/src/Server/Assets/Templates/LaboratoryReport.xlsx
Labels: enhancement, unit tests, ready, UI

#3258 Removed Admin Communications Email Tab and Functionality for AB#12261.
  Apps/AdminWebClient/src/ClientApp/src/components/core/CommunicationTable.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/modals/EmailModal.vue
Labels: enhancement, ready, UI
