Repository bcgov/healthgateway, pull requests merged in 2022-10, with the labels that each got.

#4204 Fix registration form re-appearing before redirecting AB#13904
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
Labels: bugfix, ready

#4209 Fixed missed Rider Logging Disabled Warnings for AB#14041
  Apps/Directory.Build.props
  Apps/JobScheduler/src/Listeners/BannerListener.cs
Labels: bugfix, .NET, ready

#4210 Renew Admin Blazor Token for AB#13986
  Apps/Admin/Client/Layouts/MainLayout.razor.cs
  Apps/Admin/Client/wwwroot/appsettings.json
Labels: enhancement, ready

#4211 Add model changes for admin last login for AB#13983
  Apps/Admin/Server/MapProfiles/SupportUserProfile.cs
  Apps/CommonData/src/ViewModels/SupportUser.cs
Labels: .NET, ready

#4218 Add Kong IP rate-limiting to swagger routes AB#13955
  Tools/Kong/config.tmpl
Labels: bugfix, ready

#4232 Apply code review to Admin Web Client as well for AB#14114
  Apps/AdminWebClient/src/Server/Controllers/SupportController.cs
  Apps/AdminWebClient/src/Server/Services/SupportService.cs
Labels: bugfix, .NET, ready

#4245 Fix AB#14129 to use dynamic birthdate
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
Labels: bugfix, ready

#4244 Webclient server side updates for year of birth
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Migrations/20221005233413_AddYearOfBirthToUserProfile.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/GatewayApi/src/Services/IUserProfileService.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: enhancement, unit tests, ready

#4250 Code review changes for AB#13978
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Store/SupportUser/SupportUserReducers.cs
Labels: .NET, ready

#4247 Write db delegate queries for year of birth counts
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/ICsvExportService.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/Database/src/Models/UserProfile.cs
  Apps/Database/src/Models/UserProfileHistory.cs
Labels: enhancement, .NET, ready

#4253 Add SupportService unit tests for AB#13985
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/AdminWebClient/src/Server/Controllers/SupportController.cs
  Apps/Common/src/Services/ISupportService.cs
  Apps/Common/src/Services/SupportService.cs
  Apps/Common/test/unit/CommonTests.csproj
  Apps/Common/test/unit/Services/SupportServiceTests.cs
  Apps/Common/test/unit/Utils/MapperUtil.cs
Labels: .NET, unit tests, ready

#4255 Fix phn lookup on support in Admin Web for AB#14139
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
Labels: bugfix, ready, UI

#4257 Update functional tests for Blazor admin last login support for AB#13981
  Apps/Admin/Client/Components/MessageVerificationTable.razor
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/messaging-verification.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-email.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-duplicate.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-overlay.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-potential-linkage.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-review-identifier.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-sms.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: .NET, functional tests, ready

#4256 Added year of birth button and date range picker to Analytics page
  Apps/Admin/Client/Pages/AnalyticsPage.razor
  Apps/Admin/Client/Pages/AnalyticsPage.razor.cs
  Apps/Admin/Client/Services/IAnalyticsApi.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsActions.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsEffects.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsReducers.cs
  Apps/Admin/Server/Controllers/CsvExportController.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/ICsvExportService.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Testing/functional/tests/cypress/db/seed.sql
Labels: enhancement, ready, UI

#4261 Improve timeline loading check resiliency AB#14125
  Testing/functional/tests/cypress/support/commands.js
Labels: bugfix, functional tests, ready

#4263 Update analytics functional test with year of birth download AB#14068
  Apps/Admin/Tests/Functional/cypress/integration/e2e/analytics.cy.js
Labels: functional tests, ready

#4264 Updated comment functional test for AB#14053
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/comment.js
Labels: bugfix, functional tests, ready

#4270 Adjust method for displaying loading toast on timeline AB#14152
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: bugfix, ready

#4276 Create model and auto mapper profile for AB#14166
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/Encounter/src/MapProfiles/HospitalVisitModelProfile.cs
  Apps/Encounter/src/Models/HospitalVisitModel.cs
  Apps/Encounter/src/Models/PHSA/Clinician.cs
  Apps/Encounter/src/Models/PHSA/HospitalVisit.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/src/Services/IEncounterService.cs
Labels: .NET, ready

#4278 Updated front end service and store for AB#14168
  Apps/WebClient/src/ClientApp/src/models/encounter.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restEncounterService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/encounter.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/types.ts
Labels: enhancement, javascript, ready

#4277 Update user menu button to avatar with initials AB#14036
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Testing/functional/tests/cypress/integration/ui/timeline/menu.js
Labels: enhancement, ready, user story, UI

#4279 Update UI for hospital visits AB#14172
  Apps/WebClient/src/ClientApp/src/components/report/MSPVisitsReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntryDetailsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/commentEntryType.ts
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/models/clinicalDocumentTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/hospitalVisitTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.json
Labels: bugfix, enhancement, ready

#4281 Fix failing functional test for AB#14179.
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
Labels: bugfix, functional tests, ready

#4283 Add and update unit tests for hospital visits for AB#14169
  Apps/Encounter/src/Delegates/RestHospitalVisitDelegate.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/test/unit/Controllers/EncounterControllerTests.cs
  Apps/Encounter/test/unit/Delegates/EncounterDelegateTests.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
  Apps/Encounter/test/unit/Services/EncounterServiceTests.cs
  Apps/Encounter/test/unit/Utils/MapperUtil.cs
Labels: .NET, unit tests, ready

#4284 Fixed bug in delegate and updated delegate unit tests for AB#14169.
  Apps/Encounter/src/Delegates/RestHospitalVisitDelegate.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
Labels: .NET, unit tests, ready

#4285 Create service and controller for broadcasts AB#14071
  Apps/Admin/Server/Controllers/BroadcastController.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
  Apps/Common/src/Api/ISystemBroadcastApi.cs
  Apps/Common/src/MapProfiles/BroadcastProfile.cs
  Apps/Common/src/Models/Broadcast.cs
  Apps/Common/src/Services/BroadcastService.cs
  Apps/Common/src/Services/IBroadcastService.cs
Labels: ready

#4286 Update front end service and store to handle refresh
  Apps/Encounter/src/MapProfiles/HospitalVisitModelProfile.cs
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/models/hospitalVisitResult.ts
  Apps/WebClient/src/ClientApp/src/models/hospitalVisitTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restEncounterService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/encounter.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/types.ts
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: enhancement, .NET, javascript, ready, UI

#4293 Create Fluxor store for broadcasts AB#14073
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Services/IBroadcastsApi.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsActions.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsEffects.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsReducers.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsState.cs
  Apps/Admin/Server/Controllers/BroadcastController.cs
  Apps/Common/src/MapProfiles/BroadcastProfile.cs
  Apps/Common/src/Services/BroadcastService.cs
  Apps/Common/src/Services/IBroadcastService.cs
  Apps/CommonData/src/Models/Broadcast.cs
Labels: ready

#4294 Hospital Visits Export for AB#12898
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/GatewayApi/src/Assets/Templates/HospitalVisitReport.docx
  Apps/GatewayApi/src/Assets/Templates/HospitalVisitReport.xlsx
  Apps/GatewayApi/src/GatewayApi.csproj
  Apps/GatewayApi/src/Models/ReportRequestModel.cs
  Apps/GatewayApi/test/unit/Services.Test/ReportServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/report/HospitalVisitReportComponent.vue
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
  Testing/functional/tests/cypress/fixtures/Report/hospitalVisitUnSorted.json
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: enhancement, .NET, functional tests, ready, UI

#4295 Set default values for banner effective and expiry dates AB#14076
  Apps/Admin/Client/Components/BannerDialog.razor.cs
Labels: ready

#4298 Add new mobile configuration and CSP updates for new auth for AB#14208
  Apps/WebClient/src/Server/Models/MobileConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#4299 Added functional tests for hospital visits for AB#14171
  Testing/functional/tests/cypress/integration/e2e/services/encounter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/encounter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/encounter.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
Labels: functional tests, ready

#4300 Implement Edit Notification for AB#14077
  Apps/Admin/Server/Controllers/BroadcastController.cs
  Apps/Common/src/Services/BroadcastService.cs
  Apps/Common/src/Services/IBroadcastService.cs
  Apps/Common/test/unit/Services/BroadcastServiceTests.cs
  Apps/Common/test/unit/Utils/MapperUtil.cs
Labels: enhancement, .NET, unit tests, ready

#4301 Added delete to broadcast service and controller, updated unit tests
  Apps/Admin/Server/Controllers/BroadcastController.cs
  Apps/Common/src/Services/BroadcastService.cs
  Apps/Common/src/Services/IBroadcastService.cs
  Apps/Common/test/unit/Services/BroadcastServiceTests.cs
Labels: enhancement, .NET, unit tests, ready

#4302 Update UI for broadcasts AB#14072
  Apps/Admin/Client/Components/BroadcastDialog.razor
  Apps/Admin/Client/Components/BroadcastDialog.razor.cs
  Apps/Admin/Client/Components/BroadcastsTable.razor
  Apps/Admin/Client/Components/BroadcastsTable.razor.cs
  Apps/Admin/Client/Components/CommunicationDialog.razor
  Apps/Admin/Client/Components/CommunicationDialog.razor.cs
  Apps/Admin/Client/Components/HgBannerFeedback.razor
  Apps/Admin/Client/Components/HgBannerFeedback.razor.cs
  Apps/Admin/Client/Components/HgSelect.razor
  Apps/Admin/Client/Components/HgSelect.razor.cs
  Apps/Admin/Client/Components/HgTextField.razor
  Apps/Admin/Client/Components/HgTextField.razor.cs
  Apps/Admin/Client/Models/ExtendedBroadcast.cs
  Apps/Admin/Client/Pages/CommunicationsPage.razor
  Apps/Admin/Client/Pages/CommunicationsPage.razor.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsActions.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsReducers.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsState.cs
  Apps/Admin/Client/Store/Communications/CommunicationsReducers.cs
  Apps/Admin/Client/Utils/BroadcastUtility.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
  Apps/Common/src/MapProfiles/BroadcastProfile.cs
  Apps/Common/src/Models/PHSA/BroadcastRequest.cs
  Apps/Common/src/Models/PHSA/BroadcastResponse.cs
  Apps/CommonData/src/Models/Broadcast.cs
  Apps/CommonData/src/Models/BroadcastActionType.cs
Labels: ready

#4303 Decrease coupling in Admin.Server Main() method AB#14211
  Apps/Admin/Server/Program.cs
Labels: ready

#4308 Suppress excessive class coupling warning for AB#14228
  Apps/Admin/Server/Program.cs
Labels: bugfix, .NET, ready

#4309 Fix failing functional test for AB#14230
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
Labels: bugfix, functional tests, ready

#4310 Moved UserProfile and MessagingVerification to common data for AB#14143
  Apps/Admin/Server/MapProfiles/SupportUserProfile.cs
  Apps/Admin/Server/Mappers/UserProfileCsvMap.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/UserFeedbackService.cs
  Apps/AdminWebClient/src/Server/MapProfiles/MessagingVerificationModelProfile.cs
  Apps/AdminWebClient/src/Server/MapProfiles/SupportUserProfile.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/Common/src/MapProfiles/MessagingVerificationProfile.cs
  Apps/Common/src/MapProfiles/UserProfileProfile.cs
  Apps/Common/src/Models/NotificationSettingsRequest.cs
  Apps/Common/test/unit/CommonTests.csproj
  Apps/Common/test/unit/Utils/MapperUtil.cs
  Apps/CommonData/src/Constants/LegalAgreementType.cs
  Apps/CommonData/src/Models/LegalAgreement.cs
  Apps/CommonData/src/Models/UserProfile.cs
  Apps/CommonData/src/ViewModels/UserPreferenceModel.cs
  Apps/CommonData/src/ViewModels/UserProfileModel.cs
  Apps/Database/src/Delegates/DBLegalAgreementDelegate.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/ILegalAgreementDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/Database/src/Models/LegalAgreementTypeCode.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
  Apps/Encounter/test/unit/Services/EncounterServiceTests.cs
  Apps/GatewayApi/src/GatewayApi.csproj
  Apps/GatewayApi/src/MapProfiles/TermsOfServiceProfile.cs
  Apps/GatewayApi/src/MapProfiles/UserPreferenceProfile.cs
  Apps/GatewayApi/src/MapUtils/UserProfileMapUtils.cs
  Apps/GatewayApi/src/Models/CreateUserRequest.cs
  Apps/GatewayApi/src/Services/CommentService.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/NoteService.cs
  Apps/GatewayApi/src/Services/UserFeedbackService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/CommentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/LegalAgreementDelegateMock.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileDelegateMock.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/GatewayApi/test/unit/Services.Test/NoteServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserFeedbackServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Utils/MapperUtil.cs
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/JobScheduler/src/Tasks/SendValidatedUsersToPHSA.cs
Labels: bugfix, .NET, ready

#4313 Refactor Admin.Server Main() and token swap AB#14211 AB#14227
  Apps/Admin/Server/Program.cs
  Apps/ClinicalDocument/src/Startup.cs
  Apps/Common/src/AspNetConfiguration/Modules/PhsaV2.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.csproj
Labels: ready

#4314 Add custom error message for unique constraint violation for AB#14201
  Apps/Database/src/Delegates/DBResourceDelegateDelegate.cs
Labels: bugfix, .NET, ready

#4315 Fix input fields and error message not clearing on cancel for AB#14233
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
Labels: bugfix, ready, UI
