Repository bcgov/healthgateway, pull requests merged in 2022-11, with the labels that each got.

#4316 Update mobile configuration with simple version and forceUpdate
  Apps/WebClient/src/Server/Models/MobileConfiguration.cs
  Apps/WebClient/src/appsettings.json
Labels: ready

#4321 Update Release Notes Sprint 10
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#4322 Add functional test for notifications AB#14074
  Apps/Admin/Client/Components/BroadcastDialog.razor
  Apps/Admin/Client/Components/BroadcastsTable.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
Labels: functional tests, ready

#4323 Implement UI debt changes for AB#14234
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/MultiSelectComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ResourceCentreComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/DeleteModalComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/MessageModalComponent.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
Labels: enhancement, ready, UI

#4324 Added functional test to add a communication for AB#14232
  Apps/Admin/Client/Components/CommunicationDialog.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
Labels: functional tests, ready

#4325 Remove no longer necessary tests for AB#14240.
  Testing/functional/tests/cypress/integration/ui/resourceCentre/covidcard.js
Labels: bugfix, functional tests, ready

#4329 Change health visit popover and date format for all modules for AB#14239
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
Labels: enhancement, ready, UI

#4331 Clear errors when add dependent modal is hidden AB#14243
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
Labels: bugfix, ready

#4334 Avoid exposing test credentials in functional tests AB#14287
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
Labels: bugfix, functional tests, ready

#4335 Replace KeycloakUserAdminDelegate with Refit API for AB#14281
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
  Apps/Admin/Tests/Services/CsvExportServiceTests.cs
  Apps/Common/src/AccessManagement/Administration/IUserAdminDelegate.cs
  Apps/Common/src/AccessManagement/Administration/KeycloakUserAdminDelegate.cs
  Apps/Common/src/Api/IKeycloakAdminApi.cs
  Apps/Common/test/unit/AccessManagement/Administration/KeycloakUserAdminDelegateTests.cs
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/appsettings.Development.json
  Apps/JobScheduler/src/appsettings.hgdev.json
  Apps/JobScheduler/src/appsettings.hgmock.json
  Apps/JobScheduler/src/appsettings.hgpoc.json
  Apps/JobScheduler/src/appsettings.hgtest.json
  Apps/JobScheduler/src/appsettings.json
Labels: ready

#4336 Add AutoMapper profiles for Laboratory project AB#14258
  Apps/Common/src/Models/PHSA/CovidTestResult.cs
  Apps/Laboratory/src/MapProfiles/Covid19OrderProfile.cs
  Apps/Laboratory/src/MapProfiles/Covid19TestProfile.cs
  Apps/Laboratory/src/MapProfiles/LaboratoryOrderProfile.cs
  Apps/Laboratory/src/MapProfiles/LaboratoryTestProfile.cs
  Apps/Laboratory/src/MapProfiles/PublicCovidTestRecordProfile.cs
  Apps/Laboratory/src/Models/Covid19Order.cs
  Apps/Laboratory/src/Models/Covid19Test.cs
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
  Apps/Laboratory/src/Models/LaboratoryTest.cs
  Apps/Laboratory/src/Models/PublicCovidTestRecord.cs
  Apps/Laboratory/src/Models/PublicCovidTestResponse.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/Laboratory/test/unit/Utils/MapperUtil.cs
Labels: ready

#4337 Added automapper to Encounter for AB#14257
  Apps/Encounter/src/MapProfiles/EncounterModelProfile.cs
  Apps/Encounter/src/Models/EncounterModel.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/test/unit/Utils/MapperUtil.cs
Labels: ready

#4338 Fix covid19Order.js functional test for AB#14293
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
Labels: bugfix, functional tests, ready

#4339 Add AutoMapper to Medication for AB#14259
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Medication/src/Delegates/SalesforceDelegate.cs
  Apps/Medication/src/MapProfiles/MedicationStatementHistoryProfile.cs
  Apps/Medication/src/MapProfiles/PharmacyProfile.cs
  Apps/Medication/src/MapProfiles/SpecialAuthorityRequestProfile.cs
  Apps/Medication/src/Models/MedicationStatementHistory.cs
  Apps/Medication/src/Models/Pharmacy.cs
  Apps/Medication/src/Models/Salesforce/ResponseWrapper.cs
  Apps/Medication/src/Models/Salesforce/SpecialAuthorityRequest.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/test/unit/Delegates/SalesforceDelegateTests.cs
  Apps/Medication/test/unit/Services/MedicationStatementServiceTests.cs
  Apps/Medication/test/unit/Utils/MapperUtil.cs
Labels: .NET, functional tests, unit tests, ready

#4341 Reduce size of device preview images on landing page AB#14283
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
Labels: ready, UI

#4343 Implement ProblemDetails exception handling for AB#14294
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Apps/Common/src/AspNetConfiguration/Modules/Patient.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Exceptions/ApiPatientException.cs
  Apps/Common/src/Exceptions/ApiProblemDetails.cs
  Apps/CommonData/src/ViewModels/ApiResult.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/src/Delegates/IClientRegistriesDelegate.cs
  Apps/Patient/src/Program.cs
  Apps/Patient/src/Services/IPatientService.cs
  Apps/Patient/src/Services/PatientService.cs
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
Labels: enhancement, .NET, unit tests, ready

#4358 Add automapper for Admin and AdminWebClient for AB#14288
  Apps/Admin/Server/MapProfiles/AdminUserProfileViewProfile.cs
  Apps/Admin/Server/Models/AdminUserProfileView.cs
  Apps/Admin/Server/Parsers/Immunization/VaccineDoseParser.cs
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Admin/Tests/Admin.Tests.csproj
  Apps/Admin/Tests/Services/CsvExportServiceTests.cs
  Apps/Admin/Tests/Utils/MapperUtil.cs
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/MapProfiles/VaccineDoseProfile.cs
  Apps/AdminWebClient/src/Server/Parsers/Immunization/VaccineDoseParser.cs
Labels: .NET, unit tests, ready

#4363 Fixed deserialization issue with inactive users for AB#14297
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Common/src/AccessManagement/Administration/Models/UserRepresentation.cs
Labels: bugfix, ready

#4364 Reduce Rider Warnings 1
  Apps/Admin/Client/Components/BroadcastsTable.razor.cs
  Apps/Admin/Client/Pages/Showcase/Alerts.razor
  Apps/Admin/Client/Pages/Showcase/Chips.razor
  Apps/Admin/Client/Pages/Showcase/Forms.razor
  Apps/Admin/Client/Pages/Showcase/LinksAndButtons.razor
  Apps/Admin/Client/Pages/Showcase/Pagination.razor
  Apps/Admin/Client/Pages/Showcase/Tabs.razor
  Apps/Admin/Client/Store/Analytics/AnalyticsState.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationState.cs
  Apps/Admin/Server/Models/AdminConfiguration.cs
  Apps/Admin/Server/Models/CovidSupport/CovidAssessmentRequest.cs
  Apps/Admin/Server/Pages/Error.cshtml
  Apps/Admin/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Models/AdminConfiguration.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentRequest.cs
  Apps/Medication/src/Controllers/MedicationController.cs
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Medication/src/MapProfiles/MedicationStatementHistoryProfile.cs
  Apps/Medication/src/Models/MedicationInformation.cs
  Apps/Medication/src/Models/MedicationSummary.cs
  Apps/Medication/src/Models/ODR/MedicationResult.cs
  Apps/Medication/src/Models/ODR/ProtectiveWord.cs
  Apps/Medication/src/Models/ODR/ProtectiveWordQueryResponse.cs
  Apps/Medication/src/Services/MedicationRequestService.cs
  Apps/Medication/src/Services/RestMedicationService.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/test/unit/Controllers/MedicationControllerTests.cs
  Apps/Medication/test/unit/Controllers/MedicationStatementControllerTests.cs
  Apps/Medication/test/unit/Delegates/MedicationDelegateTests.cs
  Apps/Medication/test/unit/Services/MedicationServiceTests.cs
  Apps/Medication/test/unit/Services/MedicationStatementServiceTests.cs
  Apps/WebClient/src/Server/Constants/RegistrationStatus.cs
  Apps/WebClient/src/Server/Controllers/ConfigurationController.cs
  Apps/WebClient/src/Server/Controllers/DumpHeadersController.cs
  Apps/WebClient/src/Server/Controllers/RobotsController.cs
  Apps/WebClient/src/Server/Models/ExternalConfiguration.cs
  Apps/WebClient/src/Server/Models/IdentityProviderConfiguration.cs
  Apps/WebClient/src/Server/Models/MobileAuthentication.cs
  Apps/WebClient/src/Server/Models/MobileConfiguration.cs
  Apps/WebClient/src/Server/Models/OfflineModeConfiguration.cs
  Apps/WebClient/src/Server/Models/OpenIdConnectConfiguration.cs
  Apps/WebClient/src/Server/Models/TimeoutsConfiguration.cs
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/Server/Program.cs
  Apps/WebClient/src/Server/Services/ConfigurationService.cs
  Apps/WebClient/src/Server/Services/IConfigurationService.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/test/unit/Controllers.Test/DumpHeadersControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/RobotsControllerTests.cs
  Apps/WebClient/test/unit/Services.Test/ConfigurationServiceTests.cs
Labels: ready

#4362 Added unit tests and fixed bug for client registry delegate for AB#14291
  Apps/Common/src/Constants/ErrorMessages.cs
  Apps/CommonData/src/ErrorHandling/ActionType.cs
  Apps/CommonData/src/ViewModels/ApiResult.cs
  Apps/CommonData/src/ViewModels/ApiWarning.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/src/Services/PatientService.cs
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
  Apps/Patient/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/Patient/test/unit/Services/PatientServiceTests.cs
Labels: enhancement, .NET, unit tests, ready

#4374 Fixes AuthDelegate constructor exception
  Apps/AdminWebClient/test/unit/Services.Test/AuthenticationServiceTests.cs
  Apps/AdminWebClient/test/unit/Services.Test/CovidSupportServiceTests.cs
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: bugfix, ready

#4376 Fix Rider warnings in unit tests AB#14310
  Apps/Admin/Tests/Dummy.Tests/DummyTest.cs
  Apps/Admin/Tests/Services/CsvExportServiceTests.cs
  Apps/AdminWebClient/test/unit/Services.Test/CovidSupportServiceTests.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/Common/test/unit/Delegates/CDogsDelegateTests.cs
  Apps/Common/test/unit/Delegates/RestTokenSwapDelegateTests.cs
  Apps/Common/test/unit/Delegates/VaccineProofDelegateTests.cs
  Apps/Common/test/unit/Services/AccessTokenServiceTests.cs
  Apps/Common/test/unit/Services/EmailQueueServiceTests.cs
  Apps/Common/test/unit/Services/HttpClientServiceTests.cs
  Apps/Common/test/unit/Services/PatientServiceTests.cs
  Apps/Common/test/unit/Services/PersonalAccountServiceTests.cs
  Apps/Database/test/unit/Utils/EnumUtilityTests.cs
  Apps/Encounter/test/unit/Controllers/EncounterControllerTests.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/CommentControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/CommunicationControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/DependentControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/DumpHeadersControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/NoteControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/ReportControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserFeedbackControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/GatewayApi/test/unit/Delegates.Test/CDogsDelegateTest.cs
  Apps/GatewayApi/test/unit/Services.Test/CommentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/MessagingVerificationDelegateMock.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileDelegateMock.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/GatewayApi/test/unit/Services.Test/NoteServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/ReportServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserFeedbackServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Utils/MapperUtil.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationControllerTests.cs
  Apps/Immunization/test/unit/Controllers.Test/PublicVaccineStatusControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Factories/LaboratoryDelegateFactoryTests.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/Medication/test/unit/Controllers/MedicationControllerTests.cs
  Apps/Medication/test/unit/Controllers/MedicationStatementControllerTests.cs
  Apps/Medication/test/unit/Delegates/SalesforceDelegateTests.cs
  Apps/Medication/test/unit/Services/MedicationRequestServiceTests.cs
  Apps/Medication/test/unit/Services/MedicationServiceTests.cs
  Apps/Medication/test/unit/Services/MedicationStatementServiceTests.cs
  Apps/WebClient/test/unit/Controllers/DumpHeadersControllerTests.cs
  Apps/WebClient/test/unit/Controllers/RobotsControllerTests.cs
  Apps/WebClient/test/unit/Services/ConfigurationServiceTests.cs
Labels: ready

#4377 Fix assembly detection when running unit tests with Rider EAP AB#14305
  Apps/Common/src/Auditing/AuditLogger.cs
Labels: ready

#4378 Update UI to use v2 patient endpoint
  Apps/Common/src/AspNetConfiguration/Modules/Patient.cs
  Apps/Common/src/ErrorHandling/ApiProblemDetails.cs
  Apps/CommonData/src/ErrorHandling/ApiException.cs
  Apps/CommonData/src/ViewModels/ApiResult.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/src/Services/PatientService.cs
  Apps/Patient/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/Patient/test/unit/Services/PatientServiceTests.cs
  Apps/WebClient/src/ClientApp/src/models/apiResult.ts
  Apps/WebClient/src/ClientApp/src/models/apiWarning.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
Labels: enhancement, .NET, unit tests, ready, UI

#4379 Implement V2 Patient Service API for AB#13937
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Apps/Common/src/AspNetConfiguration/Modules/Patient.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Constants/ErrorMessages.cs
  Apps/Common/src/ErrorHandling/ApiProblemDetails.cs
  Apps/CommonData/src/ErrorHandling/ActionType.cs
  Apps/CommonData/src/ErrorHandling/ApiException.cs
  Apps/CommonData/src/ViewModels/ApiResult.cs
  Apps/CommonData/src/ViewModels/ApiWarning.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/src/Delegates/IClientRegistriesDelegate.cs
  Apps/Patient/src/Program.cs
  Apps/Patient/src/Services/IPatientService.cs
  Apps/Patient/src/Services/PatientService.cs
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
  Apps/Patient/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/Patient/test/unit/Services/PatientServiceTests.cs
  Apps/WebClient/src/ClientApp/src/models/apiResult.ts
  Apps/WebClient/src/ClientApp/src/models/apiWarning.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
Labels: enhancement, .NET, unit tests, waiting, UI

#4386 Fix Rider warnings for AB#14311
  Apps/Common/src/AspNetConfiguration/Modules/Patient.cs
  Apps/DBMaintainer/Apps/BCPProvDrugDBApp.cs
  Apps/DBMaintainer/Apps/BaseDrugApp.cs
  Apps/DBMaintainer/Apps/FedDrugDBApp.cs
  Apps/DBMaintainer/Apps/IDrugApp.cs
  Apps/DBMaintainer/Mappers/ActiveIngredientMapper.cs
  Apps/DBMaintainer/Mappers/CompanyMapper.cs
  Apps/DBMaintainer/Mappers/DrugProductMapper.cs
  Apps/DBMaintainer/Mappers/FormMapper.cs
  Apps/DBMaintainer/Mappers/PackagingMapper.cs
  Apps/DBMaintainer/Mappers/PharmaCareDrugMapper.cs
  Apps/DBMaintainer/Mappers/PharmaceuticalStdMapper.cs
  Apps/DBMaintainer/Mappers/RouteMapper.cs
  Apps/DBMaintainer/Mappers/ScheduleMapper.cs
  Apps/DBMaintainer/Mappers/StatusMapper.cs
  Apps/DBMaintainer/Mappers/TherapeuticMapper.cs
  Apps/DBMaintainer/Mappers/VeterinarySpeciesMapper.cs
  Apps/DBMaintainer/Parsers/FederalDrugProductParser.cs
  Apps/DBMaintainer/Parsers/IDrugProductParser.cs
  Apps/DBMaintainer/Parsers/IPharmaCareDrugParser.cs
  Apps/DBMaintainer/Parsers/PharmaCareDrugParser.cs
  Apps/DBMaintainer/Program.cs
  Apps/JobScheduler/src/Jobs/FedDrugJob.cs
  Apps/JobScheduler/src/Jobs/ProvincialDrugJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/Utils/SchedulerHelper.cs
  Apps/Mock/src/Controllers/OdrController.cs
  Apps/Mock/src/Models/NotificationSettingRequest.cs
  Apps/Mock/src/Models/OdrRequest.cs
Labels: ready

#4366 Upgrade to .Net 7
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Layouts/MainLayout.razor
  Apps/Admin/Client/Layouts/MainLayout.razor.cs
  Apps/Admin/Client/Pages/UnauthorizedPage.razor
  Apps/Admin/Client/Pages/UnauthorizedPage.razor.cs
  Apps/Admin/Client/wwwroot/css/app.css
  Apps/Admin/Client/wwwroot/index.html
  Apps/Admin/Server/Admin.Server.csproj
  Apps/AdminWebClient/test/unit/AdminWebClientTests.csproj
  Apps/ClinicalDocument/test/unit/ClinicalDocumentTests.csproj
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Swagger/ConfigureSwaggerOptions.cs
  Apps/Common/test/unit/CommonTests.csproj
  Apps/DBMaintainer/DBMaintainer.csproj
  Apps/Database/src/Database.csproj
  Apps/Database/test/unit/DatabaseTests.csproj
  Apps/Directory.Build.props
  Apps/Encounter/test/unit/EncounterTests.csproj
  Apps/GatewayApi/src/GatewayApi.csproj
  Apps/GatewayApi/test/unit/GatewayApiTests.csproj
  Apps/Immunization/test/unit/ImmunizationTests.csproj
  Apps/JobScheduler/src/JobScheduler.csproj
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/JobScheduler/src/Utils/SchedulerHelper.cs
  Apps/Laboratory/test/unit/LaboratoryTests.csproj
  Apps/Medication/test/unit/MedicationTests.csproj
  Apps/Patient/test/unit/PatientTests.csproj
  Apps/Patient/test/unit/Services/PatientServiceTests.cs
  Apps/WebClient/src/Properties/launchSettings.json
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/WebClientTests.csproj
  Apps/global.json
  Build/hg-steps-template.yaml
  Tools/BaseImage/docker/Dockerfile
Labels: ready

#4387 Add Kong routes for PHSA AB#14274
  Tools/Kong/routes-gatewayapi.tmpl
  Tools/Kong/routes-patient.tmpl
Labels: ready

#4394 Update login redirect to work with ASP.NET Core 7.0 AB#14313
  Apps/Admin/Client/Pages/AuthenticationPage.razor.cs
Labels: ready

#4395 Disable Add Vaccines on Dashboard
  Apps/WebClient/Dockerfile
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
Labels: ready, do not merge

#4396 Fix medication and swagger bugs for AB#14312
  Apps/Common/src/Swagger/SwaggerDefaultValues.cs
  Apps/Medication/src/Models/ODR/MedicationResult.cs
  Apps/Mock/src/Assets/Medication.json
  Apps/WebClient/src/ClientApp/src/models/medicationResult.ts
  Testing/functional/tests/cypress/integration/e2e/services/medication.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/webClient.js
  Testing/functional/tests/cypress/support/functions/medication.js
Labels: bugfix, functional tests, ready

#4397 Fixes flakey unit test for AB#14318
  Apps/Common/test/unit/FileDownload/FileDownloadServiceTests.cs
Labels: ready

#4403 Fix bug in MedicationResult.cs change to dinpin and functional test failures
  Apps/Medication/src/MapProfiles/MedicationStatementHistoryProfile.cs
  Apps/Medication/src/Models/ODR/MedicationResult.cs
  Apps/Medication/test/unit/Delegates/MedicationDelegateTests.cs
  Apps/Mock/src/Assets/Medication.json
  Testing/functional/tests/cypress/integration/e2e/services/webClient/comment.js
  Testing/functional/tests/cypress/integration/e2e/user/immunizationRecordQuickLink.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: bugfix, functional tests, ready

#4404 Oust HttpClientService #4 for AB#14314
  Apps/Common/src/Common.csproj
  Apps/Common/test/unit/FileDownload/FileDownloadServiceTests.cs
  Apps/DBMaintainer/Apps/BCPProvDrugDBApp.cs
  Apps/DBMaintainer/Apps/BaseDrugApp.cs
  Apps/DBMaintainer/Apps/FedDrugDBApp.cs
  Apps/DBMaintainer/FileDownload/FileDownloadService.cs
  Apps/DBMaintainer/FileDownload/IFileDownloadService.cs
  Apps/DBMaintainer/Program.cs
  Apps/JobScheduler/src/Jobs/FedDrugJob.cs
  Apps/JobScheduler/src/Jobs/ProvincialDrugJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/Medication/src/Api/ISpecialAuthorityApi.cs
  Apps/Medication/src/Delegates/SalesforceDelegate.cs
  Apps/Medication/src/Models/Salesforce/Config.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/test/unit/Delegates/SalesforceDelegateTests.cs
Labels: ready

#4408 Oust HttpClientService in MedStatement delegate
  Apps/Common/src/Models/ODR/OdrConfig.cs
  Apps/Medication/src/Api/IOdrApi.cs
  Apps/Medication/src/Delegates/IMedStatementDelegate.cs
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
  Apps/Medication/src/Models/ODR/ProtectiveWord.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/src/appsettings.json
  Apps/Medication/test/unit/Delegates/MedicationDelegateTests.cs
Labels: ready

#4411 Remove HttpClientService from AuthDelegate for AB#14290
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
Labels: ready

#4415 Refit changes to oust IHttpClientService from RestImmunizationAdminDelegate
  Apps/AdminWebClient/src/Server/Api/IImmunizationAdminClient.cs
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
Labels: ready

#4405 Initial refit changes for Msp Visit and Laboratory for AB#14269
  Apps/Common/src/Utils/MockRefitException.cs
  Apps/Encounter/src/Api/IMspVisitApi.cs
  Apps/Encounter/src/Delegates/RestMspVisitDelegate.cs
  Apps/Encounter/src/Startup.cs
  Apps/Encounter/test/unit/Delegates/EncounterDelegateTests.cs
  Apps/Laboratory/src/Api/ILaboratoryApi.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Factories/LaboratoryDelegateFactoryTests.cs
Labels: enhancement, .NET, unit tests, draft

#4417 Fix draft communications shown for AB#14244
  Apps/Common/src/Services/CommunicationService.cs
Labels: bugfix, ready

#4418 Client Registry Delegate V2 - Change warning to throw ApiException for AB#14315
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/src/Services/PatientService.cs
  Apps/Patient/test/unit/Delegates/ClientRegistriesDelegateTests.cs
Labels: .NET, unit tests, ready

#4419 Standardize Refit API class names and signatures AB#14342
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/AdminWebClient/src/Server/Api/IImmunizationAdminApi.cs
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/test/unit/Services.Test/CovidSupportServiceTests.cs
  Apps/Common/src/Api/IKeycloakAdminApi.cs
  Apps/Common/src/Api/INotificationSettingsApi.cs
  Apps/Common/src/Delegates/PHSA/RestNotificationSettingsDelegate.cs
  Apps/Common/test/unit/Delegates/NotificationSettingsDelegateTests.cs
  Apps/Immunization/src/Api/IImmunizationApi.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Laboratory/src/Api/ILabTestKitApi.cs
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
Labels: ready

#4420 Remove IApiResponse for TokenSwap for AB#14338
  Apps/Common/src/Api/ITokenSwapApi.cs
  Apps/Common/src/Delegates/PHSA/RestTokenSwapDelegate.cs
  Apps/Common/test/unit/Delegates/RestTokenSwapDelegateTests.cs
Labels: bugfix, ready

#4422 IHospitalVisitApi - Refactor away from IApiResponse<T>
  Apps/Encounter/src/Api/IHospitalVisitApi.cs
  Apps/Encounter/src/Delegates/IHospitalVisitDelegate.cs
  Apps/Encounter/src/Delegates/RestHospitalVisitDelegate.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
  Apps/Encounter/test/unit/Services/EncounterServiceTests.cs
Labels: bugfix, ready

#4423 ISupportUserApi - refactor away from IApiResponse<T> for AB#14330.
  Apps/Admin/Client/Services/ISupportApi.cs
  Apps/Admin/Client/Store/SupportUser/SupportUserEffects.cs
  Apps/Admin/Client/Utils/StoreUtility.cs
Labels: bugfix, ready

#4424 IClinicalDocumentsApi - Refactor away from IApiResponse<T>
  Apps/ClinicalDocument/src/Api/IClinicalDocumentsApi.cs
  Apps/ClinicalDocument/src/Services/ClinicalDocumentService.cs
  Apps/ClinicalDocument/test/unit/Services/ClinicalDocumentServiceTests.cs
Labels: bugfix, ready

#4425 Update KeyCloakAdminApi and minor smell fixes for AB#14335
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Common/src/Api/IKeycloakAdminApi.cs
  Apps/Common/src/Delegates/PHSA/RestTokenSwapDelegate.cs
  Apps/Common/test/unit/Delegates/RestTokenSwapDelegateTests.cs
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
Labels: bugfix, ready

#4421 Update Broadcast API to latest Refit standards for AB#14328
  Apps/Admin/Client/Services/IBroadcastsApi.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsEffects.cs
  Apps/Common/src/Delegates/PHSA/RestTokenSwapDelegate.cs
Labels: bugfix, ready

#4428 Message verification refactor away from IApiResponse<T> for AB#14347
  Apps/Admin/Client/Services/ISupportApi.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationEffects.cs
  Apps/Admin/Client/Store/Dashboard/DashboardEffects.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationEffects.cs
  Apps/Admin/Client/Store/SupportUser/SupportUserEffects.cs
Labels: bugfix, .NET, ready

#4427 IPersonalAccountsApi - Refactor away from IApiResponse<T>
  Apps/Common/src/Api/IPersonalAccountsApi.cs
  Apps/Common/src/Services/PersonalAccountsService.cs
  Apps/Common/test/unit/Services/PersonalAccountServiceTests.cs
Labels: bugfix, ready

#4429 Refactor BroadcastApi for AB#14337
  Apps/Common/src/Api/ISystemBroadcastApi.cs
  Apps/Common/src/Services/BroadcastService.cs
  Apps/Common/test/unit/Services/BroadcastServiceTests.cs
Labels: bugfix, ready

#4426 Oust IHttpClientService from RestVaccineStatusDelegate AB#14323
  Apps/Admin/Server/Program.cs
  Apps/AdminWebClient/src/Server/Api/IImmunizationAdminApi.cs
  Apps/AdminWebClient/src/Server/Delegates/IVaccineStatusDelegate.cs
  Apps/AdminWebClient/src/Server/Delegates/RestVaccineStatusDelegate.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/Server/Startup.cs
  Apps/AdminWebClient/src/appsettings.json
  Apps/AdminWebClient/test/unit/Delegates.Test/VaccineStatusDelegateTests.cs
  Apps/AdminWebClient/test/unit/Services.Test/CovidSupportServiceTests.cs
  Apps/Common/src/Delegates/PHSA/IVaccineStatusDelegate.cs
  Apps/Common/src/Delegates/PHSA/RestVaccineStatusDelegate.cs
  Apps/Common/src/Models/PHSA/PHSAConfig.cs
  Apps/Common/src/Models/PHSA/RecordCard.cs
  Apps/Common/src/Models/PHSA/RecordCardQuery.cs
  Apps/Common/test/unit/Delegates/VaccineStatusDelegateTests.cs
  Apps/Immunization/src/Api/IImmunizationApi.cs
  Apps/Immunization/src/Api/IImmunizationPublicApi.cs
  Apps/Immunization/src/Delegates/IVaccineStatusDelegate.cs
  Apps/Immunization/src/Delegates/RestVaccineStatusDelegate.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/src/appsettings.json
  Apps/Immunization/test/unit/Delegates.Test/VaccineStatusDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
Labels: ready

#4431 Update Tag API for Refit Standards for AB#14331
  Apps/Admin/Client/Services/ITagApi.cs
  Apps/Admin/Client/Store/Tag/TagEffects.cs
Labels: bugfix, ready

#4432 IUserFeedbackApi - Refactor away from IApiResponse<T>
  Apps/Admin/Client/Services/IUserFeedbackApi.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackEffects.cs
Labels: bugfix, ready

#4433 Remove IHttpClientService AB#14270
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Apps/Common/src/Services/HttpClientService.cs
  Apps/Common/src/Services/IHttpClientService.cs
  Apps/Common/test/unit/Services/HttpClientServiceTests.cs
  Apps/DBMaintainer/Program.cs
Labels: ready

#4430 ICommunicationsApi - Refactor away from IApiResponse<T> for AB#14329
  Apps/Admin/Client/Services/ICommunicationsApi.cs
  Apps/Admin/Client/Services/ISupportApi.cs
  Apps/Admin/Client/Store/Communications/CommunicationsEffects.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationEffects.cs
  Apps/Admin/Client/Store/SupportUser/SupportUserEffects.cs
Labels: bugfix, .NET, ready

#4435 Restore expected property name for serialization AB#14350
  Apps/WebClient/src/Server/Models/TimeoutsConfiguration.cs
Labels: bugfix, ready

#4436 Fix mapping issue and cleanup minor smells for AB#14351
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Apps/CommonData/src/ViewModels/UserProfileModel.cs
  Apps/DBMaintainer/Program.cs
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
Labels: bugfix, ready

#4442 Update clinical document security policy for AB#14336
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
Labels: .NET, ready

#4443 Lab Order Test Status
  Apps/Laboratory/src/MapProfiles/LaboratoryTestProfile.cs
  Apps/Laboratory/src/Models/LaboratoryTest.cs
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrdersRefresh.json
Labels: bugfix, functional tests, ready

#4448 Removed quick link code for vaccine card and updated alerts for AB#14371
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/integration/e2e/user/immunizationRecordQuickLink.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
Labels: functional tests, ready, UI

#4447 Update Hospital Visit Disclaimers for AB#14370
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
Labels: ready, UI

#4444 IImmunizationApi - Refactor away from IApiResponse<T>
  Apps/Immunization/src/Api/IImmunizationApi.cs
  Apps/Immunization/src/Delegates/IImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestVaccineStatusDelegate.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Immunization/test/unit/Delegates.Test/VaccineStatusDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
Labels: bugfix, unit tests, ready

#4449 Remove Password grants from Public APIs
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/Models/IAuthModel.cs
  Apps/Immunization/src/Api/IImmunizationPublicApi.cs
  Apps/Immunization/src/Delegates/IVaccineStatusDelegate.cs
  Apps/Immunization/src/Delegates/RestVaccineStatusDelegate.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/src/appsettings.Development.json
  Apps/Immunization/src/appsettings.hgdev.json
  Apps/Immunization/src/appsettings.hgmock.json
  Apps/Immunization/src/appsettings.hgpoc.json
  Apps/Immunization/src/appsettings.hgtest.json
  Apps/Immunization/src/appsettings.json
  Apps/Immunization/test/unit/Delegates.Test/VaccineStatusDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
  Apps/Laboratory/src/Api/ILabTestKitApi.cs
  Apps/Laboratory/src/Api/ILaboratoryApi.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/src/appsettings.Development.json
  Apps/Laboratory/src/appsettings.hgdev.json
  Apps/Laboratory/src/appsettings.hgmock.json
  Apps/Laboratory/src/appsettings.hgpoc.json
  Apps/Laboratory/src/appsettings.hgtest.json
  Apps/Laboratory/src/appsettings.json
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Factories/LaboratoryDelegateFactoryTests.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Tools/KeyCloak/Terraform/client_hg_admin_blazor.tf
  Tools/KeyCloak/Terraform/client_hg_phsa.tf
  Tools/KeyCloak/Terraform/client_hg_public.tf
  Tools/KeyCloak/Terraform/client_scopes.tf
  Tools/KeyCloak/Terraform/variables.tf
Labels: ready

#4450 Removed disclaimer for AB#14388.
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
Labels: bugfix, ready, UI

#4454 Removing unnecessary check for adding dependent for AB#14355.
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
Labels: bugfix, functional tests, ready

#4455 Change to Clients creds in JobScheduler for AB#14387
  Apps/Immunization/src/appsettings.json
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
  Apps/JobScheduler/src/appsettings.Development.json
  Apps/JobScheduler/src/appsettings.hgdev.json
  Apps/JobScheduler/src/appsettings.hgmock.json
  Apps/JobScheduler/src/appsettings.hgpoc.json
  Apps/JobScheduler/src/appsettings.hgtest.json
  Apps/JobScheduler/src/appsettings.json
  Apps/Laboratory/src/appsettings.json
  Tools/KeyCloak/Terraform/client_hg_keycloak.tf
  Tools/KeyCloak/Terraform/client_hg_phsa.tf
  Tools/KeyCloak/Terraform/client_hg_phsa_public.tf
  Tools/KeyCloak/Terraform/client_hg_phsa_system.tf
  Tools/KeyCloak/Terraform/variables.tf
Labels: ready

#4457 Remove Password grants from Admin and cleanout oidc for AB#14403
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/AdminWebClient/src/appsettings.hgdev.json
  Apps/AdminWebClient/src/appsettings.hgmock.json
  Apps/AdminWebClient/src/appsettings.hgpoc.json
  Apps/AdminWebClient/src/appsettings.hgtest.json
  Apps/AdminWebClient/src/appsettings.json
  Apps/AdminWebClient/test/unit/Services.Test/CovidSupportServiceTests.cs
  Apps/ClinicalDocument/src/appsettings.json
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/GatewayApi/src/appsettings.Development.json
  Apps/GatewayApi/src/appsettings.hgdev.json
  Apps/GatewayApi/src/appsettings.hgmock.json
  Apps/GatewayApi/src/appsettings.hgpoc.json
  Apps/GatewayApi/src/appsettings.hgtest.json
  Apps/GatewayApi/src/appsettings.json
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/WebClient/src/appsettings.hgpoc.json
  Tools/KeyCloak/Terraform/client_hg_admin.tf
  Tools/KeyCloak/Terraform/client_hg_admin_blazor.tf
  Tools/KeyCloak/Terraform/client_hg_keycloak.tf
  Tools/KeyCloak/Terraform/client_hg_phsa_public.tf
  Tools/KeyCloak/Terraform/client_hg_phsa_system.tf
  Tools/KeyCloak/Terraform/variables.tf
  Tools/KeyCloak/dev_users.json
Labels: ready

#4464 Remove exception rethrowing AB#14434
  Apps/Common/src/AspNetConfiguration/Modules/ExceptionHandling.cs
  Apps/Common/src/Services/PersonalAccountsService.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/test/unit/Delegates/ClientRegistriesDelegateTests.cs
Labels: ready

#4462 Create front end service, store and model for Notification Centre
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/models/notification.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restNotificationService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/notification.ts
  Apps/WebClient/src/ClientApp/src/store/modules/notification/types.ts
Labels: enhancement, ready
