Repository bcgov/healthgateway, pull requests merged in 2022-07, with the labels that each got.

#3870 Increase size of timeline tags AB#13469
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: enhancement, ready, UI

#3869 Fix functional tests for timeline filtering AB#13470
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/comments.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: functional tests, ready

#3878 Remove line separating filters from results on timeline AB#13451
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: bugfix, ready

#3879 Fix functional tests for quick links AB#13472
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
Labels: bugfix, ready

#3880 Include tag functionality in functional tests for filters AB#13424
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
Labels: functional tests, ready

#3883 Added data-testids for functional tests for AB#13226
  Apps/Admin/Client/Components/BannerDialog.razor
  Apps/Admin/Client/Components/CommunicationsTable.razor
  Apps/Admin/Client/Pages/CommunicationsPage.razor
Labels: ready

#3886 Add functional tests for admin support for AB#13224
  Apps/Admin/Client/Components/HgBannerFeedback.razor
  Apps/Admin/Client/Components/HgBannerFeedback.razor.cs
  Apps/Admin/Client/Pages/Support.razor
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-email-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-email.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-sms-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-sms.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/analytics.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Testing/functional/tests/cypress/db/seed.sql
Labels: functional tests, ready

#3888 Removed data-testid from RichTextEditor due to error for AB#13226
  Apps/Admin/Client/Components/BannerDialog.razor
Labels: ready

#3890 Add data-testids to feedback review page AB#13225
  Apps/Admin/Client/Pages/FeedbackPage.razor
Labels: ready

#3891 Add functional tests for feedback review page AB#13225
  Apps/Admin/Tests/Functional/README.md
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
  Testing/functional/tests/cypress/db/seed.sql
Labels: functional tests, ready

#3892 Changing data-testids to different element for AB#13226
  Apps/Admin/Client/Pages/CommunicationsPage.razor
Labels: ready

#3903 Update error store to support too many request errors and warnings AB#13512
  Apps/WebClient/src/ClientApp/src/store/modules/error/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/errorBanner.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/types.ts
Labels: enhancement, ready

#3909 Create component to display alerts for too many requests AB#13513
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/TooManyRequestsComponent.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicCovidTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: enhancement, ready

#3913 Added { force: true } to fix flaky test when toast is blocking a button
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
Labels: bugfix, functional tests, ready

#3914 Fix margins around warning and error alerts AB#13523
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/PageErrorComponent.vue
  Apps/WebClient/src/ClientApp/src/components/TooManyRequestsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/VerifySMSComponent.vue
  Apps/WebClient/src/ClientApp/src/views/AcceptTermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/ContactUsView.vue
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/ClientApp/src/views/FaqView.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/LoginView.vue
  Apps/WebClient/src/ClientApp/src/views/LogoutCompleteView.vue
  Apps/WebClient/src/ClientApp/src/views/LogoutView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
  Apps/WebClient/src/ClientApp/src/views/TermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/ValidateEmailView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/IdirLoggedInView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/NotFoundView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/UnauthorizedView.vue
Labels: bugfix, ready

#3915 Populate initial Rider and ReSharper settings AB#13367
  .editorconfig
  Apps/HealthGateway.sln
  Apps/HealthGateway.sln.DotSettings
Labels: ready

#3919 Removed { force: true } from entryCardDetailsTitle clicks to fix test
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
Labels: bugfix, functional tests, ready

#3920 Rewrite event processing for Communication banner updates for AB#13533
  Apps/CommonData/src/ViewModels/RequestResult.cs
  Apps/Database/src/Delegates/DBCommunicationDelegate.cs
  Apps/Database/src/Delegates/ICommunicationDelegate.cs
  Apps/Database/src/Wrapper/DBResult.cs
  Apps/GatewayApi/src/Controllers/CommunicationController.cs
  Apps/GatewayApi/src/Converters/DateTimeConverter.cs
  Apps/GatewayApi/src/Listeners/BannerListener.cs
  Apps/GatewayApi/src/Services/CommunicationService.cs
  Apps/GatewayApi/src/Services/ICommunicationService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/CommunicationControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/CommunicationServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Scenario.cs
Labels: bugfix, ready

#3922 Update migrations and documentation for AB#13540
  Apps/Database/src/Migrations/20191119083157_InitialCreate.cs
  Apps/Database/src/Migrations/20191203232803_AddUpdateEmailTemplate.cs
  Apps/Database/src/Migrations/20200619221413_CommunicationDateConstraint.cs
  Apps/Database/src/Migrations/20200926222603_ModifyUniqueDateRangeConstraint.cs
  Apps/Database/src/Migrations/20201017085954_GenericCacheIndexes.cs
  Apps/Database/src/Migrations/20201118002050_AddResourceDelegate.cs
  Apps/Database/src/Migrations/20210122215516_AddCommentEntryTypeCode.cs
  Apps/Database/src/Migrations/20210316172822_FixMessagingVerification.cs
  Apps/Database/src/Migrations/20211109195934_AdminAllowOverlapMultipleStatus.cs
  Apps/Database/src/Migrations/20220419231412_EF6Upgrade.cs
  Apps/Database/src/Migrations/20220607220711_RemoveCommunicationEmail.cs
  Tools/Dev/Postgres/README.md
  Tools/Dev/Postgres/init/01_init-to-RemoveCommunicationEmail.sql
Labels: bugfix, ready

#3923 Update Rider and VS Code settings relating to documentation updates AB#13208
  Apps/HealthGateway.code-workspace
  Apps/HealthGateway.sln.DotSettings
Labels: ready

#3924 Fix feedback review table tags column collapsing too small AB#13466
  Apps/Admin/Client/Pages/FeedbackPage.razor
Labels: bugfix, ready

#3938 Add PHN mask to Admin Web Client Support search for AB#13561.
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
Labels: ready, UI

#3939 Fix Admin Web Client local development refresh issue for AB#13580.
  Apps/AdminWebClient/src/ClientApp/vue.config.js
Labels: bugfix, ready

#3941 Rewrite admin login and logout tests to avoid UI AB#13479
  Apps/Admin/Common/Models/ExternalConfiguration.cs
  Apps/Admin/Common/Models/OpenIdConnectConfiguration.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
  Apps/Admin/Tests/Functional/README.md
  Apps/Admin/Tests/Functional/cypress.config.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/analytics.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/authentication.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
  Apps/Admin/Tests/Functional/cypress/support/constants.js
  Apps/Admin/Tests/Functional/cypress/support/functions/environment.js
  Apps/Admin/Tests/Functional/cypress/support/globalStorage.js
  Apps/Admin/Tests/Functional/cypress/support/index.d.ts
  Apps/Admin/Tests/Functional/package-lock.json
  Apps/Admin/Tests/Functional/package.json
Labels: functional tests, ready

#3942 Add phn format mask to Blazor Admin Support for AB#13562.
  Apps/Admin/Client/Pages/Support.razor
  Apps/Admin/Client/Pages/Support.razor.cs
  Apps/CommonUi/src/Constants/Mask.cs
Labels: ready, UI

#3945 Clear errors and warnings when routing to new page AB#11609 AB#13537
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/types.ts
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
Labels: bugfix, enhancement, ready

#3950 Display warning alert for "too many requests" AB#13054
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/PageErrorComponent.vue
  Apps/WebClient/src/ClientApp/src/components/TooManyRequestsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/VaccineCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/VerifySMSComponent.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/errorBanner.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/views/AcceptTermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/ContactUsView.vue
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/ClientApp/src/views/FaqView.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/LoginView.vue
  Apps/WebClient/src/ClientApp/src/views/LogoutCompleteView.vue
  Apps/WebClient/src/ClientApp/src/views/LogoutView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicCovidTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
  Apps/WebClient/src/ClientApp/src/views/TermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/ValidateEmailView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/IdirLoggedInView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/NotFoundView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/UnauthorizedView.vue
Labels: ready, user story

#3940 Update dark mode and light mode themes for Admin AB#13531
  Apps/Admin/Client/Theme/DarkTheme.cs
  Apps/Admin/Client/Theme/LightTheme.cs
Labels: ready, UI

#3956 Fix Admin functional tests with new login/logout for AB#13586.
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/dependent-count-refresh.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/dependent-count.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/logged-in-count-refresh.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/logged-in-count.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/registered-count-refresh.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/registered-count.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: functional tests, ready
