Repository bcgov/healthgateway, pull requests merged in 2022-02, with the labels that each got.

#3259 Add new endpoint for COVID-19 orders AB#12293
  Apps/Laboratory/src/appsettings.hgmock.json
  Apps/Mock/src/Assets/Covid19Orders.json
  Apps/Mock/src/Assets/LaboratoryOrders.json
  Apps/Mock/src/Controllers/PhsaController.cs
  Apps/Mock/src/Mock.csproj
Labels: ready

#3262 Add inactivity dialog to Admin project AB#11869
  Apps/Admin/Client/Components/InactivityDialog.razor
  Apps/Admin/Client/Components/InactivityDialog.razor.cs
Labels: enhancement, ready

#3266 Merge Lab Results Export in DEV AB#11926
  Apps/WebClient/src/ClientApp/src/components/report/laboratory.vue
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/Server/Assets/Templates/LaboratoryReport.docx
  Apps/WebClient/src/Server/Assets/Templates/LaboratoryReport.xlsx
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/test/unit/Services.Test/ReportServiceTests.cs
  Testing/functional/tests/cypress/fixtures/Report/covid19UnSorted.json
  Testing/functional/tests/cypress/fixtures/Report/laboratoryUnSorted.json
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: ready

#3268 Set AllLaboratory configuration to false AB#12308
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
Labels: ready

#3269 Fix missing bracket in functional test AB#12309
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
Labels: bugfix, ready

#3252 Fix swagger issue for enums AB#11521
  Apps/Database/src/Constants/CommunicationType.cs
  Apps/WebClient/src/Server/Models/ReportRequestModel.cs
Labels: ready

#3270 Add session renewal in Admin project AB#12121
  Apps/Admin/Client/Components/InactivityDialog.razor
  Apps/Admin/Client/Components/InactivityDialog.razor.cs
  Apps/Admin/Client/Layouts/MainLayout.razor.cs
  Apps/Admin/Client/wwwroot/index.html
  Apps/Admin/Client/wwwroot/js/utilities.js
  Apps/CommonUi/src/Common.Ui.csproj
  Apps/CommonUi/src/Utils/IJSRuntimeExtensionMethods.cs
Labels: enhancement, ready, user story

#3271 Add refresh logic for COVID-19 orders on dependents page AB#12310
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
Labels: bugfix, ready

#3274 Update paths to certificate files for Blazor project AB#12362
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
Labels: bugfix, ready

#3275 Handle timeout error on log out for AB#12333.
  Testing/functional/tests/cypress/support/commands.js
Labels: functional tests, ready

#3276 Remove IAction where appropriate for AB#12103
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/Medication/src/Controllers/MedicationRequestController.cs
  Apps/Medication/src/Controllers/MedicationStatementController.cs
  Apps/Medication/test/unit/Controllers/MedicationStatementControllerTests.cs
  Apps/WebClient/src/Server/Controllers/CommentController.cs
  Apps/WebClient/src/Server/Controllers/CommunicationController.cs
  Apps/WebClient/src/Server/Controllers/DependentController.cs
  Apps/WebClient/src/Server/Controllers/NoteController.cs
  Apps/WebClient/src/Server/Controllers/ReportController.cs
  Apps/WebClient/src/Server/Controllers/UserFeedbackController.cs
  Apps/WebClient/src/Server/Controllers/UserProfileController.cs
  Apps/WebClient/test/unit/Controllers.Test/CommentControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/CommunicationControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/DependentControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/NoteControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/ReportControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/UserFeedbackControllerTests.cs
  Apps/WebClient/test/unit/Controllers.Test/UserProfileControllerTests.cs
Labels: bugfix, ready

#3278 Make error messages friendlier AB#12342
  Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
  Apps/WebClient/src/ClientApp/src/components/modal/authenticatedRapidTest.vue
  Apps/WebClient/src/ClientApp/src/components/modal/protectiveWord.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/note.vue
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/models/bannerError.ts
  Apps/WebClient/src/ClientApp/src/models/errorInterfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
  Apps/WebClient/src/ClientApp/src/views/covid19.vue
  Apps/WebClient/src/ClientApp/src/views/dependents.vue
  Apps/WebClient/src/ClientApp/src/views/profile.vue
  Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
  Apps/WebClient/src/ClientApp/src/views/publicVaccineCard.vue
  Apps/WebClient/src/ClientApp/src/views/registration.vue
  Apps/WebClient/src/ClientApp/src/views/reports.vue
  Apps/WebClient/src/ClientApp/src/views/timeline.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/errorBannerStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/medicationStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/userStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/vaccinationStatusStub.ts
Labels: enhancement, ready

#3280 Fix functional test for AB#12323.
  Testing/functional/tests/cypress/integration/e2e/covid19/federalProofOfVaccination.js
  Testing/functional/tests/cypress/integration/e2e/covid19/publicVaccineCard.js
Labels: bugfix, functional tests, ready

#3281 Fix functional tests on download for AB#12323
  Testing/functional/tests/cypress/integration/e2e/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/covid19/federalProofOfVaccination.js
Labels: functional tests, ready

#3284 Add backend validation for AB#12264
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
Labels: ready

#3285 Add PHN in the results when Query Type is Hdid AB#12359 AB#12360
  Apps/AdminWebClient/src/ClientApp/src/models/messageVerification.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/CommonData/src/ViewModels/MessagingVerificationModel.cs
Labels: ready

#3286 UI and UI functionality changes for AB#12304.
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/models/pcrTestData.ts
  Apps/WebClient/src/ClientApp/src/models/registerTestKitPublicRequest.ts
  Apps/WebClient/src/ClientApp/src/models/registerTestKitRequest.ts
  Apps/WebClient/src/ClientApp/src/services/restPCRTestService.ts
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
Labels: enhancement, ready, UI

#3243 Enable Lab Testkit registration
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/CommonData/src/ErrorHandling/ActionType.cs
  Apps/Laboratory/src/Api/ILabTestKitClient.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
  Apps/Laboratory/src/Laboratory.csproj
  Apps/Laboratory/src/Models/PHSA/LabTestKit.cs
  Apps/Laboratory/src/Models/PHSA/PublicLabTestKit.cs
  Apps/Laboratory/src/Services/ILabTestKitService.cs
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/src/appsettings.json
  Apps/Laboratory/test/unit/Controllers/LaboratoryControllerTests.cs
  Apps/Laboratory/test/unit/Mock/HttpContextAccessorMock.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/components/shared/hgTimeDropdown.vue
  Apps/WebClient/src/ClientApp/src/constants/pcrTestDataSource.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/pcrTestData.ts
  Apps/WebClient/src/ClientApp/src/models/registerTestKitPublicRequest.ts
  Apps/WebClient/src/ClientApp/src/models/registerTestKitRequest.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPcrTestService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/navbar.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/types.ts
  Apps/WebClient/src/ClientApp/src/utility/masks.ts
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/navbarStub.ts
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
  Tools/Dev/Postgres/README.md
  Tools/Dev/Postgres/docker-compose.yml
  Tools/Dev/Postgres/init/00_SetupDevDB.sql
Labels: ready, user story

#3287 Fix periodic failing IDIR Blocked functional test for AB#12323.
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
Labels: bugfix, functional tests, ready

#3291 Add PHN in the results when Query Type is Hdid AB#12359 AB#12360 (#3285)
  Apps/AdminWebClient/src/ClientApp/src/models/messageVerification.ts
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
  Apps/AdminWebClient/src/Server/Services/DashboardService.cs
  Apps/CommonData/src/ViewModels/MessagingVerificationModel.cs
Labels: ready

#3292 Remove code for rapid COVID-19 test submissions AB#12361
  Apps/Common/src/Models/PHSA/RapidTestResponse.cs
  Apps/Common/src/Models/PHSA/RapidTestResult.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Delegates/ILaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Models/AuthenticatedRapidTestRequest.cs
  Apps/Laboratory/src/Models/AuthenticatedRapidTestResponse.cs
  Apps/Laboratory/src/Models/LaboratoryConfig.cs
  Apps/Laboratory/src/Models/RapidTestRecord.cs
  Apps/Laboratory/src/Parsers/PhsaModelParser.cs
  Apps/Laboratory/src/Services/ILaboratoryService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/src/appsettings.json
  Apps/WebClient/src/ClientApp/src/assets/images/gov/cdc-logo.png
  Apps/WebClient/src/ClientApp/src/components/modal/authenticatedRapidTest.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/views/home.vue
  Apps/WebClient/src/appsettings.json
Labels: ready, user story

#3293 Fix enabling and disabling of pcr test route for AB#12382.
  Apps/WebClient/src/ClientApp/src/router.ts
Labels: bugfix, ready, UI

#3294 Fix loading spinner disappearing prematurely AB#12379
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: bugfix, ready

#3295 Button name change for AB#12381.
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: bugfix, ready, UI

#3297 Reset validation on PCR test form when cleared AB#12376
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: bugfix, ready

#3296 Handle component error when module is disabled AB#12393
  Apps/WebClient/src/ClientApp/src/services/restLaboratoryService.ts
  Apps/WebClient/src/ClientApp/src/services/restVaccinationStatusService.ts
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
Labels: ready

#3298 Format the source displayed in custom banner errors AB#12394
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
Labels: bugfix, ready

#3299 Scroll to top of page when routing AB#11883
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
Labels: bugfix, ready

#3288 Add azure agent builds for AB#12374
  Apps/Admin/azure/build.yaml
  Apps/Admin/azure/prbuild.yaml
  Apps/AdminWebClient/azure/build.yaml
  Apps/AdminWebClient/azure/prbuild.yaml
  Apps/Common/azure/build.yaml
  Apps/Common/azure/prbuild.yaml
  Apps/CommonData/azure/build.yaml
  Apps/CommonData/azure/prbuild.yaml
  Apps/CommonUi/azure/build.yaml
  Apps/CommonUi/azure/prbuild.yaml
  Apps/Database/azure/build.yaml
  Apps/Database/azure/prbuild.yaml
  Apps/Encounter/azure/build.yaml
  Apps/Encounter/azure/prbuild.yaml
  Apps/Immunization/azure/build.yaml
  Apps/Immunization/azure/prbuild.yml
  Apps/JobScheduler/azure/build.yaml
  Apps/JobScheduler/azure/prbuild.yaml
  Apps/Laboratory/azure/build.yaml
  Apps/Laboratory/azure/prbuild.yaml
  Apps/Medication/azure/build.yaml
  Apps/Medication/azure/prbuild.yaml
  Apps/Mock/azure/build.yaml
  Apps/Mock/azure/prbuild.yaml
  Apps/Patient/azure/build.yaml
  Apps/Patient/azure/prbuild.yaml
  Apps/WebClient/azure/build.yaml
  Apps/WebClient/azure/prbuild.yaml
  Build/hg-steps-template.yaml
  Build/hg.yaml
Labels: ready, user story

#3301 Hide COVID-19 button on home page if module is disabled AB#12403
  Apps/WebClient/src/ClientApp/src/views/home.vue
  Apps/WebClient/src/ClientApp/src/views/login.vue
  Apps/WebClient/src/ClientApp/test/login.test.ts
Labels: bugfix, ready

#3303 Fix flaky notes functional test for AB#12323.
  Testing/functional/tests/cypress/integration/e2e/timeline/notes.js
  Testing/functional/tests/cypress/support/commands.js
Labels: bugfix, functional tests, ready

#3309 Remove unnecessary checks from Federal Card functional tests AB#12442
  Testing/functional/tests/cypress/integration/ui/pages/home.js
Labels: bugfix, ready

#3310 Migrate BaseImage build to Azure cloud for AB#12444
  Tools/BaseImage/azure/build.yaml
Labels: enhancement, ready

#3314 Create docker images and import into OpenShift for ab#12445
  Apps/Admin/Dockerfile
  Apps/AdminWebClient/Dockerfile
  Apps/Encounter/Dockerfile
  Apps/Immunization/Dockerfile
  Apps/JobScheduler/Dockerfile
  Apps/Laboratory/Dockerfile
  Apps/Medication/Dockerfile
  Apps/Mock/Dockerfile
  Apps/Patient/Dockerfile
  Apps/WebClient/Dockerfile
  Build/hg-steps-template.yaml
  Build/hg.yaml
Labels: enhancement, ready

#3315 UI Changes for assessment table history AB#12436
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: ready

#3316 Create backend interface and models for AB#12440.
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/AdminWebClient/src/Server/Constants/CovidTherapyAssessmentOption.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidTherapyAssessmentDetails.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidTherapyAssessmentRequest.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidTherapyAssessmentResponse.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/PreviousAssessmentDetails.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/src/Server/Services/ICovidSupportService.cs
Labels: enhancement, ready

#3317 Add models and service AB#12448
  Apps/AdminWebClient/src/ClientApp/src/models/covidTherapyAssessmentDetails.ts
  Apps/AdminWebClient/src/ClientApp/src/models/previousAssessmentDetailsList.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restCovidSupportService.ts
Labels: ready

#3319 Add model and service in front end (Form) AB#12435
  Apps/AdminWebClient/src/ClientApp/src/constants/covidTherapyAssessmentOption.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidTherapyAssessmentRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restCovidSupportService.ts
Labels: ready

#3323 UI Assessment Form AB#12437
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/Card.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/OptionDetails.vue
  Apps/AdminWebClient/src/ClientApp/src/constants/CovidTreatmentAssessmentOption.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/covidTherapyAssessmentOption.ts
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/models/CovidTreatmentAssessmentDetails.ts
  Apps/AdminWebClient/src/ClientApp/src/models/CovidTreatmentAssessmentRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidTherapyAssessmentRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/models/previousAssessmentDetailsList.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restCovidSupportService.ts
  Apps/AdminWebClient/src/ClientApp/src/utility/masks.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: ready

#3324 Add unit tests for AB#12469
  Apps/AdminWebClient/src/Server/Api/IImmunizationAdminClient.cs
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentDetailsRequest.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/test/unit/Services.Test/CovidSupportServiceTests.cs
Labels: ready

#3325 Add AddressComponent for COVID-19 treatment assessment AB#12434
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/components/core/Address.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: enhancement, ready, UI

#3332 Fix masks and other issues on the COVID-19 treatment assessment AB#12467
  Apps/AdminWebClient/src/ClientApp/src/components/core/Address.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/utility/masks.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: bugfix, ready

#3333 Fix API post path for AB#12472
  Apps/AdminWebClient/src/Server/Api/IImmunizationAdminClient.cs
Labels: bugfix, ready

#3334 Wire up data for COVID-19 assessment history and form AB#12453 and AB#12439
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/Card.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/OptionDetails.vue
  Apps/AdminWebClient/src/ClientApp/src/constants/covidTreatmentAssessmentOption.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidTreatmentAssessmentDetails.ts
  Apps/AdminWebClient/src/ClientApp/src/models/covidTreatmentAssessmentRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/models/previousAssessmentDetailsList.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restCovidSupportService.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentDetailsResponse.cs
Labels: enhancement, ready

#3335 Update time taken dropdown for AB#12457
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: ready

#3336 Remove Zip Code from postal label
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: ready

#3337 UI Enhancement AB#12468
  Apps/AdminWebClient/src/ClientApp/src/components/core/Address.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/OptionDetails.vue
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: ready

#3342 Additional UI and Backend Fixes AB#12481
  Apps/AdminWebClient/src/ClientApp/src/components/core/Address.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/OptionDetails.vue
  Apps/AdminWebClient/src/ClientApp/src/models/covidTreatmentAssessmentRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentRequest.cs
Labels: ready

#3343 Enable warning on previously submitted test kit for AB#12451
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/WebClient/src/ClientApp/src/constants/actionType.ts
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: enhancement, ready, UI

#3345 Add config setting to toggle COVID-19 treatment assessment AB#12471
  Apps/AdminWebClient/src/ClientApp/src/components/core/BannerFeedback.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/constants/feature.ts
  Apps/AdminWebClient/src/ClientApp/src/constants/resulttype.ts
  Apps/AdminWebClient/src/ClientApp/src/models/externalConfiguration.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/config/getters.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/AdminWebClient/src/Server/Models/AdminConfiguration.cs
  Apps/AdminWebClient/src/appsettings.Development.json
  Apps/AdminWebClient/src/appsettings.json
Labels: enhancement, ready

#3344 Change link from home to logout for AB#12400
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: enhancement, ready

#3346 Use plain spinner on PCR test kit page AB#12395
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: enhancement, ready

#3351 Fix address validation and loading issue on COVID-19 card page in Admin AB#12488 AB#12495
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/AdminWebClient/src/ClientApp/src/components/core/Address.vue
  Apps/AdminWebClient/src/ClientApp/src/components/core/modals/BannerModal.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/main.ts
  Apps/AdminWebClient/src/ClientApp/src/store/modules/config/getters.ts
  Apps/AdminWebClient/src/ClientApp/src/utility/masks.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: bugfix, ready

#3357 Sort assessment history descending by date AB#12486
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: enhancement, ready

#3358 Fixed missing city in request and changed date format in history table AB#12506
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/models/covidTreatmentAssessmentRequest.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: ready

#3359 Added the date of birth in the request body AB#12508
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/models/covidTreatmentAssessmentRequest.ts
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentRequest.cs
Labels: ready

#3362 Fixed testedPositiveInPast7Days not sending to PHSA AB#12509
  Apps/AdminWebClient/src/Server/Models/CovidSupport/CovidAssessmentRequest.cs
Labels: ready

#3366 Scroll to top of page after submitting PCR test kit form AB#12450
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: enhancement, ready

#3367 Reset PHN checkbox when clearing PCR test kit form AB#12407
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: bugfix, ready

#3368 Fix truncated or wrong postal code AB#12406
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
Labels: ready

#3369 Resolve issues on PCR test kit page AB#12404 AB#12517 AB#12401 AB#12398
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/navHeader.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/sidebar.vue
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/navbar.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/types.ts
  Apps/WebClient/src/ClientApp/src/views/landing.vue
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/navbarStub.ts
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTestWithTestKit.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
Labels: bugfix, enhancement, ready

#3372 Fix sidebar displaying while redirecting to PCR test kit page AB#12398
  Apps/WebClient/src/ClientApp/src/app.vue
Labels: bugfix, ready

#3373 Clear error during pcr test submission AB#12397
  Apps/WebClient/src/ClientApp/src/store/modules/error/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/error/types.ts
  Apps/WebClient/src/ClientApp/src/views/pcrTest.vue
  Apps/WebClient/src/ClientApp/test/stubs/store/errorBannerStub.ts
Labels: ready

#3374 Admin Screener Form - Blocked PHN AB#12535
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: ready

#3375 Add e2e tests for PCR test kit registration page AB#12408
  Testing/functional/tests/cypress/fixtures/LaboratoryService/authenticatedPcrTestError.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/publicPcrTestNoValidPhn.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/publicPcrTestValidPhn.json
  Testing/functional/tests/cypress/integration/e2e/covid19/pcrTestKit.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
  Testing/functional/tests/cypress/support/utils.js
Labels: functional tests, ready
