Repository bcgov/healthgateway, pull requests merged in 2022-06, with the labels that each got.

#3745 Remove unit tests from Vue app AB#13222
  Apps/WebClient/azure/build.yaml
  Apps/WebClient/azure/prbuild.yaml
  Apps/WebClient/src/ClientApp/jest.config.js
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/views/AcceptTermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/test/app.test.ts
  Apps/WebClient/src/ClientApp/test/components/error.test.ts
  Apps/WebClient/src/ClientApp/test/components/monthYearPicker.test.ts
  Apps/WebClient/src/ClientApp/test/components/navbar.header.test.ts
  Apps/WebClient/src/ClientApp/test/healthInsights.test.ts
  Apps/WebClient/src/ClientApp/test/home.test.ts
  Apps/WebClient/src/ClientApp/test/landing.test.ts
  Apps/WebClient/src/ClientApp/test/login.test.ts
  Apps/WebClient/src/ClientApp/test/mocks/mediaFileTransformer.js
  Apps/WebClient/src/ClientApp/test/mocks/styleMock.js
  Apps/WebClient/src/ClientApp/test/reports.test.ts
  Apps/WebClient/src/ClientApp/test/router.test.ts
  Apps/WebClient/src/ClientApp/test/store/auth.test.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/authStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/commentStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/configStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/encounterStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/errorBannerStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/idleStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/immunizationStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/laboratoryStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/medicationStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/navbarStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/noteStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/storeOptionsStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/timelineStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/userStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/store/vaccinationStatusStub.ts
  Apps/WebClient/src/ClientApp/test/stubs/util.ts
  Apps/WebClient/src/ClientApp/test/timeline.test.ts
  Apps/WebClient/src/ClientApp/test/vueSetup.ts
  Apps/WebClient/src/ClientApp/tsconfig.json
  Build/hg-steps-template.yaml
  Build/hg.yaml
Labels: unit tests, ready

#3746 Removed HG references to Newtonsoft for AB#13276
  Apps/Admin/Server/Services/ConfigurationService.cs
  Apps/Admin/Server/Services/UserFeedbackService.cs
  Apps/AdminWebClient/src/Server/Services/ConfigurationService.cs
  Apps/AdminWebClient/src/Server/Services/UserFeedbackService.cs
  Apps/Common/src/Services/EmailQueueService.cs
  Apps/Common/src/Utils/JsonClaimConverter.cs
  Apps/Common/src/Utils/JsonClaimsIdentityConverter.cs
  Apps/Common/src/Utils/JsonClaimsPrincipalConverter.cs
  Apps/Common/test/unit/AccessManagement/Administration/KeycloakUserAdminDelegateTests.cs
  Apps/Common/test/unit/Utils/JsonClaimConverterTest.cs
  Apps/Common/test/unit/Utils/JsonClaimsIdentityConverterTest.cs
  Apps/Common/test/unit/Utils/JsonClaimsPrincipalConverterTest.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/GatewayApi/src/Services/UserFeedbackService.cs
  Apps/GatewayApi/src/Services/UserSMSService.cs
  Apps/JobScheduler/src/Jobs/EmailJob.cs
  Apps/Medication/src/Services/RestMedicationService.cs
Labels: ready

#3747 Initialize projects to use dotnet secrets for AB#13278
  Apps/Admin/Server/Admin.Server.csproj
  Apps/AdminWebClient/src/AdminWebClient.csproj
  Apps/Encounter/src/Encounter.csproj
  Apps/GatewayApi/src/GatewayApi.csproj
  Apps/Immunization/src/Immunization.csproj
  Apps/JobScheduler/src/JobScheduler.csproj
  Apps/JobScheduler/src/appsettings.Development.json
  Apps/Laboratory/src/Laboratory.csproj
  Apps/Medication/src/Medication.csproj
  Apps/Patient/src/Patient.csproj
  Apps/WebClient/src/WebClient.csproj
Labels: ready

#3748 Fix HasTermsOfServiceUpdated not being populated AB#13273
  Apps/GatewayApi/src/Models/UserProfileModel.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: bugfix, ready

#3749 Integrate Cypress functional testing with Admin for AB#13223
  Apps/Admin/Client/Layouts/MainLayout.razor
  Apps/Admin/Client/Pages/Login.razor
  Apps/Admin/Tests/.gitignore
  Apps/Admin/Tests/Functional/.eslintrc.json
  Apps/Admin/Tests/Functional/cypress.config.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/authentication/login.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
  Apps/Admin/Tests/Functional/cypress/support/constants.js
  Apps/Admin/Tests/Functional/cypress/support/e2e.js
  Apps/Admin/Tests/Functional/cypress/support/index.d.ts
  Apps/Admin/Tests/Functional/cypress/tsconfig.json
  Apps/Admin/Tests/Functional/package-lock.json
  Apps/Admin/Tests/Functional/package.json
Labels: .NET, functional tests, ready

#3753 Update Release Notes 2022.6.0
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#3754 Update Attestation for Add Dependent
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
Labels: ready

#3757 Add PHN column to admin support table AB#13280
  Apps/Admin/Client/Pages/Support.razor
  Apps/Admin/Client/Pages/Support.razor.cs
Labels: bugfix, ready

#3759 Add dashboard e2e functional tests for AB#13223.
  Apps/Admin/Client/Components/RatingSummary.razor
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
  Apps/Admin/Tests/Functional/cypress/support/functions/environment.js
  Apps/Admin/Tests/Functional/cypress/tsconfig.json
  Apps/Admin/Tests/Functional/package-lock.json
  Apps/Admin/Tests/Functional/package.json
  Testing/functional/tests/cypress/db/seed.sql
Labels: functional tests, ready

#3769 Fix terms of service ID acceptance calculation AB#13296
  Apps/GatewayApi/src/Services/UserProfileService.cs
Labels: bugfix

#3770 Fix flakey database update when accepting Terms of Service AB#13296
  Apps/GatewayApi/src/Services/UserProfileService.cs
Labels: bugfix, ready

#3771 Fix broken unit test AB#13296
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: bugfix, ready

#3772 Fix DBMaintainer not finding the Connection String for AB#13294
  Apps/DBMaintainer/Program.cs
Labels: ready

#3773 Allow IDIR and PHSA users access to public pages AB#13127
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/CommunicationComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/BreadcrumbComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/navbar/getters.ts
Labels: bugfix, ready

#3777 Display count of filtered records on timeline AB#13197
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Testing/functional/tests/cypress/fixtures/EncounterService/encounters.json
  Testing/functional/tests/cypress/integration/e2e/timeline/pagination.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
  Testing/functional/tests/package-lock.json
  Testing/functional/tests/package.json
Labels: enhancement, ready, user story

#3775 Replace download button for lab reports AB#13248
  Apps/Laboratory/src/Models/LaboratoryOrder.cs
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/laboratory.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrders.json
  Testing/functional/tests/cypress/fixtures/LaboratoryService/laboratoryOrdersRefresh.json
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderReport.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrderReport.js
Labels: enhancement, ready, user story, UI

#3779 Fix local/UTC query and refresh button with date range for AB#13341.
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
  Apps/Admin/Server/Services/DashboardService.cs
  Apps/AdminWebClient/src/ClientApp/src/services/dashboardService.ts
Labels: .NET, functional tests, ready

#3783 Update PR template AB#13365
  .github/pull_request_template.md
Labels: ready, documentation

#3784 Document Azure DB setup and fix config issue for AB#13360
  Apps/WebClient/src/appsettings.hgmock.json
  Tools/Postgres/AzureSetup.md
  Tools/Postgres/sql/01_init-to-AddAllLaboratoryOrdersCommentEntryType.sql
Labels: ready

#3785 Added button to remove Vaccine Card quick link button for AB#13325
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
Labels: ready, UI

#3786 Sort dependents by descending birthdate AB#13363
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
Labels: bugfix, ready

#3800 Filter user feedback by tags AB#12732
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor.cs
  Apps/Admin/Client/Program.cs
Labels: enhancement, ready, UI

#3802 Fixed recurring user count query for AB#13371.
  Apps/Database/src/Delegates/DBProfileDelegate.cs
Labels: bugfix, .NET, ready

#3801 Fix behaviour when "VaccinationStatus" module is disabled for AB#13382
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
Labels: ready

#3807 Fix recurring user query for AB#13371.
  Apps/Database/src/Delegates/DBProfileDelegate.cs
Labels: bugfix, .NET, ready

#3808 Add feedback table AB#12673
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor.cs
  Apps/Admin/Client/Services/ITagApi.cs
  Apps/Admin/Client/Services/IUserFeedbackApi.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackActions.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackEffects.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackReducers.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackState.cs
  Apps/Admin/Server/Controllers/TagController.cs
  Apps/Admin/Server/Controllers/UserFeedbackController.cs
  Apps/Admin/Server/Services/IUserFeedbackService.cs
  Apps/Admin/Server/Services/UserFeedbackService.cs
Labels: enhancement, ready, UI

#3809 Create unique days dashboard test for AB#13342.
  Apps/Admin/Tests/Functional/README.md
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard/dashboard.cy.js
Labels: functional tests, ready, documentation

#3813 Add link to navigation with hdid in feedback table for AB#12977.
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor.cs
  Apps/Admin/Client/Pages/Support.razor.cs
Labels: .NET, ready

#3819 Add dashboard functional tests using fixtures for AB#13343.
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/dependent-count.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/logged-in-count.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/registered-count.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/summary.json
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard/dashboard.cy.js
Labels: functional tests, ready

#3812 Quick Links Optional - BC Vaccine Card for AB#13245
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
Labels: functional tests, ready, UI

#3820 Removed support role auth from index.js page for AB#12997
  Apps/Admin/Client/Pages/Index.razor
Labels: bugfix, ready

#3821 Add Refresh Button test for Blazor Admin Dashboard for AB#13353.
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
Labels: functional tests, ready

#3822 Fix spinner on Profile page when Patient fails for AB#13232
  Apps/WebClient/src/ClientApp/src/services/restPatientService.ts
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
Labels: bugfix, ready

#3824 Add additional Refresh button checks with fixtures for AB#13353
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/dependent-count-refresh.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/logged-in-count-refresh.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/registered-count-refresh.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/summary-refresh.json
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard/dashboard.cy.js
  Testing/functional/tests/cypress/db/seed.sql
Labels: functional tests, ready

#3825 Fix remaining issues on feedback page AB#13384
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor.cs
  Apps/Admin/Client/Services/ITagApi.cs
  Apps/Admin/Client/Services/IUserFeedbackApi.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackActions.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackEffects.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackReducers.cs
  Apps/Admin/Common/Models/UserFeedbackTagView.cs
  Apps/Admin/Common/Models/UserFeedbackView.cs
  Apps/Admin/Server/Converters/UserFeedbackConverter.cs
  Apps/Admin/Server/Converters/UserFeedbackTagConverter.cs
  Apps/Admin/Server/Services/UserFeedbackService.cs
  Apps/AdminWebClient/src/Server/Models/UserFeedbackView.cs
  Apps/AdminWebClient/src/Server/Services/UserFeedbackService.cs
  Apps/Database/src/Delegates/DBFeedbackDelegate.cs
  Apps/Database/src/Delegates/DBProfileDelegate.cs
  Apps/Database/src/Delegates/IFeedbackDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/Database/src/Models/UserFeedbackAdmin.cs
  Apps/Database/src/Models/UserProfile.cs
Labels: enhancement, ready

#3826 Update Release Notes 2022.6.1
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#3829 Fix error loading anonymous feedback AB#13394
  Apps/Admin/Server/Services/UserFeedbackService.cs
Labels: bugfix, ready

#3832 Update DB Naming and associated scripts for AB#13399
  Tools/Dev/Postgres/init/00_SetupDevDB.sql
  Tools/Dev/Postgres/init/01_init-to-AddAllLaboratoryOrdersCommentEntryType.sql
  Tools/Postgres/AzureSetup.md
Labels: ready

#3836 Ensure GetUsers returns all results from Keycloak for AB#13381
  Apps/Admin/Tests/Functional/cypress/integration/e2e/analytics.cy.js
  Apps/Common/src/AccessManagement/Administration/KeycloakUserAdminDelegate.cs
Labels: bugfix, ready

#3837 Improve responsiveness of tag input on feedback page AB#13392
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor.cs
Labels: bugfix, ready

#3839 Rearrange pagination and buttons on timeline AB#13289
  Apps/WebClient/src/ClientApp/src/assets/scss/_variables.scss
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
Labels: ready, user story, UI

#3835 Research AutoMapper and implement on GatewayApi for AB#13374
  Apps/Common/src/Common.csproj
  Apps/GatewayApi/src/MapProfiles/DependentInformationProfile.cs
  Apps/GatewayApi/src/MapProfiles/DependentProfile.cs
  Apps/GatewayApi/src/MapProfiles/TermsOfServiceProfile.cs
  Apps/GatewayApi/src/MapProfiles/UserCommentProfile.cs
  Apps/GatewayApi/src/MapProfiles/UserNoteProfile.cs
  Apps/GatewayApi/src/MapProfiles/UserPreferenceProfile.cs
  Apps/GatewayApi/src/MapProfiles/UserProfileProfile.cs
  Apps/GatewayApi/src/MapUtils/CommentMapUtils.cs
  Apps/GatewayApi/src/MapUtils/NoteMapUtils.cs
  Apps/GatewayApi/src/MapUtils/UserProfileMapUtils.cs
  Apps/GatewayApi/src/Models/DependentInformation.cs
  Apps/GatewayApi/src/Models/DependentModel.cs
  Apps/GatewayApi/src/Models/TermsOfServiceModel.cs
  Apps/GatewayApi/src/Models/UserComment.cs
  Apps/GatewayApi/src/Models/UserNote.cs
  Apps/GatewayApi/src/Models/UserPreferenceModel.cs
  Apps/GatewayApi/src/Models/UserProfileModel.cs
  Apps/GatewayApi/src/Services/CommentService.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/NoteService.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/CommentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/GatewayApi/test/unit/Services.Test/NoteServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Utils/MapperUtil.cs
Labels: ready

#3842 Delete calendar from timeline for AB#13421
  Apps/WebClient/src/ClientApp/src/components/calendar/CalendarBodyComponent.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/CalendarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/CalendarHeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/calendar/models.ts
  Apps/WebClient/src/ClientApp/src/components/timeline/CalendarTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/timeline.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/types.ts
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/calendar.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
Labels: functional tests, ready, UI

#3843 Remove Map Converters from Admin and replace with AutoMapper
  Apps/Admin/Server/Converters/AdminTagConverter.cs
  Apps/Admin/Server/Converters/CommunicationConverter.cs
  Apps/Admin/Server/Converters/UserFeedbackConverter.cs
  Apps/Admin/Server/Converters/UserFeedbackTagConverter.cs
  Apps/Admin/Server/MapProfiles/AdminTagProfile.cs
  Apps/Admin/Server/MapProfiles/CommunicationProfile.cs
  Apps/Admin/Server/MapProfiles/UserFeedbackProfile.cs
  Apps/Admin/Server/MapProfiles/UserFeedbackTagProfile.cs
  Apps/Admin/Server/MapUtils/UserFeedbackMapUtils.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/CommunicationService.cs
  Apps/Admin/Server/Services/UserFeedbackService.cs
Labels: ready

#3844 Remove Patient models
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Models/PatientModel.cs
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
Labels: ready

#3846 Add filter tags to timeline AB#13423
  Apps/WebClient/src/ClientApp/src/components/modal/NoteEditComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/timeline.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/types.ts
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: enhancement, ready, UI

#3858 Fix intercepts unintentionally calling back-end AB#13461
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicCovidTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
  Testing/functional/tests/cypress/integration/ui/resourceCentre/covidcard.js
  Testing/functional/tests/cypress/integration/ui/timeline/errors.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/user/acceptTermsOfService.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: bugfix, functional tests, ready

#3856 Add popovers to lab test status rows AB#13257
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: ready, user story

#3859 Fix skeleton not showing when no filter has been selected for AB#13464.
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: bugfix, ready

#3867 Add filter tags to timeline AB#13258
  Apps/WebClient/src/ClientApp/src/components/modal/NoteEditComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/timelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/timelineFilter.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/timeline.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/types.ts
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: ready, user story

#3866 Admin Dashboard Loading AB#13364
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
  Apps/Admin/Client/Store/Dashboard/DashboardReducers.cs
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
Labels: functional tests, ready, UI

#3868 Add functional tests for skeleton timeline loading for AB#13428.
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/fixtures/NoteService/notes-no-records.json
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
Labels: functional tests, ready
