Repository bcgov/healthgateway, pull requests merged in 2023-07, with the labels that each got.

#5303 Convert ServicesView and ODR Card AB#15795
  Apps/WebClient/src/NewClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/NewClientApp/src/components/shared/MessageModalComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/dataSource.ts
  Apps/WebClient/src/NewClientApp/src/models/user.ts
  Apps/WebClient/src/NewClientApp/src/models/userProfile.ts
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/stores/patientData.ts
  Apps/WebClient/src/NewClientApp/src/stores/user.ts
  Apps/WebClient/src/NewClientApp/src/utility/dataSourceUtil.ts
  Apps/WebClient/src/NewClientApp/src/utility/gridUtilty.ts
  Apps/WebClient/src/NewClientApp/src/views/HomeView.vue
  Apps/WebClient/src/NewClientApp/src/views/ServicesView.vue
Labels: ready, UI

#5312 Migrate HgDatePickerComponent to vuetify AB#15741
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/components/shared/HgDatePickerComponent.vue
  Apps/WebClient/src/NewClientApp/src/models/dateWrapper.ts
  Apps/WebClient/src/NewClientApp/src/plugins/index.ts
  Apps/WebClient/src/NewClientApp/src/utility/validationUtil.ts
Labels: ready

#5319 Migrate ErrorCardComponent to vuetify AB#15686
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/authentication/LoginView.vue
  Apps/WebClient/src/NewClientApp/src/components/error/AppErrorView.vue
  Apps/WebClient/src/NewClientApp/src/components/error/ErrorCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/error/TooManyRequestsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/home/AddQuickLinkComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/home/HomeView.vue
Labels: ready

#5324 Migrate CommunicationComponent to vuetify AB#15804
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/common/HtmlTextAreaComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/error/IdirLoggedInView.vue
  Apps/WebClient/src/NewClientApp/src/components/error/NotFoundView.vue
  Apps/WebClient/src/NewClientApp/src/components/error/PageErrorComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/error/PatientRetrievalErrorView.vue
  Apps/WebClient/src/NewClientApp/src/components/error/UnauthorizedView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/services/ServicesView.vue
  Apps/WebClient/src/NewClientApp/src/components/public/release-notes/ReleaseNotesView.vue
  Apps/WebClient/src/NewClientApp/src/components/site/BreadcrumbComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/CommunicationComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/RatingComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/SidebarComponent.vue
  Apps/WebClient/src/NewClientApp/src/services/interfaces.ts
  Apps/WebClient/src/NewClientApp/src/services/restCommunicationService.ts
Labels: ready

#5325 Convert FeedbackComponent
  Apps/WebClient/src/NewClientApp/src/components/private/home/AppTourComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/FeedbackComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/RatingComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/SidebarComponent.vue
Labels: ready, UI

#5339 Migrate ProfileView & VerifySmsDialogComponent to vuetify #15807
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/assets/styles/_spacing.scss
  Apps/WebClient/src/NewClientApp/src/assets/styles/_visibility.scss
  Apps/WebClient/src/NewClientApp/src/assets/styles/main.scss
  Apps/WebClient/src/NewClientApp/src/components/common/DisplayFieldComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/PageTitleComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/SectionHeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/error/ErrorCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/home/AddQuickLinkComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/ActiveUserProfileComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/InactiveUserProfileComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/ProfileView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileAddressComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileEmailComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileManageAccountComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileSmsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/VerifySmsDialogComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/services/ServicesView.vue
  Apps/WebClient/src/NewClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/NewClientApp/src/components/site/BreadcrumbComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/ProtectiveWordComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/RatingComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/loader.ts
  Apps/WebClient/src/NewClientApp/src/models/user.ts
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/services/interfaces.ts
  Apps/WebClient/src/NewClientApp/src/services/restUserProfileService.ts
  Apps/WebClient/src/NewClientApp/src/stores/loading.ts
  Apps/WebClient/src/NewClientApp/src/stores/user.ts
Labels: ready

#5341 Convert TermsOfServiceView - AB#15813
  Apps/WebClient/src/NewClientApp/src/components/public/terms-of-service/TermsOfServiceView.vue
  Apps/WebClient/src/NewClientApp/src/router/index.ts
Labels: ready, UI

#5344 Migrate IdleComponent to vuetify AB#15812
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/site/IdleComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/IdleDialogComponent.vue
  Apps/WebClient/src/NewClientApp/src/utility/idleDetector.ts
Labels: ready

#5340 Converts - Report components
  Apps/WebClient/src/NewClientApp/src/components/common/HgDataTable.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/Covid19TestResultReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/HealthVisitReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/HospitalVisitReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/LabResultReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/MedicationReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/NoteReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ReportsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ReportsView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/SpecialAuthorityRequestReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/entryType.ts
  Apps/WebClient/src/NewClientApp/src/models/covid19LaboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/NewClientApp/src/models/reportField.ts
  Apps/WebClient/src/NewClientApp/src/plugins/vuetify.ts
  Apps/WebClient/src/NewClientApp/src/stores/comment.ts
  Apps/WebClient/src/NewClientApp/src/stores/dependent.ts
  Apps/WebClient/src/NewClientApp/src/stores/immunization.ts
  Apps/WebClient/src/NewClientApp/src/stores/note.ts
  Apps/WebClient/src/NewClientApp/src/utility/dateSortUtility.ts
Labels: ready, UI

#5345 Convert ValidateEmailView AB#15815
  Apps/WebClient/src/ClientApp/src/views/ValidateEmailView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/validate-email/ValidateEmailView.vue
  Apps/WebClient/src/NewClientApp/src/constants/loader.ts
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Testing/functional/tests/cypress/integration/ui/user/emailValidation.js
Labels: ready, UI

#5346 Update Diagnostic Imaging Card with Text and Links
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
Labels: enhancement, ready, UI

#5348 Fix HgDatePickerComponent not respecting initial value AB#15831
  Apps/WebClient/src/NewClientApp/src/components/common/HgDatePickerComponent.vue
Labels: bugfix, ready

#5347 Convert Waitlist Views - AB#15816
  Apps/WebClient/src/NewClientApp/src/components/public/waitlist/QueueFullView.vue
  Apps/WebClient/src/NewClientApp/src/components/public/waitlist/QueueView.vue
  Apps/WebClient/src/NewClientApp/src/router/beforeEachGuard.ts
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/stores/waitlist.ts
Labels: ready, UI

#5351 Convert NotificationCentreComponent - AB#15818
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/NotificationCentreComponent.vue
  Apps/WebClient/src/NewClientApp/src/stores/notification.ts
Labels: ready, UI

#5355 Convert ResourceCentreComponent - AB#15819
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/site/FooterComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/ResourceCentreComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/SidebarComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/screenWidth.ts
  Apps/WebClient/src/NewClientApp/src/stores/app.ts
Labels: ready, UI

#5363 Append updated status to DI card title
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/PatientDataAccess/src/Api/HealthDataEntry.cs
  Apps/PatientDataAccess/src/HealthData.cs
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/diagnosticImagingTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/patientDataResponse.ts
Labels: ready, UI

#5360 Upgrade public and authenticated vaccine card components for AB#15825.
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/common/HgButtonComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/MessageModalComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/PageTitleComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/error/PageErrorComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/error/TooManyRequestsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/covid19/Covid19View.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/VerifySmsDialogComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/registration/RegistrationView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/NewClientApp/src/components/public/vaccine-card/VaccineCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/vaccine-card/VaccineCardView.vue
  Apps/WebClient/src/NewClientApp/src/components/site/FeedbackComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/IdleDialogComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/ProtectiveWordComponent.vue
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/stores/vaccinationStatusAuthenticated.ts
  Apps/WebClient/src/NewClientApp/src/stores/vaccinationStatusPublic.ts
Labels: enhancement, ready, UI

#5358 Convert PcrTestView - AB#15826
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/common/PrivacyStatementComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationForm.vue
  Apps/WebClient/src/NewClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationMethodPrompt.vue
  Apps/WebClient/src/NewClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationSuccessfulDisplay.vue
  Apps/WebClient/src/NewClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationView.vue
  Apps/WebClient/src/NewClientApp/src/components/public/vaccine-card/VaccineCardView.vue
  Apps/WebClient/src/NewClientApp/src/constants/path.ts
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/utility/masks.ts
Labels: ready, UI

#5368 Merge dev into features/15545
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Tests/Functional/package-lock.json
  Apps/Admin/Tests/Functional/package.json
  Apps/AdminWebClient/src/ClientApp/package-lock.json
  Apps/AdminWebClient/src/ClientApp/package.json
  Apps/Common/src/AspNetConfiguration/Modules/Observability.cs
  Apps/Common/src/Common.csproj
  Apps/CommonUi/src/Common.Ui.csproj
  Apps/JobScheduler/src/JobScheduler.csproj
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/PatientDataAccess/src/Api/HealthDataEntry.cs
  Apps/PatientDataAccess/src/HealthData.cs
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/diagnosticImagingTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/patientDataResponse.ts
  Testing/functional/tests/package-lock.json
  Testing/functional/tests/package.json
  Testing/integration/tests/IntegrationTests.csproj
Labels: ready

#5376 Migrate timeline entry components to vuetify AB#15824
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/DisplayFieldComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/HgDataTableComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/InfoTooltipComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/SectionHeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/error/AppErrorView.vue
  Apps/WebClient/src/NewClientApp/src/components/error/TooManyRequestsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/InactiveUserProfileComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileEmailComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileSmsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/Covid19TestResultReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/HealthVisitReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/HospitalVisitReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/LabResultReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/MedicationReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/NoteReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/SpecialAuthorityRequestReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineEntryComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/comment/AddCommentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/comment/CommentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/comment/CommentSectionComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/Covid19TestResultDescriptionComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/Covid19TestResultTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/HealthVisitTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/ImmunizationTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/LabResultTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/MedicationTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/NoteTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/SpecialAuthorityRequestTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationForm.vue
  Apps/WebClient/src/NewClientApp/src/constants/entryType.ts
  Apps/WebClient/src/NewClientApp/src/main.ts
  Apps/WebClient/src/NewClientApp/src/models/patientDataResponse.ts
  Apps/WebClient/src/NewClientApp/src/models/timeline/diagnosticImagingTimelineEntry.ts
  Apps/WebClient/src/NewClientApp/src/models/timeline/healthVisitTimelineEntry.ts
  Apps/WebClient/src/NewClientApp/src/models/timeline/noteTimelineEntry.ts
  Apps/WebClient/src/NewClientApp/src/models/timeline/specialAuthorityRequestTimelineEntry.ts
  Apps/WebClient/src/NewClientApp/src/plugins/components.ts
  Apps/WebClient/src/NewClientApp/src/plugins/vuetify.ts
  Apps/WebClient/src/NewClientApp/src/stores/clinicalDocument.ts
  Apps/WebClient/src/NewClientApp/src/stores/timeline.ts
  Testing/functional/tests/cypress/integration/e2e/timeline/encounter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/encounter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/medication.js
Labels: ready

#5372 Convert Legacy Dependent Components - AB#15822
  Apps/WebClient/src/NewClientApp/src/components/common/MessageModalComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentsView.vue
Labels: ready, UI

#5373 Convert add dependent modal to Vue 3 for AB#15820.
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/views/DependentManagementView.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/AddDependentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/DependentViewSelectorComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/loader.ts
  Testing/functional/tests/cypress/integration/e2e/dependent/management.js
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
Labels: enhancement, ready, UI
