Repository bcgov/healthgateway, pull requests merged in 2023-09, with the labels that each got.

#5511 Refine BcCancer naming and DateTimes - AB#16076
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor.cs
  Apps/CommonData/src/Constants/DataSource.cs
  Apps/Patient/src/Constants/PatientDataType.cs
  Apps/Patient/src/Mappings/BcCancerScreeningProfile.cs
  Apps/Patient/src/Mappings/PatientDataAccessMappings.cs
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/Patient/src/Services/PatientDataService.cs
  Apps/Patient/test/unit/Services/PatientDataServiceTests.cs
  Apps/Patient/test/unit/Utils/MapperUtil.cs
  Apps/PatientDataAccess/src/Api/HealthDataEntry.cs
  Apps/PatientDataAccess/src/Api/HealthDataJsonConverter.cs
  Apps/PatientDataAccess/src/HealthData.cs
  Apps/PatientDataAccess/src/Mappings.cs
  Apps/PatientDataAccess/test/unit/HealthDataJsonConverterTests.cs
  Apps/PatientDataAccess/test/unit/PatientDataRepositoryTests.cs
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/FilterComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/BcCancerScreeningResultTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/NewClientApp/src/components/site/NotificationCentreComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/commentEntryType.ts
  Apps/WebClient/src/NewClientApp/src/constants/dataSource.ts
  Apps/WebClient/src/NewClientApp/src/constants/entryType.ts
  Apps/WebClient/src/NewClientApp/src/constants/errorType.ts
  Apps/WebClient/src/NewClientApp/src/models/patientDataResponse.ts
  Apps/WebClient/src/NewClientApp/src/models/timeline/bcCancerScreeningResultTimelineEntry.ts
  Apps/WebClient/src/NewClientApp/src/services/restPatientDataService.ts
  Apps/WebClient/src/NewClientApp/src/stores/patientData.ts
  Apps/WebClient/src/NewClientApp/src/utility/dataSourceUtil.ts
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/fixtures/PatientData/allTimelineData.json
  Testing/functional/tests/cypress/integration/e2e/timeline/bcCancerScreening.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
Labels: functional tests, unit tests, ready

#5508 Improve Legacy Dependent loading UX - AB#16062
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/stores/immunization.ts
  Apps/WebClient/src/NewClientApp/src/utility/dateSortUtility.ts
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
  Testing/functional/tests/cypress/support/commands.js
Labels: ready, UI

#5516 Prevent filter closure on apply - AB#16061
  Apps/WebClient/src/ClientApp/src/components/private/reports/ReportsComponent.vue
Labels: functional tests, ready

#5525 Fix filter BC Cancer test - AB#16082
  Testing/functional/tests/cypress/integration/e2e/timeline/diagnosticImaging.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
Labels: functional tests, ready

#5529 Create AddressConfirmationDialog in Admin.Client AB#16064
  Apps/Admin/Client/Components/AgentAudit/AuditReasonDialog.razor.cs
  Apps/Admin/Client/Components/Common/HgAutocomplete.razor
  Apps/Admin/Client/Components/Common/HgAutocomplete.razor.cs
  Apps/Admin/Client/Components/Support/AddressConfirmationDialog.razor
  Apps/Admin/Client/Components/Support/AddressConfirmationDialog.razor.cs
  Apps/Admin/Client/Pages/DelegationPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Store/IAddressAction.cs
  Apps/CommonData/src/Constants/CountryCode.cs
  Apps/CommonData/src/Constants/ProvinceAbbreviation.cs
  Apps/CommonData/src/Constants/StateAbbreviation.cs
  Apps/CommonData/src/Utils/AddressUtility.cs
  Apps/CommonUi/src/Constants/Mask.cs
Labels: ready, UI

#5531 Resolve class coupling warning for unit tests AB#15653
  .editorconfig
Labels: bugfix, ready

#5533 Added and updated unit tests for admin covid assessment for AB#16070.
  .editorconfig
  Apps/Admin/Tests/Services/CovidSupportServiceTests.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
Labels: .NET, unit tests, ready

#5528 Fix SonarCloud integration tests - AB#16034
  Apps/Common/src/AspNetConfiguration/Modules/JobScheduler.cs
  Apps/Common/src/Messaging/ConfigurationExtensions.cs
  Apps/DBMaintainer/FileDownload/FileDownloadService.cs
  Testing/integration/tests/Dependents/AdminApiDependentTests.cs
  Testing/integration/tests/Dependents/GatewayApiDependentTests.cs
  Testing/integration/tests/Infrastructure/MessagingTests.cs
  Testing/integration/tests/IntegrationTests.csproj
  Testing/integration/tests/ScenarioBase.cs
  Tools/SonarCloud/azure/build.yaml
Labels: unit tests, ready

#5542 Add retrieve vaccine record to controller, service and unit tests AB#16106
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/Services/ICovidSupportService.cs
  Apps/Admin/Tests/Services/CovidSupportServiceTests.cs
  Apps/Common/src/Constants/ErrorMessages.cs
  Apps/Common/src/Models/BcMailPlusConfig.cs
  Apps/Common/src/Models/VaccineCardConfig.cs
Labels: enhancement, .NET, ready

#5549 Fix functional tests after change to support search behaviour AB#16109
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Admin/Tests/Functional/cypress/utilities/supportUtilities.js
Labels: functional tests, ready

#5541 Add cancer recall to set for AB#16084
  Apps/Patient/src/Models/BcCancerScreeningType.cs
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/Patient/src/Services/PatientDataService.cs
  Apps/Patient/test/unit/Services/PatientDataServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/BcCancerScreeningTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/models/patientDataResponse.ts
  Apps/WebClient/src/ClientApp/src/models/timeline/bcCancerScreeningTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/PatientData/bcCancerTypes.json
  Testing/functional/tests/cypress/integration/e2e/timeline/bcCancerScreening.js
  Testing/functional/tests/cypress/integration/ui/timeline/bcCancerScreening.js
Labels: functional tests, unit tests, ready, UI

#5562 Add covid immunization/assessment/vaccind card to admin patient details for AB#15772.
  Apps/Admin/Client/Api/ISupportApi.cs
  Apps/Admin/Client/Components/Support/Covid19AssessmentSection.razor
  Apps/Admin/Client/Components/Support/Covid19AssessmentSection.razor.cs
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor.cs
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsReducers.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsState.cs
  Apps/Admin/Client/Store/VaccineCard/VaccineCardActions.cs
  Apps/Admin/Client/Store/VaccineCard/VaccineCardEffects.cs
  Apps/Admin/Client/Store/VaccineCard/VaccineCardReducers.cs
  Apps/Admin/Client/Store/VaccineCard/VaccineCardState.cs
Labels: enhancement, .NET, ready, UI

#5565 Add eventTracker for all entryTypes for AB#16118
  Apps/WebClient/src/ClientApp/src/stores/labResult.ts
  Apps/WebClient/src/ClientApp/src/stores/note.ts
Labels: bugfix, ready

#5563 Add Recommendations Dialog and link for AB#16071
  Apps/WebClient/src/ClientApp/src/assets/images/services/immunize-bc-logo.svg
  Apps/WebClient/src/ClientApp/src/components/private/home/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/RecommendationsDialogComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/models/reportField.ts
  Apps/WebClient/src/ClientApp/src/models/reportFilter.ts
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
  Apps/WebClient/src/ClientApp/src/stores/report.ts
  Apps/WebClient/src/ClientApp/src/stores/user.ts
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
  Apps/WebClient/src/Server/Models/FeatureToggleConfiguration.cs
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
Labels: functional tests, ready, UI

#5572 Add COVID-19 treatment assessment page AB#15851
  Apps/Admin/Client/Components/Common/HgField.razor
  Apps/Admin/Client/Components/Support/AssessmentOptionRadio.razor
  Apps/Admin/Client/Components/Support/AssessmentOptionRadio.razor.cs
  Apps/Admin/Client/Components/Support/AssessmentQuestion.razor
  Apps/Admin/Client/Components/Support/AssessmentQuestion.razor.cs
  Apps/Admin/Client/Components/Support/Covid19AssessmentSection.razor
  Apps/Admin/Client/Components/Support/Covid19AssessmentSection.razor.cs
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor.cs
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Client/Store/IAddressAction.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsActions.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsEffects.cs
  Apps/Admin/Common/Models/CovidSupport/CovidAssessmentRequest.cs
  Apps/Admin/Common/Models/PatientSupportDetails.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/CommonData/src/Utils/AddressUtility.cs
  Apps/CommonData/src/Validations/AgeRangeValidator.cs
  Apps/CommonUi/src/Constants/Mask.cs
Labels: ready

#5566 Unit tests for vaccine status and immunization admin delegates AB#16103.
  Apps/Admin/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/Admin/Server/Delegates/RestVaccineStatusDelegate.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Delegates/RestImmunizationAdminDelegateTests.cs
  Apps/Admin/Tests/Delegates/RestVaccineStatusDelegateTests.cs
  Apps/Admin/Tests/Utils/MapperUtil.cs
Labels: .NET, unit tests, ready

#5573 Fix "CA" country in address confirmation dialog AB#16134
  Apps/Admin/Client/Components/Support/AddressConfirmationDialog.razor.cs
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor.cs
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor.cs
Labels: ready

#5574 Resolve warnings and fix Admin.Client bugs AB#16140 AB#16133
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/Admin/Client/Components/Support/AddressConfirmationDialog.razor.cs
  Apps/Admin/Client/Components/Support/AssessmentOptionRadio.razor.cs
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor.cs
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor.cs
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor.cs
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsActions.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsEffects.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportActions.cs
  Apps/Admin/Client/Store/VaccineCard/VaccineCardActions.cs
  Apps/Admin/Client/Store/VaccineCard/VaccineCardEffects.cs
  Apps/Admin/Common/Models/PatientSupportDetails.cs
  Apps/Admin/Tests/Delegates/RestImmunizationAdminDelegateTests.cs
  Apps/Admin/Tests/Delegates/RestVaccineStatusDelegateTests.cs
  Apps/CommonData/src/Utils/StringManipulator.cs
Labels: ready

#5581 Remove space, link display for AB#16138 and AB#16137
  Apps/WebClient/src/ClientApp/src/components/private/reports/ImmunizationReportComponent.vue
Labels: bugfix, ready

#5583 Add vaccine recommendations card to dependent dashboard AB#16048
  Apps/WebClient/src/ClientApp/src/components/private/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/RecommendationsDialogComponent.vue
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
Labels: ready

#5582 Functional tests for coivd immunization and assessments for AB#15853.
  Apps/Admin/Client/Components/Support/AssessmentQuestion.razor
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor.cs
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
Labels: .NET, functional tests, ready, UI

#5585 Use UI Verification date conversion for AB#15671
  Apps/Admin/Client/Components/Support/MessageVerificationTable.razor
  Apps/Admin/Client/Components/Support/MessageVerificationTable.razor.cs
  Apps/Common/src/MapUtils/MessagingVerificationMapUtils.cs
Labels: ready

#5584 Update vite to refresh less often running locally AB#15803
  Apps/WebClient/src/ClientApp/vite.config.ts
Labels: bugfix, ready

#5589 Fix failing admin functional test for AB#16147.
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
Labels: bugfix, functional tests, ready

#5593 Fix null pointer exception issue affecting page load for AB#16166.
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
Labels: bugfix, .NET, ready

#5595 Re-query data when current/previous Hdid are different for AB#16169.
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
Labels: bugfix, .NET, ready

#5592 Refine recommendations dialog for AB#16149
  Apps/WebClient/src/ClientApp/src/components/private/home/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/RecommendationsDialogComponent.vue
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
Labels: functional tests, ready

#5598 Move Unique days for AB#16105
  Apps/Admin/Client/Pages/DashboardPage.razor
Labels: ready

#5599 Change LabResult report button for AB#15574
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/LabResultTimelineComponent.vue
Labels: ready

#5600 Add optional logoUri for datasets for AB#16114
  Apps/WebClient/src/ClientApp/src/assets/images/services/bc-cancer.png
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/ClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/ClientApp/src/components/public/landing/TileComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/models/infoTile.ts
Labels: ready, UI

#5603 Fix Admin Userbility for AB#16074 and AB#16176
  Apps/Admin/Client/Components/Communications/CommunicationDialog.razor
  Apps/Admin/Client/Components/Communications/CommunicationsTable.razor.cs
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Utils/CommunicationUtility.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
Labels: ready

#5606 Correct Recommendations tests for AB#16175
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
Labels: ready

#5580 helm charts to resolve #16110
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
  Tools/BaseBuild/helm/redis/templates/NOTES.txt
  Tools/BaseBuild/helm/redis/templates/_helpers.tpl
  Tools/BaseBuild/helm/redis/templates/tests/test-connection.yaml
  Tools/BaseBuild/helm/redis/values.yaml
  Tools/Helm/Charts/.gitignore
  Tools/Helm/Charts/healthgateway/.helmignore
  Tools/Helm/Charts/healthgateway/Chart.yaml
  Tools/Helm/Charts/healthgateway/README.md
  Tools/Helm/Charts/healthgateway/templates/NOTES.txt
  Tools/Helm/Charts/healthgateway/templates/_helpers.tpl
  Tools/Helm/Charts/healthgateway/templates/aps-netpol.yaml
  Tools/Helm/Charts/healthgateway/templates/common-configmap.yaml
  Tools/Helm/Charts/healthgateway/templates/common-files.yaml
  Tools/Helm/Charts/healthgateway/templates/common-secrets.yaml
  Tools/Helm/Charts/healthgateway/templates/data-protection-pvc.yaml
  Tools/Helm/Charts/healthgateway/templates/dc.tpl
  Tools/Helm/Charts/healthgateway/templates/hpa.tpl
  Tools/Helm/Charts/healthgateway/templates/netpol.tpl
  Tools/Helm/Charts/healthgateway/templates/patroni-netpol.yaml
  Tools/Helm/Charts/healthgateway/templates/patroni-secret.yaml
  Tools/Helm/Charts/healthgateway/templates/pdb.tpl
  Tools/Helm/Charts/healthgateway/templates/route.tpl
  Tools/Helm/Charts/healthgateway/templates/secret.tpl
  Tools/Helm/Charts/healthgateway/templates/service.tpl
  Tools/Helm/Charts/healthgateway/templates/services.yaml
  Tools/Helm/Charts/hgtools/.helmignore
  Tools/Helm/Charts/hgtools/Chart.yaml
  Tools/Helm/Charts/hgtools/README.md
  Tools/Helm/Charts/hgtools/templates/NOTES.txt
  Tools/Helm/Charts/hgtools/templates/azure-agent.yaml
  Tools/Helm/Charts/hgtools/templates/imagestream.yaml
  Tools/Helm/Charts/hgtools/values.yaml
  Tools/Helm/Charts/redis/Chart.yaml
  Tools/Helm/Charts/redis/templates/NOTES.txt
  Tools/Helm/Charts/redis/templates/configmap.yml
  Tools/Helm/Charts/redis/templates/netpol.yml
  Tools/Helm/Charts/redis/templates/secret.yaml
  Tools/Helm/Charts/redis/templates/service.yaml
  Tools/Helm/Charts/redis/templates/statefulset.yaml
  Tools/Helm/Charts/redis/tests/test-connection.yaml
  Tools/Helm/Charts/redis/values.yaml
  Tools/Kong/config.tmpl
  Tools/Kong/generate.sh
  Tools/Kong/publish.sh
  Tools/Kong/routes-gatewayapi.tmpl
  Tools/Kong/routes-immunization.tmpl
  Tools/Kong/routes-laboratory.tmpl
  Tools/Kong/routes-medication.tmpl
  Tools/Kong/routes-patient.tmpl
Labels: ready

#5608 Include pharmacist assessment logic in model AB#15672
  Apps/GatewayApi/src/Assets/Templates/MedicationReport.docx
  Apps/GatewayApi/src/Assets/Templates/MedicationReport.xlsx
  Apps/Medication/src/Models/MedicationSummary.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/WebClient/src/ClientApp/src/components/private/reports/MedicationReportComponent.vue
  Apps/WebClient/src/ClientApp/src/models/medicationSummary.ts
  Apps/WebClient/src/ClientApp/src/models/timeline/medicationTimelineEntry.ts
  Testing/functional/tests/cypress/fixtures/MedicationService/medicationStatement.json
  Testing/functional/tests/cypress/integration/ui/report/reportFiltering.js
Labels: ready

#5609 Fix client registry delegates to accept new response codes for AB#16173
  Apps/AccountDataAccess/src/Patient/ClientRegistriesDelegate.cs
  Apps/AccountDataAccess/test/unit/ClientRegistriesDelegateTests.cs
  Apps/Admin/Server/appsettings.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-duplicate.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Admin/Tests/Functional/cypress/utilities/supportUtilities.js
  Apps/AdminWebClient/src/appsettings.json
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/GatewayApi/src/appsettings.json
  Apps/Patient/src/appsettings.json
  Testing/functional/tests/cypress/db/seed.sql
Labels: bugfix, .NET, functional tests, unit tests, ready

#5615 Include COVID-19 details for patients w/o HG accounts AB#16170
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
Labels: bugfix, ready

#5616 Correct web alert link handling for AB#16192
  Apps/WebClient/src/ClientApp/src/components/site/NotificationCentreComponent.vue
  Testing/functional/tests/cypress/fixtures/NotificationService/notifications.json
Labels: bugfix, functional tests, ready

#5622 Add AdminReports integration tests for AB#15618
  Apps/Admin/Server/Controllers/AdminReportController.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/AdminReportService.cs
  Apps/Database/src/Delegates/DbBlockedAccessDelegate.cs
  Testing/functional/tests/cypress/db/seed.sql
  Testing/integration/tests/AdminReports/AdminApiAdminReportTests.cs
Labels: unit tests, ready

#5623 Update valid Client Registry warning response codes for AB#16204
  Apps/AccountDataAccess/src/Patient/ClientRegistriesDelegate.cs
  Apps/AccountDataAccess/test/unit/ClientRegistriesDelegateTests.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Server/appsettings.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/AdminWebClient/src/appsettings.json
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/GatewayApi/src/appsettings.json
  Apps/Patient/src/appsettings.json
  Testing/functional/tests/cypress/integration/e2e/covid19/authenticatedVaccineCard.js
Labels: bugfix, .NET, functional tests, ready

#5627 Implement admin report page in Admin.Client AB#15619
  Apps/Admin/Client/Api/IAdminReportApi.cs
  Apps/Admin/Client/Components/Site/NavMenu.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor.cs
  Apps/Admin/Client/Pages/ReportsPage.razor
  Apps/Admin/Client/Pages/ReportsPage.razor.cs
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Store/AdminReport/AdminReportActions.cs
  Apps/Admin/Client/Store/AdminReport/AdminReportEffects.cs
  Apps/Admin/Client/Store/AdminReport/AdminReportReducers.cs
  Apps/Admin/Client/Store/AdminReport/AdminReportState.cs
  Apps/Admin/Client/Utils/FormattingUtility.cs
Labels: ready

#5628 Limit access to admin covid details to SupportUser role for AB#16165
  Apps/Admin/Client/Components/Support/Covid19AssessmentSection.razor
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Common/Models/PatientSupportDetails.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Server/Services/ISupportService.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Functional/cypress.config.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
Labels: bugfix, .NET, functional tests, unit tests, ready, UI

#5631 Fix e2e and ui admin support functional test for AB16212
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: bugfix, functional tests, ready

#5632 Add functional test for admin reports AB#15620
  Apps/Admin/Tests/Functional/cypress/integration/e2e/reports.cy.js
  Apps/HealthGateway.code-workspace
  Testing/functional/tests/cypress/db/seed.sql
  Testing/integration/tests/AdminReports/AdminApiAdminReportTests.cs
Labels: functional tests, ready
