Repository bcgov/healthgateway, pull requests merged in 2023-11, with the labels that each got.

#5755 Fix column width for feedback and admin flakiness functional tests for AB#16402
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportActions.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportEffects.cs
  Apps/Admin/Client/Utils/StoreUtility.cs
  Apps/Admin/Tests/Functional/cypress/integration/ui/patient-details.cy.js
Labels: bugfix, .NET, functional tests, ready, UI

#5761 Refactor SupportService for improved parallelism AB#16398
  Apps/Admin/Server/MapUtils/PatientSupportDetailsMapUtils.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/AdminWebClient/src/Server/Services/SupportService.cs
  Apps/AdminWebClient/test/unit/Services.Test/SupportServiceTests.cs
  Apps/Common/src/MapUtils/MessagingVerificationMapUtils.cs
  Apps/Database/src/Delegates/DbResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IResourceDelegateDelegate.cs
Labels: ready

#5762 Remove JobScheduler link from Admin nav menu AB#16359
  Apps/Admin/Client/Components/Site/NavMenu.razor
  Apps/Admin/Client/Components/Site/NavMenu.razor.cs
  Apps/Admin/Common/Models/ExternalConfiguration.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.hgmock.json
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
Labels: ready, user story

#5766 Format date of birth on COVID-19 vaccination record AB#16436
  Apps/WebClient/src/ClientApp/src/components/private/covid19/Covid19View.vue
Labels: bugfix, ready

#5764 Change filter checkboxes to chips for AB#16179
  Apps/WebClient/src/ClientApp/src/components/private/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/TimelineComponent.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
Labels: functional tests, ready, UI

#5772 Trigger queries on Admin pages when hitting Enter key AB#16234
  Apps/Admin/Client/Pages/AgentAccessPage.razor
  Apps/Admin/Client/Pages/AgentAccessPage.razor.cs
  Apps/Admin/Client/Pages/DelegationPage.razor
  Apps/Admin/Client/Pages/DelegationPage.razor.cs
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Services/IKeyInterceptorService.cs
  Apps/Admin/Client/Services/KeyInterceptorService.cs
Labels: ready

#5781 Update AdminWebClient and WebClient Snow Plow calls to new event mappings
  Apps/AdminWebClient/src/ClientApp/src/plugins/extensions.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/AdminWebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/AdminWebClient/src/ClientApp/src/services/interfaces.ts
  Apps/AdminWebClient/src/ClientApp/src/services/restTrackingService.ts
  Apps/AdminWebClient/src/ClientApp/src/utility/snowPlow.ts
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
  Apps/WebClient/src/ClientApp/src/components/private/covid19/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/components/private/dependent/legacy/LegacyDependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/RecommendationsDialogComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/BcCancerScreeningTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/Covid19TestResultTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/LabResultTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/public/vaccine-card/VaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/components/site/RatingComponent.vue
  Apps/WebClient/src/ClientApp/src/ioc/identifier.ts
  Apps/WebClient/src/ClientApp/src/ioc/initialization.ts
  Apps/WebClient/src/ClientApp/src/plugins/extensions.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restTrackingService.ts
  Apps/WebClient/src/ClientApp/src/stores/clinicalDocument.ts
  Apps/WebClient/src/ClientApp/src/stores/healthVisit.ts
  Apps/WebClient/src/ClientApp/src/stores/hospitalVisit.ts
  Apps/WebClient/src/ClientApp/src/stores/immunization.ts
  Apps/WebClient/src/ClientApp/src/stores/labResult.ts
  Apps/WebClient/src/ClientApp/src/stores/medication.ts
  Apps/WebClient/src/ClientApp/src/stores/note.ts
  Apps/WebClient/src/ClientApp/src/stores/patientData.ts
  Apps/WebClient/src/ClientApp/src/stores/specialAuthorityRequest.ts
  Apps/WebClient/src/ClientApp/src/utility/eventDataUtility.ts
  Apps/WebClient/src/ClientApp/src/utility/eventTracker.ts
  Apps/WebClient/src/ClientApp/src/utility/snowPlow.ts
Labels: enhancement, ready, do not merge, UI

#5780 Add patient tabs structure for AB#16406
  Apps/Admin/Client/Components/AgentAudit/AgentAuditHistory.razor
  Apps/Admin/Client/Components/Common/HgTabs.razor
  Apps/Admin/Client/Components/Common/HgTabs.razor.cs
  Apps/Admin/Client/Components/Details/AccountTab.razor
  Apps/Admin/Client/Components/Details/AccountTab.razor.cs
  Apps/Admin/Client/Components/Details/ManageTab.razor
  Apps/Admin/Client/Components/Details/ManageTab.razor.cs
  Apps/Admin/Client/Components/Details/NotesTab.razor
  Apps/Admin/Client/Components/Details/NotesTab.razor.cs
  Apps/Admin/Client/Components/Details/ProfileTab.razor
  Apps/Admin/Client/Components/Details/ProfileTab.razor.cs
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Components/Support/DependentTable.razor
  Apps/Admin/Client/Components/Support/MessageVerificationTable.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
Labels: ready, UI

#5769 Add AdminUser permissions to COVID for AB#16407
  Apps/Admin/Client/Components/Details/ProfileTab.razor.cs
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/utilities/sharedUtilities.js
  Apps/Admin/Tests/Functional/cypress/utilities/supportUtilities.js
Labels: functional tests, ready, UI

#5795 Migrate Admin patient details page to tabs AB#16367
  Apps/Admin/Client/Components/AgentAudit/AgentAuditHistory.razor
  Apps/Admin/Client/Components/Common/HgTabs.razor
  Apps/Admin/Client/Components/Common/HgTabs.razor.cs
  Apps/Admin/Client/Components/Details/AccountTab.razor
  Apps/Admin/Client/Components/Details/AccountTab.razor.cs
  Apps/Admin/Client/Components/Details/ManageTab.razor
  Apps/Admin/Client/Components/Details/ManageTab.razor.cs
  Apps/Admin/Client/Components/Details/NotesTab.razor
  Apps/Admin/Client/Components/Details/NotesTab.razor.cs
  Apps/Admin/Client/Components/Details/ProfileTab.razor
  Apps/Admin/Client/Components/Details/ProfileTab.razor.cs
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Components/Support/DependentTable.razor
  Apps/Admin/Client/Components/Support/MessageVerificationTable.razor
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/utilities/sharedUtilities.js
  Apps/Admin/Tests/Functional/cypress/utilities/supportUtilities.js
Labels: ready

#5796 Create delegate invitation endpoint and service interface for AB#16184
  Apps/GatewayApi/src/Controllers/DelegateController.cs
  Apps/GatewayApi/src/Models/CreateDelegateInvitationRequest.cs
  Apps/GatewayApi/src/Services/IDelegateService.cs
Labels: enhancement, .NET, ready

#5800 Fix navigation guard redirects throwing errors AB#16475
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Unauthorized.vue
Labels: bugfix, ready

#5797 Update Admin dashboard layout AB#16410
  Apps/Admin/Client/Components/Dashboard/RatingSummary.razor
  Apps/Admin/Client/Pages/AnalyticsPage.razor
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
Labels: ready, UI

#5805 Update warning handling and resolve .NET 8 issues AB#16491
  .editorconfig
  Apps/Admin/Client/Authorization/RolesClaimsPrincipalFactory.cs
  Apps/Admin/Client/Components/Dashboard/RatingSummary.razor.cs
  Apps/Admin/Client/Services/KeyInterceptorService.cs
  Apps/Admin/Client/Store/AdminReport/AdminReportEffects.cs
  Apps/Admin/Client/Store/AdminReport/AdminReportReducers.cs
  Apps/Admin/Client/Store/AdminReport/AdminReportState.cs
  Apps/Admin/Client/Store/AgentAccess/AgentAccessEffects.cs
  Apps/Admin/Client/Store/AgentAccess/AgentAccessReducers.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsEffects.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsReducers.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsEffects.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsReducers.cs
  Apps/Admin/Client/Store/Communications/CommunicationsEffects.cs
  Apps/Admin/Client/Store/Communications/CommunicationsReducers.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationEffects.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationReducers.cs
  Apps/Admin/Client/Store/Dashboard/DashboardEffects.cs
  Apps/Admin/Client/Store/Dashboard/DashboardReducers.cs
  Apps/Admin/Client/Store/Delegation/DelegationEffects.cs
  Apps/Admin/Client/Store/Delegation/DelegationReducers.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsEffects.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsReducers.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportEffects.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportReducers.cs
  Apps/Admin/Client/Store/Tag/TagEffects.cs
  Apps/Admin/Client/Store/Tag/TagReducers.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackEffects.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackReducers.cs
  Apps/Admin/Client/Store/VaccineCard/VaccineCardEffects.cs
  Apps/Admin/Client/Store/VaccineCard/VaccineCardReducers.cs
  Apps/Admin/Server/Services/AgentAccessService.cs
  Apps/Common/src/AspNetConfiguration/Modules/Db.cs
  Apps/Common/test/unit/CacheProviders/DistributedCacheProviderTests.cs
  Apps/Common/test/unit/CacheProviders/MemoryCacheProviderTests.cs
  Apps/CommonData/src/Utils/AddressUtility.cs
  Apps/Directory.Build.props
  Apps/JobScheduler/src/Listeners/BannerListener.cs
  Apps/Patient/test/unit/Services/PatientDataServiceTests.cs
  Apps/PatientDataAccess/test/unit/PatientDataRepositoryTests.cs
Labels: ready

#5808 Fix date ranger pickers on Dashboard page AB#16493
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
Labels: bugfix, ready

#5810 Add unit tests for delegate invitation for AB#16178.
  Apps/Common/test/unit/Utils/VerificationCodeUtilityTests.cs
  Apps/CommonData/src/Validations/EmailValidator.cs
  Apps/CommonData/src/Validations/ExpiryDateValidator.cs
  Apps/CommonData/test/unit/CommonDataTests.csproj
  Apps/CommonData/test/unit/Validations/EmailValidatorTests.cs
  Apps/CommonData/test/unit/Validations/ExpiryDateValidatorTests.cs
  Apps/GatewayApi/src/Services/DelegateService.cs
  Apps/GatewayApi/src/Validations/CreateDelegateInvitationRequestValidator.cs
  Apps/GatewayApi/src/appsettings.json
  Apps/GatewayApi/test/unit/Services.Test/DelegateServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Utils/MapperUtil.cs
  Apps/GatewayApi/test/unit/Validations/CreateDelegateInvitationValidatorTests.cs
Labels: enhancement, .NET, unit tests, ready

#5815 Fix issues on Admin patient details page AB#16494
  Apps/Admin/Client/Components/Details/AccountTab.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
Labels: bugfix, ready

#5816 Fix functional test configuration overriding AB#16506
  Apps/WebClient/src/ClientApp/vite.config.ts
  Testing/functional/tests/cypress.config.js
  Testing/functional/tests/cypress/support/commands.js
Labels: bugfix, ready

#5818 Refactor DelegateInvitation to Delegation
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/CommonData/src/Constants/DelegationStatus.cs
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Delegates/DbDelegateInvitationDelegate.cs
  Apps/Database/src/Delegates/DbDelegationDelegate.cs
  Apps/Database/src/Delegates/IDelegateInvitationDelegate.cs
  Apps/Database/src/Delegates/IDelegationDelegate.cs
  Apps/Database/src/Migrations/20231122204954_CreateDelegation.Designer.cs
  Apps/Database/src/Migrations/20231122204954_CreateDelegation.cs
  Apps/Database/src/Migrations/GatewayDbContextModelSnapshot.cs
  Apps/Database/src/Models/Delegation.cs
  Apps/Database/src/Models/DelegationStatusCode.cs
  Apps/Database/src/Models/ResourceDelegate.cs
  Apps/GatewayApi/src/Controllers/DelegateController.cs
  Apps/GatewayApi/src/MapProfiles/DelegationProfile.cs
  Apps/GatewayApi/src/Models/CreateDelegationRequest.cs
  Apps/GatewayApi/src/Services/DelegateService.cs
  Apps/GatewayApi/src/Services/IDelegateService.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/src/Validations/CreateDelegationRequestValidator.cs
  Apps/GatewayApi/test/unit/Services.Test/DelegateServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/Utils/MapperUtil.cs
  Apps/GatewayApi/test/unit/Validations/CreateDelegationValidatorTests.cs
Labels: enhancement, .NET, unit tests, ready

#5820 Fix functional test issues AB#16508 AB#16509 AB#16510
  Apps/Admin/Tests/Functional/cypress/integration/e2e/reports.cy.js
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/support/commands.js
Labels: bugfix, functional tests, ready

#5830 Send email on create delegation for AB#16185
  Apps/Common/src/AspNetConfiguration/Modules/DataProtection.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Constants/EmailTemplateName.cs
  Apps/Common/src/Constants/EmailTemplateVariable.cs
  Apps/Common/src/Services/HttpRequestService.cs
  Apps/Common/src/Services/IHttpRequestService.cs
  Apps/Common/test/unit/Services/HttpRequestServiceTests.cs
  Apps/Database/src/Assets/docs/CreateDelegationInvite.html
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Database.csproj
  Apps/Database/src/Migrations/20231127231128_CreateDelegation.Designer.cs
  Apps/Database/src/Migrations/20231127231128_CreateDelegation.cs
  Apps/Database/src/Migrations/GatewayDbContextModelSnapshot.cs
  Apps/GatewayApi/src/Services/DelegateService.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/src/appsettings.json
  Apps/GatewayApi/test/unit/Services.Test/DelegateServiceTests.cs
  Apps/JobScheduler/src/appsettings.Development.json
  Apps/JobScheduler/src/appsettings.hgdev.json
Labels: enhancement, .NET, unit tests, ready

#5802 Add sharing view and dialog for AB#16182
  Apps/WebClient/src/ClientApp/src/components/common/BreadcrumbComponent.vue
  Apps/WebClient/src/ClientApp/src/components/common/TileComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/covid19/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/components/private/dependent/DependentManagementView.vue
  Apps/WebClient/src/ClientApp/src/components/private/dependent/DependentTimelineView.vue
  Apps/WebClient/src/ClientApp/src/components/private/dependent/legacy/LegacyDependentsView.vue
  Apps/WebClient/src/ClientApp/src/components/private/profile/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/ReportsView.vue
  Apps/WebClient/src/ClientApp/src/components/private/services/ServicesView.vue
  Apps/WebClient/src/ClientApp/src/components/private/sharing/DelegationContactStepComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/sharing/DelegationExpiryStepComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/sharing/DelegationRecordTypesStepComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/sharing/DelegationReviewStepComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/sharing/DelegationSharingCodeStepComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/sharing/DelegationWizardDialog.vue
  Apps/WebClient/src/ClientApp/src/components/private/sharing/EmptySharingPageComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/sharing/SharingView.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/UserTimelineView.vue
  Apps/WebClient/src/ClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/ClientApp/src/components/public/landing/TileComponent.vue
  Apps/WebClient/src/ClientApp/src/components/public/terms-of-service/TermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/components/site/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/delegationStatus.ts
  Apps/WebClient/src/ClientApp/src/constants/path.ts
  Apps/WebClient/src/ClientApp/src/ioc/initialization.ts
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/models/sharing/createDelegationRequest.ts
  Apps/WebClient/src/ClientApp/src/models/sharing/delegation.ts
  Apps/WebClient/src/ClientApp/src/router/index.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restDelegationService.ts
  Apps/WebClient/src/ClientApp/src/stores/delegate.ts
  Apps/WebClient/src/ClientApp/src/stores/delegation.ts
  Apps/WebClient/src/Server/Models/FeatureToggleConfiguration.cs
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/integration/e2e/sharing/owner.js
Labels: ready

#5840 Use appsettings for host instead of HttpContextAccessor for AB#16538
  Apps/CommonData/src/Models/EmailTemplateConfig.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/src/appsettings.Development.json
  Apps/GatewayApi/src/appsettings.hgdev.json
  Apps/GatewayApi/src/appsettings.hgmock.json
  Apps/GatewayApi/src/appsettings.hgpoc.json
  Apps/GatewayApi/src/appsettings.hgtest.json
  Apps/GatewayApi/src/appsettings.json
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: bugfix, .NET, ready
