Repository bcgov/healthgateway, pull requests merged in 2023-04, with the labels that each got.

#4963 Demographics for Guardian on Exports
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
Labels: bugfix, ready, UI

#4966 Add/Update functional tests for Admin add guardian for AB#15137
  Apps/Admin/Client/Components/Delegation/DelegateDialog.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/delegation.cy.js
Labels: functional tests, ready

#4967 Fix card shadows for iOS AB#15227
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardComponent.vue
Labels: bugfix, ready

#4969 UI Enhancement - dependent timeline title
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
Labels: ready, UI

#4970 Replace card buttons on dependent dashboard tab AB#15190
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardComponent.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
Labels: ready, user story, UI

#4968 Adjust page title size and remove home page subtitle AB#15277
  Apps/WebClient/src/ClientApp/src/components/shared/PageTitleComponent.vue
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
Labels: ready, UI

#4975 Add permission policy to webclient AB#15247
  Apps/Common/src/AspNetConfiguration/Modules/HttpWeb.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/appsettings.json
Labels: ready

#4977 Add loading readme and data AB#15300
  Tools/RedisLoader/README.md
  Tools/RedisLoader/data.redis
Labels: ready

#4978 Populate dependent datasets only with provided values AB#15299
  Testing/functional/tests/cypress/support/commands.js
Labels: bugfix, functional tests, ready

#4980 Enable functional tests for remaining dependent reports AB#15168
  Testing/functional/tests/cypress/integration/e2e/dependent/report.js
Labels: functional tests, ready

#4981 Tasks/15232
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/constants/commentEntryType.ts
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/featuretoggleconfig.json
Labels: ready

#4984 Fix updated by to use current user login for AB#15321
  Apps/Admin/Server/Services/DelegationService.cs
Labels: bugfix, .NET, ready

#4983 Prevent exception that hides auth failure details AB#12916
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
Labels: bugfix, ready

#4985 Web Alerts - Health Record Notifications
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
Labels: enhancement, ready, UI

#4993 Categorised Web Alert - Functional Tests
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
  Testing/functional/tests/cypress/fixtures/NotificationService/notifications.json
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
Labels: functional tests, ready

#4996 Merge Features 15239 to Dev
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
  Testing/functional/tests/cypress/fixtures/NotificationService/notifications.json
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
Labels: enhancement, ready

#4986 Add Diagnostic Imaging Timeline Components AB#15233
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/PatientDataAccess/src/Api/HealthDataEntry.cs
  Apps/PatientDataAccess/src/HealthData.cs
  Apps/PatientDataAccess/src/Mappings.cs
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/Covid19LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationRequestTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/NoteTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/models/diagnosticImagingTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
  Apps/WebClient/src/ClientApp/src/models/patientDataResponse.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientDataService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/utils.ts
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/ServicesView.vue
  Apps/WebClient/src/ClientApp/src/views/UserTimelineView.vue
Labels: ready, UI

#4998 Add reason to protect/unprotect to controller and service for AB#15256
  Apps/Admin/Server/Controllers/DelegationController.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/IDelegationService.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Database/src/Delegates/DbDelegationDelegate.cs
  Apps/Database/src/Delegates/IDelegationDelegate.cs
  Apps/Database/src/Migrations/20230412022509_CreateDependentAuditTables.Designer.cs
  Apps/Database/src/Migrations/20230412022509_CreateDependentAuditTables.cs
  Apps/Database/src/Migrations/GatewayDbContextModelSnapshot.cs
  Apps/Database/src/Models/DependentAudit.cs
  Testing/functional/tests/cypress/db/seed.sql
Labels: enhancement, .NET, unit tests, ready

#4997 Added dependent duplicate validation AB#11061
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Testing/functional/tests/cypress/integration/e2e/dependent/management.js
Labels: ready, UI

#4994 Add Functional tests for diagnostic imaging timeline AB#15234
  Apps/WebClient/src/ClientApp/src/services/restPatientDataService.ts
  Testing/functional/tests/cypress/integration/e2e/timeline/diagnosticImaging.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
Labels: ready

#5003 Update unit tests for protect/unprotect delegation for AB#15257
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Database/src/Models/DependentAudit.cs
Labels: .NET, unit tests, ready

#5004 Add diagnostic imaging to timeline AB#13917
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/PatientDataAccess/src/Api/HealthDataEntry.cs
  Apps/PatientDataAccess/src/HealthData.cs
  Apps/PatientDataAccess/src/Mappings.cs
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/Covid19LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationRequestTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/NoteTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/commentEntryType.ts
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/models/diagnosticImagingTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
  Apps/WebClient/src/ClientApp/src/models/patientDataResponse.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientDataService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/utils.ts
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/ServicesView.vue
  Apps/WebClient/src/ClientApp/src/views/UserTimelineView.vue
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/integration/e2e/timeline/diagnosticImaging.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
Labels: ready, UI

#5005 Improve test coverage for patient data access AB#15313
  Apps/PatientDataAccess/src/Api/HealthDataEntry.cs
  Apps/PatientDataAccess/src/ConfigurationExtensions.cs
  Apps/PatientDataAccess/test/unit/HealthDataJsonConverterTests.cs
  Apps/PatientDataAccess/test/unit/HealthOptionDataJsonConverterTests.cs
Labels: ready

#5007 Agent Log on Protect User Update - update front end
  Apps/Admin/Client/Api/IDelegationApi.cs
  Apps/Admin/Client/Components/Delegation/DelegationConfirmationDialog.razor
  Apps/Admin/Client/Components/Delegation/DelegationConfirmationDialog.razor.cs
  Apps/Admin/Client/Store/Delegation/DelegationActions.cs
  Apps/Admin/Client/Store/Delegation/DelegationEffects.cs
  Apps/Admin/Common/Models/ProtectDependentRequest.cs
  Apps/Admin/Common/Models/UnprotectDependentRequest.cs
  Apps/Admin/Server/Controllers/DelegationController.cs
Labels: enhancement, ready, UI

#5013 Fix Failing Cypress tests - AB#15339
  Testing/functional/tests/cypress/fixtures/PatientData/donorRegistrationNotRegistered.json
  Testing/functional/tests/cypress/fixtures/PatientData/donorRegistrationRegistered.json
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
Labels: ready

#5014 Remove tutorial component from WebClient AB#15323
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/TutorialComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/AddNoteButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/AddCommentComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/user.ts
  Apps/WebClient/src/ClientApp/src/views/DependentManagementView.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/integration/ui/user/tutorial.js
Labels: ready

#5016 Agent Log on Protect User Update - update functional tests
  Apps/Admin/Tests/Functional/cypress/integration/e2e/delegation.cy.js
Labels: functional tests, ready

#5020 Update UI for delegation change history AB#15268
  Apps/Admin/Client/Components/Delegation/DelegationChangeEntry.razor
  Apps/Admin/Client/Components/Delegation/DelegationChangeEntry.razor.cs
  Apps/Admin/Client/Components/Delegation/DependentTable.razor
  Apps/Admin/Client/Pages/DelegationPage.razor
  Apps/Admin/Client/Pages/DelegationPage.razor.cs
  Apps/Admin/Client/Store/Delegation/DelegationActions.cs
  Apps/Admin/Client/Store/Delegation/DelegationEffects.cs
  Apps/Admin/Client/Store/Delegation/DelegationReducers.cs
  Apps/Admin/Client/Store/Delegation/DelegationState.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
Labels: ready, UI

#5021 Update history after protecting/unprotecting dependent AB#15348
  Apps/Admin/Client/Api/IDelegationApi.cs
  Apps/Admin/Client/Store/Delegation/DelegationActions.cs
  Apps/Admin/Client/Store/Delegation/DelegationEffects.cs
  Apps/Admin/Client/Store/Delegation/DelegationReducers.cs
  Apps/Admin/Server/Controllers/DelegationController.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/IDelegationService.cs
Labels: ready

#5027 Change message on organ donor tile for AB#15272
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
Labels: ready, UI

#5025 Add effective expiry date validation to broadcast service for AB#12843
  Apps/Common/src/Services/BroadcastService.cs
  Apps/Common/test/unit/Services/BroadcastServiceTests.cs
  Apps/CommonData/src/Validations/BroadcastValidator.cs
  Apps/CommonData/test/unit/Validations/BroadcastValidatorTests.cs
Labels: bugfix, .NET, ready

#5028 Migrate to latest package versions AB#15026
  Apps/Common/test/unit/CacheProviders/RedisCacheProviderTests.cs
  Apps/Common/test/unit/CommonTests.csproj
  Apps/CommonData/src/Common.Data.csproj
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/src/Validations/ProtectiveWordValidator.cs
Labels: ready

#5034 Add HasTourChanged Property AB#15331
  Apps/CommonData/src/ViewModels/UserProfileModel.cs
  Apps/GatewayApi/src/Constants/TourApplicationSettings.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: ready

#5036 Fix unreliable idle detection AB#13081
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/modal/IdleComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntryDetailsComponent.vue
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/shims-vue.d.ts
  Apps/WebClient/src/ClientApp/src/utility/idleDetector.ts
  Apps/WebClient/src/ClientApp/src/utility/reliableTimer.ts
Labels: bugfix, ready

#5040 Add dismiss test to notification centre by seed PHSA data for AB#14977
  Apps/CommonData/test/unit/Validations/BroadcastValidatorTests.cs
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
  Testing/functional/tests/cypress/integration/e2e/user/notificationCentre.js
  Tools/KeyCloak/Terraform/client_hg_admin.tf
Labels: bugfix, functional tests, ready

#5044 Fix paging not appearing on old admin support page AB#15415
  Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
Labels: bugfix, ready

#5045 Fixed App.Vue so error alerts functional tests do not fail for AB#15416
  Apps/WebClient/src/ClientApp/src/app.vue
Labels: bugfix, functional tests, ready

#5035 Add components for App Tour modal AB#15325
  Apps/CommonData/src/ViewModels/UserProfileModel.cs
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/assets/images/tour/add-quicklink.png
  Apps/WebClient/src/ClientApp/src/assets/images/tour/filter-timeline.gif
  Apps/WebClient/src/ClientApp/src/components/modal/AppTourComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/models/userProfile.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
Labels: ready, UI

#5047 Update error message when adding dependent without HDID AB#15236
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
Labels: ready

#5053 Refactor EMPI Delegate and propagate through consumers (V2 pathway) - updates
  Apps/Patient/src/Services/PatientService.cs
Labels: ready

#5049 Update field appearance on add dependent modal AB#15381
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NoteEditComponent.vue
Labels: ready, UI

#5048 Replace smart apostrophe with regular apostrophe for AB#15380
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
Labels: enhancement, .NET, ready

#5054 Unit tests for PatientRepository
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/Patient/test/unit/Services/PatientServiceTests.cs
Labels: unit tests, ready

#5055 Configure Initial Slides for App Tour AB#15392
  Apps/Database/src/Migrations/20230421214103_TourChangeInitial.cs
  Apps/WebClient/src/ClientApp/src/assets/images/tour/add-quicklink.png
  Apps/WebClient/src/ClientApp/src/assets/images/tour/filter-timeline.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/mobile/app-tour-home-quick-link-mobile.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/mobile/app-tour-notifications-mobile.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/mobile/app-tour-timeline-filter-mobile.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/app-tour-home-quick-link-web.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/app-tour-notification-centre-web.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/app-tour-timeline-filter-web.gif
  Apps/WebClient/src/ClientApp/src/components/modal/AppTourComponent.vue
Labels: ready, UI

#5064 Update support page table in Admin AB#15378
  Apps/Admin/Client/Api/ISupportApi.cs
  Apps/Admin/Client/Models/ExtendedPatientSupportDetails.cs
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportActions.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportEffects.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportReducers.cs
  Apps/Admin/Client/Store/PatientSupport/PatientSupportState.cs
Labels: ready
