Repository bcgov/healthgateway, pull requests merged in 2023-02, with the labels that each got.

#4707 AdminWebClient Support Lookup Broken
  Apps/AdminWebClient/src/Server/Constants/UserQueryType.cs
  Apps/AdminWebClient/src/Server/Controllers/SupportController.cs
  Apps/AdminWebClient/src/Server/Startup.cs
Labels: bugfix, ready

#4708 Added reviewer role access to analytics page for AB#14854
  Apps/Admin/Client/Components/NavMenu.razor
  Apps/Admin/Client/Pages/AnalyticsPage.razor
Labels: enhancement, ready

#4712 Fixed date picker for Reports AB#12176, Notes AB#14864, Dependents AB#14865 and Timeline FilterAB#14866
  Apps/WebClient/src/ClientApp/src/components/DatePickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NoteEditComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
Labels: bugfix, ready, UI

#4706 Update authorization and functional tests for PHSA access AB#14650
  Apps/Common/src/AccessManagement/Authorization/Handlers/BaseFhirAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/FhirResourceAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/PersonalAccessHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/SystemDelegatedAccessHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/UserDelegatedAccessHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Policy/SystemDelegatedPatientPolicy.cs
  Apps/Common/src/AccessManagement/Authorization/Requirements/FhirRequirement.cs
  Apps/Common/src/AccessManagement/Authorization/Requirements/GeneralFhirRequirement.cs
  Apps/Common/src/AccessManagement/Authorization/Requirements/PersonalFhirRequirement.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Common/src/Constants/FhirResource.cs
  Apps/Common/src/Constants/FhirSubjectLookupMethod.cs
  Apps/Common/test/unit/AccessManagement/Authorization/PersonalAccessHandlerTests.cs
  Apps/Common/test/unit/AccessManagement/Authorization/SystemDelegatedAccessHandlerTests.cs
  Apps/Common/test/unit/AccessManagement/Authorization/UserDelegatedAccessHandlerTests.cs
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Testing/functional/tests/cypress.config.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/comment.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/communication.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/note.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/phsa.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/userFeedback.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/userProfile.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/webClient.js
Labels: ready, user story

#4720 Prevent leaking dev credentials on functional test failure AB#14886
  Testing/functional/tests/cypress/integration/e2e/services/webClient/phsa.js
Labels: bugfix, functional tests, ready

#4713 Admin Support Last Login in PST
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
  Apps/Common/src/Services/SupportService.cs
  Apps/Common/src/Utils/MessagingVerificationMapUtils.cs
  Apps/Common/src/Utils/SupportUserMapUtils.cs
  Apps/Common/test/unit/Services/SupportServiceTests.cs
Labels: unit tests, ready, UI

#4722 Add Address to admin support for AB#14878 amd AB#14874
  Apps/Admin/Client/Components/MessageVerificationTable.razor
  Apps/Admin/Client/Components/RatingSummary.razor
  Apps/Admin/Client/Models/ExtendedSupportUser.cs
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Theme/HgTheme.cs
  Apps/Common/src/MapUtils/MessagingVerificationMapUtils.cs
  Apps/Common/src/MapUtils/SupportUserMapUtils.cs
  Apps/Common/src/Services/SupportService.cs
  Apps/Common/src/Utils/AddressUtility.cs
  Apps/CommonData/src/ViewModels/SupportUser.cs
Labels: enhancement, .NET, ready, UI

#4726 Add unit and functional tests for admin support addresses for AB#14879 and AB#14880
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-duplicate.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn.json
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Common/src/Utils/AddressUtility.cs
  Apps/Common/test/unit/Services/SupportServiceTests.cs
  Apps/Common/test/unit/Utils/AddressUtilityTests.cs
Labels: bugfix, .NET, functional tests, unit tests, ready, UI

#4728 Address section should only exist for hdid and phn query for AB#14891
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: bugfix, functional tests, ready, UI

#4732 Update functional test to look for label for AB#14895
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: bugfix, functional tests, ready

#4734 Revamp config settings - update backend
  Apps/WebClient/src/Server/Models/FeatureToggleConfiguration.cs
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/Server/Services/ConfigurationService.cs
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/featuretoggleconfig.json
Labels: ready

#4735 Refactor medication store to index by HDID AB#14894
  Apps/WebClient/src/ClientApp/src/components/FeedbackComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/ProtectiveWordComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationRequestReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/datasetState.ts
  Apps/WebClient/src/ClientApp/src/models/medicationRequest.ts
  Apps/WebClient/src/ClientApp/src/models/medicationRequestTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restSpecialAuthorityService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/request.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/util.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/statement.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/statement/util.ts
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: ready

#4736 Update immunization store for AB#14892
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/datasetState.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/immunization.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/util.ts
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: enhancement, javascript, ready

#4738 Refactor clinical document store to index by HDID AB#14893
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/NotesReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/clinicalDocument.ts
  Apps/WebClient/src/ClientApp/src/models/clinicalDocumentTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/datasetState.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restClinicalDocumentService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/clinicalDocument.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/clinicalDocument/util.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/comment.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/comment/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/immunization/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/note.ts
  Apps/WebClient/src/ClientApp/src/store/modules/note/types.ts
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
Labels: ready

#4737 Revamp config settings - refactor notification centre feature toggle
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/services/restNotificationService.ts
  Apps/WebClient/src/Server/Models/FeatureToggleConfiguration.cs
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
  Testing/functional/tests/cypress/support/commands.js
Labels: javascript, ready

#4733 Test and Prod new PHSAv2 urls to resolve AB#14280
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
  Apps/ClinicalDocument/src/appsettings.hgtest.json
  Apps/ClinicalDocument/src/appsettings.json
  Apps/GatewayApi/src/appsettings.hgtest.json
  Apps/GatewayApi/src/appsettings.json
Labels: ready

#4739 Refactor timeline view and component AB#14745
  Apps/WebClient/src/ClientApp/src/components/modal/ProtectiveWordComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/Covid19LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntryDetailsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationRequestTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/NoteTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/commentEntryType.ts
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/models/covid19LaboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/encounterTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/laboratoryOrderTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/models/medicationRequestTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/encounter/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/laboratory/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/medication/modules/request/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/types.ts
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/UserTimelineView.vue
Labels: ready

#4748 Fix action URLs not showing in dialog after saving AB#14904
  Apps/Admin/Client/Components/BroadcastDialog.razor.cs
Labels: bugfix, do not merge

#4754 modified PHSAv2 test endpoints to new urls
  Apps/Admin/Server/appsettings.hgtest.json
  Apps/Admin/Server/appsettings.json
  Apps/ClinicalDocument/src/appsettings.hgtest.json
  Apps/ClinicalDocument/src/appsettings.json
  Apps/GatewayApi/src/appsettings.hgtest.json
  Apps/GatewayApi/src/appsettings.json
Labels: ready

#4757 Revamp Config - Covid19 for AB#14885
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Testing/functional/tests/cypress/integration/e2e/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/pages/Registration.js
  Testing/functional/tests/cypress/integration/e2e/pages/breadcrumbs.js
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/pages/publicRoute.js
  Testing/functional/tests/cypress/integration/ui/pages/vaccineCard.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
Labels: ready

#4760 Update router to use new configuration for AB#14917
  Apps/WebClient/src/ClientApp/src/router.ts
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
  Testing/functional/tests/cypress/support/commands.js
Labels: javascript, functional tests, ready

#4761 Refactor cypress configureSettings command for AB#14975.
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
  Testing/functional/tests/cypress/support/commands.js
Labels: enhancement, javascript, functional tests

#4774 Fix router and functional tests for AB#14979
  Apps/WebClient/src/ClientApp/src/router.ts
  Testing/functional/tests/cypress/integration/e2e/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/pages/Registration.js
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/pages/publicRoute.js
  Testing/functional/tests/cypress/integration/ui/pages/vaccineCard.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
Labels: bugfix, enhancement, ready

#4775 Code reviews changes from AB#14979 for AB#14995.
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/pages/publicRoute.js
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
Labels: functional tests, ready

#4779 Remove client module Ticket reference from service and view for AB#14996
  Apps/WebClient/src/ClientApp/src/services/restTicketService.ts
  Apps/WebClient/src/ClientApp/src/views/waitlist/QueueView.vue
Labels: enhancement, javascript, ready

#4783 Remove modules and replace with configure setttngs for AB#15002
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedPcrTestWithTestKit.js
  Testing/functional/tests/cypress/integration/ui/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/covid19/federalProofOfVaccination.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicCovidTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/Routes.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/pages/publicRoute.js
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/report/reportFiltering.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: enhancement, javascript, functional tests, ready

#4785 Changed e2e functional tests to configure settings for AB#15003
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
  Testing/functional/tests/cypress/integration/e2e/covid19/authenticatedVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/covid19/federalProofOfVaccination.js
  Testing/functional/tests/cypress/integration/e2e/covid19/pcrTestKit.js
  Testing/functional/tests/cypress/integration/e2e/covid19/publicCovidTest.js
  Testing/functional/tests/cypress/integration/e2e/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/e2e/pages/breadcrumbs.js
  Testing/functional/tests/cypress/integration/e2e/pages/communication.js
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/e2e/resourceCentre/resourceCentre.js
  Testing/functional/tests/cypress/integration/e2e/timeline/clinicalDocument.js
  Testing/functional/tests/cypress/integration/e2e/timeline/comments.js
  Testing/functional/tests/cypress/integration/e2e/timeline/medication.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/clinicalDocument.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/encounter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderQueued.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/laboratoryOrderReport.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/medication.js
  Testing/functional/tests/cypress/integration/e2e/timeline/modals/protectiveWordModal.js
  Testing/functional/tests/cypress/integration/e2e/timeline/notes.js
  Testing/functional/tests/cypress/integration/e2e/timeline/pagination.js
  Testing/functional/tests/cypress/integration/e2e/user/acceptTermsOfService.js
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/e2e/user/feedback.js
  Testing/functional/tests/cypress/integration/e2e/user/notificationCentre.js
  Testing/functional/tests/cypress/integration/e2e/user/profile.js
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
  Testing/functional/tests/cypress/integration/e2e/user/starRating.js
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/pages/publicRoute.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/support/commands.js
  Testing/functional/tests/cypress/support/index.d.ts
Labels: ready

#4787 Add dependent timeline page AB#14548
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/Covid19LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntryDetailsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationRequestTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/NoteTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/dependent/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/dependent/dependent.ts
  Apps/WebClient/src/ClientApp/src/store/modules/dependent/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/dependent/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/dependent/types.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/store/types.ts
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/DependentsView.vue
  Apps/WebClient/src/Server/Models/FeatureToggleConfiguration.cs
  Apps/WebClient/src/featuretoggleconfig.json
Labels: ready, user story

#4790 Dependent Export Refactor
  Apps/WebClient/src/ClientApp/src/components/report/Covid19ReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/HospitalVisitReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MSPVisitsReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationRequestReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/NotesReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
Labels: ready

#4792 Add functional tests for dependent timeline AB#14747
  Testing/functional/tests/cypress/integration/e2e/timeline/comments.js
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
  Testing/functional/tests/cypress/support/commands.js
  Testing/functional/tests/cypress/support/constants.js
Labels: functional tests, ready

#4798 Add skeletons for new dependent components AB#14959
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentViewSelectorComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/utility/dependentUtil.ts
  Apps/WebClient/src/ClientApp/src/views/DependentManagementView.vue
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
Labels: ready
