Repository bcgov/healthgateway, pull requests merged in 2023-05, with the labels that each got.

#5065 Fix patient support query for dependents AB#15472
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/Database/src/Context/GatewayDbContext.cs
Labels: ready

#5067 Update functional tests for support page AB#15472
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-email-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-email.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-duplicate.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-phn.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-sms-no-results.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-sms.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/delegation.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: functional tests, ready

#5050 Task 15383: Implement message bus and outbox
  .editorconfig
  Apps/Common/src/AspNetConfiguration/Modules/MessageBus.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/CacheProviders/DistributedCacheProvider.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Messaging/AzureServiceBus.cs
  Apps/Common/src/Messaging/ConfigurationExtensions.cs
  Apps/Common/src/Messaging/HangFireOutboxStore.cs
  Apps/Common/src/Messaging/IMessageReceiver.cs
  Apps/Common/src/Messaging/IMessageSender.cs
  Apps/Common/src/Messaging/IOutboxStore.cs
  Apps/Common/src/Messaging/MessageBase.cs
  Apps/Common/src/Messaging/OutboxMessageSender.cs
  Apps/Common/src/Utils/PolymorphicJsonConverter.cs
  Apps/Common/src/Utils/SerializationHelper.cs
  Apps/Database/src/Models/MessageOutboxEntry.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/HealthGateway.sln
  Apps/JobScheduler/src/Startup.cs
  Apps/hg-start.cmd
  Testing/integration/.gitignore
  Testing/integration/tests/HangfireMessageSenderTests.cs
  Testing/integration/tests/IntegrationTests.csproj
  Testing/integration/tests/ScenarioBase.cs
  Testing/integration/tests/Usings.cs
Labels: ready

#5070 Update patient support query AB#15481
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Admin/Tests/Functional/cypress/utilities/sharedUtilities.js
  Apps/Admin/Tests/Functional/cypress/utilities/supportUtilities.js
Labels: ready

#5072 Add release note for app tour AB#15428
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#5073 removed ApiResult from patient v2
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/hg-start.cmd
  Apps/hg-watch.cmd
Labels: ready

#5077 Update add dependent to return no HDID when appropriate AB#15490
  Apps/GatewayApi/src/Services/DependentService.cs
Labels: bugfix, ready

#5075 Add intro slide and hide icon when incorrectly authenticated AB#15489
  Apps/WebClient/src/ClientApp/src/assets/images/tour/mobile/app-tour-start-mobile.png
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/app-tour-start.png
  Apps/WebClient/src/ClientApp/src/components/modal/AppTourComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Testing/functional/tests/cypress/integration/ui/user/appTour.js
Labels: ready, UI

#5078 Fix patient fixtures for AB#15491
  Testing/functional/tests/cypress/fixtures/PatientService/patientCombinedAddress.json
  Testing/functional/tests/cypress/fixtures/PatientService/patientDifferentAddress.json
  Testing/functional/tests/cypress/fixtures/PatientService/patientNoAddress.json
  Testing/functional/tests/cypress/fixtures/PatientService/patientOnlyPhysicalAddress.json
  Testing/functional/tests/cypress/fixtures/PatientService/patientOnlyPostalAddress.json
Labels: bugfix, ready

#5092 Update GatewayDbContextModelSnapshot to be in synch with latest code
  Apps/Database/src/Migrations/GatewayDbContextModelSnapshot.cs
Labels: bugfix, .NET, ready

#5095 Admin - Support User Details - update front end
  Apps/Admin/Client/Components/Common/HgField.razor
  Apps/Admin/Client/Components/Common/HgField.razor.cs
  Apps/Admin/Client/Components/Support/MessageVerificationTable.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
Labels: enhancement, ready, UI

#5081 Upgrade Hangfire to 1.8.0
  Apps/Common/src/Common.csproj
  Apps/JobScheduler/src/JobScheduler.csproj
  Apps/JobScheduler/src/Utils/SchedulerHelper.cs
Labels: bugfix, .NET, ready

#5087 Remediate critical SonarCloud bugs AB#15494
  Apps/AccountDataAccess/src/Patient/PatientRepository.cs
  Apps/Common/src/Services/CommunicationService.cs
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
Labels: bugfix, ready

#5089 Add patient to cache after calling phsa patient-identity for AB#15500
  Apps/AccountDataAccess/src/Patient/PatientRepository.cs
Labels: bugfix, .NET, ready

#5099 Merge to master for Sprint 97.1
  Apps/AccountDataAccess/src/Patient/PatientRepository.cs
  Apps/Admin/Client/Components/Common/HgField.razor
  Apps/Admin/Client/Components/Common/HgField.razor.cs
  Apps/Admin/Client/Components/Support/MessageVerificationTable.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Services/CommunicationService.cs
  Apps/Database/src/Migrations/GatewayDbContextModelSnapshot.cs
  Apps/JobScheduler/src/JobScheduler.csproj
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
  Apps/JobScheduler/src/Utils/SchedulerHelper.cs
  Apps/WebClient/src/ClientApp/src/assets/images/tour/mobile/at-filter-mobile.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/mobile/at-intro-mobile.png
  Apps/WebClient/src/ClientApp/src/assets/images/tour/mobile/at-notifications-mobile.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/mobile/at-quick-link-mobile.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/app-tour-home-quick-link-web.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/app-tour-notification-centre-web.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/app-tour-start.png
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/app-tour-timeline-filter-web.gif
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/at-filter.png
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/at-intro.png
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/at-notifications-web.png
  Apps/WebClient/src/ClientApp/src/assets/images/tour/web/at-quick-link.png
  Apps/WebClient/src/ClientApp/src/components/modal/AppTourComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
Labels: ready

#5079 Refactor UserProfileServiceMock AB#15454
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileDelegateMock.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: ready

#5096 Migrate first components to composition API AB#10562
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/DatePickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/HtmlTextAreaComponent.vue
  Apps/WebClient/src/ClientApp/src/components/LoadingComponent.vue
  Apps/WebClient/src/ClientApp/src/components/MonthYearPickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NoteEditComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/VerifySMSComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/BreadcrumbComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/Covid19ReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/HospitalVisitReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MSPVisitsReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationRequestReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/NotesReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgDateDropdownComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgDropdownComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/StatusLabelComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/CommentSectionComponent.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicCovidTestView.vue
  Apps/WebClient/src/ClientApp/src/views/PublicVaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/views/TermsOfServiceView.vue
Labels: ready

#5106 Add delegation service to patient requests AB#15466
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Patient/src/Program.cs
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
  Testing/functional/tests/cypress/support/constants.js
Labels: ready

#5108 Admin - Support User Details - functional tests
  Apps/Admin/Client/Components/Common/HgField.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid-deceased.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid-not-found.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/users-hdid-not-user.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/patient-details.cy.js
Labels: functional tests, ready

#5116 Support Details Date/Time in UTC
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
Labels: bugfix, ready, UI

#5122 Update components to composition API (Group 1) AB#15552
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/models/vaccineRecordState.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/util.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/vaccinationStatus.ts
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#5125 Resolve vue-router integration with composition API AB#15580
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
Labels: ready

#5124 Improve Common test coverage AB#15493
  Apps/Common/src/Auditing/RedisAuditLogger.cs
  Apps/Common/src/Models/BcMailPlusResponse.cs
  Apps/Common/src/Models/ContentSecurityPolicyConfig.cs
  Apps/Common/src/Models/NotificationSettingsConfig.cs
  Apps/Common/src/Models/NotificationSettingsResponse.cs
  Apps/Common/src/Utils/Odr/OdrAuthorizationHandler.cs
  Apps/Common/src/Utils/Phsa/AuthHeaderHandler.cs
  Apps/Common/src/Utils/StaticAuthHeaderHandler.cs
  Apps/Common/test/unit/CacheProviders/MemoryCacheProviderTests.cs
  Apps/Common/test/unit/CacheProviders/RedisCacheProviderTests.cs
  Apps/Common/test/unit/Converters/DateTimeConverterTests.cs
  Apps/Common/test/unit/Utils/SerializationHelperTests.cs
Labels: unit tests, ready

#5130 Add and fix unit tests for AB#15564
  Apps/AccountDataAccess/src/Patient/PatientRepository.cs
  Apps/AccountDataAccess/test/unit/AuditRepositoryTests.cs
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/HdidAllStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/HdidEmpiStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/HdidPhsaStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/PhnEmpiStrategyTests.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/Common/test/unit/Utils/SerializationHelperTests.cs
Labels: .NET, unit tests, ready

#5137 Hotfix merge to master
  Apps/Common/src/Models/NotificationSettingsResponse.cs
Labels: ready

#5138 Fix migration down when moving data from AgentAudit back to DependentAudit
  Apps/Database/src/Migrations/20230508204917_CreateBlockedAccessTable.cs
Labels: bugfix, .NET, ready

#5140 Fix sonar issues for AB#15589.
  Apps/AdminWebClient/src/ClientApp/src/components/core/Address.vue
  Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
Labels: bugfix, ready

#5145 Add organ donor registration link text for AB#15569
  Apps/Patient/src/Mappings/OrganDonorRegistrationProfile.cs
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/Patient/test/unit/Mappings/OrganDonorRegistrationProfileTests.cs
  Apps/Patient/test/unit/Services/PatientDataServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/models/patientDataResponse.ts
  Testing/functional/tests/cypress/integration/e2e/services/organDonorDetailsCard.js
Labels: .NET, functional tests, unit tests, ready, UI

#5148 Add organ donor tile message for AB#15613
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
Labels: ready, UI

#5149 Update components to composition API (Group 3) AB#15554
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/components/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/FeedbackComponent.vue
  Apps/WebClient/src/ClientApp/src/components/LoadingComponent.vue
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ResourceCentreComponent.vue
  Apps/WebClient/src/ClientApp/src/components/TooManyRequestsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/VaccineCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/IdleComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/BreadcrumbComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/Covid19ReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgDateDropdownComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgTimeDropdownComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/PageTitleComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/AddNoteButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/CommentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/CommentSectionComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationRequestTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/dateWrapper.ts
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/LogoutCompleteView.vue
  Apps/WebClient/src/ClientApp/src/views/PcrTestView.vue
  Apps/WebClient/src/ClientApp/src/views/TermsOfServiceView.vue
  Apps/WebClient/src/ClientApp/src/views/UserTimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/ValidateEmailView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/IdirLoggedInView.vue
Labels: ready

#5152 Add DataAccess Section to details page
  Apps/Admin/Client/Api/ISupportApi.cs
  Apps/Admin/Client/Components/AgentAudit/AgentAuditHistory.razor
  Apps/Admin/Client/Components/AgentAudit/AgentAuditHistory.razor.cs
  Apps/Admin/Client/Components/AgentAudit/AuditReasonDialog.razor
  Apps/Admin/Client/Components/AgentAudit/AuditReasonDialog.razor.cs
  Apps/Admin/Client/Components/Delegation/DelegationConfirmationDialog.razor.cs
  Apps/Admin/Client/Components/Delegation/DependentTable.razor.cs
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor.cs
  Apps/Admin/Client/Pages/DelegationPage.razor.cs
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Client/Store/BaseAgentAuditAction.cs
  Apps/Admin/Client/Store/Delegation/DelegationActions.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsActions.cs
Labels: ready, UI

#5162 Added protect/unprotect change feed events
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/IDelegationService.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Common/src/Models/Events/DependentProtectionAddedEvent.cs
  Apps/Common/src/Models/Events/DependentProtectionRemovedEvent.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/appsettings.Development.json
  Apps/GatewayApi/src/appsettings.json
  Apps/GatewayApi/test/unit/Controllers.Test/DependentControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/PhsaControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Testing/integration/tests/Dependents/AdminApiDependentTests.cs
  Testing/integration/tests/Dependents/GatewayApiDependentTests.cs
  Testing/integration/tests/Infrastructure/MessagingTests.cs
  Testing/integration/tests/IntegrationTests.csproj
  Testing/integration/tests/ScenarioBase.cs
Labels: ready

#5163 Functional tests for Admin BlockAccess AB#15412
  Apps/Admin/Client/Components/AgentAudit/AgentAuditHistory.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
Labels: ready

#5166 Fixed unused variable warning for AccountDataAccess unit tests for AB#15642
  Apps/AccountDataAccess/test/unit/Strategy/HdidPhsaStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/PhnEmpiStrategyTests.cs
Labels: bugfix, ready

#5153 Update UI Frameworks - Group 6: Many Small Files
  Apps/WebClient/src/ClientApp/src/components/MonthYearPickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/ReleaseNoteComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/ProtectiveWordComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/HospitalVisitReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/AddCommentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ImmunizationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/NoteTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/medicationRequestTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/views/LogoutView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/AppErrorView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/UnauthorizedView.vue
  Apps/WebClient/src/ClientApp/src/views/waitlist/QueueView.vue
Labels: ready

#5170 Add "Clear" Button to Support Lookup
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: functional tests, ready, UI

#5171 Update delegation dialog test ids AB#15644
  Apps/Admin/Tests/Functional/cypress/integration/e2e/delegation.cy.js
Labels: functional tests, ready

#5172 Display pharmacist assessments on timeline AB#15597 AB#15598
  Apps/Medication/src/Models/MedicationSummary.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/medicationSummary.ts
  Apps/WebClient/src/ClientApp/src/models/medicationTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/utility/phoneUtil.ts
  Testing/functional/tests/cypress/fixtures/MedicationService/medicationStatement.json
  Testing/functional/tests/cypress/fixtures/Report/medicationStatementUnSorted.json
  Testing/functional/tests/cypress/integration/e2e/timeline/medication.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/medication.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/medication.js
Labels: functional tests, ready, UI

#5173 Diagnostic Imaging Status Updates
  Apps/Patient/src/Mappings/DiagnosticImagingExamProfile.cs
  Apps/Patient/src/Models/DiagnosticImagingStatus.cs
  Apps/Patient/test/unit/Services/PatientDataServiceTests.cs
Labels: ready, UI

#5186 Remove procedure description from DI timeline entry AB#15651
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/diagnosticImaging.js
Labels: functional tests, ready

#5187 Fix dependent special authority related functional tests for AB#15652
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/integration/e2e/dependent/report.js
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
Labels: functional tests, ready

#5189 Fix admin dashboard functional test for AB#15654
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
Labels: functional tests, ready

#5178 Admin COVID Treatment Update - update component text
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
  Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/OptionDetails.vue
Labels: ready, UI

#5188 Refine Agent Audit History AB#15647
  Apps/Admin/Client/Components/AgentAudit/AgentAuditHistory.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
Labels: ready, UI

#5179 Group 5 - Many Small file conversion to Composition API AB#15556
  Apps/WebClient/src/ClientApp/src/components/CommunicationComponent.vue
  Apps/WebClient/src/ClientApp/src/components/MultiSelectComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentViewSelectorComponent.vue
  Apps/WebClient/src/ClientApp/src/components/interfaces/MultiSelectComponent.ts
  Apps/WebClient/src/ClientApp/src/components/modal/AppTourComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/FooterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationRequestReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/NotesReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgIconComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntryDetailsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/LaboratoryOrderTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/MedicationTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
  Apps/WebClient/src/ClientApp/src/views/ReportsView.vue
  Apps/WebClient/src/ClientApp/src/views/ServicesView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/NotFoundView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/PatientRetrievalErrorView.vue
  Testing/functional/tests/cypress/integration/ui/timeline/menu.js
Labels: ready, do not merge

#5194 Update components to composition API (Group 2) AB#15553
  Apps/HealthGateway.code-workspace
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntryDetailsComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/entryType.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/ClientApp/src/views/LandingView.vue
Labels: ready
