Repository bcgov/healthgateway, pull requests merged in 2023-03, with the labels that each got.

#4799 Dependent Timeline Navigation - Added back arrow button to return to dependents page
  Apps/WebClient/src/ClientApp/src/components/shared/PageTitleComponent.vue
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
Labels: ready, UI

#4800 Fix sorting on broadcast and communication tables and admin functional tests for AB#15009 and AB#15012
  Apps/Admin/Client/Components/BroadcastsTable.razor
  Apps/Admin/Client/Components/BroadcastsTable.razor.cs
  Apps/Admin/Client/Components/CommunicationsTable.razor
  Apps/Admin/Client/Components/CommunicationsTable.razor.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/analytics.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
Labels: bugfix, functional tests, ready

#4803 Bug: The same quick links are added multiple times
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
Labels: bugfix, functional tests, ready

#4804 Update dependent dashboard tab component for AB#14961.
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardButtonComponent.vue
Labels: enhancement, ready, UI

#4801 Dependent Timeline Navigation - functional test
  Apps/WebClient/src/ClientApp/src/views/DependentTimelineView.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
Labels: functional tests, ready

#4806 PHSA URL changes to resolve AB#15023
  Apps/ClinicalDocument/src/Api/IClinicalDocumentsApi.cs
  Apps/ClinicalDocument/src/Services/ClinicalDocumentService.cs
  Apps/ClinicalDocument/test/unit/Services/ClinicalDocumentServiceTests.cs
  Apps/GatewayApi/src/Api/IWebAlertApi.cs
  Apps/GatewayApi/src/Services/WebAlertService.cs
  Apps/GatewayApi/test/unit/Services.Test/WebAlertServiceTests.cs
Labels: ready

#4807 Update card appearance on dependent dashboard tab AB#15052
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardButtonComponent.vue
Labels: ready, UI

#4811 Add and populate total delegate count in DependentModel AB#15029
  Apps/Database/src/Delegates/DbResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IResourceDelegateDelegate.cs
  Apps/Database/src/Models/ResourceDelegate.cs
  Apps/GatewayApi/src/Controllers/DependentController.cs
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/GatewayApi/src/MapUtils/DependentMapUtils.cs
  Apps/GatewayApi/src/Models/DependentModel.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/IDependentService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/DependentControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/PhsaControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
Labels: ready

#4812 Updates roles for pulling System Analytics for AB#15043
  Apps/Admin/Server/Controllers/CsvExportController.cs
Labels: bugfix, ready

#4810 Create functional tests for dependent dashboard management for AB#14960.
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Testing/functional/tests/cypress/integration/e2e/user/dependents/dashboard.js
Labels: functional tests, ready

#4814 Fix command so laboratoryOrder functional test can succeed for AB@15070
  Testing/functional/tests/cypress/support/commands.js
Labels: functional tests, ready

#4815 Correct Phone validation for empty values AB#14983
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/src/Services/UserSmsService.cs
  Apps/GatewayApi/src/Validations/UserProfileValidator.cs
  Apps/GatewayApi/test/unit/Validations/UserProfileValidatorTests.cs
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: ready

#4813 Show no records found for report export on mobile for AB#15048
  Apps/WebClient/src/ClientApp/src/components/report/Covid19ReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/HospitalVisitReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MSPVisitsReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationRequestReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/NotesReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
Labels: bugfix, ready, UI

#4823 Fix functional tests for Reports for AB#15076
  Apps/WebClient/src/ClientApp/src/components/report/Covid19ReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/HospitalVisitReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MSPVisitsReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationRequestReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/NotesReportComponent.vue
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
Labels: functional tests, ready

#4825 Add profile tab to dependent management page AB#15030
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentProfileTabComponent.vue
  Apps/WebClient/src/ClientApp/src/models/dependent.ts
Labels: ready, UI

#4834 Fix SMS related functional tests for AB#15037.
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: bugfix, functional tests, ready

#4835 Fix SMS related functional test failures for AB#15037
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfile.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileSMSVerified.json
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: bugfix, functional tests, ready

#4824 Dependent DOB Picker - Future
  Apps/CommonData/src/Validations/DateOfBirthValidator.cs
  Apps/CommonData/test/unit/Validations/DateOfBirthValidatorTests.cs
  Apps/GatewayApi/src/Validations/AddDependentRequestValidator.cs
  Apps/WebClient/src/ClientApp/src/components/DatePickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
Labels: bugfix, unit tests, ready, UI

#4833 Update Release Notes - Sprint 6
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#4836 Add functional tests for new dependent profile tab AB#15031
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentCardComponent.vue
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/dependent/management.js
  Testing/functional/tests/cypress/integration/e2e/dependent/profile.js
  Testing/functional/tests/cypress/support/functions/dependent.js
Labels: functional tests, ready

#4837 Add new dependent profile tab AB#14584
  Apps/Database/src/Delegates/DbResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IResourceDelegateDelegate.cs
  Apps/Database/src/Models/ResourceDelegate.cs
  Apps/GatewayApi/src/Controllers/DependentController.cs
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/GatewayApi/src/MapUtils/DependentMapUtils.cs
  Apps/GatewayApi/src/Models/DependentModel.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/IDependentService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/DependentControllerTests.cs
  Apps/GatewayApi/test/unit/Controllers.Test/PhsaControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentProfileTabComponent.vue
  Apps/WebClient/src/ClientApp/src/models/dependent.ts
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/dependent/management.js
  Testing/functional/tests/cypress/integration/e2e/dependent/profile.js
  Testing/functional/tests/cypress/support/functions/dependent.js
Labels: ready, user story

#4839 Resolve Vue warning in DatePickerComponent AB#15087
  Apps/WebClient/src/ClientApp/src/components/DatePickerComponent.vue
Labels: bugfix, ready

#4844 Add organ donor registration tests AB#15059
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Testing/functional/tests/cypress/integration/e2e/user/organDonorCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/services/servicesTestConstants.js
  Testing/functional/tests/cypress/integration/ui/services/view.js
Labels: ready

#4845 Update icons for timeline and export records pages AB#15065
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
Labels: ready, UI

#4846 Add spacing between timeline card title and date AB#15066
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EntrycardTimelineComponent.vue
Labels: ready, UI

#4849 Prevent scroll on mobile when menu open AB#15068
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
Labels: ready, UI

#4850 Fix feedback review admin functional tests for AB#15111.
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
Labels: bugfix, functional tests, ready

#4851 Replace Material icons with Font Awesome icons AB#15067
  Apps/Admin/Client/Components/BroadcastsTable.razor
  Apps/Admin/Client/Components/CommunicationsTable.razor
  Apps/Admin/Client/Components/NavMenu.razor
  Apps/Admin/Client/Components/RatingSummary.razor
  Apps/Admin/Client/Layouts/MainLayout.razor
  Apps/Admin/Client/Pages/AgentAccessPage.razor
  Apps/Admin/Client/Pages/AnalyticsPage.razor
  Apps/Admin/Client/Pages/CommunicationsPage.razor
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/Showcase/Forms.razor
  Apps/Admin/Client/Pages/Showcase/LinksAndButtons.razor
  Apps/Admin/Client/Pages/Showcase/ToolBar.razor
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/wwwroot/index.html
  Apps/Admin/Server/appsettings.json
Labels: ready, UI

#4848 Add Organ Donor Registration Card to homepage AB#14572
  Apps/WebClient/src/ClientApp/src/assets/images/services/odr-logo.svg
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/serviceName.ts
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/utility/configUtil.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/Server/Models/FeatureToggleConfiguration.cs
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/integration/e2e/user/organDonorCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/services/servicesTestConstants.js
  Testing/functional/tests/cypress/integration/ui/services/view.js
Labels: ready

#4855 Check services.services to exist AB#15119
  Apps/WebClient/src/ClientApp/src/utility/configUtil.ts
Labels: ready

#4852 Add account created date time to support query result for AB#15064.
  Apps/Admin/Client/Models/ExtendedSupportUser.cs
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/wwwroot/appsettings.json
  Apps/Common/src/MapProfiles/UserProfileProfile.cs
  Apps/Common/src/MapUtils/SupportUserMapUtils.cs
  Apps/Common/src/Services/SupportService.cs
  Apps/CommonData/src/ViewModels/SupportUser.cs
Labels: enhancement, ready, UI

#4858 Add cypress config setup for services AB#15120
  Testing/functional/tests/cypress/integration/e2e/user/organDonorCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/services/view.js
  Testing/functional/tests/cypress/support/commands.js
Labels: ready

#4865 Update file ID for clinical document file download test AB#15126
  Testing/functional/tests/cypress/integration/e2e/services/clinicalDocument.js
Labels: bugfix, ready

#4866 Rename PatientData to Patient AB#15127
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/models/patient.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/user.ts
  Apps/WebClient/src/ClientApp/src/views/ProfileView.vue
Labels: ready

#4864 Update name Organ Donor quick link control AB#15123
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
Labels: ready, UI

#4868 Dependent PHN Lookup
  Apps/Admin/Common/Constants/DelegationStatus.cs
  Apps/Admin/Common/Models/DelegateInfo.cs
  Apps/Admin/Common/Models/DelegationResponse.cs
  Apps/Admin/Common/Models/DependentInfo.cs
  Apps/Admin/Server/Controllers/DelegationController.cs
  Apps/Admin/Server/MapProfiles/DelegateInfoProfile.cs
  Apps/Admin/Server/MapProfiles/DependentInfoProfile.cs
  Apps/Admin/Server/Models/CovidSupport/MailDocumentRequest.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/IDelegationService.cs
  Apps/Admin/Server/Validations/DelegationValidator.cs
  Apps/Admin/Server/appsettings.json
  Apps/AdminWebClient/src/Server/Models/CovidSupport/MailDocumentRequest.cs
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/src/Delegates/IVaccineProofDelegate.cs
  Apps/Common/src/Delegates/VaccineProofDelegate.cs
  Apps/Common/src/Models/PatientModel.cs
  Apps/Common/src/Utils/AddressUtility.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/Common/test/unit/Delegates/VaccineProofDelegateTests.cs
  Apps/Common/test/unit/Utils/AddressUtilityTests.cs
  Apps/CommonData/src/Models/Address.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/src/Models/PatientModelV2.cs
  Apps/Patient/test/unit/Controllers/PatientControllerTests.cs
  Apps/Patient/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Testing/functional/tests/cypress/db/seed.sql
Labels: enhancement, .NET, ready

#4878 Add Blazor store and Refit API for delegation lookup AB#15080
  Apps/Admin/Client/Api/IDelegationApi.cs
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/Store/Delegation/DelegationActions.cs
  Apps/Admin/Client/Store/Delegation/DelegationEffects.cs
  Apps/Admin/Client/Store/Delegation/DelegationReducers.cs
  Apps/Admin/Client/Store/Delegation/DelegationState.cs
  Apps/Admin/Common/Models/DelegationInfo.cs
  Apps/Admin/Server/Controllers/DelegationController.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/IDelegationService.cs
Labels: ready

#4877 Add patientData store AB#15060
  Apps/WebClient/src/ClientApp/src/constants/serviceCodes.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientDataService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/patientData.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/utils.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/utility/configUtil.ts
  Apps/WebClient/src/ClientApp/tsconfig.json
Labels: ready

#4881 Dependent PHN Lookup - Update error handling and add unit tests
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Admin/Tests/Utils/MapperUtil.cs
Labels: unit tests, ready

#4884 Admin Dashboard - Analytics User
  Apps/Admin/Client/Authorization/Roles.cs
  Apps/Admin/Client/Components/AgentAccessDialog.razor.cs
  Apps/Admin/Client/Components/NavMenu.razor
  Apps/Admin/Client/Layouts/MainLayout.razor
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/IndexPage.razor
  Apps/Admin/Client/Pages/IndexPage.razor.cs
  Apps/Admin/Client/Pages/UserInfoPage.razor
  Apps/Admin/Common/Constants/IdentityAccessRole.cs
  Apps/Admin/Server/Controllers/DashboardController.cs
Labels: enhancement, ready

#4854 Authorise delegate special authority requests AB#15085
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Medication/src/Startup.cs
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
Labels: ready, UI

#4890 Admin Dashboard - Analytics User - functional tests
  Apps/Admin/Tests/Functional/cypress/integration/e2e/agentaccess.cy.js
Labels: functional tests, ready

#4853 Add medications to Dependent Timelines AB#15083
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
Labels: ready, UI

#4887 Add organ details card to front end AB#15061
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientDataService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/types.ts
  Apps/WebClient/src/ClientApp/src/views/ServicesView.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
Labels: ready, UI

#4898 Add functional tests for delegation page AB#15082
  Apps/Admin/Client/Components/Delegation/DelegateTable.razor
  Apps/Admin/Client/Components/Delegation/DependentTable.razor
  Apps/Admin/Tests/Functional/cypress/integration/e2e/delegation.cy.js
Labels: functional tests, ready

#4899 Fix failing dependent medication timeline tests AB#15180
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
Labels: functional tests, ready

#4892 Add cypress ui Organ Donor Card tests AB#15062
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Testing/functional/tests/cypress/fixtures/PatientData/donorRegistrationNotRegistered.json
  Testing/functional/tests/cypress/fixtures/PatientData/donorRegistrationRegistered.json
  Testing/functional/tests/cypress/integration/ui/services/organDonorRegistration.js
Labels: waiting

#4863 Add delegated health visits to dependents timeline AB#15084
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
Labels: ready, UI

#4900 Add organ donor registration card to services page AB#14902
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/errorType.ts
  Apps/WebClient/src/ClientApp/src/constants/serviceCodes.ts
  Apps/WebClient/src/ClientApp/src/main.ts
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.config.ts
  Apps/WebClient/src/ClientApp/src/plugins/inversify.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restPatientDataService.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/patientData.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/patientData/utils.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/utility/configUtil.ts
  Apps/WebClient/src/ClientApp/src/views/ServicesView.vue
  Apps/WebClient/src/ClientApp/tsconfig.json
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/tests/cypress/fixtures/PatientData/donorRegistrationNotRegistered.json
  Testing/functional/tests/cypress/fixtures/PatientData/donorRegistrationRegistered.json
  Testing/functional/tests/cypress/integration/ui/services/organDonorRegistration.js
Labels: ready, user story

#4912 Change Snow Plow Event Tracker on Clin Docs
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/ClinicalDocumentTimelineComponent.vue
Labels: ready

#4901 Specify JSON converters for enums via attribute AB#15186
  Apps/Patient/src/Constants/PatientDataType.cs
  Apps/Patient/src/Program.cs
Labels: bugfix, ready

#4902 Add PatientData endpoints for remaining environments AB#15192
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
Labels: bugfix, ready

#4913 Update release notes - 2023.03.16
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#4914 Correct base64 to byte array AB#15203
  Apps/PatientDataAccess/src/PatientDataRepository.cs
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/models/patientData.ts
Labels: ready

#4916 Fix too many requests alerts functional tests for AB#15200
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
Labels: bugfix, functional tests, ready

#4917 Add Base64 conversion test AB#15208
  Apps/PatientDataAccess/test/unit/PatientDataRepositoryTests.cs
Labels: ready

#4891 Implement controller and service for AB#15117
  Apps/Admin/Server/Controllers/DelegationController.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/IDelegationService.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Database/src/Delegates/DbDelegationDelegate.cs
  Apps/Database/src/Delegates/IDelegationDelegate.cs
Labels: enhancement, .NET, ready

#4920 Add snow plow calls for star rating on logout for AB#15071.
  Apps/WebClient/src/ClientApp/src/components/modal/RatingComponent.vue
Labels: enhancement, ready

#4921 Change OrganDonorRegistration status mapping to custom enum value AB#15194
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/Patient/src/Services/PatientDataService.cs
  Apps/Patient/test/unit/Services/PatientDataServiceTests.cs
  Apps/PatientDataAccess/src/Api/IPatientApi.cs
  Apps/PatientDataAccess/src/DonorRegistrationStatus.cs
Labels: ready

#4922 Add disclaimer to timeline when clinical doc filter is selected for AB#15195.
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
Labels: enhancement, functional tests, ready, UI

#4924 Functional test failures - Registration tests
  Testing/functional/tests/cypress/integration/e2e/pages/Registration.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
Labels: bugfix, functional tests, ready

#4926 Job scheduler job to update dependent expiry date for AB#15173.
  Apps/JobScheduler/src/Jobs/DependentExpiryDateJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/appsettings.Development.json
  Apps/JobScheduler/src/appsettings.hgdev.json
  Apps/JobScheduler/src/appsettings.hgmock.json
  Apps/JobScheduler/src/appsettings.hgpoc.json
  Apps/JobScheduler/src/appsettings.hgtest.json
  Apps/JobScheduler/src/appsettings.json
  Testing/functional/tests/cypress/db/seed.sql
Labels: enhancement, .NET, ready

#4937 Check protected status when adding dependent AB#15171
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
Labels: ready

#4938 Update error message for adding protected dependent AB#15172
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
Labels: ready, UI

#4939 Admin protect dependent functional tests for AB#15118
  Apps/Admin/Tests/Functional/cypress/integration/e2e/delegation.cy.js
  Testing/functional/tests/cypress/db/seed.sql
Labels: functional tests, ready

#4951 Fix dashboard counts in functional test for AB#15248
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
Labels: bugfix, functional tests, ready

#4952 Fix dashboard counts in functional test for AB#15248
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
Labels: bugfix, functional tests, ready

#4936 Activate dependent functional tests AB#15241
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
Labels: ready

#4953 Add functional tests for add protected dependents for AB#15174
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
Labels: functional tests, ready

#4950 Check protected status when adding dependent AB#14827
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Apps/WebClient/src/ClientApp/src/components/modal/NewDependentComponent.vue
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
Labels: ready, user story

#4955 Unit tests for add guardian to allow list for AB#15138
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Admin/Tests/Validations/DelegatePatientValidatorTests.cs
Labels: .NET, unit tests, ready

#4956 Update store and API to retrieve and add delegates AB#15135
  Apps/Admin/Client/Api/IDelegationApi.cs
  Apps/Admin/Client/Store/Delegation/DelegationActions.cs
  Apps/Admin/Client/Store/Delegation/DelegationEffects.cs
  Apps/Admin/Client/Store/Delegation/DelegationReducers.cs
  Apps/Admin/Client/Store/Delegation/DelegationState.cs
Labels: ready

#4935 Dependent Exports - Implement export component in new tab
  Apps/WebClient/src/ClientApp/src/components/dependent/DependentCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/dependent/tabs/DependentReportsTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/Covid19ReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/HospitalVisitReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ImmunizationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/LaboratoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MSPVisitsReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/MedicationRequestReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/NotesReportComponent.vue
  Apps/WebClient/src/ClientApp/src/components/report/ReportsComponent.vue
  Apps/WebClient/src/ClientApp/src/models/dependent.ts
  Testing/functional/tests/cypress/integration/e2e/report/report.js
  Testing/functional/tests/cypress/integration/ui/report/reportSorting.js
Labels: enhancement, ready, UI

#4959 Convert emails to links AB#15250
  Apps/WebClient/src/ClientApp/src/components/ErrorCardComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/modal/NoteEditComponent.vue
  Apps/WebClient/src/ClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/views/errors/PatientRetrievalErrorView.vue
Labels: ready, UI

#4960 Make control more visible in dark mode when toggled off AB#15188
  Apps/Admin/Client/Components/Delegation/DependentTable.razor
Labels: ready, UI
