Repository bcgov/healthgateway, pull requests merged in 2023-08, with the labels that each got.

#5379 Add timeline alert for Diagnostic Imaging
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
Labels: ready, UI

#5380 Remove Facility from Diagnostic Imaging Card
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/diagnosticImaging.js
Labels: ready

#5381 Upgrade Dependent to Vue 3 for AB#15821.
  Apps/WebClient/src/NewClientApp/src/components/common/InfoPopoverComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/PrivacyStatementComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/DependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/DependentManagementView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/DependentTimelineView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/DependentViewSelectorComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentsView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/tabs/DependentProfileTabComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationForm.vue
  Apps/WebClient/src/NewClientApp/src/components/public/vaccine-card/VaccineCardView.vue
  Apps/WebClient/src/NewClientApp/src/router/index.ts
Labels: enhancement, ready, UI

#5399 merge 'dev' into 'features/15545' - AB#15903
  .editorconfig
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/appsettings.json
  Apps/ClinicalDocument/src/appsettings.json
  Apps/Encounter/src/appsettings.json
  Apps/GatewayApi/src/MapProfiles/WebAlertProfile.cs
  Apps/GatewayApi/src/appsettings.json
  Apps/Immunization/src/appsettings.json
  Apps/JobScheduler/src/appsettings.json
  Apps/Laboratory/src/appsettings.json
  Apps/Medication/src/appsettings.json
  Apps/Patient/src/Program.cs
  Apps/Patient/src/appsettings.json
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/appsettings.json
  Testing/functional/tests/cypress/integration/e2e/timeline/diagnosticImaging.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
Labels: ready

#5400 Refine UX Issues - AB#15878
  Apps/WebClient/src/NewClientApp/src/components/common/InfoTooltipComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/PageTitleComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/comment/CommentSectionComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/IdleComponent.vue
Labels: ready

#5397 Fix web alerts external/internal link and notification badge for AB#15899.
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
  Apps/WebClient/src/ClientApp/src/components/navmenu/HeaderComponent.vue
Labels: bugfix, ready

#5408 Add DevBannerComponent - AB#15920
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/site/DevBannerComponent.vue
Labels: bugfix, ready, UI

#5401 Use action type instead of is external url check for AB#15899.
  Apps/WebClient/src/ClientApp/src/components/NotificationCentreComponent.vue
Labels: bugfix, ready

#5419 Add DI Timeline Alert - AB#15886
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
Labels: ready, UI

#5418 Align e2e tests - AB#15917
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/AddDependentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/DependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/home/AppTourComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ReportsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/NoteDialogComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/comment/AddCommentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/comment/CommentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/DiagnosticImagingTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/stores/medication.ts
  Testing/functional/tests/cypress/integration/e2e/dependent/management.js
  Testing/functional/tests/cypress/integration/e2e/dependent/profile.js
  Testing/functional/tests/cypress/integration/e2e/dependent/report.js
  Testing/functional/tests/cypress/integration/e2e/pages/Registration.js
  Testing/functional/tests/cypress/integration/e2e/timeline/clinicalDocument.js
  Testing/functional/tests/cypress/integration/e2e/timeline/comments.js
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
  Testing/functional/tests/cypress/integration/e2e/timeline/diagnosticImaging.js
  Testing/functional/tests/cypress/integration/e2e/timeline/encounter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/medication.js
  Testing/functional/tests/cypress/integration/e2e/timeline/modals/protectiveWordModal.js
  Testing/functional/tests/cypress/integration/e2e/timeline/notes.js
  Testing/functional/tests/cypress/integration/e2e/timeline/pagination.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/support/commands.js
  Testing/functional/tests/cypress/support/functions/vuetify.js
Labels: functional tests, ready

#5422 Fix scroll issue in add dependent modal when in mobile mode for AB#15939
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/AddDependentComponent.vue
Labels: bugfix, ready, UI

#5424 Align - UI Pages AB#15941
  Apps/WebClient/src/NewClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/integration/ui/pages/Login.js
  Testing/functional/tests/cypress/integration/ui/pages/home.js
  Testing/functional/tests/cypress/integration/ui/pages/vaccineCard.js
Labels: functional tests, ready

#5430 Align ui report functional tests to work with Vue 3 changes for AB#15942
  Apps/WebClient/src/NewClientApp/src/components/common/HgDataTableComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ReportsComponent.vue
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
  Testing/functional/tests/cypress/integration/ui/report/reportFiltering.js
  Testing/functional/tests/cypress/support/index.d.ts
Labels: functional tests, ready

#5436 Align - UI - errors tests - AB#15940
  Apps/WebClient/src/NewClientApp/src/components/authentication/LoginCallbackView.vue
  Apps/WebClient/src/NewClientApp/src/components/error/PatientRetrievalErrorView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/AddDependentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileEmailComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/VerifySmsDialogComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/FullscreenTimelineEntryComponent.vue
  Apps/WebClient/src/NewClientApp/src/router/afterEachHook.ts
  Apps/WebClient/src/NewClientApp/src/stores/user.ts
  Testing/functional/tests/cypress/integration/e2e/dependent/report.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
Labels: functional tests, ready

#5434 Align ui services functional tests to work with Vue 3 for AB#15943
  Apps/WebClient/src/NewClientApp/src/components/common/InfoTooltipComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/SidebarComponent.vue
  Testing/functional/tests/cypress/integration/ui/services/menu.js
  Testing/functional/tests/cypress/integration/ui/services/organDonorRegistration.js
Labels: functional tests, ready, UI

#5439 Align UI timeline desktop functional tests to Vue 3 for AB#15943.
  Apps/WebClient/src/ClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/SidebarComponent.vue
  Testing/functional/tests/cypress/integration/e2e/pages/home.js
  Testing/functional/tests/cypress/integration/ui/timeline/encounter.js
  Testing/functional/tests/cypress/integration/ui/timeline/errors.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
  Testing/functional/tests/cypress/integration/ui/timeline/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/medicationrequest.js
  Testing/functional/tests/cypress/integration/ui/timeline/menu.js
  Testing/functional/tests/cypress/vue2-integration/ui/timeline/menu.js
Labels: functional tests, ready

#5440 Align UI Tests for user folder - AB#15945
  Apps/WebClient/src/NewClientApp/src/components/common/HgCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileEmailComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
  Testing/functional/tests/cypress/integration/ui/user/acceptTermsOfService.js
  Testing/functional/tests/cypress/integration/ui/user/appTour.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: functional tests, ready

#5442 Update navbar to work with hamburger menu - AB#15967
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/SidebarComponent.vue
  Apps/WebClient/src/NewClientApp/src/stores/navigation.ts
  Testing/functional/tests/cypress/integration/ui/services/menu.js
  Testing/functional/tests/cypress/integration/ui/timeline/menu.js
Labels: functional tests, ready, UI

#5443 Shrink Health Link Logo to prevent misalignment - AB#15870
  Apps/WebClient/src/NewClientApp/src/components/private/home/HomeView.vue
Labels: ready, UI

#5444 Apply proportional fixed height to carousel - AB#15869
  Apps/WebClient/src/NewClientApp/src/components/private/home/AppTourComponent.vue
Labels: ready, UI

#5448 Fix non-existent row element - AB#15869
  Apps/WebClient/src/NewClientApp/src/components/private/home/AppTourComponent.vue
Labels: ready

#5446 Align timeline mobile functional tests to Vue 3 for AB#15961.
  Apps/WebClient/src/NewClientApp/src/components/common/InfoTooltipComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/LabResultTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/MedicationTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/stores/labResult.ts
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/covid19Order.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/immunization.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/medication.js
Labels: functional tests, ready

#5447 Add mobile improvements - AB#15964
  Apps/WebClient/src/NewClientApp/src/assets/styles/main.scss
  Apps/WebClient/src/NewClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/NewClientApp/src/components/site/DevBannerComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/HeaderComponent.vue
Labels: ready, UI

#5452 Align e2e and ui notificationCentre Cypress tests to Vue 3 for AB#15985
  Testing/functional/tests/cypress/integration/e2e/user/notificationCentre.js
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
Labels: functional tests, ready

#5453 Fix dependent functional tests for Vue 3 site AB#15991
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/AddDependentComponent.vue
  Testing/functional/tests/cypress/integration/e2e/dependent/dashboard.js
  Testing/functional/tests/cypress/integration/e2e/dependent/management.js
Labels: functional tests, ready

#5456 Make site v-container fluid - AB#15972
  Apps/WebClient/src/NewClientApp/src/App.vue
Labels: ready, UI

#5455 Add scroll on timeline page change - AB#15994
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
Labels: ready, UI

#5458 Fix flakiness in notification centre functional tests for AB#15985
  Testing/functional/tests/cypress/integration/e2e/user/notificationCentre.js
  Testing/functional/tests/cypress/integration/ui/user/notificationCentre.js
Labels: functional tests, ready

#5461 Fix breaking timeline record count tests - AB#16008
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/pagination.js
  Testing/functional/tests/cypress/integration/ui/timeline/filter.js
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrder.js
Labels: functional tests, ready

#5462 Fix result popover on dependent COVID-19 table AB#16009
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentCardComponent.vue
Labels: bugfix, ready

#5463 Clean up margins and fix link styling AB#16016 AB#16006
  Apps/WebClient/src/NewClientApp/src/components/common/HtmlTextAreaComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/error/PatientRetrievalErrorView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/AddDependentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/tabs/DependentProfileTabComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/home/AddQuickLinkComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileAddressComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/registration/RegistrationView.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ReportsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/NoteDialogComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/HealthVisitTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationForm.vue
  Apps/WebClient/src/NewClientApp/src/components/site/FeedbackComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/ProtectiveWordComponent.vue
Labels: ready

#5464 Display datepicker in centre of screen on small devices AB#16011
  Apps/WebClient/src/NewClientApp/src/components/common/HgDatePickerComponent.vue
Labels: bugfix, ready

#5465 Fixed NotificationCentre swiping, unauth presence - AB#16010
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/site/NotificationCentreComponent.vue
Labels: ready

#5467 Only show paper clip icon when file id exists for AB#16019
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/DiagnosticImagingTimelineComponent.vue
Labels: bugfix, ready, UI

#5469 Log out of site if access token expires AB#16014
  Apps/WebClient/src/NewClientApp/src/components/authentication/LogoutView.vue
  Apps/WebClient/src/NewClientApp/src/stores/auth.ts
Labels: bugfix, ready

#5466 Add disabled to active link in Breadcrumb - AB#16012
  Apps/WebClient/src/NewClientApp/src/components/site/BreadcrumbComponent.vue
Labels: ready, UI

#5470 Refine sizing and styles of landing page - AB#16018
  Apps/WebClient/src/NewClientApp/src/components/public/landing/LandingView.vue
Labels: ready, UI

#5471 Update input variant to "solo" AB#15990
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/DependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileEmailComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileSmsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/comment/AddCommentComponent.vue
  Apps/WebClient/src/NewClientApp/src/plugins/vuetify.ts
Labels: bugfix, ready

#5468 move EF Migration history into gateway schema
  Apps/Common/src/AspNetConfiguration/Modules/Db.cs
  Apps/DBMaintainer/Program.cs
  Apps/Database/src/Migrations/20230508204917_CreateBlockedAccessTable.cs
  Tools/Dev/Postgres/MoveMigrationHistory.sql
  Tools/Dev/Postgres/init/01_init-to-AddDiagnosticImagingCommentEntryTypeCode.sql
Labels: do not merge

#5472 Fix readonly text fields being clearable AB#16026
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileEmailComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileSmsComponent.vue
Labels: bugfix, ready

#5473 Remove resource centre AB#16024
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/site/ResourceCentreComponent.vue
  Testing/functional/tests/cypress/integration/e2e/resourceCentre/resourceCentre.js
Labels: bugfix, ready

#5475 Fix broken tests and landing page bug - AB#16023
  Apps/WebClient/src/NewClientApp/src/components/public/landing/LandingView.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/dependent.js
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/integration/ui/pages/vaccineCard.js
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
Labels: bugfix, functional tests, ready

#5480 Refine Logout redirect code with fallback - AB#16028
  Apps/WebClient/src/NewClientApp/src/components/authentication/LogoutCompleteView.vue
  Apps/WebClient/src/NewClientApp/src/components/site/RatingComponent.vue
  Apps/WebClient/src/appsettings.json
Labels: bugfix, ready

#5484 Remove sidebar covid19 link - AB#15895
  Apps/WebClient/src/NewClientApp/src/components/site/SidebarComponent.vue
Labels: ready, UI

#5483 Remove release notes and add cms link AB#15995
  Apps/WebClient/src/NewClientApp/src/components/public/release-notes/ReleaseNoteComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/release-notes/ReleaseNotesView.vue
  Apps/WebClient/src/NewClientApp/src/components/site/FooterComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/path.ts
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Testing/functional/tests/cypress/integration/e2e/pages/breadcrumbs.js
  Testing/functional/tests/cypress/integration/e2e/pages/communication.js
  Testing/functional/tests/cypress/integration/ui/pages/breadcrumbs.js
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
Labels: functional tests, ready, UI

#5485 Vue 3 UI enhancements AB#15946
  Apps/WebClient/src/NewClientApp/src/components/common/HgButtonComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/HgIconButtonComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/InfoPopoverComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/common/InfoTooltipComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/legacy/LegacyDependentCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/dependent/tabs/DependentProfileTabComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/UserProfileManageAccountComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/profile/VerifySmsDialogComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/Covid19TestResultReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/HealthVisitReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/HospitalVisitReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ImmunizationReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/LabResultReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/MedicationReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/NoteReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/ReportsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/reports/SpecialAuthorityRequestReportComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/FilterComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/comment/AddCommentComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/HealthVisitTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/private/timeline/entry/LabResultTimelineComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/public/vaccine-card/VaccineCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/FeedbackComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/site/NotificationCentreComponent.vue
Labels: ready, UI

#5486 Fix api calls to support multi categories and return only cancer result
  Apps/Patient/src/Mappings/CancerScreeningProfile.cs
  Apps/Patient/src/Models/CancerScreeningType.cs
  Apps/Patient/src/Services/IPatientDataService.cs
  Apps/Patient/src/Services/PatientDataService.cs
  Apps/PatientDataAccess/src/Api/IPatientApi.cs
  Apps/PatientDataAccess/src/Mappings.cs
Labels: enhancement, .NET, ready

#5490 Add services section to landing page -AB#15769
  Apps/WebClient/src/NewClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/NewClientApp/src/components/public/landing/TileComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/entryType.ts
  Apps/WebClient/src/NewClientApp/src/models/infoTile.ts
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
Labels: functional tests, ready, UI

#5491 Add unit tests for getting cancer screening exams for AB#15999.
  Apps/Patient/test/unit/Services/PatientDataServiceTests.cs
  Apps/Patient/test/unit/Utils/MapperUtil.cs
  Apps/PatientDataAccess/test/unit/HealthDataJsonConverterTests.cs
  Apps/PatientDataAccess/test/unit/PatientDataRepositoryTests.cs
Labels: .NET, unit tests, ready

#5492 Update Lab Result Copy - AB#15769
  Apps/WebClient/src/NewClientApp/src/constants/entryType.ts
Labels: ready, UI

#5502 Removed unnecessary file mapping for cancer screening for AB#16063.
  Apps/PatientDataAccess/src/Mappings.cs
Labels: bugfix, .NET, ready

#5504 Provide access to Blazor admin for support users AB#15771
  Apps/Admin/Client/Components/Site/NavMenu.razor
  Apps/Admin/Client/Pages/IndexPage.razor
  Apps/Admin/Client/Pages/IndexPage.razor.cs
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsReducers.cs
  Apps/Admin/Common/Models/PatientSupportDetails.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Server/Services/ISupportService.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
Labels: ready

#5499 Show date in local timezone on Admin Feedback Review page for AB#16057.
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor.cs
Labels: bugfix, .NET, ready, UI
