Repository bcgov/healthgateway, pull requests merged in 2023-12, with the labels that each got.

#5864 Swap year of birth chart for age chart AB#16483
  Apps/Admin/Client/Api/IDashboardApi.cs
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
  Apps/Admin/Client/Store/Dashboard/DashboardActions.cs
  Apps/Admin/Client/Store/Dashboard/DashboardEffects.cs
  Apps/Admin/Client/Store/Dashboard/DashboardReducers.cs
  Apps/Admin/Client/Store/Dashboard/DashboardState.cs
  Apps/Admin/Server/Controllers/DashboardController.cs
  Apps/Admin/Server/Mappers/UserFeedbackCsvMap.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/DashboardService.cs
  Apps/Admin/Server/Services/IDashboardService.cs
  Apps/Admin/Tests/Services/CsvExportServiceTests.cs
  Apps/CommonData/src/Models/UserProfile.cs
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Delegates/DbProfileDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/Database/src/Models/UserProfileHistory.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
Labels: ready

#5865 Associate on redirect to sharing for AB#16187
  Apps/GatewayApi/src/Controllers/DelegationController.cs
  Apps/WebClient/src/ClientApp/src/components/private/sharing/SharingView.vue
  Apps/WebClient/src/ClientApp/src/plugins/extensions.ts
  Apps/WebClient/src/ClientApp/src/router/index.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restDelegationService.ts
  Apps/WebClient/src/ClientApp/src/stores/delegation.ts
Labels: ready

#5866 Removed ticket/waitlist/waitingQueue from Kong for AB#16550
  Tools/Kong/README.md
  Tools/Kong/config.tmpl
  Tools/Kong/publish.sh
  Tools/Kong/routes-gatewayapi.tmpl
Labels: ready

#5867 Associate delegation invite functional test for AB#16274
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/integration/e2e/sharing/invite.js
Labels: functional tests, ready

#5871 Disable GC Notify in Job Scheduler for local and dev envs for AB#16563.
  Apps/JobScheduler/src/appsettings.Development.json
  Apps/JobScheduler/src/appsettings.hgdev.json
Labels: bugfix, .NET, ready

#5873 Update admin dashboard AB#16401
  Apps/Admin/Client/Api/IDashboardApi.cs
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
  Apps/Admin/Client/Store/Dashboard/DashboardActions.cs
  Apps/Admin/Client/Store/Dashboard/DashboardEffects.cs
  Apps/Admin/Client/Store/Dashboard/DashboardReducers.cs
  Apps/Admin/Client/Store/Dashboard/DashboardState.cs
  Apps/Admin/Common/Models/AllTimeDashboardCounts.cs
  Apps/Admin/Server/Controllers/DashboardController.cs
  Apps/Admin/Server/Mappers/UserFeedbackCsvMap.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/DashboardService.cs
  Apps/Admin/Server/Services/IDashboardService.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/dashboard.cy.js
  Apps/Admin/Tests/Services/CsvExportServiceTests.cs
  Apps/CommonData/src/Models/UserProfile.cs
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Delegates/DbProfileDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/Database/src/Models/UserProfileHistory.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Testing/functional/tests/cypress/db/seed.sql
Labels: ready, user story

#5874 Remove ticket/waitlist from Web Client and Terraform for AB#16540
  Apps/WebClient/src/ClientApp/src/App.vue
  Apps/WebClient/src/ClientApp/src/components/public/waitlist/QueueFullView.vue
  Apps/WebClient/src/ClientApp/src/components/public/waitlist/QueueView.vue
  Apps/WebClient/src/ClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/path.ts
  Apps/WebClient/src/ClientApp/src/constants/serviceCodes.ts
  Apps/WebClient/src/ClientApp/src/constants/ticketStatus.ts
  Apps/WebClient/src/ClientApp/src/ioc/identifier.ts
  Apps/WebClient/src/ClientApp/src/ioc/initialization.ts
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/models/ticket.ts
  Apps/WebClient/src/ClientApp/src/router/beforeEachGuard.ts
  Apps/WebClient/src/ClientApp/src/router/index.ts
  Apps/WebClient/src/ClientApp/src/services/httpDelegate.ts
  Apps/WebClient/src/ClientApp/src/services/interfaces.ts
  Apps/WebClient/src/ClientApp/src/services/restAuthService.ts
  Apps/WebClient/src/ClientApp/src/services/restTicketService.ts
  Apps/WebClient/src/ClientApp/src/stores/auth.ts
  Apps/WebClient/src/ClientApp/src/stores/event.ts
  Apps/WebClient/src/ClientApp/src/stores/waitlist.ts
  Apps/WebClient/src/Server/Models/FeatureToggleConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/src/featuretoggleconfig.json
  Apps/WebClient/test/unit/Assets/featuretoggleconfig.json
  Apps/WebClient/test/unit/Services/ConfigurationServiceTests.cs
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
  Tools/KeyCloak/Terraform/client_hg_tickets.tf
  Tools/KeyCloak/Terraform/variables.tf
Labels: .NET, functional tests, ready, UI

#5875 Add public logo for emails for AB#16534
  Apps/WebClient/src/ClientApp/public/Logo.png
Labels: ready

#5876 Add check before waiting on intercept for AB#16567.
  Testing/functional/tests/cypress/integration/e2e/covid19/authenticatedVaccineCard.js
Labels: bugfix, functional tests, ready

#5877 Add wait on query to complete before attempting to edit for AB#16566
  Apps/Admin/Tests/Functional/cypress/integration/e2e/agentaccess.cy.js
Labels: bugfix, functional tests, ready

#5882 Fix ui dependents test failure for AB#16568.
  Testing/functional/tests/cypress/integration/ui/user/dependents.js
Labels: bugfix, functional tests, ready

#5884 Remove unused date parameters in analytics endpoints AB#16503
  Apps/Admin/Client/Api/IAnalyticsApi.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsActions.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsEffects.cs
  Apps/Admin/Client/Store/Analytics/BaseAnalyticsLoadAction.cs
  Apps/Admin/Server/Controllers/CsvExportController.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/ICsvExportService.cs
Labels: ready

#5889 Admin dashboard and reports move time offset from client to server side for AB#16549
  Apps/Admin/Client/Api/IAnalyticsApi.cs
  Apps/Admin/Client/Api/IDashboardApi.cs
  Apps/Admin/Client/Pages/AnalyticsPage.razor.cs
  Apps/Admin/Client/Pages/DashboardPage.razor.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsActions.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsEffects.cs
  Apps/Admin/Client/Store/Dashboard/DashboardActions.cs
  Apps/Admin/Client/Store/Dashboard/DashboardEffects.cs
  Apps/Admin/Server/Controllers/CsvExportController.cs
  Apps/Admin/Server/Controllers/DashboardController.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/DashboardService.cs
  Apps/Admin/Server/Services/ICsvExportService.cs
  Apps/Admin/Server/Services/IDashboardService.cs
  Apps/Admin/Server/Services/IInactiveUserService.cs
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Admin/Tests/Services/CsvExportServiceTests.cs
  Apps/CommonData/src/Utils/DateFormatter.cs
  Apps/CommonData/test/unit/CommonDataTests.csproj
  Apps/CommonData/test/unit/Utils/DateFormatterTests.cs
Labels: .NET, unit tests, ready

#5888 Replace outdated references to "modules" AB#16473
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Apps/WebClient/src/ClientApp/src/services/restVaccinationStatusService.ts
  Apps/WebClient/src/ClientApp/src/utility/errorTranslator.ts
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
  Testing/functional/tests/cypress/integration/e2e/dependent/management.js
  Testing/functional/tests/cypress/integration/e2e/user/dependents.js
  Testing/functional/tests/cypress/integration/e2e/user/healthConnectRegistryQuickLink.js
  Testing/functional/tests/cypress/integration/e2e/user/organDonorCardQuickLink.js
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicPcrTest.js
  Testing/functional/tests/cypress/integration/ui/covid19/publicVaccineCard.js
  Testing/functional/tests/cypress/integration/ui/pages/LandingPage.js
  Testing/functional/tests/cypress/integration/ui/pages/vaccineCard.js
  Testing/functional/tests/cypress/support/index.d.ts
Labels: ready

#5891 Make WebClient.Server async AB#16546
  Apps/WebClient/src/Server/Controllers/ConfigurationController.cs
  Apps/WebClient/src/Server/Services/ConfigurationService.cs
  Apps/WebClient/src/Server/Services/IConfigurationService.cs
  Apps/WebClient/test/unit/Services/ConfigurationServiceTests.cs
Labels: ready

#5887 Fix SonarCloud findings for AB#16539
  .editorconfig
  Apps/Admin/Client/Pages/Showcase/Chips.razor
  Apps/Admin/Client/Program.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/CsvExportService.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Common/src/CacheProviders/ICacheProvider.cs
  Apps/Common/src/Delegates/PHSA/RestTokenSwapDelegate.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/GatewayApi/src/Controllers/DependentController.cs
  Apps/GatewayApi/src/Controllers/NoteController.cs
  Apps/GatewayApi/src/Program.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/WebClient/src/ClientApp/src/components/common/InfoTooltipComponent.vue
Labels: ready

#5883 Expand email validation for AB#16520
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Validations/OptionalEmailAddressValidator.cs
  Apps/GatewayApi/test/unit/Validations/OptionalEmailAddressValidatorTests.cs
  Apps/WebClient/src/ClientApp/src/components/private/profile/UserProfileEmailComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/registration/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/constants/validationRegEx.ts
Labels: ready

#5903 Add health check and update helm for AB#16532
  Apps/Offline/nginx.conf
  Apps/Offline/src/health.html
  Tools/Helm/Charts/healthgateway/README.md
Labels: ready, helm

#5911 Change cypress Url to prevent loadbalancing
  Apps/Admin/Tests/Functional/cypress.config.js
  Testing/functional/tests/cypress.config.js
Labels: functional tests, ready

#5912 Revert "Change cypress Url to prevent loadbalancing"
  Apps/Admin/Tests/Functional/cypress.config.js
  Testing/functional/tests/cypress.config.js
Labels: ready

#5915 Make Job Scheduler async
  Apps/Common/src/Jobs/IAdminFeedbackJob.cs
  Apps/Common/src/Jobs/IEmailJob.cs
  Apps/Common/src/Services/EmailQueueService.cs
  Apps/Common/src/Services/IEmailQueueService.cs
  Apps/Common/src/Services/INotificationSettingsService.cs
  Apps/Common/src/Services/NotificationSettingsService.cs
  Apps/Common/test/unit/Services/EmailQueueServiceTests.cs
  Apps/Common/test/unit/Services/NotificationSettingsServiceTests.cs
  Apps/Database/src/Delegates/DbApplicationSettingsDelegate.cs
  Apps/Database/src/Delegates/DbEmailDelegate.cs
  Apps/Database/src/Delegates/DbFeedbackDelegate.cs
  Apps/Database/src/Delegates/DbProfileDelegate.cs
  Apps/Database/src/Delegates/IApplicationSettingsDelegate.cs
  Apps/Database/src/Delegates/IEmailDelegate.cs
  Apps/Database/src/Delegates/IFeedbackDelegate.cs
  Apps/Database/src/Delegates/IUserProfileDelegate.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Services/UserFeedbackService.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/JobScheduler/src/Jobs/AdminFeedbackJob.cs
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/JobScheduler/src/Jobs/DbMigrationsJob.cs
  Apps/JobScheduler/src/Jobs/DeleteEmailJob.cs
  Apps/JobScheduler/src/Jobs/EmailJob.cs
  Apps/JobScheduler/src/Jobs/IOtherEmailJob.cs
  Apps/JobScheduler/src/Jobs/OneTimeJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/Tasks/CopyEmailToMessagingVerification.cs
  Apps/JobScheduler/src/Tasks/IOneTimeTask.cs
  Apps/JobScheduler/src/Tasks/SendValidatedUsersToPhsa.cs
  Apps/JobScheduler/src/Utils/SchedulerHelper.cs
Labels: .NET, unit tests, ready
