Repository bcgov/healthgateway, pull requests merged in 2023-01, with the labels that each got.

#4566 Remove Logic for Hospital Attending
  Apps/Encounter/src/MapProfiles/HospitalVisitModelProfile.cs
Labels: bugfix, ready

#4586 CommunicationService refactoring
  Apps/Common/src/Common.csproj
  Apps/Common/src/Services/CommunicationService.cs
  Apps/Common/test/unit/Services/CommunicationServiceTests.cs
Labels: ready

#4565 CommentService refactoring
  Apps/Database/src/Constants/CommentEntryType.cs
  Apps/Database/src/Context/GatewayDbContext.cs
  Apps/Database/src/Delegates/DbCommentDelegate.cs
  Apps/Database/src/Delegates/ICommentDelegate.cs
  Apps/GatewayApi/src/Services/CommentService.cs
  Apps/GatewayApi/src/Validations/UserCommentValidator.cs
  Apps/GatewayApi/test/unit/Services.Test/CommentServiceTests.cs
Labels: ready

#4564 LabTestKitService refactoring
  Apps/Common/src/Factories/RequestResultFactory.cs
  Apps/CommonData/src/Validations/PhnValidator.cs
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Laboratory/src/Validations/PublicLabTestKitValidator.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
Labels: ready, do not merge

#4573 UserProfileService refactoring
  Apps/Common/src/Factories/RequestResultFactory.cs
  Apps/CommonData/src/Validations/AgeRangeValidator.cs
  Apps/CommonData/src/Validations/DependentAgeValidator.cs
  Apps/CommonData/test/unit/Validations/AgeRangeValidatorTests.cs
  Apps/CommonData/test/unit/Validations/DependentAgeValidatorTests.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/GatewayApi/src/Services/IUserProfileService.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/src/Validations/AddDependentRequestValidator.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
Labels: ready

#4571 RestMedicationService refactoring
  Apps/Common/src/Factories/RequestResultFactory.cs
  Apps/CommonData/test/unit/Validations/AgeRangeValidatorTests.cs
  Apps/CommonData/test/unit/Validations/DependentAgeValidatorTests.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/Medication/src/Services/RestMedicationService.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/src/Validations/ProtectiveWordValidator.cs
  Apps/Medication/test/unit/Services/MedicationServiceTests.cs
Labels: ready

#4563 LaboratoryService refactoring
  Apps/Common/src/Converters/EnumHelper.cs
  Apps/Common/src/Factories/RequestResultFactory.cs
  Apps/Common/test/unit/Converters/EnumHelperTests.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: ready

#4595 NoteService refactoring
  Apps/GatewayApi/src/Services/NoteService.cs
Labels: ready

#4596 Resolve enum serialization issues AB#14644
  Apps/Admin/Common/Models/Communication.cs
  Apps/Admin/Server/Constants/CovidTherapyAssessmentOption.cs
  Apps/AdminWebClient/src/Server/Constants/CovidTherapyAssessmentOption.cs
  Apps/CommonData/src/Constants/CommunicationStatus.cs
  Apps/GatewayApi/src/Models/ReportRequestModel.cs
  Apps/WebClient/src/ClientApp/src/models/reportRequest.ts
Labels: bugfix, ready

#4597 Add models and controller for agent provisioning AB#14639
  Apps/Admin/Client/Authorization/Roles.cs
  Apps/Admin/Common/Admin.Common.csproj
  Apps/Admin/Common/Constants/IdentityAccessRole.cs
  Apps/Admin/Common/Constants/KeycloakIdentityProvider.cs
  Apps/Admin/Common/Models/AdminAgent.cs
  Apps/Admin/Server/Controllers/AgentAccessController.cs
  Apps/Admin/Server/Services/IAgentAccessService.cs
  Apps/Admin/Server/Services/InactiveUserService.cs
Labels: ready

#4599 Update agent access controller to latest standard AB#14660
  Apps/Admin/Server/Controllers/AgentAccessController.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/IAgentAccessService.cs
Labels: ready

#4600 Refactor Problem Details for better code coverage for AB#14661.
  Apps/Common/src/AspNetConfiguration/Modules/ExceptionHandling.cs
  Apps/Common/src/ErrorHandling/ApiProblemDetails.cs
  Apps/CommonData/src/ErrorHandling/ApiException.cs
  Apps/CommonData/src/ErrorHandling/ExceptionUtility.cs
  Apps/CommonData/src/ErrorHandling/ProblemDetails.cs
  Apps/CommonData/src/ErrorHandling/ProblemDetailsException.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Patient/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Patient/src/Program.cs
  Apps/Patient/src/Services/PatientService.cs
  Apps/Patient/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/Patient/test/unit/Services/PatientServiceTests.cs
Labels: bugfix, .NET, unit tests, ready

#4605 Fix code coverage on common data for AB#14542
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/CommonData/src/ErrorHandling/ProblemDetailsException.cs
  Apps/CommonData/src/Utils/StringManipulator.cs
  Apps/CommonData/test/unit/Utils/DateFormatterTests.cs
  Apps/CommonData/test/unit/Utils/StringManipulatorTests.cs
Labels: bugfix, unit tests, ready

#4598 Update Terraform to create a new client for AB#14646
  Tools/KeyCloak/Terraform/client_hg_tickets.tf
  Tools/KeyCloak/Terraform/idp_phsa.tf
  Tools/KeyCloak/Terraform/variables.tf
Labels: ready

#4606 Hotfix for immunization retry logic
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
Labels: ready

#4614 Back merge master->dev
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
Labels: ready

#4609 Medication protected result handling fix
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/test/unit/Services/MedicationStatementServiceTests.cs
Labels: ready

#4616 AB#14642 Fix for clinical document error
  Apps/ClinicalDocument/src/appsettings.json
  Apps/Common/src/AssemblyInfo.cs
  Apps/Common/src/Common.csproj
  Apps/GatewayApi/src/appsettings.json
Labels: ready

#4617 Add edit dialog for agent provisioning AB#14641
  Apps/Admin/Client/Components/AgentAccessDialog.razor
  Apps/Admin/Client/Components/AgentAccessDialog.razor.cs
  Apps/Admin/Client/Pages/AgentAccessPage.razor
  Apps/Admin/Client/Pages/AgentAccessPage.razor.cs
  Apps/Admin/Client/Store/AgentAccess/AgentAccessEffects.cs
  Apps/Admin/Client/Utils/AgentUtility.cs
  Apps/Admin/Common/Models/AdminAgent.cs
Labels: ready

#4615 Fix Rider warnings for AB#14677
  Apps/Admin/Client/Components/BroadcastDialog.razor.cs
  Apps/Admin/Common/Models/Communication.cs
  Apps/Admin/Server/Constants/CovidTherapyAssessmentOption.cs
  Apps/AdminWebClient/src/Server/Constants/CovidTherapyAssessmentOption.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
Labels: ready

#4620 Update inactive user report last login date time to PST for AB#14633
  Apps/Admin/Server/Converters/DateOutputConverter.cs
  Apps/Admin/Server/MapUtils/AdminUserProfileMapUtils.cs
  Apps/Admin/Server/Mappers/AdminUserProfileViewCsvMap.cs
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Admin/Server/appsettings.json
  Apps/Admin/Tests/Converters/DateOutputConverterTests.cs
  Apps/CommonData/src/Common.Data.csproj
  Apps/CommonData/src/Utils/DateFormatter.cs
  Apps/JobScheduler/src/Utils/SchedulerHelper.cs
Labels: enhancement, .NET, unit tests, ready

#4625 Update namespace for admin unit tests for AB#14521.
  Apps/Admin/Tests/Admin.Tests.csproj
  Apps/Admin/Tests/Converters/DateOutputConverterTests.cs
  Apps/Admin/Tests/Services/CsvExportServiceTests.cs
  Apps/Admin/Tests/Utils/MapperUtil.cs
Labels: bugfix, .NET, unit tests, ready

#4628 Disable CS1591 and SA1600 warnings for AB#14204
  Apps/Admin/Client/Store/Analytics/AnalyticsEffects.cs
  Apps/Admin/Client/Store/Analytics/AnalyticsReducers.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsEffects.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsReducers.cs
  Apps/Admin/Client/Store/Communications/CommunicationsEffects.cs
  Apps/Admin/Client/Store/Communications/CommunicationsReducers.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationEffects.cs
  Apps/Admin/Client/Store/Configuration/ConfigurationReducers.cs
  Apps/Admin/Client/Store/Dashboard/DashboardEffects.cs
  Apps/Admin/Client/Store/Dashboard/DashboardReducers.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationEffects.cs
  Apps/Admin/Client/Store/MessageVerification/MessageVerificationReducers.cs
  Apps/Admin/Client/Store/SupportUser/SupportUserEffects.cs
  Apps/Admin/Client/Store/SupportUser/SupportUserReducers.cs
  Apps/Admin/Client/Store/Tag/TagEffects.cs
  Apps/Admin/Client/Store/Tag/TagReducers.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackEffects.cs
  Apps/Admin/Client/Store/UserFeedback/UserFeedbackReducers.cs
  Apps/Admin/Tests/Converters/DateOutputConverterTests.cs
Labels: bugfix, .NET, ready

#4627 AB#14701 Cache refactoring
  Apps/Common/src/AspNetConfiguration/Modules/GatewayCache.cs
  Apps/Common/src/CacheProviders/DistributedCacheProvider.cs
  Apps/Common/src/CacheProviders/ICacheProvider.cs
  Apps/Common/src/CacheProviders/MemoryCacheProvider.cs
  Apps/Common/src/CacheProviders/RedisCacheProvider.cs
  Apps/Common/src/Common.csproj
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/Common/test/unit/CacheProviders/DistributedCacheProviderTests.cs
  Apps/Common/test/unit/CacheProviders/MemoryCacheProviderTests.cs
  Apps/Common/test/unit/CacheProviders/RedisCacheProviderTests.cs
  Apps/Common/test/unit/Services/CommunicationServiceTests.cs
Labels: ready

#4629 fixed compile warning as error to address AB#14705
  Apps/Medication/src/Delegates/RestMedStatementDelegate.cs
Labels: ready

#4626 Admin Agent Provisioning - create back end
  Apps/Admin/Client/Components/AgentAccessDialog.razor.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/AgentAccessService.cs
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Common/src/AccessManagement/Administration/Models/RoleRepresentation.cs
  Apps/Common/src/AccessManagement/Administration/Models/UserRepresentation.cs
  Apps/Common/src/Api/IKeycloakAdminApi.cs
  Apps/Common/src/Constants/ErrorMessages.cs
  Apps/CommonData/src/Utils/EnumUtility.cs
  Apps/CommonData/test/unit/Utils/EnumUtilityTests.cs
Labels: enhancement, ready

#4632 Display custom error when provisioning pre-existing user AB#14704
  Apps/Admin/Client/Components/AgentAccessDialog.razor
  Apps/Admin/Client/Components/AgentAccessDialog.razor.cs
  Apps/Admin/Client/Store/AgentAccess/AgentAccessEffects.cs
  Apps/Admin/Client/Utils/StoreUtility.cs
Labels: bugfix, ready

#4631 Added client IP mapping into delegate request value
  Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
Labels: bugfix, ready

#4634 added missing loaded and queued properties mapping to resolve AB#14708
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/test/unit/Services/EncounterServiceTests.cs
Labels: bugfix, ready

#4636 Fix Blazor Admin logout/login for AB#14712 and obsolete SignOutSessionStateManager for AB#14344
  Apps/Admin/Client/Layouts/MainLayout.razor
  Apps/Admin/Client/Layouts/MainLayout.razor.cs
  Apps/Admin/Client/Pages/AuthenticationPage.razor.cs
  Apps/Admin/Client/Pages/UnauthorizedPage.razor
  Apps/Admin/Client/Pages/UnauthorizedPage.razor.cs
Labels: bugfix, .NET, ready

#4644 added missing mapping of loadstate to resolve AB#14708
  Apps/Encounter/src/Delegates/RestHospitalVisitDelegate.cs
  Apps/Encounter/src/Services/EncounterService.cs
Labels: bugfix, ready

#4635 Display alert when agent search returns max number of results AB#14711
  Apps/Admin/Client/Pages/AgentAccessPage.razor
  Apps/Admin/Client/Pages/AgentAccessPage.razor.cs
Labels: bugfix, ready

#4645 default backoff value for Encounter AB#14708
  Apps/Encounter/src/appsettings.json
Labels: ready

#4647 Resolve error alert issues with dialogs AB#14718 AB#14719
  Apps/Admin/Client/Components/AgentAccessDialog.razor
  Apps/Admin/Client/Components/AgentAccessDialog.razor.cs
  Apps/Admin/Client/Components/BroadcastDialog.razor.cs
  Apps/Admin/Client/Components/CommunicationDialog.razor
  Apps/Admin/Client/Components/CommunicationDialog.razor.cs
  Apps/Admin/Client/Store/AgentAccess/AgentAccessActions.cs
  Apps/Admin/Client/Store/AgentAccess/AgentAccessReducers.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsActions.cs
  Apps/Admin/Client/Store/Broadcasts/BroadcastsReducers.cs
  Apps/Admin/Client/Store/Communications/CommunicationsActions.cs
  Apps/Admin/Client/Store/Communications/CommunicationsReducers.cs
Labels: bugfix, ready

#4646 Problem details not handling custom exception for AB#14710.
  Apps/Admin/Server/Pages/Error.cshtml
  Apps/Admin/Server/Pages/ErrorModel.cs
  Apps/Admin/Server/Program.cs
Labels: bugfix, .NET, ready

#4643 Fixed protective word hash not getting serialized properly
  Apps/Common/src/AspNetConfiguration/Modules/GatewayCache.cs
  Apps/Common/src/CacheProviders/DistributedCacheProvider.cs
  Apps/Common/src/CacheProviders/MemoryCacheProvider.cs
  Apps/Common/src/CacheProviders/RedisCacheProvider.cs
  Apps/Common/test/unit/CacheProviders/DistributedCacheProviderTests.cs
  Apps/Common/test/unit/CacheProviders/MemoryCacheProviderTests.cs
  Apps/Common/test/unit/CacheProviders/RedisCacheProviderTests.cs
Labels: bugfix, ready

#4651 Fix test failure on observer loop error by ignoring in Cypress
  Apps/Admin/Tests/Functional/cypress/support/commands.js
Labels: functional tests, ready

#4652 Replace PrimitiveRequestResult with RequestResult AB#14628
  Apps/CommonData/src/ViewModels/PrimitiveRequestResult.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/GatewayApi/src/Services/IUserEmailService.cs
  Apps/GatewayApi/src/Services/IUserSmsService.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Services/UserSmsService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserProfileControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceTests.cs
Labels: bugfix, ready

#4654 Added Dependent to Support Page for AB#14734
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/CommonData/src/Constants/UserQueryType.cs
Labels: enhancement, ready, UI

#4656 Hospital Discharge Dates Null
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/hospitalVisitTimelineEntry.ts
Labels: bugfix, ready, UI

#4624 Added Kong plugin to verify waiting queue token for AB#14509
  Tools/Kong/README.md
  Tools/Kong/config.tmpl
  Tools/Kong/routes-gatewayapi.tmpl
Labels: ready

#4657 Backend changes for AB#14643
  Apps/Admin/Client/Pages/SupportPage.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Common/src/MapProfiles/UserProfileProfile.cs
  Apps/Common/src/Services/IPatientService.cs
  Apps/Common/src/Services/ISupportService.cs
  Apps/Common/src/Services/PatientService.cs
  Apps/Common/src/Services/SupportService.cs
  Apps/Common/test/unit/Services/SupportServiceTests.cs
  Apps/CommonData/src/Utils/DateFormatter.cs
  Apps/CommonData/src/ViewModels/SupportUser.cs
  Apps/Database/src/Delegates/DbResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IResourceDelegateDelegate.cs
Labels: ready

#4665 Implement session storage on web client for AB#14733
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/timeline.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/ClientApp/vue.config.js
Labels: enhancement, ready

#4668 Immunization mapping fix for AB#14795
  Apps/Immunization/src/MapUtils/ImmunizationRecommendationMapUtils.cs
Labels: bugfix, ready

#4669 Merge pull request #4649 from bcgov/dev
  Apps/Immunization/src/MapUtils/ImmunizationRecommendationMapUtils.cs
Labels: ready

#4672 refactored hospital visits to handle no null results properly to resolve AB#14803
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/Common/src/Models/PHSA/PHSAConfig.cs
  Apps/Encounter/src/Api/IHospitalVisitApi.cs
  Apps/Encounter/src/Delegates/RestHospitalVisitDelegate.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
  Apps/Immunization/src/Api/IImmunizationApi.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
Labels: bugfix, ready

#4658 Added new controller and updated service for AB#14739
  Apps/Database/src/Delegates/DbResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IResourceDelegateDelegate.cs
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/GatewayApi/src/Models/GetDependentResponse.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/IDependentService.cs
Labels: enhancement, ready

#4671 Add guard logic for waitlist queue for AB#14781
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/waitlist.ts
Labels: enhancement, ready

#4674 Implement session storage for waitlist queue on web client for AB#14698
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/LinearTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/timeline.ts
  Apps/WebClient/src/ClientApp/src/store/modules/timeline/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/vaccinationStatus/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/types.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/waitlist.ts
  Apps/WebClient/src/ClientApp/src/store/options.ts
  Apps/WebClient/src/ClientApp/src/views/TimelineView.vue
  Apps/WebClient/src/ClientApp/vue.config.js
Labels: enhancement, ready

#4675 Fix failing waitlist functional tests for AB#14811.
  Testing/functional/tests/cypress/integration/ui/user/waitlist.js
Labels: bugfix, functional tests, ready

#4676 Fix URL path combining for ODR API AB#14812
  Apps/Common/src/AspNetConfiguration/Modules/OdrConfiguration.cs
Labels: bugfix, ready

#4677 Dependent Endpoint for PHSA - unit tests
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/GatewayApi/test/unit/Controllers.Test/PhsaControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
Labels: unit tests, ready

#4678 Updated route to protect endpoints in PhsaController for AB#14740
  Tools/Kong/routes-gatewayapi.tmpl
Labels: ready

#4679 Merge the Dependent Endpoint for PHSA feature branch to dev
  Apps/Database/src/Delegates/DbResourceDelegateDelegate.cs
  Apps/Database/src/Delegates/IResourceDelegateDelegate.cs
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/GatewayApi/src/Models/GetDependentResponse.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/IDependentService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/PhsaControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Tools/Kong/routes-gatewayapi.tmpl
Labels: enhancement, ready

#4685 Use local storage instead of session storage for AB#14821.
  Apps/WebClient/src/ClientApp/src/store/options.ts
Labels: enhancement, javascript, ready

#4689 Update hospital visit timeline card AB#14770
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/HospitalVisitTimelineComponent.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/encounter.js
  Testing/functional/tests/cypress/integration/e2e/timeline/mobile/encounter.js
Labels: ready, user story, UI
