Repository bcgov/healthgateway, pull requests merged in 2023-06, with the labels that each got.

#5195 Fix Rider Warnings for Patient Repository and Serialization Helper Tests for AB#15656
  Apps/AccountDataAccess/src/Patient/PatientRepository.cs
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/Common/test/unit/Utils/SerializationHelperTests.cs
Labels: bugfix, .NET, unit tests, ready

#5196 Set communications page date and times to PST
  Apps/Admin/Client/Components/AgentAudit/AgentAuditHistory.razor.cs
  Apps/Admin/Client/Components/Communications/BroadcastsTable.razor
  Apps/Admin/Client/Components/Communications/BroadcastsTable.razor.cs
  Apps/Admin/Client/Components/Communications/CommunicationsTable.razor
  Apps/Admin/Client/Components/Communications/CommunicationsTable.razor.cs
  Apps/Admin/Client/Models/BaseTableFluxorComponent.cs
Labels: ready

#5203 Restrict BlockAccess feature on patient details page to AdminUser AB#15662
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor.cs
  Apps/Admin/Client/Pages/PatientDetailsPage.razor
  Apps/Admin/Client/Pages/PatientDetailsPage.razor.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Tests/Functional/cypress.config.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
Labels: bugfix, ready

#5199 Update waitlist ticket check-in and release flow AB#15614
  Apps/WebClient/src/ClientApp/src/app.vue
  Apps/WebClient/src/ClientApp/src/eventbus.ts
  Apps/WebClient/src/ClientApp/src/router.ts
  Apps/WebClient/src/ClientApp/src/store/modules/auth/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/actions.ts
  Apps/WebClient/src/ClientApp/src/store/modules/waitlist/types.ts
  Apps/WebClient/src/ClientApp/src/views/LogoutView.vue
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgtest.json
Labels: ready

#5200 Fixes delete old emails for AB#14194
  Apps/Common/src/MapProfiles/MessagingVerificationProfile.cs
  Apps/Database/src/Delegates/DbEmailDelegate.cs
  Apps/Database/src/Delegates/DbProfileDelegate.cs
  Apps/JobScheduler/src/Tasks/CopyEmailToMessagingVerification.cs
  Apps/JobScheduler/src/appsettings.json
  Testing/functional/tests/cypress/db/seed.sql
Labels: bugfix, ready

#5205 Remove new password config AB#15675
  Apps/Admin/Tests/Functional/cypress.config.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
Labels: bugfix, functional tests, ready

#5207 Extend UserProfile to house blocked datasets for AB#15456
  Apps/AccountDataAccess/src/Patient/PatientRepository.cs
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/Common/src/CacheProviders/ICacheProvider.cs
  Apps/CommonData/src/ViewModels/UserProfileModel.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/PatientRepositoryMock.cs
  Apps/GatewayApi/test/unit/Services.Test/Mock/UserProfileServiceMock.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
  Apps/Patient/src/appsettings.json
Labels: .NET, unit tests, ready

#5218 Guard Dataset API Calls with BlockedAccess for AB#15457
  Apps/AccountDataAccess/src/Patient/IPatientRepository.cs
  Apps/AccountDataAccess/src/Patient/PatientRepository.cs
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/ClinicalDocument/src/ClinicalDocument.csproj
  Apps/ClinicalDocument/src/Services/ClinicalDocumentService.cs
  Apps/ClinicalDocument/src/Startup.cs
  Apps/ClinicalDocument/test/unit/Services/ClinicalDocumentServiceTests.cs
  Apps/Encounter/src/Encounter.csproj
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/src/Startup.cs
  Apps/Encounter/src/appsettings.Development.json
  Apps/Encounter/src/appsettings.hgdev.json
  Apps/Encounter/src/appsettings.hgmock.json
  Apps/Encounter/src/appsettings.hgpoc.json
  Apps/Encounter/src/appsettings.hgtest.json
  Apps/Encounter/src/appsettings.json
  Apps/Encounter/test/unit/Services/EncounterServiceTests.cs
  Apps/GatewayApi/src/Services/NoteService.cs
  Apps/GatewayApi/test/unit/Services.Test/NoteServiceTests.cs
  Apps/Immunization/src/Immunization.csproj
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/src/appsettings.Development.json
  Apps/Immunization/src/appsettings.hgdev.json
  Apps/Immunization/src/appsettings.hgmock.json
  Apps/Immunization/src/appsettings.hgpoc.json
  Apps/Immunization/src/appsettings.hgtest.json
  Apps/Immunization/src/appsettings.json
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
  Apps/Laboratory/src/Laboratory.csproj
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/src/appsettings.Development.json
  Apps/Laboratory/src/appsettings.hgdev.json
  Apps/Laboratory/src/appsettings.hgmock.json
  Apps/Laboratory/src/appsettings.hgpoc.json
  Apps/Laboratory/src/appsettings.hgtest.json
  Apps/Laboratory/src/appsettings.json
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
  Apps/Medication/src/Medication.csproj
  Apps/Medication/src/Services/MedicationRequestService.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/src/appsettings.Development.json
  Apps/Medication/src/appsettings.hgdev.json
  Apps/Medication/src/appsettings.hgmock.json
  Apps/Medication/src/appsettings.hgpoc.json
  Apps/Medication/src/appsettings.hgtest.json
  Apps/Medication/src/appsettings.json
  Apps/Medication/test/unit/Services/MedicationRequestServiceTests.cs
  Apps/Medication/test/unit/Services/MedicationStatementServiceTests.cs
  Apps/Patient/src/Mappings/PatientDataAccessMappings.cs
  Apps/Patient/src/Services/PatientDataService.cs
  Apps/Patient/test/unit/Services/PatientDataServiceTests.cs
Labels: enhancement, .NET, unit tests, ready

#5224 Consume new blocked access property in front-end for AB#15458
  Apps/WebClient/src/ClientApp/src/components/services/OrganDonorDetailsCard.vue
  Apps/WebClient/src/ClientApp/src/components/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/dataSource.ts
  Apps/WebClient/src/ClientApp/src/models/user.ts
  Apps/WebClient/src/ClientApp/src/models/userProfile.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/getters.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/types.ts
  Apps/WebClient/src/ClientApp/src/utility/dataSourceUtil.ts
Labels: enhancement, ready, UI

#5231 Change Diagnostic Imaging Status In Progress to return Pending for AB#15670
  Apps/Patient/src/Mappings/DiagnosticImagingExamProfile.cs
Labels: .NET, ready

#5232 Auth, user, config and error stores translated to Pinia
  Apps/Gateway/src/ClientApp/src/stores/auth.ts
  Apps/Gateway/src/ClientApp/src/stores/config.ts
  Apps/Gateway/src/ClientApp/src/stores/error.ts
  Apps/Gateway/src/ClientApp/src/stores/user.ts
Labels: ready

#5234 Fixed failing functional tests due to timezone and Mud Blazor release version
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
  Apps/CommonUi/src/Common.Ui.csproj
Labels: functional tests, ready

#5236 Use midnight pacific time not utc on default date values for AB#15718
  Apps/Admin/Client/Components/Communications/BroadcastDialog.razor.cs
  Apps/Admin/Client/Components/Communications/CommunicationDialog.razor.cs
  Apps/Admin/Client/Services/DateConversionService.cs
  Apps/Admin/Client/Services/IDateConversionService.cs
Labels: bugfix, .NET, ready

#5235 Mulitple Store Tasks - AB#15545
  Apps/WebClient/src/NewClientApp/src/stores/auth.ts
  Apps/WebClient/src/NewClientApp/src/stores/clinicalDocument.ts
  Apps/WebClient/src/NewClientApp/src/stores/comment.ts
  Apps/WebClient/src/NewClientApp/src/stores/dependent.ts
  Apps/WebClient/src/NewClientApp/src/stores/healthVisits.ts
  Apps/WebClient/src/NewClientApp/src/stores/hospitalVisits.ts
  Apps/WebClient/src/NewClientApp/src/stores/immunization.ts
  Apps/WebClient/src/NewClientApp/src/stores/notification.ts
  Apps/WebClient/src/NewClientApp/src/stores/user.ts
  Apps/WebClient/src/NewClientApp/src/stores/utils/DatasetMapUtils.ts
Labels: ready

#5241 Migrate HgButtonComponent to vuetify AB#15712
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/components/shared/HgButtonComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/shared/HgIconButtonComponent.vue
  Apps/WebClient/src/NewClientApp/src/plugins/index.ts
  Apps/WebClient/src/NewClientApp/src/plugins/vuetify.ts
Labels: ready

#5237 Stores - Laboratory Results AB#15701
  Apps/WebClient/src/NewClientApp/src/stores/covid19TestResult.ts
  Apps/WebClient/src/NewClientApp/src/stores/labResult.ts
Labels: ready

#5240 Stores - Medication Service related AB#15702
  Apps/WebClient/src/NewClientApp/src/stores/medication.ts
  Apps/WebClient/src/NewClientApp/src/stores/specialAuthorityRequest.ts
  Apps/WebClient/src/NewClientApp/src/stores/utils/DatasetMapUtils.ts
Labels: ready

#5244 Fix UTC/PST bug in Admin Communication Tests for AB#15718
  Apps/Admin/Client/Components/Communications/BroadcastDialog.razor.cs
  Apps/Admin/Client/Components/Communications/CommunicationDialog.razor.cs
  Apps/Admin/Client/Services/DateConversionService.cs
  Apps/Admin/Client/Services/IDateConversionService.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
Labels: bugfix, .NET, functional tests, ready

#5242 Stores - navbar translated AB#15704
  Apps/WebClient/src/NewClientApp/src/stores/navbar.ts
Labels: ready

#5243 Stores - waitlist translated AB#15710
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/stores/index.ts
  Apps/WebClient/src/NewClientApp/src/stores/waitlist.ts
Labels: ready

#5247 Release Notes May 10, 2023
  Apps/WebClient/src/ClientApp/src/views/ReleaseNotesView.vue
Labels: ready

#5251 Update onetime job to copy email by batch size for AB#14194
  Apps/JobScheduler/src/Tasks/CopyEmailToMessagingVerification.cs
  Apps/JobScheduler/src/appsettings.json
Labels: bugfix, .NET, ready

#5253 Removed offset from query for AB#14194
  Apps/JobScheduler/src/Tasks/CopyEmailToMessagingVerification.cs
Labels: bugfix, .NET, ready

#5250 Migrate LoadingComponent to vuetify AB#15735
  Apps/WebClient/src/ClientApp/src/components/LoadingComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/shared/LoadingComponent.vue
  Testing/functional/tests/cypress/integration/ui/report/immunizationReport.js
Labels: ready

#5254 Improve query performance and added log message for AB#14194.
  Apps/JobScheduler/src/Tasks/CopyEmailToMessagingVerification.cs
Labels: bugfix, .NET, ready

#5252 Converted Notes store to Vue 3.0
  Apps/WebClient/src/NewClientApp/src/stores/note.ts
Labels: enhancement, ready

#5263 Fix store name for AB#15705.
  Apps/WebClient/src/NewClientApp/src/stores/note.ts
Labels: bugfix, ready

#5248 Store - patientData translated AB#15707
  Apps/WebClient/src/NewClientApp/src/models/datasetState.ts
  Apps/WebClient/src/NewClientApp/src/stores/patientData.ts
Labels: ready

#5261 Vuetify - HeaderComponent AB#15714
  Apps/WebClient/src/NewClientApp/index.html
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/navmenu/HeaderComponent.vue
Labels: ready

#5262 Migrate PageTitleComponent to vuetify AB#15736
  Apps/WebClient/src/NewClientApp/src/components/shared/HgButtonComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/shared/HgIconButtonComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/shared/PageTitleComponent.vue
Labels: ready

#5268 Add Procedure Description Back to Diagnostic Imaging Timeline
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/DiagnosticImagingTimelineComponent.vue
  Testing/functional/tests/cypress/integration/e2e/timeline/diagnosticImaging.js
Labels: ready

#5271 Fix User Guide Link for Health Visit
  Apps/WebClient/src/ClientApp/src/components/timeline/entryCard/EncounterTimelineComponent.vue
Labels: ready

#5269 Apply PR feedback for AB#15711
  Apps/WebClient/src/NewClientApp/src/views/LandingView.vue
Labels: ready

#5264 Vue3 - LandingView AB#15711
  Apps/WebClient/src/NewClientApp/public/favicon.ico
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/HelloWorld.vue
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/views/Home.vue
  Apps/WebClient/src/NewClientApp/src/views/LandingView.vue
Labels: ready

#5266 Convert vaccination status store to VUE 3.0 for AB#15709
  Apps/WebClient/src/NewClientApp/src/stores/note.ts
  Apps/WebClient/src/NewClientApp/src/stores/vaccinationStatusAuthenticated.ts
  Apps/WebClient/src/NewClientApp/src/stores/vaccinationStatusPublic.ts
Labels: enhancement, ready, UI

#5270 Implement timeline store for Vue 3.0 for AB#15708
  Apps/WebClient/src/NewClientApp/src/stores/timeline.ts
Labels: enhancement, ready, UI

#5272 Swap font to BC Sans AB#15763
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/assets/fonts/2023_01_01_BCSans-BoldItalic_2f.woff2
  Apps/WebClient/src/NewClientApp/src/assets/fonts/2023_01_01_BCSans-Bold_2f.woff2
  Apps/WebClient/src/NewClientApp/src/assets/fonts/2023_01_01_BCSans-Italic_2f.woff2
  Apps/WebClient/src/NewClientApp/src/assets/fonts/2023_01_01_BCSans-LightItalic_2f.woff2
  Apps/WebClient/src/NewClientApp/src/assets/fonts/2023_01_01_BCSans-Regular_2f.woff2
  Apps/WebClient/src/NewClientApp/src/assets/fonts/2023_03_14_BCSans-Light_2g.woff2
  Apps/WebClient/src/NewClientApp/src/assets/styles/_fonts.scss
  Apps/WebClient/src/NewClientApp/src/assets/styles/main.scss
  Apps/WebClient/src/NewClientApp/src/plugins/index.ts
  Apps/WebClient/src/NewClientApp/src/plugins/vuetify.ts
  Apps/WebClient/src/NewClientApp/src/plugins/webfontloader.ts
Labels: ready

#5273 Apply default styling for p, ul, and ol elements AB#15773
  Apps/WebClient/src/NewClientApp/src/assets/styles/_spacing.scss
  Apps/WebClient/src/NewClientApp/src/assets/styles/main.scss
Labels: ready

#5274 Migrate StatusLabelComponent to vuetify AB#15739
  Apps/WebClient/src/NewClientApp/src/components/shared/DisplayFieldComponent.vue
Labels: ready

#5276 Fix medication report download failure - AB#15778
  Apps/WebClient/src/ClientApp/src/components/report/MedicationHistoryReportComponent.vue
Labels: ready

#5277 Convert BreadcrumbComponent, ReleaseNoteComponent and ReleaseNotesView to Vue 3.
  Apps/WebClient/src/NewClientApp/src/components/ReleaseNoteComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/navmenu/BreadcrumbComponent.vue
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/views/ReleaseNotesView.vue
Labels: enhancement, ready, UI

#5279 Convert TooManyRequestsComponent to Vue 3 for AB#15781
  Apps/WebClient/src/NewClientApp/src/components/TooManyRequestsComponent.vue
  Apps/WebClient/src/NewClientApp/src/stores/timeline.ts
Labels: enhancement, ready, UI

#5265 Convert Authentication Views - AB#15748
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/shared/HtmlTextAreaComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/shared/PageErrorComponent.vue
  Apps/WebClient/src/NewClientApp/src/main.ts
  Apps/WebClient/src/NewClientApp/src/plugins/index.ts
  Apps/WebClient/src/NewClientApp/src/router/afterEachHook.ts
  Apps/WebClient/src/NewClientApp/src/router/beforeEachGuard.ts
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/stores/auth.ts
  Apps/WebClient/src/NewClientApp/src/stores/user.ts
  Apps/WebClient/src/NewClientApp/src/views/HomeView.vue
  Apps/WebClient/src/NewClientApp/src/views/LoginCallbackView.vue
  Apps/WebClient/src/NewClientApp/src/views/LoginView.vue
  Apps/WebClient/src/NewClientApp/src/views/LogoutCompleteView.vue
  Apps/WebClient/src/NewClientApp/src/views/LogoutView.vue
  Apps/WebClient/src/NewClientApp/src/views/RegistrationView.vue
  Apps/WebClient/src/NewClientApp/src/views/errors/AppErrorView.vue
  Apps/WebClient/src/NewClientApp/src/views/errors/IdirLoggedInView.vue
  Apps/WebClient/src/NewClientApp/src/views/errors/NotFoundView.vue
  Apps/WebClient/src/NewClientApp/src/views/errors/PatientRetrievalErrorView.vue
  Apps/WebClient/src/NewClientApp/src/views/errors/UnauthorizedView.vue
Labels: ready

#5286 Migrate HgDateDropdownComponent to vuetify AB#15742
  Apps/WebClient/src/NewClientApp/src/components/shared/HgDateDropdownComponent.vue
  Apps/WebClient/src/NewClientApp/src/models/selectOption.ts
Labels: ready

#5280 Add Health Link Card to Home View - AB#15767
  Apps/WebClient/src/ClientApp/src/assets/images/services/health-link-logo.svg
  Apps/WebClient/src/ClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/ClientApp/src/components/shared/HgCardButtonComponent.vue
  Apps/WebClient/src/ClientApp/src/constants/serviceName.ts
  Apps/WebClient/src/ClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/ClientApp/src/store/modules/user/mutations.ts
  Apps/WebClient/src/ClientApp/src/views/HomeView.vue
  Apps/WebClient/src/featuretoggleconfig.json
  Testing/functional/tests/cypress/integration/e2e/user/healthConnectRegistryQuickLink.js
Labels: ready, UI

#5293 Downgrade Mud Blazor 6.5.1 to 6.3.1 due to failing admin functional test failures
  Apps/Admin/Client/Admin.Client.csproj
  Apps/CommonUi/src/Common.Ui.csproj
Labels: .NET, functional tests, ready

#5291 Convert SidebarComponent to Vue 3 for AB#15786
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/dependent/DependentViewSelectorComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/navmenu/HeaderComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/stores/navbar.ts
  Apps/WebClient/src/NewClientApp/src/stores/user.ts
  Apps/WebClient/src/NewClientApp/src/views/Covid19View.vue
  Apps/WebClient/src/NewClientApp/src/views/ServicesView.vue
  Apps/WebClient/src/NewClientApp/src/views/UserTimelineView.vue
Labels: enhancement, ready, UI

#5296 Fix PST/UTC problem with admin analytics functional tests for AB#15796
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/analytics.cy.js
  Apps/Admin/Tests/Functional/cypress/utilities/sharedUtilities.js
Labels: bugfix, functional tests, ready

#5304 Add missing export reports link to sidebar component
  Apps/WebClient/src/NewClientApp/src/components/navmenu/SidebarComponent.vue
  Apps/WebClient/src/NewClientApp/src/router/index.ts
  Apps/WebClient/src/NewClientApp/src/views/ReportsView.vue
Labels: enhancement, ready, UI

#5290 AppTour and Rating components - AB#15749
  Apps/WebClient/src/NewClientApp/src/App.vue
  Apps/WebClient/src/NewClientApp/src/components/modal/AppTourComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/modal/RatingComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/navmenu/HeaderComponent.vue
Labels: ready, UI

#5292 HomeView and AddQuickLinkComponent AB#15790
  Apps/WebClient/src/NewClientApp/package-lock.json
  Apps/WebClient/src/NewClientApp/package.json
  Apps/WebClient/src/NewClientApp/src/assets/images/services/health-link-logo.svg
  Apps/WebClient/src/NewClientApp/src/components/TooManyRequestsComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/modal/AddQuickLinkComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/modal/AppTourComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/modal/RatingComponent.vue
  Apps/WebClient/src/NewClientApp/src/components/shared/HgCardComponent.vue
  Apps/WebClient/src/NewClientApp/src/constants/entryType.ts
  Apps/WebClient/src/NewClientApp/src/constants/serviceName.ts
  Apps/WebClient/src/NewClientApp/src/constants/userPreferenceType.ts
  Apps/WebClient/src/NewClientApp/src/stores/timeline.ts
  Apps/WebClient/src/NewClientApp/src/stores/user.ts
  Apps/WebClient/src/NewClientApp/src/views/HomeView.vue
Labels: ready, UI

#5294 Convert MessageModalComponent - AB#15793
  Apps/WebClient/src/NewClientApp/index.html
  Apps/WebClient/src/NewClientApp/public/snowplow.js
  Apps/WebClient/src/NewClientApp/src/components/shared/MessageModalComponent.vue
  Apps/WebClient/src/NewClientApp/src/views/HomeView.vue
Labels: ready, UI
