Repository bcgov/healthgateway, pull requests merged in 2024-01, with the labels that each got.

#5928 Fix concurrency issues with tests to single file for AB#16592
  Testing/functional/tests/cypress/db/seed.sql
  Testing/functional/tests/cypress/integration/e2e/user/healthConnectRegistryQuickLink.js
  Testing/functional/tests/cypress/integration/e2e/user/organDonorCardQuickLink.js
  Testing/functional/tests/cypress/integration/e2e/user/quickLinks.js
  Testing/functional/tests/cypress/integration/e2e/user/vaccineCardQuickLink.js
Labels: ready

#5933 Refactor GatewayApi service unit tests for AB#16591
  Apps/Database/src/Delegates/ICommentDelegate.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/test/unit/Services.Test/CommentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/NoteServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceTests.cs
Labels: .NET, unit tests, ready

#5940 Add cancellation token to encounter for AB#16596
  Apps/Encounter/src/Api/IMspVisitApi.cs
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/Encounter/src/Delegates/IMspVisitDelegate.cs
  Apps/Encounter/src/Delegates/RestMspVisitDelegate.cs
  Apps/Encounter/src/Services/EncounterService.cs
  Apps/Encounter/src/Services/IEncounterService.cs
  Apps/Encounter/test/unit/Controllers/EncounterControllerTests.cs
  Apps/Encounter/test/unit/Delegates/EncounterDelegateTests.cs
  Apps/Encounter/test/unit/Services/EncounterServiceTests.cs
Labels: enhancement, .NET, unit tests, ready

#5942 Add cancellation token to Laboratory for AB#16595.
  Apps/Laboratory/src/Api/ILabTestKitApi.cs
  Apps/Laboratory/src/Api/ILaboratoryApi.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Delegates/ILaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Services/ILabTestKitService.cs
  Apps/Laboratory/src/Services/ILaboratoryService.cs
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryDelegateMock.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: enhancement, .NET, unit tests, ready

#5941 Refactor Drug App Jobs to Async for AB#16593
  Apps/DBMaintainer/Apps/BCPProvDrugDBApp.cs
  Apps/DBMaintainer/Apps/BaseDrugApp.cs
  Apps/DBMaintainer/Apps/FedDrugDBApp.cs
  Apps/DBMaintainer/Apps/IDrugApp.cs
  Apps/DBMaintainer/FileDownload/FileDownloadService.cs
  Apps/DBMaintainer/FileDownload/IFileDownloadService.cs
  Apps/DBMaintainer/Parsers/IPharmaCareDrugParser.cs
  Apps/DBMaintainer/Parsers/PharmaCareDrugParser.cs
  Apps/DBMaintainer/Program.cs
  Apps/JobScheduler/src/Jobs/FedDrugJob.cs
  Apps/JobScheduler/src/Jobs/ProvincialDrugJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/Utils/SchedulerHelper.cs
Labels: ready

#5945 Add cancellation token to Immunization
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/AdminReportService.cs
  Apps/Common/src/Services/EmailQueueService.cs
  Apps/Common/test/unit/Services/CommunicationServiceTests.cs
  Apps/Common/test/unit/Services/EmailQueueServiceTests.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceTests.cs
  Apps/Immunization/src/Api/IImmunizationApi.cs
  Apps/Immunization/src/Api/IImmunizationPublicApi.cs
  Apps/Immunization/src/Controllers/AuthenticatedVaccineStatusController.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Controllers/PublicVaccineStatusController.cs
  Apps/Immunization/src/Delegates/IImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/IVaccineStatusDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestVaccineStatusDelegate.cs
  Apps/Immunization/src/Services/IImmunizationService.cs
  Apps/Immunization/src/Services/IVaccineStatusService.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationControllerTests.cs
  Apps/Immunization/test/unit/Controllers.Test/PublicVaccineStatusControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Immunization/test/unit/Delegates.Test/VaccineStatusDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Testing/integration/tests/WebAppFixture.cs
Labels: enhancement, .NET, unit tests, ready

#5947 Make IAuthenticationDelegate async AB#16578
  Apps/Admin/Server/Services/AgentAccessService.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/Services/InactiveUserService.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Services/CovidSupportServiceTests.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/AdminWebClient/src/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/AdminWebClient/src/Server/Services/CovidSupportService.cs
  Apps/AdminWebClient/test/unit/Services.Test/CovidSupportServiceTests.cs
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/IAuthenticationDelegate.cs
  Apps/Common/src/AccessManagement/Authentication/Models/ClientCredentialsRequest.cs
  Apps/Common/src/AccessManagement/Authentication/Models/ClientCredentialsRequestParameters.cs
  Apps/Common/src/AccessManagement/Authentication/Models/JwtModel.cs
  Apps/Common/src/Jobs/INotificationSettingsJob.cs
  Apps/Common/src/Services/AccessTokenService.cs
  Apps/Common/src/Services/NotificationSettingsService.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/Common/test/unit/Services/AccessTokenServiceTests.cs
  Apps/Common/test/unit/Services/NotificationSettingsServiceTests.cs
  Apps/Database/src/Delegates/DbEventLogDelegate.cs
  Apps/Database/src/Delegates/IEventLogDelegate.cs
  Apps/Encounter/src/Delegates/RestHospitalVisitDelegate.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Services/VaccineStatusService.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
  Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/JobScheduler/src/Jobs/NotificationSettingsJob.cs
  Apps/Laboratory/src/Services/LabTestKitService.cs
  Apps/Laboratory/src/Services/LaboratoryService.cs
  Apps/Laboratory/test/unit/Mock/LaboratoryServiceMock.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
  Apps/Medication/src/Delegates/SalesforceMedicationRequestDelegate.cs
  Apps/Medication/src/Models/Salesforce/Config.cs
  Apps/Medication/test/unit/Delegates/SalesforceMedicationRequestDelegateTests.cs
  Apps/Medication/test/unit/Services/MedicationStatementServiceTests.cs
Labels: ready

#5949 Change from fixed expected data for AB#16583
  Testing/integration/tests/AdminReports/AdminApiAdminReportTests.cs
Labels: ready

#5953 Replace Microsoft.*.ApiExplorer with Asp.*.ApiExplorer for AB#16594.
  Apps/Admin/Server/Controllers/AdminReportController.cs
  Apps/Admin/Server/Controllers/AgentAccessController.cs
  Apps/Admin/Server/Controllers/BroadcastController.cs
  Apps/Admin/Server/Controllers/CommunicationController.cs
  Apps/Admin/Server/Controllers/ConfigurationController.cs
  Apps/Admin/Server/Controllers/CsvExportController.cs
  Apps/Admin/Server/Controllers/DashboardController.cs
  Apps/Admin/Server/Controllers/DelegationController.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Server/Controllers/TagController.cs
  Apps/Admin/Server/Controllers/UserFeedbackController.cs
  Apps/AdminWebClient/src/Server/Controllers/AuthenticationController.cs
  Apps/AdminWebClient/src/Server/Controllers/ConfigurationController.cs
  Apps/AdminWebClient/src/Server/Controllers/CovidSupportController.cs
  Apps/AdminWebClient/src/Server/Controllers/SupportController.cs
  Apps/ClinicalDocument/src/Controllers/ClinicalDocumentController.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Swagger/ConfigureSwaggerGenOptions.cs
  Apps/Common/src/Swagger/ConfigureSwaggerUiOptions.cs
  Apps/Common/src/Swagger/ServicesExtensions.cs
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/GatewayApi/src/Controllers/CommentController.cs
  Apps/GatewayApi/src/Controllers/CommunicationController.cs
  Apps/GatewayApi/src/Controllers/DependentController.cs
  Apps/GatewayApi/src/Controllers/NoteController.cs
  Apps/GatewayApi/src/Controllers/NotificationController.cs
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/GatewayApi/src/Controllers/ReportController.cs
  Apps/GatewayApi/src/Controllers/UserFeedbackController.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/Immunization/src/Controllers/AuthenticatedVaccineStatusController.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Controllers/PublicVaccineStatusController.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
  Apps/Medication/src/Controllers/MedicationController.cs
  Apps/Medication/src/Controllers/MedicationRequestController.cs
  Apps/Medication/src/Controllers/MedicationStatementController.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Controllers/PatientDataController.cs
  Apps/WebClient/src/Server/Controllers/ConfigurationController.cs
  Apps/WebClient/src/Server/Controllers/RobotsController.cs
Labels: bugfix, .NET, ready

#5958 Fix update/save user profile in DbProfileDelegate for AB#16605.
  Apps/Database/src/Delegates/DbProfileDelegate.cs
Labels: bugfix, .NET, ready

#5957 Implement .net 8 IExceptionHandler for global error handling for AB#16601
  Apps/Admin/Server/Program.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/Common/src/AspNetConfiguration/Modules/ExceptionHandling.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/ErrorHandling/GlobalExceptionHandler.cs
  Apps/Common/src/MapProfiles/ProblemDetailsProfile.cs
  Apps/CommonData/src/ErrorHandling/ExceptionUtility.cs
  Apps/CommonData/src/ErrorHandling/ProblemDetails.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Apps/Patient/src/Program.cs
Labels: ready

#5965 Ensure User Profile is saved or deferred properly for AB#16610
  Apps/Database/src/Delegates/DbProfileDelegate.cs
Labels: bugfix, .NET, ready

#5977 Re-enable web client auth and fix flakiness (incl admin) for AB#16603.
  Apps/Admin/Tests/Functional/cypress/integration/e2e/unauthorized.cy.js
  Testing/functional/tests/cypress/integration/e2e/authentication/auth.js
  Testing/functional/tests/cypress/support/commands.js
  Testing/functional/tests/package-lock.json
  Testing/functional/tests/package.json
  Tools/Pipelines/scripts/azp_runFunctionalTests.sh
Labels: bugfix, functional tests, ready

#5979 Disable auth functional tests for AB#16603.
  Tools/Pipelines/scripts/azp_runFunctionalTests.sh
Labels: bugfix, functional tests, ready

#5980 Update BC Cancer Components for AB#16618
  Apps/WebClient/src/ClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/BcCancerScreeningTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/timeline/bcCancerScreeningTimelineEntry.ts
  Testing/functional/tests/cypress/integration/ui/timeline/bcCancerScreening.js
Labels: functional tests, ready, UI

#5987 Update exception handlers for AB#16608
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/Common/src/AspNetConfiguration/Modules/ExceptionHandling.cs
  Apps/Common/src/ErrorHandling/DefaultExceptionHandler.cs
  Apps/Common/src/ErrorHandling/ExceptionUtilities.cs
  Apps/Common/src/ErrorHandling/ValidationExceptionHandler.cs
Labels: ready

#5989 Update cancer category name for AB#16625
  Apps/WebClient/src/ClientApp/src/components/site/NotificationCentreComponent.vue
Labels: bugfix, ready

#5993 Update BC Cancer timline content for AB#16334
  Apps/WebClient/src/ClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/BcCancerScreeningTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/models/timeline/bcCancerScreeningTimelineEntry.ts
  Testing/functional/tests/cypress/integration/e2e/timeline/bcCancerScreening.js
  Testing/functional/tests/cypress/integration/ui/timeline/bcCancerScreening.js
Labels: functional tests, ready

#5994 Add post-function plugin to Kong for AB#16627
  Tools/Kong/config.tmpl
Labels: ready, helm, kong
