Repository bcgov/healthgateway, pull requests merged in 2024-07, with the labels that each got.

#6251 Add intercept and wait on admin endpoint calls for AB#16782
  Apps/Admin/Tests/Functional/cypress/integration/e2e/agentaccess.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/beta-access.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/delegation.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/reports.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
  Apps/Admin/Tests/Functional/cypress/support/functions/intercept.js
  Apps/Admin/Tests/Functional/cypress/utilities/supportUtilities.js
Labels: bugfix, functional tests, ready

#6254 Add scheduled job to assign beta feature access AB#16788
  Apps/JobScheduler/src/Jobs/AssignBetaFeatureAccessJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/appsettings.json
Labels: ready

#6252 Update CreateUserProfile to better bundle DB commits AB#16784
  Apps/Database/src/Delegates/DbMessagingVerificationDelegate.cs
  Apps/Database/src/Delegates/IMessagingVerificationDelegate.cs
  Apps/GatewayApi/src/Controllers/UserProfileControllerV2.cs
  Apps/GatewayApi/src/Services/IUserEmailServiceV2.cs
  Apps/GatewayApi/src/Services/IUserSmsServiceV2.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Services/UserEmailServiceV2.cs
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
  Apps/GatewayApi/src/Services/UserSmsService.cs
  Apps/GatewayApi/src/Services/UserSmsServiceV2.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceTests.cs
Labels: ready

#6255 End-of-sprint merge to master
  Apps/Admin/Tests/Functional/cypress/integration/e2e/agentaccess.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/beta-access.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/communications.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/delegation.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/feedback-review.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/reports.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
  Apps/Admin/Tests/Functional/cypress/support/commands.js
  Apps/Admin/Tests/Functional/cypress/support/functions/intercept.js
  Apps/Admin/Tests/Functional/cypress/utilities/supportUtilities.js
  Apps/Common/src/AccessManagement/Authorization/Handlers/UserAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Policy/UserPolicy.cs
  Apps/Common/src/AccessManagement/Authorization/Requirements/UserRequirement.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Common/test/unit/AccessManagement/Authorization/UserAuthorizationHandlerTests.cs
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
  Apps/JobScheduler/src/Jobs/AssignBetaFeatureAccessJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/appsettings.json
Labels: ready

#6256 Remove unnecessary payload when removing dependent AB#16794
  Apps/GatewayApi/src/Controllers/DependentController.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/IDependentService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/DependentControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
Labels: bugfix, ready

#6257 Hotfix to resolve remove dependent issue on mobile app
  Apps/GatewayApi/src/Controllers/DependentController.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/IDependentService.cs
  Apps/GatewayApi/test/unit/Controllers.Test/DependentControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
Labels: ready

#6259 Increase access to beta and add SnowPlow tracking AB#16787
  Apps/JobScheduler/src/appsettings.json
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/ClientApp/src/plugins/extensions.ts
Labels: ready

#6260 Hotfix to increase access to beta
  Apps/JobScheduler/src/appsettings.json
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/ClientApp/src/plugins/extensions.ts
Labels: ready

#6258 Add unit test coverage for UserEmailServiceV2 for AB#16792.
  Apps/GatewayApi/src/Services/UserEmailServiceV2.cs
  Apps/GatewayApi/src/Validations/OptionalEmailAddressValidator.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceV2Tests.cs
Labels: .NET, unit tests, ready

#6263 Create task to resolve incomplete registrations AB#16790
  Apps/JobScheduler/src/Tasks/FinalizeIncompleteUserRegistrations.cs
Labels: ready

#6266 Fix notification settings including unverified email AB#16801
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
Labels: bugfix, ready

#6264 Add unit test coverage for UserProfileServiceV2 for AB#16791.
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceV2Tests.cs
Labels: .NET, unit tests, ready

#6267 Fix and improve registration AB#16789
  Apps/Database/src/Delegates/DbMessagingVerificationDelegate.cs
  Apps/Database/src/Delegates/IMessagingVerificationDelegate.cs
  Apps/GatewayApi/src/Controllers/UserProfileControllerV2.cs
  Apps/GatewayApi/src/Services/IUserEmailServiceV2.cs
  Apps/GatewayApi/src/Services/IUserSmsServiceV2.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Services/UserEmailServiceV2.cs
  Apps/GatewayApi/src/Services/UserProfileService.cs
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
  Apps/GatewayApi/src/Services/UserSmsService.cs
  Apps/GatewayApi/src/Services/UserSmsServiceV2.cs
  Apps/GatewayApi/src/Validations/OptionalEmailAddressValidator.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceTests.cs
  Apps/JobScheduler/src/Tasks/FinalizeIncompleteUserRegistrations.cs
Labels: ready

#6268 Remove covid assessment from admin for AB#16800.
  Apps/Admin/Client/Api/ISupportApi.cs
  Apps/Admin/Client/Components/Details/ProfileTab.razor
  Apps/Admin/Client/Components/Details/ProfileTab.razor.cs
  Apps/Admin/Client/Components/Support/AssessmentOptionRadio.razor
  Apps/Admin/Client/Components/Support/AssessmentOptionRadio.razor.cs
  Apps/Admin/Client/Components/Support/AssessmentQuestion.razor
  Apps/Admin/Client/Components/Support/AssessmentQuestion.razor.cs
  Apps/Admin/Client/Components/Support/Covid19AssessmentSection.razor
  Apps/Admin/Client/Components/Support/Covid19AssessmentSection.razor.cs
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor
  Apps/Admin/Client/Pages/Covid19TreatmentAssessmentPage.razor.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsActions.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsEffects.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsReducers.cs
  Apps/Admin/Client/Store/PatientDetails/PatientDetailsState.cs
  Apps/Admin/Common/Models/CovidSupport/CovidAssessmentDetailsResponse.cs
  Apps/Admin/Common/Models/CovidSupport/CovidAssessmentRequest.cs
  Apps/Admin/Common/Models/CovidSupport/CovidAssessmentResponse.cs
  Apps/Admin/Common/Models/PatientSupportDetails.cs
  Apps/Admin/Server/Api/IImmunizationAdminApi.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/Services/ICovidSupportService.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/patient-details-one-dose.json
  Apps/Admin/Tests/Functional/cypress/fixtures/SupportService/patient-details.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Admin/Tests/Services/CovidSupportServiceTests.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
Labels: .NET, functional tests, unit tests, ready, UI

#6271 Fix registration page issues AB#16783 AB#16793
  Apps/WebClient/src/ClientApp/src/components/private/registration/RegistrationView.vue
  Apps/WebClient/src/ClientApp/src/services/restAuthService.ts
  Apps/WebClient/src/ClientApp/src/utility/validationUtil.ts
Labels: bugfix, ready

#6273 Complete unit test coverage V2 services for AB#16785
  Apps/GatewayApi/test/unit/Services.Test/LegalAgreementServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserPreferenceServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceV2Tests.cs
Labels: .NET, unit tests, ready

#6274 Fixed incorrect ProducesResponse for GetLastTermsOfService for AB#16805
  Apps/GatewayApi/src/Controllers/UserProfileControllerV2.cs
Labels: bugfix, .NET, ready

#6277 Update vaccine card redirect on landing site for AB#16804
  Apps/Landing/src/ClientApp/src/constants/path.ts
  Apps/Landing/src/ClientApp/src/models/configData.ts
  Apps/Landing/src/ClientApp/src/router/beforeEachGuard.ts
  Apps/Landing/src/ClientApp/src/router/index.ts
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/appsettings.Development.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
Labels: enhancement, ready

#6279 Expand beta access by 100,000 users per day AB#16810
  Apps/JobScheduler/src/appsettings.json
Labels: ready

#6278 Update MudBlazor to 7.4.0 in Admin.Client AB#16807
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Api/IAdminReportApi.cs
  Apps/Admin/Client/Components/AgentAccess/AgentAccessDialog.razor.cs
  Apps/Admin/Client/Components/AgentAudit/AgentAuditHistory.razor
  Apps/Admin/Client/Components/AgentAudit/AuditReasonDialog.razor.cs
  Apps/Admin/Client/Components/BetaAccess/BetaAccessTable.razor
  Apps/Admin/Client/Components/Common/HgAutocomplete.razor
  Apps/Admin/Client/Components/Common/HgAutocomplete.razor.cs
  Apps/Admin/Client/Components/Communications/BroadcastDialog.razor
  Apps/Admin/Client/Components/Communications/BroadcastDialog.razor.cs
  Apps/Admin/Client/Components/Communications/BroadcastsTable.razor.cs
  Apps/Admin/Client/Components/Communications/CommunicationDialog.razor
  Apps/Admin/Client/Components/Communications/CommunicationDialog.razor.cs
  Apps/Admin/Client/Components/Communications/CommunicationsTable.razor.cs
  Apps/Admin/Client/Components/Delegation/DelegateDialog.razor.cs
  Apps/Admin/Client/Components/Delegation/DelegateTable.razor
  Apps/Admin/Client/Components/Delegation/DependentTable.razor
  Apps/Admin/Client/Components/Delegation/DependentTable.razor.cs
  Apps/Admin/Client/Components/Details/AccountTab.razor
  Apps/Admin/Client/Components/Details/ProfileTab.razor
  Apps/Admin/Client/Components/Site/InactivityDialog.razor.cs
  Apps/Admin/Client/Components/Support/AddressConfirmationDialog.razor.cs
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor.cs
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor.cs
  Apps/Admin/Client/Layouts/DefaultLayout.razor
  Apps/Admin/Client/Layouts/DefaultLayout.razor.cs
  Apps/Admin/Client/Layouts/MainLayout.razor
  Apps/Admin/Client/Layouts/MainLayout.razor.cs
  Apps/Admin/Client/Pages/AgentAccessPage.razor.cs
  Apps/Admin/Client/Pages/AnalyticsPage.razor
  Apps/Admin/Client/Pages/CommunicationsPage.razor.cs
  Apps/Admin/Client/Pages/DashboardPage.razor
  Apps/Admin/Client/Pages/DelegationPage.razor
  Apps/Admin/Client/Pages/DelegationPage.razor.cs
  Apps/Admin/Client/Pages/FeedbackPage.razor
  Apps/Admin/Client/Pages/FeedbackPage.razor.cs
  Apps/Admin/Client/Pages/ReportsPage.razor.cs
  Apps/Admin/Client/Pages/Showcase/Chips.razor
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Theme/DarkTheme.cs
  Apps/Admin/Client/Theme/HgTheme.cs
  Apps/Admin/Client/Theme/LightTheme.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/agentaccess.cy.js
Labels: ready

#6280 Fix bug to access correct PHSA config for admin for AB#16808
  Apps/Admin/Server/Program.cs
Labels: bugfix, .NET, ready

#6281 Update landing site redirect for email verification AB#16813
  Apps/Landing/src/ClientApp/src/router/beforeEachGuard.ts
  Apps/Landing/src/ClientApp/src/router/index.ts
Labels: ready
