Repository bcgov/healthgateway, pull requests merged in 2024-06, with the labels that each got.

#6188 Fix registration bug when checkboxes unchecked for AB#16750.
  Apps/WebClient/src/ClientApp/src/components/private/registration/RegistrationView.vue
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileUnregisteredRegistered.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileValidate.json
  Testing/functional/tests/cypress/integration/ui/pages/registration.js
Labels: bugfix, .NET, functional tests, ready

#6190 Add additional validation checks to registration functional test for AB#16751
  Testing/functional/tests/cypress/integration/e2e/pages/Registration.js
  Testing/functional/tests/cypress/integration/e2e/pages/communication.js
Labels: bugfix, functional tests, ready

#6199 Update UI on landing page to match beta styling AB#16757
  Apps/Landing/src/src/assets/images/gov/hg-logo-rev.svg
  Apps/Landing/src/src/assets/images/gov/hg-logo.png
  Apps/Landing/src/src/assets/images/landing/landing-top.png
  Apps/Landing/src/src/assets/styles/_appbar.scss
  Apps/Landing/src/src/assets/styles/main.scss
  Apps/Landing/src/src/components/error/AppErrorView.vue
  Apps/Landing/src/src/components/public/landing/LandingView.vue
  Apps/Landing/src/src/components/site/FooterComponent.vue
  Apps/Landing/src/src/components/site/HeaderComponent.vue
  Apps/Landing/src/src/plugins/vuetify.ts
Labels: ready, UI

#6195 Create Dockerfile and Pipeline for Landing for AB#16752 and AB16753
  Apps/Landing/Dockerfile
  Apps/Landing/azure/build.yaml
  Apps/Landing/azure/prbuild.yaml
  Apps/Landing/nginx.conf
  Apps/Landing/src/package-lock.json
  Apps/Landing/src/package.json
  Apps/Landing/src/vite.config.ts
  Build/hg-steps-template.yaml
  Build/hg.yaml
  Tools/Helm/Charts/hgtools/values.yaml
  Tools/Pipelines/scripts/azp_tagImages.sh
Labels: enhancement

#6204 Fix artifacts on landing page image AB#16759
  Apps/Landing/src/ClientApp/src/assets/images/landing/landing-top.png
Labels: bugfix, ready

#6213 Simplified build:development task for AB#16760.
  Apps/Landing/src/ClientApp/package-lock.json
  Apps/Landing/src/ClientApp/package.json
  Apps/Landing/src/ClientApp/vite.config.ts
Labels: ready

#6214 Remove non-prod banner for classic and legacy routes AB#16761
  Apps/Landing/src/ClientApp/src/components/site/DevBannerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/DevBannerComponent.vue
Labels: bugfix, ready

#6215 Resolve Rider warnings AB#16762
  .editorconfig
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/Admin/Client/Components/AgentAccess/AgentAccessDialog.razor
  Apps/Admin/Client/Components/Common/HgComponentBase.cs
  Apps/Admin/Client/Components/Delegation/DelegateTable.razor
  Apps/Admin/Client/Components/Delegation/DependentTable.razor
  Apps/Admin/Client/Components/Details/AccountTab.razor
  Apps/Admin/Client/Components/Support/AssessmentOptionRadio.razor
  Apps/Admin/Client/Components/Support/AssessmentOptionRadio.razor.cs
  Apps/Admin/Client/Components/Support/AssessmentQuestion.razor.cs
  Apps/Admin/Client/Components/Support/DatasetAccessSection.razor
  Apps/Admin/Client/Pages/AnalyticsPage.razor.cs
  Apps/Admin/Client/Pages/Showcase/Forms.razor
  Apps/Admin/Client/Pages/Showcase/LinksAndButtons.razor
  Apps/Common/test/unit/ErrorHandling/ExceptionHandlerTests.cs
  Apps/Common/test/unit/Messaging/AzureServiceBusTests.cs
  Apps/Common/test/unit/Messaging/DbOutboxStoreTests.cs
  Apps/Common/test/unit/Messaging/OutboxMessageSenderTests.cs
  Apps/Database/src/Context/BaseDbContext.cs
  Apps/Database/src/Delegates/DbAdminUserProfileDelegate.cs
  Apps/Encounter/test/unit/Delegates/EncounterDelegateTests.cs
  Apps/Encounter/test/unit/Delegates/RestHospitalVisitDelegateTests.cs
  Apps/GatewayApi/src/Controllers/DumpHeadersController.cs
  Apps/GatewayApi/src/GatewayApi.csproj
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Views/Auth/Index.cshtml
  Apps/GatewayApi/src/Views/DumpHeaders/Index.cshtml
  Apps/GatewayApi/src/Views/Shared/Error.cshtml
  Apps/GatewayApi/src/Views/Shared/_Layout.cshtml
  Apps/GatewayApi/src/Views/_ViewImports.cshtml
  Apps/GatewayApi/src/Views/_ViewStart.cshtml
  Apps/GatewayApi/src/appsettings.json
  Apps/GatewayApi/test/unit/Controllers.Test/DumpHeadersControllerTests.cs
  Apps/JobScheduler/src/Controllers/DumpHeadersController.cs
  Apps/JobScheduler/src/JobScheduler.csproj
  Apps/JobScheduler/src/Jobs/CloseAccountJob.cs
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/Views/DumpHeaders/Index.cshtml
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
Labels: ready

#6218 Fix messaging verification issues AB#16763
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Services/UserSmsService.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceTests.cs
Labels: bugfix, ready

#6222 Update Fluxor in Admin.Client AB#16764
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Client/Components/AgentAudit/AuditReasonDialog.razor.cs
  Apps/Admin/Client/Components/Common/HgBannerFeedback.razor.cs
  Apps/Admin/Client/Components/Site/InactivityDialog.razor.cs
  Apps/Admin/Client/Components/Support/AddressConfirmationDialog.razor.cs
  Apps/Admin/Client/Components/Support/Covid19ImmunizationSection.razor.cs
  Apps/Admin/Client/Pages/AgentAccessPage.razor.cs
  Apps/Admin/Client/Pages/AnalyticsPage.razor.cs
  Apps/Admin/Client/Pages/BetaAccessPage.razor.cs
  Apps/Admin/Client/Pages/DelegationPage.razor.cs
  Apps/Admin/Client/Pages/SupportPage.razor.cs
  Apps/Admin/Client/Program.cs
  Apps/Admin/Client/wwwroot/appsettings.Development.json
  Apps/Admin/Client/wwwroot/appsettings.hgdev.json
  Apps/Admin/Client/wwwroot/appsettings.json
Labels: ready

#6229 Fix fluxor initialization on Agent Access for AB#16767.
  Apps/Admin/Client/Admin.Client.csproj
  Apps/Admin/Tests/Functional/cypress/integration/e2e/agentaccess.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/e2e/support.cy.js
Labels: bugfix, .NET, ready

#6231 Enforce smaller max width on landing site AB#16766
  Apps/Landing/src/ClientApp/src/App.vue
  Apps/Landing/src/ClientApp/src/assets/styles/main.scss
  Apps/Landing/src/ClientApp/src/components/site/CommunicationComponent.vue
  Apps/Landing/src/ClientApp/src/components/site/FooterComponent.vue
  Apps/Landing/src/ClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/CommunicationComponent.vue
Labels: ready, UI

#6230 Update functional tests to use UserProfileControllerV2 AB#16769
  Testing/functional/tests/cypress/fixtures/NoteService/dbError.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/termsOfService.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfile.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileAcceptTos.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileClinicalDocDatasetBlocked.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileMultipleDatasetsBlocked.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileOrganDonorRegistrationDatasetBlocked.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileQuickLinks.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileSMSVerified.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileUnregistered.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileUnregisteredRegistered.json
  Testing/functional/tests/cypress/fixtures/UserProfileService/userProfileValidate.json
  Testing/functional/tests/cypress/fixtures/WebClientService/EmailValidation/expired.json
  Testing/functional/tests/cypress/fixtures/WebClientService/EmailValidation/invalid.json
  Testing/functional/tests/cypress/fixtures/WebClientService/EmailValidation/valid.json
  Testing/functional/tests/cypress/integration/e2e/pages/breadcrumbs.js
  Testing/functional/tests/cypress/integration/e2e/pages/communication.js
  Testing/functional/tests/cypress/integration/e2e/services/webClient/userProfile.js
  Testing/functional/tests/cypress/integration/e2e/user/acceptTermsOfService.js
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
  Testing/functional/tests/cypress/integration/ui/errors/tooManyRequestsAlerts.js
  Testing/functional/tests/cypress/integration/ui/pages/registration.js
  Testing/functional/tests/cypress/integration/ui/timeline/errors.js
  Testing/functional/tests/cypress/integration/ui/user/acceptTermsOfService.js
  Testing/functional/tests/cypress/integration/ui/user/emailValidation.js
  Testing/functional/tests/cypress/integration/ui/user/profile.js
  Testing/functional/tests/cypress/support/functions/intercept.js
Labels: functional tests, ready

#6236 Remove unused endpoints AB#16614
  Apps/GatewayApi/src/appsettings.json
  Apps/Immunization/src/Api/IImmunizationApi.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Delegates/IImmunizationDelegate.cs
  Apps/Immunization/src/Delegates/RestImmunizationDelegate.cs
  Apps/Immunization/src/Services/IImmunizationService.cs
  Apps/Immunization/src/Services/ImmunizationService.cs
  Apps/Immunization/test/unit/Controllers.Test/ImmunizationControllerTests.cs
  Apps/Immunization/test/unit/Delegates.Test/ImmunizationDelegateTests.cs
  Apps/Immunization/test/unit/Services.Test/ImmunizationServiceTests.cs
  Apps/Medication/src/Controllers/MedicationController.cs
  Apps/Medication/src/Services/IMedicationService.cs
  Apps/Medication/src/Services/RestMedicationService.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/test/unit/Controllers/MedicationControllerTests.cs
  Apps/Medication/test/unit/Services/MedicationServiceTests.cs
  Testing/functional/tests/cypress/integration/e2e/services/immunization.js
  Testing/functional/tests/cypress/integration/e2e/services/medication.js
  Tools/Kong/routes-medication.tmpl
Labels: ready

#6240 Change priority subject determination for AB#16772.
  Apps/Common/src/AccessManagement/Authorization/Handlers/BaseFhirAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/PersonalAccessHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Handlers/UserDelegatedAccessHandler.cs
  Apps/Common/src/Auditing/AuditLogger.cs
  Apps/Common/src/Utils/HttpContextHelper.cs
  Apps/Common/test/unit/Auditing/DbAuditLoggerTests.cs
  Apps/Common/test/unit/Utils/HttpContextHelperTests.cs
Labels: bugfix, .NET, ready

#6243 Update set of excluded fee descriptions for encounters AB#16716
  Apps/Encounter/src/appsettings.json
  Apps/Encounter/test/unit/Services/EncounterServiceTests.cs
Labels: ready

#6244 Fix sonar code smells for AB#16776.
  Apps/GatewayApi/src/Models/CreateUserRequest.cs
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
  Apps/Laboratory/src/Models/PHSA/LabTestKit.cs
  Apps/Laboratory/src/Models/PHSA/PublicLabTestKit.cs
Labels: bugfix, .NET, ready

#6246 Improve admin patient details functional test performance for AB#16778.
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
Labels: functional tests, ready

#6247 Remove obsolete user authorization handler and policies AB#14828
  Apps/Common/src/AccessManagement/Authorization/Handlers/UserAuthorizationHandler.cs
  Apps/Common/src/AccessManagement/Authorization/Policy/UserPolicy.cs
  Apps/Common/src/AccessManagement/Authorization/Requirements/UserRequirement.cs
  Apps/Common/src/AspNetConfiguration/Modules/Auth.cs
  Apps/Common/test/unit/AccessManagement/Authorization/UserAuthorizationHandlerTests.cs
Labels: ready

#6248 Fix user profile not being saved before verifying email AB#16781
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
Labels: bugfix, ready
