Repository bcgov/healthgateway, pull requests merged in 2024-02, with the labels that each got.

#5990 Upgrade Vuetify for AB#16537
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/common/HgDatePickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/common/InfoPopoverComponent.vue
  Apps/WebClient/src/ClientApp/src/components/common/PageTitleComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/RecommendationsDialogComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/FullscreenTimelineEntryComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/NoteDialogComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/TimelineEntryComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/comment/CommentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/comment/CommentSectionComponent.vue
  Apps/WebClient/src/ClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/ClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationForm.vue
  Apps/WebClient/src/ClientApp/src/components/public/vaccine-card/VaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/components/site/DevBannerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/FooterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/plugins/vuetify.ts
  Apps/WebClient/src/ClientApp/src/stores/app.ts
  Apps/WebClient/src/ClientApp/src/stores/layout.ts
Labels: bugfix, ready, UI

#6001 Disable open telemetry in dev environment for AB#16629.
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/ClinicalDocument/src/appsettings.hgdev.json
  Apps/Encounter/src/appsettings.hgdev.json
  Apps/GatewayApi/src/appsettings.hgdev.json
  Apps/Immunization/src/appsettings.hgdev.json
  Apps/JobScheduler/src/appsettings.hgdev.json
  Apps/Laboratory/src/appsettings.hgdev.json
  Apps/Medication/src/appsettings.hgdev.json
  Apps/Patient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgdev.json
Labels: .NET, ready

#5998 Fix Admin Agent Access Provision Edit User flakey test for AB#16621
  Apps/Admin/Tests/Functional/cypress/integration/e2e/agentaccess.cy.js
Labels: bugfix, functional tests, ready

#6002 Replace gridUtility with useGrid composable AB#16630
  Apps/WebClient/src/ClientApp/src/components/private/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/ClientApp/src/components/private/services/ServicesView.vue
  Apps/WebClient/src/ClientApp/src/utility/gridUtilty.ts
  Apps/WebClient/src/ClientApp/src/utility/useGrid.ts
Labels: bugfix, ready

#6006 Fix BC Cancer functional tests AB#16634
  Testing/functional/tests/cypress/integration/e2e/timeline/bcCancerScreening.js
  Testing/functional/tests/cypress/integration/ui/timeline/bcCancerScreening.js
Labels: functional tests, ready

#6009 Include dataset for BC Cancer download analytics event AB#16635
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/BcCancerScreeningTimelineComponent.vue
Labels: bugfix, ready

#6010 Merge to master (final BC Cancer timeline changes)
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Tests/Functional/cypress/integration/e2e/agentaccess.cy.js
  Apps/ClinicalDocument/src/appsettings.hgdev.json
  Apps/Encounter/src/appsettings.hgdev.json
  Apps/GatewayApi/src/appsettings.hgdev.json
  Apps/Immunization/src/appsettings.hgdev.json
  Apps/JobScheduler/src/appsettings.hgdev.json
  Apps/Laboratory/src/appsettings.hgdev.json
  Apps/Medication/src/appsettings.hgdev.json
  Apps/Patient/src/appsettings.hgdev.json
  Apps/WebClient/src/ClientApp/package-lock.json
  Apps/WebClient/src/ClientApp/package.json
  Apps/WebClient/src/ClientApp/src/components/common/HgDatePickerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/common/InfoPopoverComponent.vue
  Apps/WebClient/src/ClientApp/src/components/common/PageTitleComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/dependent/tabs/DependentDashboardTabComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/ClientApp/src/components/private/reports/RecommendationsDialogComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/services/ServicesView.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/FilterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/FullscreenTimelineEntryComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/NoteDialogComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/TimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/TimelineEntryComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/comment/CommentComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/comment/CommentSectionComponent.vue
  Apps/WebClient/src/ClientApp/src/components/private/timeline/entry/BcCancerScreeningTimelineComponent.vue
  Apps/WebClient/src/ClientApp/src/components/public/landing/LandingView.vue
  Apps/WebClient/src/ClientApp/src/components/public/pcr-test-kit-registration/PcrTestKitRegistrationForm.vue
  Apps/WebClient/src/ClientApp/src/components/public/vaccine-card/VaccineCardView.vue
  Apps/WebClient/src/ClientApp/src/components/site/DevBannerComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/FooterComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/HeaderComponent.vue
  Apps/WebClient/src/ClientApp/src/components/site/SidebarComponent.vue
  Apps/WebClient/src/ClientApp/src/models/timeline/bcCancerScreeningTimelineEntry.ts
  Apps/WebClient/src/ClientApp/src/plugins/vuetify.ts
  Apps/WebClient/src/ClientApp/src/stores/app.ts
  Apps/WebClient/src/ClientApp/src/stores/layout.ts
  Apps/WebClient/src/ClientApp/src/utility/gridUtilty.ts
  Apps/WebClient/src/ClientApp/src/utility/useGrid.ts
  Apps/WebClient/src/appsettings.hgdev.json
  Testing/functional/tests/cypress/integration/e2e/timeline/bcCancerScreening.js
  Testing/functional/tests/cypress/integration/ui/timeline/bcCancerScreening.js
  Tools/KeyCloak/Terraform/idp_azidir.tf
Labels: ready

#5988 Standardise and update exception handling for AB#14666
  Apps/AccountDataAccess/src/Patient/ClientRegistriesDelegate.cs
  Apps/AccountDataAccess/src/Patient/Strategy/PhnEmpiStrategy.cs
  Apps/AccountDataAccess/test/unit/ClientRegistriesDelegateTests.cs
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/PhnEmpiStrategyTests.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/Admin/Server/Delegates/RestVaccineStatusDelegate.cs
  Apps/Admin/Server/Services/AdminReportService.cs
  Apps/Admin/Server/Services/AgentAccessService.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Server/Services/SupportService.cs
  Apps/Admin/Server/Validations/DelegatePatientValidator.cs
  Apps/Admin/Server/Validations/DependentPatientValidator.cs
  Apps/Admin/Tests/Delegates/RestImmunizationAdminDelegateTests.cs
  Apps/Admin/Tests/Delegates/RestVaccineStatusDelegateTests.cs
  Apps/Admin/Tests/Services/CovidSupportServiceTests.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/AdminWebClient/src/Server/Controllers/SupportController.cs
  Apps/Common/src/AspNetConfiguration/Modules/ExceptionHandling.cs
  Apps/Common/src/Constants/ErrorMessages.cs
  Apps/Common/src/ErrorHandling/DefaultExceptionHandler.cs
  Apps/Common/src/ErrorHandling/ErrorCodes.cs
  Apps/Common/src/ErrorHandling/ExceptionUtilities.cs
  Apps/Common/src/ErrorHandling/Exceptions/AlreadyExistsException.cs
  Apps/Common/src/ErrorHandling/Exceptions/DatabaseException.cs
  Apps/Common/src/ErrorHandling/Exceptions/HealthGatewayException.cs
  Apps/Common/src/ErrorHandling/Exceptions/InvalidDataException.cs
  Apps/Common/src/ErrorHandling/Exceptions/NotFoundException.cs
  Apps/Common/src/ErrorHandling/Exceptions/UpstreamServiceException.cs
  Apps/Common/src/ErrorHandling/GlobalExceptionHandler.cs
  Apps/Common/src/ErrorHandling/ValidationExceptionHandler.cs
  Apps/Common/src/MapProfiles/ProblemDetailsProfile.cs
  Apps/Common/src/Services/EmailQueueService.cs
  Apps/Common/src/Services/PatientService.cs
  Apps/CommonData/src/ErrorHandling/ActionType.cs
  Apps/CommonData/src/ErrorHandling/ExceptionUtility.cs
  Apps/CommonData/src/ErrorHandling/ProblemDetails.cs
  Apps/CommonData/src/ErrorHandling/ProblemDetailsException.cs
  Apps/CommonData/src/Validations/PhnValidator.cs
  Apps/GatewayApi/src/Controllers/DependentController.cs
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/GatewayApi/src/Controllers/UserProfileController.cs
  Apps/GatewayApi/src/Services/DependentService.cs
  Apps/GatewayApi/src/Services/NoteService.cs
  Apps/GatewayApi/src/Services/PatientDetailsService.cs
  Apps/GatewayApi/src/Services/UserEmailService.cs
  Apps/GatewayApi/src/Services/UserSmsService.cs
  Apps/GatewayApi/src/Validations/UserProfileValidator.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/NoteServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceTests.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Controllers/PatientDataController.cs
  Apps/Patient/src/Services/PatientService.cs
  Apps/Patient/test/unit/Services/PatientServiceTests.cs
Labels: ready

#6012 Add missing timezone config to Laboratory for AB#16637.
  Apps/Laboratory/src/appsettings.json
Labels: bugfix, .NET, ready

#6013 Fix Redis Auditing Issue for AB#16639
  Apps/Common/src/AspNetConfiguration/Modules/Audit.cs
  Apps/Common/src/AspNetConfiguration/Modules/GatewayCache.cs
  Apps/JobScheduler/src/Startup.cs
  Testing/functional/tests/cypress/integration/ui/timeline/mobile/clinicalDocument.js
Labels: bugfix, .NET, functional tests, ready

#6014 Move configuration overrides from Helm to Appsettings for AB#16636.
  Apps/Admin/Server/appsettings.json
  Apps/Common/src/AspNetConfiguration/Modules/GatewayCache.cs
  Apps/GatewayApi/src/appsettings.json
  Apps/JobScheduler/src/appsettings.json
Labels: .NET, ready

#5909 Exclude models from code coverage calculations AB#16589
  Apps/AccountDataAccess/src/Audit/IAuditRepository.cs
  Apps/AccountDataAccess/src/Patient/Api/PatientIdentity.cs
  Apps/AccountDataAccess/src/Patient/Strategy/PatientQueryContext.cs
  Apps/AccountDataAccess/test/unit/Strategy/HdidAllStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/HdidPhsaStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/PatientQueryFactoryTests.cs
  Apps/AccountDataAccess/test/unit/Utils/RefitExceptionUtil.cs
  Apps/Common/src/AccessManagement/Authentication/AuthenticationDelegate.cs
  Apps/Common/test/unit/AccessManagement/Authentication/AuthenticationDelegateTests.cs
  Apps/WebClient/src/ClientApp/src/constants/validationRegEx.ts
Labels: unit tests, ready

#6020 Fix failing functional tests for AB#16641.
  Testing/functional/tests/cypress/integration/e2e/timeline/notes.js
  Testing/functional/tests/cypress/integration/e2e/timeline/pagination.js
Labels: bugfix, functional tests, ready

#6022 Fix patient retrieval errors reporting as site too busy AB#16645
  Apps/WebClient/src/ClientApp/src/components/error/PatientRetrievalErrorView.vue
  Apps/WebClient/src/ClientApp/src/stores/user.ts
  Testing/functional/tests/cypress/integration/ui/errors/errorAlerts.js
Labels: bugfix, ready

#6026 Improve problem details handling AB#16649
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/appsettings.Development.json
  Apps/Admin/Server/appsettings.hgdev.json
  Apps/Admin/Server/appsettings.json
  Apps/Common/src/ErrorHandling/DefaultExceptionHandler.cs
  Apps/Common/src/ErrorHandling/ExceptionUtilities.cs
  Apps/Common/src/ErrorHandling/Exceptions/AlreadyExistsException.cs
  Apps/Common/src/ErrorHandling/Exceptions/DatabaseException.cs
  Apps/Common/src/ErrorHandling/Exceptions/HealthGatewayException.cs
  Apps/Common/src/ErrorHandling/Exceptions/InvalidDataException.cs
  Apps/Common/src/ErrorHandling/Exceptions/NotFoundException.cs
  Apps/Common/src/ErrorHandling/Exceptions/UpstreamServiceException.cs
  Apps/Common/src/ErrorHandling/ValidationExceptionHandler.cs
  Apps/GatewayApi/src/appsettings.Development.json
  Apps/GatewayApi/src/appsettings.hgdev.json
  Apps/GatewayApi/src/appsettings.json
  Apps/Patient/src/appsettings.Development.json
  Apps/Patient/src/appsettings.hgdev.json
  Apps/Patient/src/appsettings.json
Labels: ready

#6029 Moved webclient and gateway api overrides from helm to appsettings
  Apps/Common/src/Models/CDogs/CDogsConfig.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/src/appsettings.Development.json
  Apps/GatewayApi/src/appsettings.hgdev.json
  Apps/GatewayApi/src/appsettings.hgtest.json
  Apps/GatewayApi/src/appsettings.json
  Apps/WebClient/src/appsettings.hgdev.json
  Apps/WebClient/src/appsettings.hgmock.json
  Apps/WebClient/src/appsettings.hgpoc.json
  Apps/WebClient/src/appsettings.hgtest.json
  Apps/WebClient/src/appsettings.json
  Tools/Helm/Charts/healthgateway/templates/route.tpl
Labels: .NET, ready

#6030 Resolve DateOnly issues in drug parsers AB#16648
  Apps/DBMaintainer/Parsers/FederalDrugProductParser.cs
  Apps/DBMaintainer/Parsers/PharmaCareDrugParser.cs
Labels: bugfix, ready

#6038 Update routing when user state is invalid AB#16654
  Apps/WebClient/src/ClientApp/src/router/index.ts
Labels: bugfix, ready

#6039 Fix timeline filter positioning when scrolling AB#16633
  Apps/WebClient/src/ClientApp/src/components/private/timeline/TimelineComponent.vue
Labels: bugfix, ready, UI

#6040 Configured robots controller to use configuration for AB#16622
  Apps/GatewayApi/src/Assets/Robots.Production.txt
  Apps/GatewayApi/src/Assets/Robots.txt
  Apps/GatewayApi/src/GatewayApi.csproj
  Apps/WebClient/src/Server/Assets/Robots.Production.txt
  Apps/WebClient/src/Server/Controllers/RobotsController.cs
  Apps/WebClient/src/Server/Models/WebClientConfiguration.cs
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Controllers/RobotsControllerTests.cs
Labels: enhancement, .NET, unit tests, ready

#6041 Disable connection-tracking cookies on OpenShift routes AB#16655
  Tools/Helm/Charts/healthgateway/templates/route.tpl
Labels: bugfix, ready

#6050 Fix error when medication statement collection is null AB#16668
  Apps/Medication/src/Services/RestMedicationStatementService.cs
Labels: ready

#6048 Install Java 17 in SonarCloud pipeline AB#16425
  .sonarcloud.properties
  Apps/sonar-config.xml
  Tools/SonarCloud/azure/build.yaml
Labels: ready

#6047 Increase unit test coverage for Medication for AB#16642.
  Apps/Medication/src/Controllers/MedicationController.cs
  Apps/Medication/src/Models/Salesforce/ResponseWrapper.cs
  Apps/Medication/src/Services/MedicationRequestService.cs
  Apps/Medication/src/Services/RestMedicationStatementService.cs
  Apps/Medication/test/unit/Controllers/MedicationStatementControllerTests.cs
  Apps/Medication/test/unit/Delegates/MedicationDelegateTests.cs
  Apps/Medication/test/unit/Services/MedicationStatementServiceTests.cs
Labels: .NET, unit tests, ready

#6054 Update Rider and SonarCloud filters for code coverage AB#16669
  Apps/.runsettings
  Apps/HealthGateway.sln.DotSettings
  Apps/sonar-config.xml
Labels: ready

#6053 Increase code coverage and fix sonar code smells for AB#16662
  Apps/Laboratory/src/Delegates/MockLaboratoryDelegate.cs
  Apps/Laboratory/src/Delegates/RestLaboratoryDelegate.cs
  Apps/Laboratory/src/Models/Covid19Test.cs
  Apps/Laboratory/src/Models/PHSA/PhsaCovid19Test.cs
  Apps/Laboratory/src/Services/ILaboratoryMappingService.cs
  Apps/Laboratory/src/Services/LaboratoryMappingService.cs
  Apps/Laboratory/test/unit/Delegates/LaboratoryDelegateTests.cs
  Apps/Laboratory/test/unit/MapProfiles/LaboratoryOrderProfileTests.cs
  Apps/Laboratory/test/unit/MapProfiles/LaboratoryTestProfileTests.cs
  Apps/Laboratory/test/unit/Services/LabTestKitServiceTests.cs
  Apps/Laboratory/test/unit/Services/LaboratoryServiceTests.cs
Labels: .NET, unit tests, ready
