Repository bcgov/healthgateway, pull requests merged in 2024-08, with the labels that each got.

#6282 Add paging when retrieving all beta users AB#16799
  Apps/Admin/Client/Api/IBetaFeatureApi.cs
  Apps/Admin/Client/Components/BetaAccess/AllBetaAccessTable.razor
  Apps/Admin/Client/Components/BetaAccess/AllBetaAccessTable.razor.cs
  Apps/Admin/Client/Pages/BetaAccessPage.razor
  Apps/Admin/Client/Pages/BetaAccessPage.razor.cs
  Apps/Admin/Client/Store/BetaAccess/BetaAccessEffects.cs
  Apps/Admin/Client/Store/BetaAccess/BetaAccessReducers.cs
  Apps/Admin/Server/Controllers/BetaFeatureController.cs
  Apps/Admin/Server/Services/BetaFeatureService.cs
  Apps/Admin/Server/Services/IBetaFeatureService.cs
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/support/functions/intercept.js
  Apps/Admin/Tests/Services/BetaFeatureServiceTests.cs
  Apps/CommonData/src/Models/PaginatedResult.cs
  Apps/Database/src/Delegates/DbBetaFeatureAccessDelegate.cs
  Apps/Database/src/Delegates/IBetaFeatureAccessDelegate.cs
Labels: ready

#6285 Create UserValidationService and RegistrationService from UserProfileServiceV2 for AB#16811
  Apps/GatewayApi/src/Controllers/UserProfileControllerV2.cs
  Apps/GatewayApi/src/Services/IRegistrationService.cs
  Apps/GatewayApi/src/Services/IUserProfileServiceV2.cs
  Apps/GatewayApi/src/Services/IUserValidationService.cs
  Apps/GatewayApi/src/Services/RegistrationService.cs
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
  Apps/GatewayApi/src/Services/UserValidationService.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Services.Test/RegistrationServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserValidationServiceTests.cs
Labels: .NET, unit tests, ready

#6287 Fix Beta Access sort. order for email address AB#16815.
  Apps/Admin/Tests/Functional/cypress/integration/e2e/patient-details.cy.js
  Apps/Database/src/Delegates/DbBetaFeatureAccessDelegate.cs
Labels: bugfix, .NET, functional tests, ready

#6286 Add Logo.png to landing site AB#16816
  Apps/Landing/src/ClientApp/public/Logo.png
Labels: ready

#6292 Refactor and simplify configureSettings AB#14988
  Apps/WebClient/src/ClientApp/src/models/configData.ts
  Testing/functional/tests/cypress/support/commands.js
Labels: functional tests, ready

#6295 Fix hover flakiness on ui dashboard functional tests for AB#16820.
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/age-count.json
  Apps/Admin/Tests/Functional/cypress/fixtures/DashboardService/daily-usage-counts.json
  Apps/Admin/Tests/Functional/cypress/integration/ui/dashboard.cy.js
  Apps/Admin/Tests/Functional/cypress/tsconfig.json
  Apps/Admin/Tests/Functional/package-lock.json
  Apps/Admin/Tests/Functional/package.json
Labels: bugfix, functional tests, ready

#6296 Remove grey banding in immunization reports for AB#16822.
  Apps/GatewayApi/src/Assets/Templates/ImmunizationRecommendationReport.docx
  Apps/GatewayApi/src/Assets/Templates/ImmunizationReport.docx
Labels: .NET, ready

#6297 Return Salesforce beta access for all users AB#16823
  Apps/GatewayApi/src/MapProfiles/UserProfileProfile.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
  Testing/functional/tests/cypress/integration/e2e/user/betaFeatures.js
Labels: ready

#6298 Lighten banding and darken text in immunization reports AB#16822
  Apps/GatewayApi/src/Assets/Templates/DependentImmunizationRecommendationReport.docx
  Apps/GatewayApi/src/Assets/Templates/DependentImmunizationReport.docx
  Apps/GatewayApi/src/Assets/Templates/ImmunizationRecommendationReport.docx
  Apps/GatewayApi/src/Assets/Templates/ImmunizationReport.docx
Labels: ready, UI

#6303 Lighten banding and darken text in remaining reports AB#16825
  Apps/GatewayApi/src/Assets/Templates/CovidReport.docx
  Apps/GatewayApi/src/Assets/Templates/EncounterReport.docx
  Apps/GatewayApi/src/Assets/Templates/HospitalVisitReport.docx
  Apps/GatewayApi/src/Assets/Templates/LaboratoryReport.docx
  Apps/GatewayApi/src/Assets/Templates/MedicationReport.docx
  Apps/GatewayApi/src/Assets/Templates/MedicationRequestReport.docx
  Apps/GatewayApi/src/Assets/Templates/NotesReport.docx
Labels: ready

#6302 Fix checksum for AB#16826.
  Tools/Helm/Charts/healthgateway/templates/dc.tpl
Labels: ready

#6293 Fix sonar cloud recommendations for AB#16818
  Apps/Admin/Client/Theme/HgTheme.cs
  Apps/GatewayApi/src/Controllers/UserProfileControllerV2.cs
  Apps/GatewayApi/src/Services/IJobService.cs
  Apps/GatewayApi/src/Services/IMessagingVerificationService.cs
  Apps/GatewayApi/src/Services/IUserEmailServiceV2.cs
  Apps/GatewayApi/src/Services/IUserProfileModelService.cs
  Apps/GatewayApi/src/Services/IUserSmsServiceV2.cs
  Apps/GatewayApi/src/Services/JobService.cs
  Apps/GatewayApi/src/Services/MessagingVerificationService.cs
  Apps/GatewayApi/src/Services/RegistrationService.cs
  Apps/GatewayApi/src/Services/UserEmailServiceV2.cs
  Apps/GatewayApi/src/Services/UserProfileModelService.cs
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
  Apps/GatewayApi/src/Services/UserSmsServiceV2.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Services.Test/JobServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/MessagingVerificationServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/RegistrationServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileModelServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceV2Tests.cs
Labels: enhancement, .NET, ready

#6306 Ensure DC redeployment on file, secret and config changes for AB#16826
  Tools/Helm/Charts/healthgateway/templates/dc.tpl
Labels: ready

#6309 Update banner on classic to new healthgateway site for AB#16832.
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
Labels: ready, UI

#6310 Change link to new site AB#16835
  Apps/WebClient/src/appsettings.json
Labels: ready

#6312 Update device preview images on landing site AB#16834
  Apps/Landing/src/ClientApp/src/assets/images/landing/preview-laptop.png
  Apps/Landing/src/ClientApp/src/assets/images/landing/preview-smartphone.png
  Apps/Landing/src/ClientApp/src/assets/images/landing/preview-tablet.png
Labels: ready, UI

#6313 Increase code coverage in Admin for AB16821
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Tests/Services/AdminReportServiceTests.cs
  Apps/Admin/Tests/Services/AgentAccessServiceTests.cs
  Apps/Admin/Tests/Services/BetaFeatureServiceTests.cs
  Apps/Admin/Tests/Services/CovidSupportServiceTests.cs
  Apps/Admin/Tests/Services/DashboardServiceTests.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Admin/Tests/Services/InactiveUserServiceTests.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/Admin/Tests/Services/UserFeedbackServiceTests.cs
Labels: .NET, unit tests, ready

#6315 Mid-sprint merge to master
  Apps/Admin/Client/Theme/HgTheme.cs
  Apps/Admin/Server/Services/CovidSupportService.cs
  Apps/Admin/Server/Services/DelegationService.cs
  Apps/Admin/Tests/Services/AdminReportServiceTests.cs
  Apps/Admin/Tests/Services/AgentAccessServiceTests.cs
  Apps/Admin/Tests/Services/BetaFeatureServiceTests.cs
  Apps/Admin/Tests/Services/CovidSupportServiceTests.cs
  Apps/Admin/Tests/Services/DashboardServiceTests.cs
  Apps/Admin/Tests/Services/DelegationServiceTests.cs
  Apps/Admin/Tests/Services/InactiveUserServiceTests.cs
  Apps/Admin/Tests/Services/SupportServiceTests.cs
  Apps/Admin/Tests/Services/UserFeedbackServiceTests.cs
  Apps/GatewayApi/src/Assets/Templates/CovidReport.docx
  Apps/GatewayApi/src/Assets/Templates/EncounterReport.docx
  Apps/GatewayApi/src/Assets/Templates/HospitalVisitReport.docx
  Apps/GatewayApi/src/Assets/Templates/LaboratoryReport.docx
  Apps/GatewayApi/src/Assets/Templates/MedicationReport.docx
  Apps/GatewayApi/src/Assets/Templates/MedicationRequestReport.docx
  Apps/GatewayApi/src/Assets/Templates/NotesReport.docx
  Apps/GatewayApi/src/Controllers/UserProfileControllerV2.cs
  Apps/GatewayApi/src/Services/IJobService.cs
  Apps/GatewayApi/src/Services/IMessagingVerificationService.cs
  Apps/GatewayApi/src/Services/IUserEmailServiceV2.cs
  Apps/GatewayApi/src/Services/IUserProfileModelService.cs
  Apps/GatewayApi/src/Services/IUserSmsServiceV2.cs
  Apps/GatewayApi/src/Services/JobService.cs
  Apps/GatewayApi/src/Services/MessagingVerificationService.cs
  Apps/GatewayApi/src/Services/RegistrationService.cs
  Apps/GatewayApi/src/Services/UserEmailServiceV2.cs
  Apps/GatewayApi/src/Services/UserProfileModelService.cs
  Apps/GatewayApi/src/Services/UserProfileServiceV2.cs
  Apps/GatewayApi/src/Services/UserSmsServiceV2.cs
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/test/unit/Services.Test/JobServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/MessagingVerificationServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/RegistrationServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileModelServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceV2Tests.cs
  Apps/Landing/src/ClientApp/src/assets/images/landing/preview-laptop.png
  Apps/Landing/src/ClientApp/src/assets/images/landing/preview-smartphone.png
  Apps/Landing/src/ClientApp/src/assets/images/landing/preview-tablet.png
  Apps/WebClient/src/ClientApp/src/components/private/home/HomeView.vue
  Apps/WebClient/src/appsettings.json
  Tools/Helm/Charts/healthgateway/templates/dc.tpl
Labels: ready
