Repository bcgov/healthgateway, pull requests merged in 2024-09, with the labels that each got.

#6333 Fix retry logic in BannerListener and AuditQueueListener for AB#16837.
  Apps/JobScheduler/src/Listeners/AuditQueueListener.cs
  Apps/JobScheduler/src/Listeners/BannerListener.cs
  Apps/JobScheduler/src/appsettings.json
Labels: bugfix, .NET, ready

#6336 Override Kong plugin that rewrites HTTP error responses AB#16842
  Tools/Kong/config.tmpl
Labels: ready

#6337 Remove AvailabilityFilter and DumpHeadersController AB#16844
  Apps/ClinicalDocument/src/Controllers/ClinicalDocumentController.cs
  Apps/Common/src/Filters/AvailabilityFilter.cs
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/GatewayApi/src/Controllers/NoteController.cs
  Apps/Immunization/src/Controllers/AuthenticatedVaccineStatusController.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Controllers/PublicVaccineStatusController.cs
  Apps/Immunization/src/appsettings.Development.json
  Apps/Immunization/src/appsettings.json
  Apps/JobScheduler/Views/DumpHeaders/Index.cshtml
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
  Apps/WebClient/src/Server/Controllers/DumpHeadersController.cs
  Apps/WebClient/src/Views/DumpHeaders/Index.cshtml
  Apps/WebClient/src/WebClient.csproj
  Apps/WebClient/src/appsettings.json
  Apps/WebClient/test/unit/Controllers/DumpHeadersControllerTests.cs
Labels: ready

#6339 Improve problem details responses AB#16846
  Apps/AccountDataAccess/src/Patient/ClientRegistriesDelegate.cs
  Apps/Admin/Server/Controllers/SupportController.cs
  Apps/Admin/Server/Delegates/RestImmunizationAdminDelegate.cs
  Apps/Admin/Server/Delegates/RestVaccineStatusDelegate.cs
  Apps/Admin/Tests/Services/CovidSupportServiceTests.cs
  Apps/Common/src/AspNetConfiguration/Modules/ExceptionHandling.cs
  Apps/Common/src/ErrorHandling/ErrorCodes.cs
  Apps/Common/src/ErrorHandling/ExceptionHandlers/ApiExceptionHandler.cs
  Apps/Common/src/ErrorHandling/ExceptionHandlers/DbUpdateExceptionHandler.cs
  Apps/Common/src/ErrorHandling/ExceptionHandlers/DefaultExceptionHandler.cs
  Apps/Common/src/ErrorHandling/ExceptionHandlers/ValidationExceptionHandler.cs
  Apps/Common/src/ErrorHandling/ExceptionUtilities.cs
  Apps/Common/src/ErrorHandling/Exceptions/AlreadyExistsException.cs
  Apps/Common/src/ErrorHandling/Exceptions/DatabaseException.cs
  Apps/Common/src/ErrorHandling/Exceptions/HealthGatewayException.cs
  Apps/Common/src/ErrorHandling/Exceptions/InvalidDataException.cs
  Apps/Common/src/ErrorHandling/Exceptions/NotFoundException.cs
  Apps/Common/src/ErrorHandling/Exceptions/UpstreamServiceException.cs
  Apps/Common/src/ErrorHandling/ProblemType.cs
  Apps/Common/test/unit/ErrorHandling/ExceptionHandlerTests.cs
  Apps/GatewayApi/src/Controllers/PhsaController.cs
  Apps/GatewayApi/src/Controllers/UserProfileControllerV2.cs
  Apps/Patient/src/Controllers/PatientController.cs
  Apps/Patient/src/Controllers/PatientDataController.cs
Labels: ready

#6338 Fix UI intercept endpoint definitions to use fixtures for AB#16845.
  Apps/Admin/Tests/Functional/cypress/integration/ui/patient-details.cy.js
  Apps/Admin/Tests/Functional/cypress/integration/ui/support.cy.js
Labels: bugfix, functional tests, ready

#6335 Increase code coverage in common project for AB#16838
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
  Apps/Common/test/unit/Delegates/VaccineProofDelegateTests.cs
  Apps/Common/test/unit/Services/CommunicationServiceTests.cs
  Apps/Common/test/unit/Services/EmailQueueServiceTests.cs
  Apps/Common/test/unit/Services/NotificationSettingsServiceTests.cs
  Apps/Common/test/unit/Services/PatientServiceTests.cs
  Apps/Common/test/unit/Utils/Scenario.cs
Labels: .NET, unit tests, ready

#6340 Refactor mock setup for account data access and common client registry delegate unit tests for AB#16847
  Apps/AccountDataAccess/test/unit/ClientRegistriesDelegateTests.cs
  Apps/Common/test/unit/Delegates/ClientRegistriesDelegateTests.cs
Labels: .NET, unit tests, ready

#6341 Fix Sonar Reliability issues in BannerListener for AB#16849
  Apps/JobScheduler/src/Listeners/BannerListener.cs
Labels: .NET, ready

#6343 Configure services to output to Azure Monitor AB#16831
  Apps/Admin/Server/appsettings.json
  Apps/ClinicalDocument/src/Startup.cs
  Apps/ClinicalDocument/src/appsettings.json
  Apps/Common/src/AspNetConfiguration/Modules/Observability.cs
  Apps/Common/src/AspNetConfiguration/StartupConfiguration.cs
  Apps/Common/src/Common.csproj
  Apps/Common/src/Models/OpenTelemetryConfig.cs
  Apps/Encounter/src/Startup.cs
  Apps/Encounter/src/appsettings.json
  Apps/GatewayApi/src/Startup.cs
  Apps/GatewayApi/src/appsettings.json
  Apps/Immunization/src/Startup.cs
  Apps/Immunization/src/appsettings.json
  Apps/JobScheduler/src/Startup.cs
  Apps/JobScheduler/src/appsettings.json
  Apps/Laboratory/src/Startup.cs
  Apps/Laboratory/src/appsettings.json
  Apps/Medication/src/Delegates/SalesforceMedicationRequestDelegate.cs
  Apps/Medication/src/Startup.cs
  Apps/Medication/src/appsettings.json
  Apps/Patient/src/Program.cs
  Apps/Patient/src/appsettings.json
  Apps/WebClient/src/Server/Startup.cs
  Apps/WebClient/src/appsettings.json
Labels: ready

#6344 Change filter text to return no results for AB#16853.
  Testing/functional/tests/cypress/integration/e2e/timeline/filter.js
Labels: bugfix, functional tests, ready

#6347 Reorganize unit test mock data setup for AB#16851
  Apps/AccountDataAccess/src/Patient/ClientRegistriesDelegate.cs
  Apps/AccountDataAccess/test/unit/AuditRepositoryTests.cs
  Apps/AccountDataAccess/test/unit/PatientMappingsTests.cs
  Apps/AccountDataAccess/test/unit/PatientRepositoryTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/CacheProviderTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/HdidAllStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/HdidEmpiStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/HdidPhsaStrategyTests.cs
  Apps/AccountDataAccess/test/unit/Strategy/PhnEmpiStrategyTests.cs
  Apps/Admin/Tests/Services/AgentAccessServiceTests.cs
  Apps/Admin/Tests/Services/CsvExportServiceTests.cs
  Apps/ClinicalDocument/src/Controllers/ClinicalDocumentController.cs
  Apps/ClinicalDocument/test/unit/Services/ClinicalDocumentServiceTests.cs
  Apps/Common/test/unit/Auditing/DbAuditLoggerTests.cs
  Apps/Common/test/unit/Utils/HttpContextHelperTests.cs
  Apps/Encounter/src/Controllers/EncounterController.cs
  Apps/GatewayApi/src/Controllers/NoteController.cs
  Apps/GatewayApi/test/unit/Controllers.Test/UserFeedbackControllerTests.cs
  Apps/GatewayApi/test/unit/Services.Test/ApplicationSettingsServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/DependentServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/GatewayApiCommunicationServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/JobServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/LegalAgreementServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/LegalAgreementServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/PatientDetailsServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/RegistrationServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserEmailServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserFeedbackServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserPreferenceServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserPreferenceServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileModelServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserProfileServiceV2Tests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserSmsServiceTests.cs
  Apps/GatewayApi/test/unit/Services.Test/UserValidationServiceTests.cs
  Apps/Immunization/src/Controllers/AuthenticatedVaccineStatusController.cs
  Apps/Immunization/src/Controllers/ImmunizationController.cs
  Apps/Immunization/src/Controllers/PublicVaccineStatusController.cs
  Apps/Laboratory/src/Controllers/LaboratoryController.cs
  Apps/Laboratory/src/Controllers/PublicLaboratoryController.cs
Labels: .NET, unit tests, ready
